; NOTE: comments marked [AI] are machine-generated by claude-opus-4-8 and may be
; inaccurate; treat them as hints, not verified annotation.

; Generated by disasm_z80
; Source: DOWNLOAD
; Range:  $0100-$02FF  (512 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_FCB          EQU $005C               ; Default File Control Block — populated by CCP from command-line argument 1. Standard 36-byte FCB structure (drive + filename + extents + record number).
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).

    INCLUDE "cpm22.inc"                  ; CP/M 2.2 ABI (provides TPA = $0100)
    ORG TPA

; [AI] Program entry point at $0100 (top of the TPA); checks the command-tail length byte to decide
;       whether a filename was supplied, branching to the error/exit path if not.
TPA_START:
        LD A,(DEFAULT_DMA)               ; $0100  3A 80 00
TPA_START_1:
        OR A                             ; $0103  B7
TPA_START_2:
        LD DE,MSG_COMMAND_ERROR          ; $0104  11 C0 01
TPA_START_3:
        JP Z,TPA_START_11                ; $0107  CA 8D 01
        LD C,$13                         ; $010A  0E 13
        LD DE,DEFAULT_FCB                ; $010C  11 5C 00
        PUSH DE                          ; $010F  D5
        CALL BDOS_VEC                    ; $0110  CD 05 00
        POP DE                           ; $0113  D1
        LD C,$16                         ; $0114  0E 16
        CALL BDOS_VEC                    ; $0116  CD 05 00
        INC A                            ; $0119  3C
        LD DE,MSG_NO_DIR_SPACE           ; $011A  11 CE 01
        JP Z,TPA_START_11                ; $011D  CA 8D 01
; [AI] Handshake wait loop: receives bytes from the serial port until the protocol start character
;       'R' ($52) arrives, then replies 'S' to signal readiness.
TPA_START_4:
        CALL SERIAL_GET_BYTE             ; $0120  CD A0 01
        CP $52                           ; $0123  FE 52
        JP NZ,TPA_START_4                ; $0125  C2 20 01
        LD E,$53                         ; $0128  1E 53
        CALL SERIAL_PUT_BYTE             ; $012A  CD 93 01
; [AI] Second handshake wait loop: receives bytes until the 'G' (go, $47) character arrives,
;       marking the start of the actual data transfer.
TPA_START_5:
        CALL SERIAL_GET_BYTE             ; $012D  CD A0 01
        CP $47                           ; $0130  FE 47
        JP NZ,TPA_START_5                ; $0132  C2 2D 01
        LD HL,MSG_DOWNLOADING            ; $0135  21 F5 01
; [AI] Banner-send loop: walks the null-terminated "Downloading" string at $01F5 and transmits each
;       character out the serial port to the host.
TPA_START_6:
        LD A,(HL)                        ; $0138  7E
        OR A                             ; $0139  B7
        JP Z,TPA_START_7                 ; $013A  CA 47 01
        PUSH HL                          ; $013D  E5
        LD E,A                           ; $013E  5F
        CALL BDOS_CONOUT                 ; $013F  CD BB 01
        POP HL                           ; $0142  E1
        INC HL                           ; $0143  23
        JP TPA_START_6                   ; $0144  C3 38 01
; [AI] Record-receive loop: reads one 128-byte data record plus a checksum byte from the serial
;       port into the DMA buffer, accumulating an XOR checksum.
TPA_START_7:
        LD HL,DEFAULT_DMA                ; $0147  21 80 00
        LD C,$00                         ; $014A  0E 00
        LD D,$81                         ; $014C  16 81
; [AI] Inner byte-receive loop for one record: fetches each byte via the port-read routine, stores
;       it to the buffer, and folds it into the running XOR checksum.
TPA_START_8:
        CALL SERIAL_GET_BYTE             ; $014E  CD A0 01
        LD (HL),A                        ; $0151  77
        XOR C                            ; $0152  A9
        LD C,A                           ; $0153  4F
        INC HL                           ; $0154  23
        DEC D                            ; $0155  15
        JP NZ,TPA_START_8                ; $0156  C2 4E 01
        OR A                             ; $0159  B7
        JP Z,TPA_START_9                 ; $015A  CA 6A 01
        LD E,$42                         ; $015D  1E 42
        CALL BDOS_CONOUT                 ; $015F  CD BB 01
        LD E,$42                         ; $0162  1E 42
        CALL SERIAL_PUT_BYTE             ; $0164  CD 93 01
        JP TPA_START_7                   ; $0167  C3 47 01
; [AI] Good-record path: transmits a '.' progress mark, then calls BDOS write-sequential (function
;       21) to append the received 128-byte record to the output file before looping for the next
;       record.
TPA_START_9:
        LD E,$2E                         ; $016A  1E 2E
        CALL BDOS_CONOUT                 ; $016C  CD BB 01
        LD DE,DEFAULT_FCB                ; $016F  11 5C 00
        LD C,$15                         ; $0172  0E 15
        CALL BDOS_VEC                    ; $0174  CD 05 00
        LD E,$47                         ; $0177  1E 47
        CALL SERIAL_PUT_BYTE             ; $0179  CD 93 01
        JP TPA_START_7                   ; $017C  C3 47 01
; [AI] End-of-transfer handler: reached when the host sends the terminator byte ($83); closes the
;       output file via BDOS close (function 16) and points to the completion message before
;       exiting.
TPA_START_10:
        LD ($E010),A                     ; $017F  32 10 E0
        LD DE,DEFAULT_FCB                ; $0182  11 5C 00
        LD C,$10                         ; $0185  0E 10
        CALL BDOS_VEC                    ; $0187  CD 05 00
        LD DE,MSG_DOWNLOAD_COMPLETE      ; $018A  11 E1 01
; [AI] Common message-and-exit tail: prints the DE-pointed '$'-terminated status string then falls
;       through to warm-boot back to CP/M.
TPA_START_11:
        CALL BDOS_PRINT_STRING           ; $018D  CD B6 01
; [AI] Final exit: jumps to the warm-boot vector to terminate the program and return to the CCP
;       prompt.
TPA_START_12:
        JP WBOOT_VEC                     ; $0190  C3 00 00
; [AI] Serial transmit routine: polls the port status register ($E0AE) for the transmit-ready bit,
;       then writes the byte in E to the data register ($E0AF).
SERIAL_PUT_BYTE:
        LD A,($E0AE)                     ; $0193  3A AE E0
        AND $02                          ; $0196  E6 02
        JP Z,SERIAL_PUT_BYTE             ; $0198  CA 93 01
        LD A,E                           ; $019B  7B
        LD ($E0AF),A                     ; $019C  32 AF E0
        RET                              ; $019F  C9
; [AI] Serial receive routine: polls the status register for receive-ready; while waiting it also
;       watches a control register ($E000) for the $83 end-of-transfer signal, diverting to the
;       close-file path when it appears.
SERIAL_GET_BYTE:
        LD A,($E0AE)                     ; $01A0  3A AE E0
        RRA                              ; $01A3  1F
        JP C,SERIAL_RX_READY             ; $01A4  DA B2 01
        LD A,($E000)                     ; $01A7  3A 00 E0
        CP $83                           ; $01AA  FE 83
        JP Z,TPA_START_10                ; $01AC  CA 7F 01
        JP SERIAL_GET_BYTE               ; $01AF  C3 A0 01
; [AI] Receive-ready exit of the read routine: loads the just-arrived byte from the data register
;       ($E0AF) into A and returns it to the caller.
SERIAL_RX_READY:
        LD A,($E0AF)                     ; $01B2  3A AF E0
        RET                              ; $01B5  C9
; [AI] Print-string helper: sets C to BDOS function 9 (print '$'-terminated string) and tail-jumps
;       into the BDOS call so the DE-pointed message is displayed.
BDOS_PRINT_STRING:
        LD C,$09                         ; $01B6  0E 09
; [AI] Shared BDOS tail-call: a JP $0005 reused as the final dispatch for the print-string helper.
BDOS_PRINT_STRING_1:
        JP BDOS_VEC                      ; $01B8  C3 05 00
; [AI] Console-output helper: sets C to BDOS function 2 (console out) and tail-jumps to BDOS to
;       echo the single character in E to the screen (used for the progress dots and banner).
BDOS_CONOUT:
        LD C,$02                         ; $01BB  0E 02
        JP BDOS_VEC                      ; $01BD  C3 05 00
MSG_COMMAND_ERROR:
        DEFB    "Command Error$"                                 ; $01C0  ('$' = BDOS fn 9 terminator)
MSG_NO_DIR_SPACE:
        DEFB    "No directory space$"                            ; $01CE
MSG_DOWNLOAD_COMPLETE:
        DEFB    $0D,$0A,"DOWNLOAD Complete$"                     ; $01E1  CR LF then text
MSG_DOWNLOADING:
        DEFB    "Downloading"    ; $01F5  string
        DEFB    $00    ; $0200  terminator

; ── Leftover relocatable image in the file's final record ($0201-$02FF) ──────
;
; The real DOWNLOAD program ends at $01BD; $01C0-$0200 are its '$'/NUL-terminated
; messages. The remaining bytes ($0201-$02FF) are NOT referenced by any path
; above -- but they are also NOT random "stale TPA residue". Decoded as
; page-relative Z-80 (run base $0000) the span is coherent, densely-connected
; routine code: the same family of relocatable build-runtime overlay that
; DUMP.COM's BSS tail also carries (char classifier, the RLA/AND $38 + RLA/AND
; $30 nibble extractors, a 4-byte field walker at $008D, a BDOS-call thunk at
; $0000). Every internal CALL/JP lands on an instruction boundary; the only
; out-of-image operands ($1124, $11D4, $114B, $073C, $121B, $09C8, $16DE...) are
; page-relative-to-another-base references the loader's relocator would fix at run
; time, left here as literal addresses.
;
; The image is a WINDOW truncated by the 512-byte (4-record) file boundary, so a
; few genuine fragments remain DEFB, each for a concrete reason:
;   $0000  FA 09 C3 ...  the head is the tail of an instruction cut off before
;                        $0201; it happens to decode as a valid 3-byte JP M, which
;                        is what we emit (byte-identical) -- treat $0000-$0001 as a
;                        truncated lead-in, not a real routine entry.
;   $00E0  DEFB $21      the LD-HL opcode byte that the overlapping JP Z,$00E1 at
;                        $00CF skips into mid-operand (a shared-instruction-tail
;                        idiom; the jump enters $00E1 = DD 16 7E = LD D,$7E).
;   $00FD  3A CB ..      a trailing LD A,(nn) whose 3rd (high-operand) byte falls
;                        past the file's end -- truncated by the record boundary.
; Decoded below at run base $0000 via DISP, in a local MODULE so its labels do not
; collide with the loader's.
DOWNLOAD_BSS_IMAGE:
    MODULE DOWNLOAD_OVERLAY
    DISP $0000                           ; leftover image is page-relative; internal labels resolve at $0000
; [AI] Truncated lead-in (first instruction's head was cut off before $0201);
;       the real routine starts at $0005: load C with ',' ($2C), preserve A, and
;       emit the char via the $1124 output thunk -- a print-comma helper.
OVL_LEADIN:
        JP M,$C309                       ; $0000  FA 09 C3   (truncated lead-in; see note)
        ADC A,E                          ; $0003  8B
        INC DE                           ; $0004  13
        LD C,$2C                         ; $0005  0E 2C
        PUSH AF                          ; $0007  F5
        LD A,C                           ; $0008  79
        CALL $1124                       ; $0009  CD 24 11
        POP AF                           ; $000C  F1
        RET                              ; $000D  C9
; [AI] Whitespace/separator classifier: fetch a char via the $11D4 input thunk;
;       Z is set on space (returned by the thunk), and a tab ($09) is also treated
;       as a separator. Entry+1 ($000F) is the common "classify current char" target.
OVL_IS_SEPARATOR:
        CALL $11D4                       ; $000E  CD D4 11
        RET Z                            ; $0011  C8
        CP $09                           ; $0012  FE 09
        RET                              ; $0014  C9
; [AI] Read one whitespace-skipped token: fetch a char ($114B input thunk), abort
;       to $073C on CR, skip leading separators (loop back to entry+1 $0016), then
;       blank the 6-byte field buffer at $09C8 ready to receive the token.
OVL_READ_TOKEN:
        CALL $114B                       ; $0015  CD 4B 11
        CP $0D                           ; $0018  FE 0D
        JP Z,$073C                       ; $001A  CA 3C 07
        CALL OVL_IS_SEPARATOR+1          ; $001D  CD 0F 00
        JP Z,OVL_READ_TOKEN+1            ; $0020  CA 16 00
        LD C,$06                         ; $0023  0E 06
        LD HL,$09C8                      ; $0025  21 C8 09
OVL_BLANK_FIELD:
        LD (HL),$20                      ; $0028  36 20
        INC HL                           ; $002A  23
        DEC C                            ; $002B  0D
        JP NZ,OVL_BLANK_FIELD+1          ; $002C  C2 29 00
        LD C,$07                         ; $002F  0E 07
        LD HL,$09C8                      ; $0031  21 C8 09
        LD (HL),A                        ; $0034  77
; [AI] Token-character copy loop: read each char ($114B), stop at a separator
;       (return Z), store into the field, decrement the 7-byte field counter, and
;       abort to $073C if the field overflows.
OVL_COPY_TOKEN:
        CALL $114B                       ; $0035  CD 4B 11
        CALL OVL_IS_SEPARATOR+1          ; $0038  CD 0F 00
        RET Z                            ; $003B  C8
        INC HL                           ; $003C  23
        DEC C                            ; $003D  0D
        JP Z,$073C                       ; $003E  CA 3C 07
        JP OVL_COPY_TOKEN                ; $0041  C3 35 00
; [AI] Parse the field into a 16-bit value via the $121B number thunk; copies the
;       DE result to BC and sets flags (DEC B/INC B) for the checked wrapper below.
OVL_PARSE_VALUE:
        CALL $121B                       ; $0044  CD 1B 12
        LD C,E                           ; $0047  4B
        LD B,D                           ; $0048  42
        LD A,C                           ; $0049  79
        DEC B                            ; $004A  05
        INC B                            ; $004B  04
        RET                              ; $004C  C9
; [AI] Checked parse: run OVL_PARSE_VALUE+1 preserving BC; abort to $073C on a
;       parse error (NZ), else return the parsed value.
OVL_PARSE_VALUE_CHECKED:
        PUSH BC                          ; $004D  C5
        CALL OVL_PARSE_VALUE+1           ; $004E  CD 45 00
        POP BC                           ; $0051  C1
        JP NZ,$073C                      ; $0052  C2 3C 07
        RET                              ; $0055  C9
; [AI] Index extractor: A <<3, mask $38 -- isolates bits 3-5 (a x8 index, e.g.
;       a 3-bit field scaled into a table-row offset). Byte-identical to DUMP.asm's
;       OVL_INDEX_X8 (shared relocatable overlay family); named to match.
OVL_INDEX_X8:
        RLA                              ; $0056  17
        RLA                              ; $0057  17
        RLA                              ; $0058  17
        AND $38                          ; $0059  E6 38
        RET                              ; $005B  C9
; [AI] Index extractor: A <<4, mask $30 -- isolates bits 4-5 (a x16 index).
;       Byte-identical to DUMP.asm's OVL_INDEX_X16 (shared relocatable overlay
;       family); named to match.
OVL_INDEX_X16:
        RLA                              ; $005C  17
        RLA                              ; $005D  17
        RLA                              ; $005E  17
        RLA                              ; $005F  17
        AND $30                          ; $0060  E6 30
        RET                              ; $0062  C9
; [AI] Scan-for-byte loop: compare A against (HL), advancing while the C counter
;       lasts; Z exit ($0064) on a match. Entry $0063 does the first compare.
OVL_SCAN_BYTE:
        CP (HL)                          ; $0063  BE
OVL_SCAN_BYTE_LOOP:
        RET Z                            ; $0064  C8
        INC HL                           ; $0065  23
        DEC C                            ; $0066  0D
        JP NZ,OVL_SCAN_BYTE_LOOP         ; $0067  C2 64 00
        DEC C                            ; $006A  0D
        RET                              ; $006B  C9
; [AI] Table-match search: takes the search key in HL (via EX at $006C) and walks
;       the table whose head pointer is at ($09C8), comparing each 2-byte entry for
;       a match. Returns Z on hit. $006D is the entry that loads the table pointer.
OVL_TABLE_MATCH:
        EX DE,HL                         ; $006C  EB
OVL_TABLE_MATCH_LOAD:
        LD HL,($09C8)                    ; $006D  2A C8 09
        EX DE,HL                         ; $0070  EB
        LD A,E                           ; $0071  7B
OVL_TABLE_MATCH_CMP:
        CP (HL)                          ; $0072  BE
        JP NZ,OVL_TABLE_MATCH_NEXT       ; $0073  C2 7E 00
        INC HL                           ; $0076  23
        LD A,D                           ; $0077  7A
        DEC C                            ; $0078  0D
        CP (HL)                          ; $0079  BE
        RET Z                            ; $007A  C8
        INC C                            ; $007B  0C
        DEC HL                           ; $007C  2B
        DEC HL                           ; $007D  2B
OVL_TABLE_MATCH_NEXT:
        DEC HL                           ; $007E  2B
        DEC C                            ; $007F  0D
        JP NZ,OVL_TABLE_MATCH_CMP        ; $0080  C2 72 00
        DEC C                            ; $0083  0D
        RET                              ; $0084  C9
; [AI] Trailing-blank check: the byte at $09CC of the parsed field must be a space
;       ($20), else abort to $073C (rejects an over-long token).
OVL_CHECK_FIELD_PAD:
        LD A,($09CC)                     ; $0085  3A CC 09
        CP $20                           ; $0088  FE 20
        JP NZ,$073C                      ; $008A  C2 3C 07
; [AI] 4-byte field walker: seeds a mode flag at $16DE ('H' $48), then walks the
;       field in 4-byte records (B=4) against the $09C8 buffer, applying the
;       suffix classifier (OVL_MATCH_SUFFIX) and advancing HL by -4 ($FFFC) per row.
OVL_FIELD_WALK:
        LD A,$48                         ; $008D  3E 48
        LD ($16DE),A                     ; $008F  32 DE 16
        LD B,$04                         ; $0092  06 04
        PUSH HL                          ; $0094  E5
        LD DE,$09C8                      ; $0095  11 C8 09
        LD A,(HL)                        ; $0098  7E
OVL_FIELD_WALK_CMP:
        CP $40                           ; $0099  FE 40
        LD A,(DE)                        ; $009B  1A
        CALL Z,OVL_MATCH_SUFFIX          ; $009C  CC B8 00
        CP (HL)                          ; $009F  BE
        JP NZ,OVL_FIELD_WALK_NEXT        ; $00A0  C2 AC 00
        INC HL                           ; $00A3  23
        INC DE                           ; $00A4  13
        DEC B                            ; $00A5  05
        JP NZ,OVL_FIELD_WALK_CMP         ; $00A6  C2 99 00
        POP DE                           ; $00A9  D1
        RET                              ; $00AA  C9
OVL_FIELD_WALK_RESTORE:
        POP HL                           ; $00AB  E1
OVL_FIELD_WALK_NEXT:
        LD DE,$FFFC                      ; $00AC  11 FC FF
        ADD HL,DE                        ; $00AF  19
        DEC C                            ; $00B0  0D
        JP NZ,OVL_FIELD_WALK+1           ; $00B1  C2 8E 00
        LD B,C                           ; $00B4  41
        DEC C                            ; $00B5  0D
        RET                              ; $00B6  C9
; [AI] Suffix classifier: bump the caller's return address past the inline data
;       byte (EX (SP),HL / INC HL / EX (SP),HL), record the suffix at $16DE, then
;       test for the 'H'/'X'/'Y' radix-or-register suffixes. $00C0 is the bare
;       'X'/'Y' test (entry+1 reused as OVL_IS_XY).
OVL_MATCH_SUFFIX_THUNK:
        EX (SP),HL                       ; $00B7  E3
OVL_MATCH_SUFFIX:
        INC HL                           ; $00B8  23
        EX (SP),HL                       ; $00B9  E3
        LD ($16DE),A                     ; $00BA  32 DE 16
        CP $48                           ; $00BD  FE 48
        RET Z                            ; $00BF  C8
OVL_IS_XY:
        CP $58                           ; $00C0  FE 58
        RET Z                            ; $00C2  C8
        CP $59                           ; $00C3  FE 59
        RET                              ; $00C5  C9
; [AI] Bracketed-expression parser: read a token (OVL_READ_TOKEN+1); if it opens
;       with '[' ($5B) dispatch to the bracket body, else look the 8-entry symbol
;       table at $09AE up via OVL_TABLE_MATCH and return its index, aborting to
;       $073C on no match.
OVL_PARSE_BRACKET:
        PUSH BC                          ; $00C6  C5
        CALL OVL_READ_TOKEN+1            ; $00C7  CD 16 00
        LD A,($09C8)                     ; $00CA  3A C8 09
        CP $5B                           ; $00CD  FE 5B
        JP Z,OVL_BRACKET_BODY            ; $00CF  CA E1 00
        LD C,$08                         ; $00D2  0E 08
        LD HL,$09AE                      ; $00D4  21 AE 09
        CALL OVL_TABLE_MATCH_LOAD        ; $00D7  CD 6D 00
        JP NZ,$073C                      ; $00DA  C2 3C 07
        LD A,C                           ; $00DD  79
        POP BC                           ; $00DE  C1
        RET                              ; $00DF  C9
        DEFB    $21                                              ; $00E0  LD-HL opcode skipped into mid-operand by JP Z,$00E1
OVL_BRACKET_BODY:
        DEFB $DD  ; ignored IX prefix; inner: LD D,$7E ; $00E1  DD 16 7E
        LD D,$7E                         ; $00E2  16 7E
        OR A                             ; $00E4  B7
        JP NZ,$073C                      ; $00E5  C2 3C 07
        INC (HL)                         ; $00E8  34
        LD A,($09CD)                     ; $00E9  3A CD 09
        CP $5D                           ; $00EC  FE 5D
        JP NZ,$073C                      ; $00EE  C2 3C 07
        LD A,($09C9)                     ; $00F1  3A C9 09
        CALL OVL_IS_XY+1                 ; $00F4  CD C1 00
        JP NZ,$073C                      ; $00F7  C2 3C 07
        CALL $017E                       ; $00FA  CD 7E 01
        DEFB    $3A,$CB                                          ; $00FD  truncated LD A,(nn): high operand byte past file end
    ENT
    ENDMODULE

    SAVEBIN "DOWNLOAD.bin", $0100, $0200
