; Generated by disasm_z80
; Source: RW13.COM
; Range:  $0100-$09FF  (2304 bytes)
;
; [AI] RW13.COM -- Apple ][ CP/M "13 Sector Disk Conversion" utility (Microsoft, 1980).
; [AI] The SoftCard normally runs CP/M from 16-sector (DOS 3.3 era) diskettes. This tool
; [AI]   reconfigures one drive so the BIOS will read/write the older Apple 13-sector
; [AI]   (DOS 3.2.1 era) format, and can restore a drive to 16-sector operation. A 16-sector
; [AI]   disk will not boot a drive set up for 13-sector and vice-versa, so RW13 ships on the
; [AI]   16-sector disk to copy 13-sector CP/M files in [DOC Vol1 1-8; facts sec.8.8].
; [AI] Usage:
; [AI]   RW13 X        -> install the 13-sector low-level driver (Apple 6502 side) and
; [AI]                    redirect the BIOS sector handler to it.
; [AI]   RW13 <drive>  -> a bare drive letter restores that drive to 16-sector operation.
; [AI] Architecture: the Z-80 front end (this $0100-$02D5 code) prints via BDOS function 9
; [AI]   [DOC CPMREF 3-44; facts sec.5] and pokes the SoftCard/BIOS data area ($Fxxx). The
; [AI]   bytes from $0300 onward are a 6502 machine-code payload (Apple-side 13-sector RWTS
; [AI]   replacement plus nibble/skew tables); the install path stages it, points the
; [AI]   SoftCard 6502 call vector A$VEC (A_VEC) [DOC S&HD 2-25; facts sec.4.2] at the engine,
; [AI]   and writes through Z$CPU (Z_CPU) [DOC S&HD 2-24/2-25; facts sec.4.3] to hand the CPU
; [AI]   to the 6502 for each sector I/O. The 6502 block is real source in RW13_6502.s (ca65,
; [AI]   ORG'd at its $1300 run address) and INCBIN'd back below byte-for-byte.

    DEVICE NOSLOT64K
    INCLUDE "apple_softcard.inc"   ; Apple/SoftCard external names (single source of truth)

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_FCB          EQU $005C               ; Default File Control Block — populated by CCP from command-line argument 1. Standard 36-byte FCB structure (drive + filename + extents + record number).

    ORG $0100

; [AI] ===== Program entry ($0100) =====
; [AI] Print the banner, then dispatch on the first character of the command argument.
START:
        LD DE,MSG_BANNER                 ; $0100  11 A8 01  ; [AI] DE -> "APPLE ][ CP/M 13 Sector..." banner
START_PRINT_BANNER:
        LD C,$09                         ; $0103  0E 09     ; [AI] BDOS fn 9 = print $-terminated string [DOC CPMREF 3-44; facts sec.5]
START_PRINT_CALL:
        CALL BDOS_VEC                    ; $0105  CD 05 00  ; [AI] emit banner to console
START_DISPATCH:
        LD A,($0082)                     ; $0108  3A 82 00  ; [AI] A = first char of command tail arg ($0080=len, $0081=' ', $0082=arg[0])
        CP $58                           ; $010B  FE 58     ; [AI] 'X' (upper) -> install 13-sector mode
        JR Z,INSTALL_13SEC               ; $010D  28 04
        CP $78                           ; $010F  FE 78     ; [AI] 'x' (lower) -> install 13-sector mode
        JR NZ,CHECK_RESTORE              ; $0111  20 3D     ; [AI] not X/x -> treat arg as a drive to restore to 16-sector

; [AI] ----- Install 13-sector driver -----
INSTALL_13SEC:
        LD A,($FE0A)                     ; $0113  3A 0A FE  ; [AI] BIOS flag: current sector mode of selected drive
        CP $0E                           ; $0116  FE 0E     ; [AI] already 13-sector? ($0E sentinel) -> skip re-patch
        JR Z,INSTALL_DONE_MSG            ; $0118  28 18
        LD HL,($F3EE)                    ; $011A  2A EE F3  ; [AI] HL = saved BIOS sector-handler vector
        LD ($FE09),HL                    ; $011D  22 09 FE  ; [AI] stash original 16-sector handler for later restore
        LD C,$00                         ; $0120  0E 00     ; [AI] select BIOS jump-table slot 0 (read entry)
        CALL BIOS_JMPTAB_ENTRY           ; $0122  CD 37 01  ; [AI] HL -> operand bytes of that BIOS jump-table entry
        LD E,(HL)                        ; $0125  5E        ; [AI] read current low byte of handler address
        INC HL                           ; $0126  23
        LD D,(HL)                        ; $0127  56        ; [AI] DE = current handler address
        PUSH DE                          ; $0128  D5
        LD C,$01                         ; $0129  0E 01     ; [AI] select BIOS jump-table slot 1 (write entry)
        CALL BIOS_JMPTAB_ENTRY           ; $012B  CD 37 01  ; [AI] HL -> operand bytes of write entry
        POP DE                           ; $012E  D1
        LD (HL),E                        ; $012F  73        ; [AI] copy handler address into the write slot
        INC HL                           ; $0130  23
        LD (HL),D                        ; $0131  72
INSTALL_DONE_MSG:
        LD DE,MSG_TO16SEC                ; $0132  11 35 02  ; [AI] (reused buffer) "Drive returned to 16 sector operation"
        JR PRINT_AND_WBOOT               ; $0135  18 11     ; [AI] print result then warm boot

; [AI] BIOS_JMPTAB_ENTRY: reach a BIOS jump-vector entry via a computed JP (HL), then
; [AI]   adjust HL by +$0A so it addresses that entry's 2-byte operand. ($0001/$0002 hold
; [AI]   the addr of WBOOT+1, i.e. the BIOS warm-boot JP; forcing L=$1B lands in the
; [AI]   jump-vector area.) NOTE: the dispatch goes THROUGH a BIOS JP (CALL JP_HL_THUNK =
; [AI]   JP (HL)) and relies on that path returning to $013F, so the "+$0A -> operand"
; [AI]   framing is inferred from the surrounding read/copy use, not proven from the flow.
BIOS_JMPTAB_ENTRY:
        LD HL,($0001)                    ; $0137  2A 01 00  ; [AI] HL = BIOS warm-boot vector (page from $0002)
        LD L,$1B                         ; $013A  2E 1B     ; [AI] point into BIOS jump-table region
        CALL JP_HL_THUNK                 ; $013C  CD 44 01  ; [AI] (indirect; see note) advance via jump table
        LD DE,$000A                      ; $013F  11 0A 00
        ADD HL,DE                        ; $0142  19        ; [AI] HL += $0A -> operand bytes of target entry
        RET                              ; $0143  C9

; [AI] JP_HL_THUNK: 'JP (HL)' used as a computed call landing pad / no-op pass-through.
JP_HL_THUNK:
        JP (HL)                          ; $0144  E9

; [AI] Invalid-drive error exit (DE preset to "Invalid Drive").
ERR_INVALID_DRIVE:
        LD DE,MSG_INVALID_DRIVE          ; $0145  11 23 02
; [AI] PRINT_AND_WBOOT: print $-string at DE via BDOS fn 9 [DOC CPMREF 3-44; facts sec.5],
; [AI]   then JP WBOOT (warm boot).
PRINT_AND_WBOOT:
        LD C,$09                         ; $0148  0E 09     ; [AI] BDOS fn 9 = print $-string
PRINT_AND_WBOOT_CALL:
        CALL BDOS_VEC                    ; $014A  CD 05 00
PRINT_AND_WBOOT_C9:
        JP WBOOT_VEC                     ; $014D  C3 00 00  ; [AI] return to CP/M via warm boot

; [AI] ----- Restore path: bare drive letter argument -----
; [AI] Validate the drive, and if currently in 13-sector mode, put it back to 16-sector.
CHECK_RESTORE:
        LD A,($FE0A)                     ; $0150  3A 0A FE  ; [AI] BIOS sector-mode flag
CHECK_RESTORE_1:
        CP $0E                           ; $0153  FE 0E     ; [AI] is the drive in 13-sector mode?
CHECK_RESTORE_MSG:
        LD DE,MSG_MUST_RW13_FIRST        ; $0155  11 71 02  ; [AI] preload "Must 'RW13 X' first"
        JR NZ,PRINT_AND_WBOOT            ; $0158  20 EE     ; [AI] not in 13-sector -> nothing to restore, complain
        LD A,(DEFAULT_FCB)               ; $015A  3A 5C 00  ; [AI] A = drive code from parsed FCB (0=default,1=A,...) [DOC CPMREF 3-46/3-47; facts sec.7.4]
        CP $01                           ; $015D  FE 01
        JR Z,ERR_INVALID_DRIVE           ; $015F  28 E4     ; [AI] drive 1 here is rejected as invalid
        JR NC,RESTORE_DRIVE              ; $0161  30 05     ; [AI] >=2 -> valid drive, proceed
        LD DE,MSG_COMMAND_ERROR          ; $0163  11 5F 02  ; [AI] 0 -> no drive given
        JR PRINT_AND_WBOOT               ; $0166  18 E0

RESTORE_DRIVE:
        LD C,A                           ; $0168  4F        ; [AI] C = drive code
        ADD A,$40                        ; $0169  C6 40     ; [AI] convert to ASCII drive letter (1->'A')...
        LD (MSG_DRIVE_LETTER),A          ; $016B  32 FB 01  ; [AI] patch the 'Z:' slot in the converted-message text
        LD A,(DSKCNT)                     ; $016E  3A B8 F3  ; [AI] BIOS Disk Count Byte (controllers x 2) [DOC S&HD 2-27; facts sec.3.7]
        CP C                             ; $0171  B9
        JR C,ERR_INVALID_DRIVE           ; $0172  38 D1     ; [AI] requested drive > count -> invalid
        CALL HEAD_SELECT                 ; $0174  CD D0 02  ; [AI] A = side/parity (1 or 2) for this drive
        LD (RW13_6502_PARAM_HEAD),A      ; $0177  32 15 08  ; [AI] store into 6502 engine head/side param @ run $1815
        DEC C                            ; $017A  0D
        LD A,C                           ; $017B  79
        ADD A,A                          ; $017C  87        ; [AI] (drive-1) * 8 -> slot/select nibble
        ADD A,A                          ; $017D  87
        ADD A,A                          ; $017E  87
        AND $F0                          ; $017F  E6 F0
        CPL                              ; $0181  2F
        ADD A,$61                        ; $0182  C6 61     ; [RE] compute slot-I/O base offset for 6502 driver (encodes (drive-1) into a slot*16 index byte; $60 for drive A)
        LD (RW13_6502_PARAM_SLOT),A      ; $0184  32 0E 08  ; [AI] store into 6502 engine slot-I/O param @ run $180E
        LD HL,($0001)                    ; $0187  2A 01 00  ; [AI] HL = BIOS warm-boot vector base
        LD L,$1B                         ; $018A  2E 1B
        CALL BIOS_JMPTAB_ENTRY           ; $018C  CD 37 01  ; [AI] HL -> BIOS jump-table operand to repoint
        LD (HL),$F0                      ; $018F  36 F0     ; [AI] low byte of new (6502-driver) handler address
        INC HL                           ; $0191  23
        LD A,($0007)                     ; $0192  3A 07 00  ; [AI] high byte of BIOS/BDOS region (top of TPA marker)
        SUB $09                          ; $0195  D6 09     ; [AI] derive driver page in high RAM
        LD (HL),A                        ; $0197  77        ; [AI] high byte of new handler address
        LD HL,$1300                      ; $0198  21 00 13  ; [AI] $1300 = 6502 engine run address (13-sector marker)
        LD (A_VEC),HL                    ; $019B  22 D0 F3  ; [AI] arm A$VEC with 6502 routine address [DOC S&HD 2-25; facts sec.4.2]
        LD HL,(Z_CPU)                    ; $019E  2A DE F3  ; [AI] HL = Z$CPU SoftCard location [DOC S&HD 2-24/2-25; facts sec.4.3]
        LD (HL),A                        ; $01A1  77        ; [AI] store driver page (write also primes the CPU-switch cell)
        LD DE,MSG_CONVERTED              ; $01A2  11 F5 01  ; [AI] "Drive Z: converted to 13 sec. operation"
        JP PRINT_AND_WBOOT               ; $01A5  C3 48 01

; [AI] ===== Messages ($-terminated for BDOS fn 9) =====
MSG_BANNER:
        DEFB    $0D,$0A,$0D,$0A                                  ; $01A8
        DEFB    "     APPLE ][ CP/M"    ; $01AC  string
        DEFB    $0D    ; $01BE  terminator
        DEFB    $0A                                              ; $01BF
        DEFB    "13 Sector Disk Conversion"    ; $01C0  string
        DEFB    $0D    ; $01D9  terminator
        DEFB    $0A                                              ; $01DA
        DEFB    "   (C) 1980 Microsoft"    ; $01DB  string
        DEFB    $0D    ; $01F0  terminator
        DEFB    $0A,$0D,$0A,$24                                  ; $01F1   ; [AI] trailing CR/LF + '$'
MSG_CONVERTED:
        DEFB    "Drive "    ; $01F5  string
MSG_DRIVE_LETTER:
        DEFB    "Z: converted to 13 sec. operation"    ; $01FB  string  ; [AI] 'Z' is patched to the real drive letter at $016B
        DEFB    $0D    ; $021C  terminator
        DEFB    $0A,$0D,$0A,$24,$0A,$24                          ; $021D   ; [AI] '$' terminators
MSG_INVALID_DRIVE:
        DEFB    "Invalid Drive"    ; $0223  string
        DEFB    $0D    ; $0230  terminator
        DEFB    $0A,$0D,$0A,$24                                  ; $0231
MSG_TO16SEC:
        DEFB    "Drive returned to 16 sector operation"    ; $0235  string
        DEFB    $0D    ; $025A  terminator
        DEFB    $0A,$0D,$0A,$24                                  ; $025B
MSG_COMMAND_ERROR:
        DEFB    "Command Error"    ; $025F  string
        DEFB    $0D    ; $026C  terminator
        DEFB    $0A,$0D,$0A,$24                                  ; $026D
MSG_MUST_RW13_FIRST:
        DEFB    "Must 'RW13 X' first"    ; $0271  string
        DEFB    $0D    ; $0284  terminator
        DEFB    $0A,$0D,$0A,$24                                  ; $0285
        DEFS    71, $00    ; $0289  fill

; [AI] HEAD_SELECT: from drive code in C, return A = 1 or 2 (disk side / head select
; [AI]   alternating by drive parity) for the 6502 driver.
HEAD_SELECT:
        LD A,C                           ; $02D0  79
        DEC A                            ; $02D1  3D
        AND $01                          ; $02D2  E6 01     ; [AI] drive parity (even/odd)
        INC A                            ; $02D4  3C        ; [AI] -> 1 or 2
        RET                              ; $02D5  C9
        DEFS    42, $00    ; $02D6  fill
; ============================================================================
; EMBEDDED 6502 PAYLOAD  ($0300-$09FF)  -- 13-sector disk engine
;
; RW13 is a Z-80 transient that reconfigures a drive to read/write the older
; Apple 13-sector format. The actual low-level disk I/O runs on the 6502: this
; block is genuine 6502 machine code (NOT Z-80), carried verbatim in the .COM.
; The Z-80 front end stages it, points the SoftCard 6502 vector A$VEC (A_VEC) at
; $1300 (LD HL,$1300 / LD (A_VEC),HL above), and installs a BIOS sector handler
; that hands the CPU to the 6502 (SoftCard RPC via A_VEC/Z_CPU) for each I/O.
;
; The 6502 is disassembled as REAL 6502 in RW13_6502.s (ca65) and INCBIN'd here
; byte-for-byte, so each CPU's code is real source in its own assembler (the
; CPM_RPC6502 / CPM56 cross-CPU INCBIN pattern). The block is staged at Z-80
; $0300 but RUNS at Apple 6502 $1300, so RW13_6502.s is ORG'd at $1300; the
; staged bytes here are the same image. Routine map (run addresses; see
; RW13_6502.s for the full disassembly + the code/data split):
;   $1300 RELOCATE_PATCH  $1383 PATCH_SCAN  $1403 PRENIBBLE_WRITE
;   $146D WRITE_SECTOR    $1500 READ_SECTOR $1568 READ_ADDR_FIELD
;   $15C4 DENIBBLE_SECTOR $1621 SEEK_TRACK  $167E STEP_DELAY
;   $1800 DISK_DRIVER (resident 13-sector RWTS) + the $19E0 13-sector skew table
;
; Cross-CPU references: the Z-80 install path patches two parameter bytes inside
; the engine (see RW13_6502_PARAM_SLOT / _HEAD below). They are the only Z-80
; refs into the block; the "DEFW" words the 56K Z-80 disassembler reported inside
; this block are not real refs (they are 6502 code/table bytes -- see RW13_6502.s).
; ============================================================================
RW13_6502:
        INCBIN  "RW13_6502.bin"          ; $0300-$09FF  (1792 bytes of 6502, run @ $1300)
; Cross-CPU EQUs: the Z-80 patches these two bytes inside the staged 6502 image.
; Block base is Z-80 $0300 (= 6502 run $1300); offsets are file-relative.
RW13_6502_PARAM_SLOT EQU RW13_6502 + $050E  ; $080E  CMP #$60 operand at DISK_DRIVER $180D: slot-I/O base
RW13_6502_PARAM_HEAD EQU RW13_6502 + $0515  ; $0815  CMP #$02 operand at DISK_DRIVER $1814: head/side select

    SAVEBIN "RW13.bin", $0100, $0900
