; NOTE: comments marked [AI] are machine-generated by claude-opus-4-8 and may be
; inaccurate; treat them as hints, not verified annotation.

; Generated by disasm_z80
; Source: MFT
; Range:  $0100-$06FF  (1536 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
CDISK                EQU $0004               ; Current drive (low nibble: 0=A, 1=B, ..., 15=P) and current user (high nibble, 0-15).
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_FCB          EQU $005C               ; Default File Control Block — populated by CCP from command-line argument 1. Standard 36-byte FCB structure (drive + filename + extents + record number).
DEFAULT_CR           EQU $007C               ; Default FCB current record byte (overlaps end of DEFAULT_FCB2).
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).
CMDLINE              EQU $0081               ; Command-line tail characters (uppercase, with leading space). Same buffer as DEFAULT_DMA.

    ORG $0100

; [AI] Program entry at $0100. Sets the stack, prints the banner, clears state flags, and computes
;       how much free TPA memory is available to buffer copied files.
TPA_START:
        LD SP,$0A41                      ; $0100  31 41 0A
TPA_START_1:
        LD HL,MSG_BANNER                 ; $0103  21 E5 04
TPA_START_2:
        CALL PRINT_STRING                ; $0106  CD A2 04
TPA_START_3:
        XOR A                            ; $0109  AF
TPA_START_4:
        LD ($0B44),A                     ; $010A  32 44 0B
TPA_START_5:
        LD ($0B45),A                     ; $010D  32 45 0B
TPA_START_6:
        LD ($0B46),A                     ; $0110  32 46 0B
TPA_START_7:
        LD HL,($0006)                    ; $0113  2A 06 00
TPA_START_8:
        LD DE,$0B80                      ; $0116  11 80 0B
TPA_START_9:
        XOR A                            ; $0119  AF
TPA_START_10:
        SBC HL,DE                        ; $011A  ED 52
TPA_START_11:
        ADD HL,HL                        ; $011C  29
TPA_START_12:
        LD L,H                           ; $011D  6C
TPA_START_13:
        ADC A,A                          ; $011E  8F
TPA_START_14:
        LD H,A                           ; $011F  67
TPA_START_15:
        DEC HL                           ; $0120  2B
TPA_START_16:
        LD ($0A81),HL                    ; $0121  22 81 0A
TPA_START_17:
        LD A,(DEFAULT_DMA)               ; $0124  3A 80 00
TPA_START_18:
        DEC A                            ; $0127  3D
TPA_START_19:
        LD (DEFAULT_DMA),A               ; $0128  32 80 00
TPA_START_20:
        JP P,TPA_START_35                ; $012B  F2 51 01
TPA_START_21:
        XOR A                            ; $012E  AF
TPA_START_22:
        LD (DEFAULT_DMA),A               ; $012F  32 80 00
TPA_START_23:
        CALL PRINT_CRLF                  ; $0132  CD AB 04
TPA_START_24:
        LD A,$2A                         ; $0135  3E 2A
TPA_START_25:
        CALL CONOUT                      ; $0137  CD B2 04
TPA_START_26:
        LD A,$50                         ; $013A  3E 50
TPA_START_27:
        LD DE,DEFAULT_DMA                ; $013C  11 80 00
TPA_START_28:
        LD (DE),A                        ; $013F  12
TPA_START_29:
        LD C,$0A                         ; $0140  0E 0A
TPA_START_30:
        CALL BDOS_VEC                    ; $0142  CD 05 00
TPA_START_31:
        LD A,(CMDLINE)                   ; $0145  3A 81 00
TPA_START_32:
        LD (DEFAULT_DMA),A               ; $0148  32 80 00
TPA_START_33:
        OR A                             ; $014B  B7
TPA_START_34:
        JR Z,TPA_START_21                ; $014C  28 E0
        CALL PRINT_CRLF                  ; $014E  CD AB 04
TPA_START_35:
        LD HL,MSG_INSERT_SOURCE          ; $0151  21 3E 05
        CALL PRINT_STRING                ; $0154  CD A2 04
        CALL WAIT_FOR_RETURN             ; $0157  CD BD 04
        LD A,($0B44)                     ; $015A  3A 44 0B
        OR A                             ; $015D  B7
        JR NZ,TPA_START_39               ; $015E  20 3A
        LD HL,DEFAULT_DMA                ; $0160  21 80 00
        LD DE,$0A85                      ; $0163  11 85 0A
        LD B,(HL)                        ; $0166  46
        LD C,$00                         ; $0167  0E 00
        INC HL                           ; $0169  23
        INC HL                           ; $016A  23
TPA_START_36:
        LD A,(HL)                        ; $016B  7E
        CP $60                           ; $016C  FE 60
        JR C,TPA_START_37                ; $016E  38 02
        SUB $20                          ; $0170  D6 20
TPA_START_37:
        CP $20                           ; $0172  FE 20
        JR Z,TPA_START_38                ; $0174  28 01
        INC C                            ; $0176  0C
TPA_START_38:
        LD (DE),A                        ; $0177  12
        INC DE                           ; $0178  13
        INC HL                           ; $0179  23
        DJNZ TPA_START_36                ; $017A  10 EF
        XOR A                            ; $017C  AF
        LD (DE),A                        ; $017D  12
        CP C                             ; $017E  B9
        JR Z,TPA_START_21                ; $017F  28 AD
        LD HL,$0A85                      ; $0181  21 85 0A
        LD ($0AD5),HL                    ; $0184  22 D5 0A
        CALL PARSE_SOURCE_FCB_LIST       ; $0187  CD 7E 03
        LD A,($0B46)                     ; $018A  3A 46 0B
        OR A                             ; $018D  B7
        JP Z,TPA_START_56                ; $018E  CA 72 03
        LD HL,MSG_PRESS_RETURN           ; $0191  21 40 06
        LD ($0ADB),HL                    ; $0194  22 DB 0A
        LD ($0ADD),HL                    ; $0197  22 DD 0A
TPA_START_39:
        LD HL,MSG_COPYING                ; $019A  21 68 05
        CALL PRINT_STRING                ; $019D  CD A2 04
        LD HL,$0B80                      ; $01A0  21 80 0B
        LD ($0ADF),HL                    ; $01A3  22 DF 0A
        LD HL,($0A81)                    ; $01A6  2A 81 0A
        LD ($0A83),HL                    ; $01A9  22 83 0A
        LD A,($0B44)                     ; $01AC  3A 44 0B
        OR A                             ; $01AF  B7
        JR Z,TPA_START_40                ; $01B0  28 22
        LD HL,$0AE1                      ; $01B2  21 E1 0A
        LD DE,DEFAULT_FCB                ; $01B5  11 5C 00
        LD BC,$0021                      ; $01B8  01 21 00
        LDIR                             ; $01BB  ED B0
        XOR A                            ; $01BD  AF
        LD ($0B44),A                     ; $01BE  32 44 0B
        LD A,$01                         ; $01C1  3E 01
        LD ($0B45),A                     ; $01C3  32 45 0B
        LD HL,($0ADB)                    ; $01C6  2A DB 0A
        LD DE,$FFFC                      ; $01C9  11 FC FF
        ADD HL,DE                        ; $01CC  19
        LD ($0ADB),HL                    ; $01CD  22 DB 0A
        EX DE,HL                         ; $01D0  EB
        JP TPA_START_41                  ; $01D1  C3 02 02
TPA_START_40:
        LD HL,($0ADB)                    ; $01D4  2A DB 0A
        LD A,(HL)                        ; $01D7  7E
        CP $FF                           ; $01D8  FE FF
        JP Z,TPA_START_45                ; $01DA  CA 83 02
        LD (HL),$01                      ; $01DD  36 01
        INC HL                           ; $01DF  23
        LD DE,$005D                      ; $01E0  11 5D 00
        LD BC,$000B                      ; $01E3  01 0B 00
        LDIR                             ; $01E6  ED B0
        LD ($0ADB),HL                    ; $01E8  22 DB 0A
        LD HL,$005D                      ; $01EB  21 5D 00
        CALL PRINT_FCB_NAME              ; $01EE  CD 89 04
        XOR A                            ; $01F1  AF
        LD (DEFAULT_FCB),A               ; $01F2  32 5C 00
        LD ($0068),A                     ; $01F5  32 68 00
        LD (DEFAULT_CR),A                ; $01F8  32 7C 00
        CALL BDOS_DELETE_FILE            ; $01FB  CD CD 04
        LD HL,($0ADB)                    ; $01FE  2A DB 0A
        EX DE,HL                         ; $0201  EB
TPA_START_41:
        LD HL,($0ADF)                    ; $0202  2A DF 0A
        LD A,H                           ; $0205  7C
        LD (DE),A                        ; $0206  12
        INC DE                           ; $0207  13
        LD A,L                           ; $0208  7D
        LD (DE),A                        ; $0209  12
        INC DE                           ; $020A  13
        EX DE,HL                         ; $020B  EB
        LD ($0ADB),HL                    ; $020C  22 DB 0A
        LD HL,WBOOT_VEC                  ; $020F  21 00 00
        LD ($0AD7),HL                    ; $0212  22 D7 0A
TPA_START_42:
        LD HL,($0ADF)                    ; $0215  2A DF 0A
        EX DE,HL                         ; $0218  EB
        CALL BDOS_SET_DMA                ; $0219  CD DD 04
        LD C,$14                         ; $021C  0E 14
        LD DE,DEFAULT_FCB                ; $021E  11 5C 00
        CALL BDOS_VEC                    ; $0221  CD 05 00
        OR A                             ; $0224  B7
        JR Z,TPA_START_43                ; $0225  28 12
        CP $01                           ; $0227  FE 01
        JR Z,TPA_START_44                ; $0229  28 3A
        LD HL,MSG_DISK_READ_ERROR        ; $022B  21 92 05
        CALL PRINT_STRING                ; $022E  CD A2 04
        LD HL,$005D                      ; $0231  21 5D 00
        CALL PRINT_FCB_NAME              ; $0234  CD 89 04
        JR TPA_START_44                  ; $0237  18 2C
TPA_START_43:
        LD HL,($0ADF)                    ; $0239  2A DF 0A
        LD DE,DEFAULT_DMA                ; $023C  11 80 00
        ADD HL,DE                        ; $023F  19
        LD ($0ADF),HL                    ; $0240  22 DF 0A
        LD HL,($0AD7)                    ; $0243  2A D7 0A
        INC HL                           ; $0246  23
        LD ($0AD7),HL                    ; $0247  22 D7 0A
        LD HL,($0A83)                    ; $024A  2A 83 0A
        DEC HL                           ; $024D  2B
        LD ($0A83),HL                    ; $024E  22 83 0A
        LD A,H                           ; $0251  7C
        OR L                             ; $0252  B5
        JR NZ,TPA_START_42               ; $0253  20 C0
        LD HL,DEFAULT_FCB                ; $0255  21 5C 00
        LD DE,$0AE1                      ; $0258  11 E1 0A
        LD BC,$0021                      ; $025B  01 21 00
        LDIR                             ; $025E  ED B0
        LD A,$01                         ; $0260  3E 01
        LD ($0B44),A                     ; $0262  32 44 0B
TPA_START_44:
        LD DE,DEFAULT_DMA                ; $0265  11 80 00
        CALL BDOS_SET_DMA                ; $0268  CD DD 04
        CALL BDOS_CLOSE_FILE             ; $026B  CD D5 04
        LD HL,($0AD7)                    ; $026E  2A D7 0A
        EX DE,HL                         ; $0271  EB
        LD HL,($0ADB)                    ; $0272  2A DB 0A
        LD (HL),D                        ; $0275  72
        INC HL                           ; $0276  23
        LD (HL),E                        ; $0277  73
        INC HL                           ; $0278  23
        LD ($0ADB),HL                    ; $0279  22 DB 0A
        LD A,($0B44)                     ; $027C  3A 44 0B
        OR A                             ; $027F  B7
        JP Z,TPA_START_40                ; $0280  CA D4 01
TPA_START_45:
        LD HL,MSG_INSERT_DEST            ; $0283  21 A6 05
        CALL PRINT_STRING                ; $0286  CD A2 04
        CALL WAIT_FOR_RETURN             ; $0289  CD BD 04
        LD C,$0D                         ; $028C  0E 0D
        CALL BDOS_VEC                    ; $028E  CD 05 00
        LD A,($0B45)                     ; $0291  3A 45 0B
        OR A                             ; $0294  B7
        JR Z,TPA_START_46                ; $0295  28 1A
        LD HL,$0B02                      ; $0297  21 02 0B
        LD DE,DEFAULT_FCB                ; $029A  11 5C 00
        LD BC,$0021                      ; $029D  01 21 00
        LDIR                             ; $02A0  ED B0
        CALL BDOS_DELETE_FILE            ; $02A2  CD CD 04
        LD HL,($0ADD)                    ; $02A5  2A DD 0A
        LD DE,$FFFC                      ; $02A8  11 FC FF
        ADD HL,DE                        ; $02AB  19
        LD ($0ADD),HL                    ; $02AC  22 DD 0A
        JR TPA_START_49                  ; $02AF  18 4B
TPA_START_46:
        LD HL,($0ADD)                    ; $02B1  2A DD 0A
        LD A,(HL)                        ; $02B4  7E
        OR A                             ; $02B5  B7
        JP Z,TPA_START_55                ; $02B6  CA 6B 03
        CP $FF                           ; $02B9  FE FF
        JP Z,TPA_START_55                ; $02BB  CA 6B 03
TPA_START_47:
        INC HL                           ; $02BE  23
        LD DE,$005D                      ; $02BF  11 5D 00
        LD BC,$000B                      ; $02C2  01 0B 00
        LDIR                             ; $02C5  ED B0
        LD ($0ADD),HL                    ; $02C7  22 DD 0A
        XOR A                            ; $02CA  AF
        LD (DEFAULT_FCB),A               ; $02CB  32 5C 00
        LD ($0068),A                     ; $02CE  32 68 00
        LD (DEFAULT_CR),A                ; $02D1  32 7C 00
        LD A,($0065)                     ; $02D4  3A 65 00
        AND $7F                          ; $02D7  E6 7F
        LD ($0065),A                     ; $02D9  32 65 00
        LD A,($0066)                     ; $02DC  3A 66 00
        AND $7F                          ; $02DF  E6 7F
        LD ($0066),A                     ; $02E1  32 66 00
        LD DE,DEFAULT_FCB                ; $02E4  11 5C 00
        PUSH DE                          ; $02E7  D5
        LD C,$13                         ; $02E8  0E 13
        CALL BDOS_VEC                    ; $02EA  CD 05 00
        POP DE                           ; $02ED  D1
        LD C,$16                         ; $02EE  0E 16
        CALL BDOS_VEC                    ; $02F0  CD 05 00
TPA_START_48:
        INC A                            ; $02F3  3C
        JR NZ,TPA_START_49               ; $02F4  20 06
        LD HL,MSG_DISK_FULL              ; $02F6  21 FB 05
        JP TPA_START_54                  ; $02F9  C3 60 03
TPA_START_49:
        LD HL,($0ADD)                    ; $02FC  2A DD 0A
        LD D,(HL)                        ; $02FF  56
        INC HL                           ; $0300  23
        LD E,(HL)                        ; $0301  5E
        INC HL                           ; $0302  23
TPA_START_50:
        EX DE,HL                         ; $0303  EB
        LD ($0ADF),HL                    ; $0304  22 DF 0A
        EX DE,HL                         ; $0307  EB
        LD D,(HL)                        ; $0308  56
        INC HL                           ; $0309  23
        LD E,(HL)                        ; $030A  5E
        INC HL                           ; $030B  23
        EX DE,HL                         ; $030C  EB
        LD ($0AD7),HL                    ; $030D  22 D7 0A
        LD ($0AD9),HL                    ; $0310  22 D9 0A
        EX DE,HL                         ; $0313  EB
        LD ($0ADD),HL                    ; $0314  22 DD 0A
        LD HL,($0AD7)                    ; $0317  2A D7 0A
        LD A,H                           ; $031A  7C
        OR L                             ; $031B  B5
        JR Z,TPA_START_52                ; $031C  28 27
TPA_START_51:
        LD HL,($0ADF)                    ; $031E  2A DF 0A
        EX DE,HL                         ; $0321  EB
        CALL BDOS_SET_DMA                ; $0322  CD DD 04
        LD C,$15                         ; $0325  0E 15
        LD DE,DEFAULT_FCB                ; $0327  11 5C 00
        CALL BDOS_VEC                    ; $032A  CD 05 00
        OR A                             ; $032D  B7
        JR NZ,TPA_START_53               ; $032E  20 2D
        LD HL,($0ADF)                    ; $0330  2A DF 0A
        LD DE,DEFAULT_DMA                ; $0333  11 80 00
        ADD HL,DE                        ; $0336  19
        LD ($0ADF),HL                    ; $0337  22 DF 0A
        LD HL,($0AD7)                    ; $033A  2A D7 0A
        DEC HL                           ; $033D  2B
        LD ($0AD7),HL                    ; $033E  22 D7 0A
        LD A,H                           ; $0341  7C
        OR L                             ; $0342  B5
        JR NZ,TPA_START_51               ; $0343  20 D9
TPA_START_52:
        LD HL,DEFAULT_FCB                ; $0345  21 5C 00
        LD DE,$0B02                      ; $0348  11 02 0B
        LD BC,$0021                      ; $034B  01 21 00
        LDIR                             ; $034E  ED B0
        LD DE,DEFAULT_DMA                ; $0350  11 80 00
        CALL BDOS_SET_DMA                ; $0353  CD DD 04
        CALL BDOS_CLOSE_FILE             ; $0356  CD D5 04
        INC A                            ; $0359  3C
        JP NZ,TPA_START_46               ; $035A  C2 B1 02
TPA_START_53:
        LD HL,MSG_DISK_IO_ERROR          ; $035D  21 1C 06
TPA_START_54:
        CALL PRINT_STRING                ; $0360  CD A2 04
        LD HL,$005D                      ; $0363  21 5D 00
        CALL PRINT_FCB_NAME              ; $0366  CD 89 04
        JR TPA_START_56                  ; $0369  18 07
TPA_START_55:
        LD A,($0B44)                     ; $036B  3A 44 0B
        OR A                             ; $036E  B7
        JP NZ,TPA_START_35               ; $036F  C2 51 01
TPA_START_56:
        LD HL,MSG_INSERT_SYSTEM          ; $0372  21 D2 05
        CALL PRINT_STRING                ; $0375  CD A2 04
        CALL WAIT_FOR_RETURN             ; $0378  CD BD 04
        JP WBOOT_VEC                     ; $037B  C3 00 00
; [AI] Parses the entire command tail into a list of source-file FCB patterns, validating each via
;       BDOS search-first ($11) and counting how many ambiguous (wildcard) names were given.
PARSE_SOURCE_FCB_LIST:
        LD HL,MSG_PRESS_RETURN           ; $037E  21 40 06
        LD ($0ADB),HL                    ; $0381  22 DB 0A
PARSE_SOURCE_FCB_LIST_1:
        LD HL,($0AD5)                    ; $0384  2A D5 0A
        LD A,(HL)                        ; $0387  7E
        OR A                             ; $0388  B7
        RET Z                            ; $0389  C8
        CALL PARSE_FCB_TOKEN             ; $038A  CD 13 04
        LD ($0AD5),HL                    ; $038D  22 D5 0A
        JR NC,PARSE_SOURCE_FCB_LIST_2    ; $0390  30 09
        LD HL,MSG_COMMAND_ERROR          ; $0392  21 76 05
        CALL PRINT_STRING                ; $0395  CD A2 04
        JP TPA_START_56                  ; $0398  C3 72 03
PARSE_SOURCE_FCB_LIST_2:
        XOR A                            ; $039B  AF
        LD ($0B2F),A                     ; $039C  32 2F 0B
        LD DE,$0B23                      ; $039F  11 23 0B
        LD C,$11                         ; $03A2  0E 11
PARSE_SOURCE_FCB_LIST_3:
        CALL BDOS_VEC                    ; $03A4  CD 05 00
        CP $FF                           ; $03A7  FE FF
        JR NZ,PARSE_SOURCE_FCB_LIST_4    ; $03A9  20 0E
        LD HL,MSG_NOT_FOUND              ; $03AB  21 86 05
        CALL PRINT_STRING                ; $03AE  CD A2 04
        LD HL,$0B24                      ; $03B1  21 24 0B
        CALL PRINT_FCB_NAME              ; $03B4  CD 89 04
        JR PARSE_SOURCE_FCB_LIST_1       ; $03B7  18 CB
PARSE_SOURCE_FCB_LIST_4:
        AND $03                          ; $03B9  E6 03
        LD L,A                           ; $03BB  6F
        LD H,$00                         ; $03BC  26 00
        ADD HL,HL                        ; $03BE  29
        ADD HL,HL                        ; $03BF  29
        ADD HL,HL                        ; $03C0  29
        ADD HL,HL                        ; $03C1  29
        ADD HL,HL                        ; $03C2  29
        LD DE,DEFAULT_DMA                ; $03C3  11 80 00
        ADD HL,DE                        ; $03C6  19
        LD C,$12                         ; $03C7  0E 12
        PUSH HL                          ; $03C9  E5
        POP IX                           ; $03CA  DD E1
        BIT 7,(IX+10)                    ; $03CC  DD CB 0A 7E
        JR NZ,PARSE_SOURCE_FCB_LIST_3    ; $03D0  20 D2
PARSE_SOURCE_FCB_LIST_5:
        EX DE,HL                         ; $03D2  EB
        LD HL,$0B46                      ; $03D3  21 46 0B
        INC (HL)                         ; $03D6  34
        LD HL,($0ADB)                    ; $03D7  2A DB 0A
        EX DE,HL                         ; $03DA  EB
        LD BC,$000C                      ; $03DB  01 0C 00
        LDIR                             ; $03DE  ED B0
        LD HL,BDOS_SET_DMA_11            ; $03E0  21 2F 06
        LD BC,CDISK                      ; $03E3  01 04 00
        LDIR                             ; $03E6  ED B0
        EX DE,HL                         ; $03E8  EB
        LD ($0ADB),HL                    ; $03E9  22 DB 0A
        LD (HL),$FF                      ; $03EC  36 FF
        LD DE,$0B23                      ; $03EE  11 23 0B
PARSE_SOURCE_FCB_LIST_6:
        LD C,$12                         ; $03F1  0E 12
        CALL BDOS_VEC                    ; $03F3  CD 05 00
        CP $FF                           ; $03F6  FE FF
        JR Z,PARSE_SOURCE_FCB_LIST_1     ; $03F8  28 8A
        AND $03                          ; $03FA  E6 03
        LD L,A                           ; $03FC  6F
        LD H,$00                         ; $03FD  26 00
        ADD HL,HL                        ; $03FF  29
        ADD HL,HL                        ; $0400  29
        ADD HL,HL                        ; $0401  29
        ADD HL,HL                        ; $0402  29
        ADD HL,HL                        ; $0403  29
        LD DE,DEFAULT_DMA                ; $0404  11 80 00
        ADD HL,DE                        ; $0407  19
        PUSH HL                          ; $0408  E5
        POP IX                           ; $0409  DD E1
        BIT 7,(IX+10)                    ; $040B  DD CB 0A 7E
        JR NZ,PARSE_SOURCE_FCB_LIST_6    ; $040F  20 E0
        JR PARSE_SOURCE_FCB_LIST_5       ; $0411  18 BF
; [AI] Extracts one filename token from the command tail into an 11-byte FCB pattern: skips
;       comma/space separators, uppercases, expands '*' to '?' fill, and splits name from extension;
;       returns carry set on syntax error.
PARSE_FCB_TOKEN:
        LD A,(HL)                        ; $0413  7E
        OR A                             ; $0414  B7
        RET Z                            ; $0415  C8
        CP $2C                           ; $0416  FE 2C
        JR Z,PARSE_FCB_TOKEN_1           ; $0418  28 04
        CP $20                           ; $041A  FE 20
        JR NZ,PARSE_FCB_TOKEN_2          ; $041C  20 03
PARSE_FCB_TOKEN_1:
        INC HL                           ; $041E  23
        JR PARSE_FCB_TOKEN               ; $041F  18 F2
PARSE_FCB_TOKEN_2:
        LD DE,$0B23                      ; $0421  11 23 0B
        XOR A                            ; $0424  AF
        LD (DE),A                        ; $0425  12
        INC DE                           ; $0426  13
        PUSH DE                          ; $0427  D5
        LD B,$0B                         ; $0428  06 0B
        LD A,$20                         ; $042A  3E 20
PARSE_FCB_TOKEN_3:
        LD (DE),A                        ; $042C  12
        INC DE                           ; $042D  13
        DEC B                            ; $042E  05
        JR NZ,PARSE_FCB_TOKEN_3          ; $042F  20 FB
        POP DE                           ; $0431  D1
        LD B,$09                         ; $0432  06 09
PARSE_FCB_TOKEN_4:
        LD A,(HL)                        ; $0434  7E
        OR A                             ; $0435  B7
        JR Z,PARSE_FCB_TOKEN_10          ; $0436  28 4D
        INC HL                           ; $0438  23
        CP $2C                           ; $0439  FE 2C
        JR Z,PARSE_FCB_TOKEN_10          ; $043B  28 48
        CP $20                           ; $043D  FE 20
        JR Z,PARSE_FCB_TOKEN_10          ; $043F  28 44
        CP $2E                           ; $0441  FE 2E
        JR Z,PARSE_FCB_TOKEN_7           ; $0443  28 1A
        CP $2A                           ; $0445  FE 2A
        JR Z,PARSE_FCB_TOKEN_5           ; $0447  28 07
        LD (DE),A                        ; $0449  12
        INC DE                           ; $044A  13
        DEC B                            ; $044B  05
        JR Z,PARSE_FCB_TOKEN_11          ; $044C  28 39
        JR PARSE_FCB_TOKEN_4             ; $044E  18 E4
PARSE_FCB_TOKEN_5:
        DEC B                            ; $0450  05
        JR Z,PARSE_FCB_TOKEN_6           ; $0451  28 06
        LD A,$3F                         ; $0453  3E 3F
        LD (DE),A                        ; $0455  12
        INC DE                           ; $0456  13
        JR PARSE_FCB_TOKEN_5             ; $0457  18 F7
PARSE_FCB_TOKEN_6:
        LD A,(HL)                        ; $0459  7E
        CP $2E                           ; $045A  FE 2E
        JR NZ,PARSE_FCB_TOKEN_10         ; $045C  20 27
        INC HL                           ; $045E  23
PARSE_FCB_TOKEN_7:
        LD DE,$0B2C                      ; $045F  11 2C 0B
        LD B,$04                         ; $0462  06 04
PARSE_FCB_TOKEN_8:
        LD A,(HL)                        ; $0464  7E
        OR A                             ; $0465  B7
        JR Z,PARSE_FCB_TOKEN_10          ; $0466  28 1D
        INC HL                           ; $0468  23
        CP $2C                           ; $0469  FE 2C
        JR Z,PARSE_FCB_TOKEN_10          ; $046B  28 18
        CP $20                           ; $046D  FE 20
        JR Z,PARSE_FCB_TOKEN_10          ; $046F  28 14
        CP $2A                           ; $0471  FE 2A
        JR Z,PARSE_FCB_TOKEN_9           ; $0473  28 07
        LD (DE),A                        ; $0475  12
        INC DE                           ; $0476  13
        DEC B                            ; $0477  05
        JR Z,PARSE_FCB_TOKEN_11          ; $0478  28 0D
        JR PARSE_FCB_TOKEN_8             ; $047A  18 E8
PARSE_FCB_TOKEN_9:
        DEC B                            ; $047C  05
        JR Z,PARSE_FCB_TOKEN_10          ; $047D  28 06
        LD A,$3F                         ; $047F  3E 3F
        LD (DE),A                        ; $0481  12
        INC DE                           ; $0482  13
        JR PARSE_FCB_TOKEN_9             ; $0483  18 F7
PARSE_FCB_TOKEN_10:
        XOR A                            ; $0485  AF
        RET                              ; $0486  C9
PARSE_FCB_TOKEN_11:
        SCF                              ; $0487  37
        RET                              ; $0488  C9
; [AI] Prints an 8.3 filename from an FCB-style buffer to the console (8 name chars, a dot, then
;       the extension), used in error messages to show the offending file.
PRINT_FCB_NAME:
        LD B,$08                         ; $0489  06 08
PRINT_FCB_NAME_1:
        LD A,(HL)                        ; $048B  7E
        INC HL                           ; $048C  23
        CP $20                           ; $048D  FE 20
        JR Z,PRINT_FCB_NAME_2            ; $048F  28 03
        CALL CONOUT                      ; $0491  CD B2 04
PRINT_FCB_NAME_2:
        DJNZ PRINT_FCB_NAME_1            ; $0494  10 F5
        LD A,$2E                         ; $0496  3E 2E
        CALL CONOUT                      ; $0498  CD B2 04
        CALL PRINT_STRING                ; $049B  CD A2 04
        CALL PRINT_CRLF                  ; $049E  CD AB 04
        RET                              ; $04A1  C9
; [AI] Prints a null-terminated string pointed to by HL one character at a time via the console-
;       output helper; the standard message-printing routine.
PRINT_STRING:
        LD A,(HL)                        ; $04A2  7E
PRINT_STRING_1:
        OR A                             ; $04A3  B7
PRINT_STRING_2:
        RET Z                            ; $04A4  C8
PRINT_STRING_3:
        CALL CONOUT                      ; $04A5  CD B2 04
PRINT_STRING_4:
        INC HL                           ; $04A8  23
PRINT_STRING_5:
        JR PRINT_STRING                  ; $04A9  18 F7
; [AI] Emits a CRLF (carriage return $0D then line feed $0A) to the console by falling through into
;       the single-character output routine.
PRINT_CRLF:
        LD A,$0D                         ; $04AB  3E 0D
PRINT_CRLF_1:
        CALL CONOUT                      ; $04AD  CD B2 04
PRINT_CRLF_2:
        LD A,$0A                         ; $04B0  3E 0A
; [AI] Outputs the single character in A to the console via BDOS function 2, preserving HL and BC;
;       the lowest-level console-write primitive.
CONOUT:
        PUSH HL                          ; $04B2  E5
CONOUT_1:
        PUSH BC                          ; $04B3  C5
CONOUT_2:
        LD C,$02                         ; $04B4  0E 02
CONOUT_3:
        LD E,A                           ; $04B6  5F
CONOUT_4:
        CALL BDOS_VEC                    ; $04B7  CD 05 00
CONOUT_5:
        POP BC                           ; $04BA  C1
CONOUT_6:
        POP HL                           ; $04BB  E1
CONOUT_7:
        RET                              ; $04BC  C9
; [AI] Disk-swap pause: reads console keystrokes via BDOS function 1 until the user presses RETURN
;       ($0D), then prints a CRLF. The leading read of $E010 touches Apple II soft-switch/firmware
;       space mapped on the SoftCard.
WAIT_FOR_RETURN:
        LD A,($E010)                     ; $04BD  3A 10 E0
WAIT_FOR_RETURN_1:
        LD C,$01                         ; $04C0  0E 01
        CALL BDOS_VEC                    ; $04C2  CD 05 00
WAIT_FOR_RETURN_2:
        CP $0D                           ; $04C5  FE 0D
        JR NZ,WAIT_FOR_RETURN_1          ; $04C7  20 F7
        CALL PRINT_CRLF                  ; $04C9  CD AB 04
        RET                              ; $04CC  C9
; [AI] Deletes any existing destination file via BDOS function 15 (open... here used to
;       delete/erase) on the default FCB before re-creating it, preventing duplicate directory
;       entries.
BDOS_DELETE_FILE:
        LD DE,DEFAULT_FCB                ; $04CD  11 5C 00
        LD C,$0F                         ; $04D0  0E 0F
        JP BDOS_VEC                      ; $04D2  C3 05 00
; [AI] Closes the default FCB via BDOS function 16, flushing the directory entry after a file has
;       been written.
BDOS_CLOSE_FILE:
        LD DE,DEFAULT_FCB                ; $04D5  11 5C 00
        LD C,$10                         ; $04D8  0E 10
        JP BDOS_VEC                      ; $04DA  C3 05 00
; [AI] Sets the DMA transfer address to the buffer in DE via BDOS function 26 before each disk read
;       or write, then restores DE.
BDOS_SET_DMA:
        PUSH DE                          ; $04DD  D5
        LD C,$1A                         ; $04DE  0E 1A
        CALL BDOS_VEC                    ; $04E0  CD 05 00
        POP DE                           ; $04E3  D1
        RET                              ; $04E4  C9
MSG_BANNER:
        DEFB    $0D,$0A,$09,"  Softcard CP"        ; $04E5  CRLF TAB "  Softcard CP"
        DEFB    "/M",$0D,$0A,"Single Drive"        ; $04F5  "/M" CRLF "Single Drive"
        DEFB    " File Transfer Program"           ; $0505  string
        DEFB    $0D    ; $051B  terminator
        DEFB    $0A,"     (C) 1980 b"              ; $051C  LF "     (C) 1980 b"
        DEFB    "y Mycroft Labs"    ; $052C  string
        DEFB    $0D    ; $053A  terminator
        DEFB    $0A,$0A,$00                                      ; $053B
MSG_INSERT_SOURCE:
        DEFB    "Insert SOURCE      disk and press RETURN "    ; $053E  string
        DEFB    $00    ; $0567  terminator
MSG_COPYING:
        DEFB    $0D,$0A,"Copying -",$0D,$0A,$00 ; $0568  CRLF "Copying -" CRLF NUL
MSG_COMMAND_ERROR:
        DEFB    "Command error"    ; $0576  string
        DEFB    $0D    ; $0583  terminator
        DEFB    $0A,$00                                          ; $0584
MSG_NOT_FOUND:
        DEFB    "Not found: "    ; $0586  string
        DEFB    $00    ; $0591  terminator
MSG_DISK_READ_ERROR:
        DEFB    $0D,$0A,"Disk read erro"    ; $0592  CRLF "Disk read erro"
        DEFB    "r: "                        ; $05A2  "r: "
        DEFB    $00                          ; $05A5  terminator
MSG_INSERT_DEST:
        DEFB    $0D,$0A,"Insert DESTINA"    ; $05A6  CRLF "Insert DESTINA"
        DEFB    "TION disk and press RETURN "    ; $05B6  string
        DEFB    $00    ; $05D1  terminator
MSG_INSERT_SYSTEM:
        DEFB    $0D,$0A,"Insert a syste"    ; $05D2  CRLF "Insert a syste"
        DEFB    "m disk and press RETURN "    ; $05E2  string
        DEFB    $00    ; $05FA  terminator
MSG_DISK_FULL:
        DEFB    $0D,$0A,"Disk or direct"    ; $05FB  CRLF "Disk or direct"
        DEFB    "ory full error: "    ; $060B  string
        DEFB    $00    ; $061B  terminator
MSG_DISK_IO_ERROR:
        DEFB    $0D,$0A,"Disk I/O error"    ; $061C  CRLF "Disk I/O error"
        DEFB    ": ",$00                     ; $062C  ": " NUL
BDOS_SET_DMA_11:
        ; [AI] First 4 bytes are live numeric data: the LDIR at $03E0-$03E6 copies them
        ;      (BC=4) over CDISK..$0007 as an FCB-field init (all zero). The trailing
        ;      "INATION disk " ASCII is overlapping string-table tail shared with the
        ;      end of MSG_INSERT_DEST, never read as text from here.
        DEFB    $00,$00,$00,$00             ; $062F  4-byte zero data field (copied by LDIR)
        DEFB    "INATION disk "             ; $0633  overlapping string tail (data, not reached as text)
MSG_PRESS_RETURN:
        DEFB    "and press RETURN "    ; $0640  string
        DEFB    $00    ; $0651  terminator
        ; [AI] Unreferenced duplicate of MSG_INSERT_SYSTEM ($05D2); no live code points here.
        DEFB    $0D,$0A,"Insert a syste"    ; $0652  CRLF "Insert a syste"
        DEFB    "m disk and press RETURN "    ; $0662  string
        DEFB    $00    ; $067A  terminator
; [AI] $067B-$06FF: DEAD TAIL IMAGE -- left as DEFB data, NOT decoded to instructions.
;      These 133 bytes are code-shaped (they look like a relocated/alternate copy of the
;      destination-copy and error-report routines: CALLs to $02F3/$0303/$02BE, "JP $0371",
;      a "0D 0A Dis..." string fragment), but NO label, JP, CALL, or computed jump anywhere
;      in MFT reaches this range -- it is past the last live data (MSG_PRESS_RETURN $0640
;      and the unreferenced string at $0652). Several of its absolute operands also point
;      into the middle of live instructions/strings ($0371 is mid-"JP NZ" at $036F, $04F4 is
;      mid-MSG_BANNER), so the bytes do not form coherent code at THIS load address. It is a
;      stale build/relocation artifact in the file tail that is never executed; preserved
;      verbatim only to keep MFT.COM byte-identical.
DEAD_TAIL_IMAGE:
        DEFB    $0D,$0A,$44,$69,$73,$F3,$02,$CD,$03,$03,$CD,$BE,$02,$0E,$2C,$CD ; $067B
        DEFB    $15,$00,$C3,$F4,$04,$21,$12,$06,$C3,$99,$04,$21,$0E,$06,$CD,$F3 ; $068B
        DEFB    $02,$CD,$03,$03,$CD,$BE,$02,$C3,$71,$03,$7A,$E6,$38,$0F,$4F,$21 ; $069B
        DEFB    $EE,$05,$09,$CD,$F3,$02,$C3,$C5,$04,$21,$EA,$05,$CD,$F3,$02,$CD ; $06AB
        DEFB    $03,$03,$CD,$BE,$02,$0E,$2C,$CD,$15,$00,$7A,$E6,$07,$CD,$BE,$02 ; $06BB
        DEFB    $C3,$71,$03,$79,$87,$87,$4F,$21,$CE,$05,$09,$CD,$F3,$02,$CD,$A3 ; $06CB
        DEFB    $02,$F5,$CD,$A3,$02,$57,$F1,$5F,$CD,$95,$06,$C3,$71,$03,$79,$87 ; $06DB
        DEFB    $87,$4F,$21,$A6,$05,$09,$CD,$F3,$02,$CD,$A3,$02,$CD,$92,$06,$C3 ; $06EB
        DEFB    $71,$03,$79,$87,$87                              ; $06FB

    SAVEBIN "MFT.bin", $0100, $0600
