; NOTE: comments marked [AI] are machine-generated by claude-opus-4-8 and may be
; inaccurate; treat them as hints, not verified annotation.

; Generated by disasm_z80
; Source: diskcallbacks_223.bin
; Range:  $1A00-$1BFF  (512 bytes)

    DEVICE NOSLOT64K

    ORG $1A00

; [AI] Base/entry of the CP/M 2.23 SoftCard disk-callback thunk table ($1A00-$1AB3): a dense block
;       of Z-80 jump/call thunks that bridge BDOS/BIOS disk requests to the 6502 RWTS dispatch area
;       (CALL/JP into $A8xx-$A9xx) and read/write the disk-parameter variable block at $9Fxx.
;       Includes the sector-translate/deblocking math (LD HL,($9F43); ... ($A9AF)/($A9AD)), a
;       SETDMA/SETTRK/SETSEC-style address shuffle into ($A9B1)/($A9AD), a read/write driver call
;       (LD A,$02; LD ($A9D5),A; CALL $A707; CZ $A603), and a warm-boot stack reload (LD HL,($9F0F);
;       LD SP,HL). The disassembler decoded only the first opcode and emitted the remainder as DEFB;
;       bytes $1AB4-$1BFF are a separate undifferentiated data/status-bitmap table (repeating FF FF
;       00 00 / F7 F7 pattern, no distinct labels).
L_1A00:
        XOR C                            ; $1A00  A9
        JP $A929                         ; $1A01  C3 29 A9
        DEFB    $3A,$42,$9F,$C3,$01,$9F,$EB,$22,$B1,$A9,$C3,$DA,$A1,$2A,$BF,$A9 ; $1A04
        DEFB    $C3,$29,$A9,$2A,$AD,$A9,$C3,$29,$A9,$CD,$51,$A8,$CD,$3B,$A4,$C3 ; $1A14
        DEFB    $01,$A3,$2A,$BB,$A9,$22,$45,$9F,$C9,$3A,$D6,$A9,$FE,$FF,$C2,$3B ; $1A24
        DEFB    $A9,$3A,$41,$9F,$C3,$01,$9F,$E6,$1F,$32,$41,$9F,$C9,$CD,$51,$A8 ; $1A34
        DEFB    $C3,$93,$A7,$CD,$51,$A8,$C3,$9C,$A7,$CD,$51,$A8,$C3,$D2,$A7,$2A ; $1A44
        DEFB    $43,$9F,$7D,$2F,$5F,$7C,$2F,$2A,$AF,$A9,$A4,$57,$7D,$A3,$5F,$2A ; $1A54
        DEFB    $AD,$A9,$EB,$22,$AF,$A9,$7D,$A3,$6F,$7C,$A2,$67,$22,$AD,$A9,$C9 ; $1A64
        DEFB    $3A,$DE,$A9,$B7,$CA,$91,$A9,$2A,$43,$9F,$36,$00,$3A,$E0,$A9,$B7 ; $1A74
        DEFB    $CA,$91,$A9,$77,$3A,$DF,$A9,$32,$D6,$A9,$CD,$45,$A8,$2A,$0F,$9F ; $1A84
        DEFB    $F9,$2A,$45,$9F,$7D,$44,$C9,$CD,$51,$A8,$3E,$02,$32,$D5,$A9,$0E ; $1A94
        DEFB    $00,$CD,$07,$A7,$CC,$03,$A6,$C9,$E5,$00,$00,$00,$00,$80,$00,$00 ; $1AA4
        DEFS    76, $00    ; $1AB4  fill
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1B00
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$10,$10,$FF,$FF,$00,$10,$FF,$FF,$10,$00 ; $1B10
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$10,$10,$FF,$FF,$00,$10,$FF,$FF,$10,$00 ; $1B20
        DEFB    $F7,$F7,$00,$00,$F7,$F7,$00,$10,$F7,$F7,$00,$00,$F7,$F7,$10,$00 ; $1B30
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$10,$10,$FF,$FF,$00,$10,$FF,$FF,$10,$00 ; $1B40
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1B50
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1B60
        DEFB    $F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00 ; $1B70
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1B80
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1B90
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1BA0
        DEFB    $F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00 ; $1BB0
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1BC0
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1BD0
        DEFB    $FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00 ; $1BE0
        DEFB    $F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00 ; $1BF0

    SAVEBIN "CPM_DiskCallbacks.bin", $1A00, $0200
