; NOTE: comments marked [AI] are machine-generated by claude-opus-4-8 and may be
; inaccurate; treat them as hints, not verified annotation.

; Generated by disasm_z80
; Source: CPM223_BIOS_Disk
; Range:  $FA00-$FDFF  (1024 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
CDISK                EQU $0004               ; Current drive (low nibble: 0=A, 1=B, ..., 15=P) and current user (high nibble, 0-15).
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).
BDOS_ENTRY_223       EQU $9C06               ; BDOS entry point -- planted at $0005-$0007 as JP $9C06
BDOS_SENTINEL        EQU $9C08               ; First-boot vs warm-boot detect (initialized to $9C; $FB7F-$FB85 checks)
SLOT_INFO_BASE       EQU $F3B8               ; Slot-info table for cold-boot generator (F3B8+E = slot E's device code, E=1..7)
HOME_IMPL            EQU $FE6C               ; HOME implementation (jump-table entry 8 target)
SETTRK_IMPL          EQU $FE77               ; SETTRK implementation (jump-table entry 10 target)
INIT_KEYBOARD        EQU $FE81               ; Slot init for keyboard / generic input (device code 3)
SELDSK_IMPL          EQU $FE8E               ; SELDSK implementation (jump-table entry 9 target)
READ_IMPL            EQU $FEBD               ; READ implementation (jump-table entry 13 target)
WRITE_IMPL           EQU $FEC0               ; WRITE implementation (jump-table entry 14 target)
BOOT_LANDING         EQU $FED1               ; BOOT NOP-slide landing -- runtime-generated entry to device-scan
BIOS_FLAG_FED8       EQU $FED8               ; Zeroed by cold-boot setup at $FB9F
BIOS_FLAG_FEDD       EQU $FEDD               ; Zeroed by cold-boot setup at $FB9C

    ORG $FA00

; [AI] First BIOS jump-table entry; cold-start entry reached from the boot loader, vectoring to the
;       device-scan landing routine.
BOOT:
        JP BOOT_LANDING                  ; $FA00  C3 D1 FE
; [AI] Warm-boot jump-table entry; reloads the CCP and re-establishes the page-zero vectors after a
;       program exits.
WBOOT:
        JP WBOOT_IMPL                    ; $FA03  C3 B8 FA
; [AI] Console status jump-table entry; returns A=$FF if a console character is ready, $00
;       otherwise.
CONST:
        JP CONST_IMPL                    ; $FA06  C3 10 FB
; [AI] Console input jump-table entry; waits for and returns the next console keystroke in A.
CONIN:
        JP CONIN_IMPL                    ; $FA09  C3 1A FB
; [AI] Console output jump-table entry; writes the character in C to the console device.
CONOUT:
        JP CONOUT_IMPL                   ; $FA0C  C3 4D FB
; [AI] List-device (printer) output jump-table entry; sends the character in C to the LST: device.
LIST:
        JP LIST_IMPL                     ; $FA0F  C3 70 FB
; [AI] Paper-tape punch output jump-table entry; sends the character in C to the PUN: device.
PUNCH:
        JP PUNCH_IMPL                    ; $FA12  C3 7F FB
; [AI] Paper-tape reader input jump-table entry; returns the next character from the RDR: device in
;       A.
READER:
        JP READER_IMPL                   ; $FA15  C3 91 FB
; [AI] HOME jump-table entry; vectors to the routine that seeks the selected drive to track 0.
HOME:
        JP HOME_IMPL                     ; $FA18  C3 6C FE
; [AI] SELDSK jump-table entry; vectors to drive selection, returning the chosen drive's DPH
;       pointer.
SELDSK:
        JP SELDSK_IMPL                   ; $FA1B  C3 8E FE
; [AI] SETTRK jump-table entry; vectors to the routine that latches the target track for the next
;       transfer.
SETTRK:
        JP SETTRK_IMPL                   ; $FA1E  C3 77 FE
; [AI] SETSEC jump-table entry; latches the target sector number for the next READ/WRITE.
SETSEC:
        JP SETSEC_IMPL                   ; $FA21  C3 F4 FB
; [AI] SETDMA jump-table entry; sets the memory address the next disk transfer reads into or writes
;       from.
SETDMA:
        JP SETDMA_IMPL                   ; $FA24  C3 F9 FB
; [AI] READ jump-table entry; vectors to the sector-read routine that fills the DMA buffer.
READ:
        JP READ_IMPL                     ; $FA27  C3 BD FE
; [AI] WRITE jump-table entry; vectors to the sector-write routine that flushes the DMA buffer to
;       disk.
WRITE:
        JP WRITE_IMPL                    ; $FA2A  C3 C0 FE
; [AI] List-status jump-table entry; here a stub that always returns A=0 (printer never ready),
;       since the SoftCard list device has no status query.
LISTST:
        XOR A                            ; $FA2D  AF
        RET                              ; $FA2E  C9
        DEFB    $00                                              ; $FA2F
; [AI] Sector-translate jump-table entry; performs a null (identity) translation by returning the
;       logical sector in HL unchanged, deferring real skew to the disk routines.
SECTRAN:
        LD H,B                           ; $FA30  60
        LD L,C                           ; $FA31  69
        RET                              ; $FA32  C9
        DEFS    8, $00    ; $FA33  fill
        DEFB    $E4,$FE,$73,$FA,$AC,$FF,$64,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; $FA3B
        DEFB    $E4,$FE,$73,$FA,$B8,$FF,$76,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; $FA4B
        DEFB    $E4,$FE,$73,$FA,$C4,$FF,$88,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; $FA5B
        DEFB    $E4,$FE,$73,$FA,$D0,$FF,$9A,$FF,$20,$00,$03,$07,$00,$8B,$00,$2F ; $FA6B
        DEFB    $00,$C0,$00,$0C,$00,$03,$00                      ; $FA7B
; [AI] Cold-boot device-scan driver; sets the loop counter to scan slots 7 down to 1 looking for
;       recognized peripherals.
DEVICE_SCAN:
        LD DE,$0007                      ; $FA82  11 07 00
; [AI] Body of the slot-scan loop; reads SLOT_INFO_BASE+E for the current slot and dispatches on
;       its device code to the matching initializer (keyboard, Pascal 1.0, Pascal 1.1).
DEVICE_SCAN_1:
        LD HL,SLOT_INFO_BASE             ; $FA85  21 B8 F3
        ADD HL,DE                        ; $FA88  19
        LD A,(HL)                        ; $FA89  7E
        SUB $03                          ; $FA8A  D6 03
        JR NZ,DEVICE_SCAN_2              ; $FA8C  20 07
        CALL INIT_KEYBOARD               ; $FA8E  CD 81 FE
        LD (HL),$03                      ; $FA91  36 03
        LD (HL),$15                      ; $FA93  36 15
DEVICE_SCAN_2:
        DEC A                            ; $FA95  3D
        JR NZ,DEVICE_SCAN_3              ; $FA96  20 0B
        CALL INIT_PASCAL_1_0             ; $FA98  CD 83 FD
        LD HL,$C800                      ; $FA9B  21 00 C8
        CALL RPC_DISPATCH                ; $FA9E  CD 45 FB
        JR DEVICE_SCAN_4                 ; $FAA1  18 0A
DEVICE_SCAN_3:
        CP $02                           ; $FAA3  FE 02
        JR NZ,DEVICE_SCAN_4              ; $FAA5  20 06
        LD HL,$0DD0                      ; $FAA7  21 D0 0D
        CALL INIT_PASCAL_1_1             ; $FAAA  CD B0 FD
DEVICE_SCAN_4:
        DEC E                            ; $FAAD  1D
        JR NZ,DEVICE_SCAN_1              ; $FAAE  20 D5
        RET                              ; $FAB0  C9
        DEFB    $21,$00,$E0,$7B,$B4,$67,$C9                      ; $FAB1
; [AI] WBOOT body; resets the stack to $0080, reinitializes devices, and on a warm boot rebuilds
;       the page-zero jump vectors before returning to the CCP.
WBOOT_IMPL:
        LD SP,DEFAULT_DMA                ; $FAB8  31 80 00
        LD A,($E051)                     ; $FABB  3A 51 E0
        LD HL,$0E00                      ; $FABE  21 00 0E
        CALL RPC_DISPATCH                ; $FAC1  CD 45 FB
        CALL DEVICE_SCAN                 ; $FAC4  CD 82 FA
        LD A,(BDOS_SENTINEL)             ; $FAC7  3A 08 9C
        CP $9C                           ; $FACA  FE 9C
        JR Z,INSTALL_PAGE0_VEC           ; $FACC  28 11
        LD HL,$FF59                      ; $FACE  21 59 FF
        LD ($F3D0),HL                    ; $FAD1  22 D0 F3
        LD HL,($F3DE)                    ; $FAD4  2A DE F3
        LD A,$77                         ; $FAD7  3E 77
        LD ($000B),A                     ; $FAD9  32 0B 00
        JP $000B                         ; $FADC  C3 0B 00
; [AI] Cold-boot branch taken when the sentinel matches; clears BIOS flags and plants the page-zero
;       JP WBOOT at $0000 and JP BDOS at $0005.
INSTALL_PAGE0_VEC:
        XOR A                            ; $FADF  AF
        LD ($9307),A                     ; $FAE0  32 07 93
        XOR A                            ; $FAE3  AF
        LD (BIOS_FLAG_FEDD),A            ; $FAE4  32 DD FE
        LD (BIOS_FLAG_FED8),A            ; $FAE7  32 D8 FE
        LD A,$C3                         ; $FAEA  3E C3
        LD (WBOOT_VEC),A                 ; $FAEC  32 00 00
        LD HL,WBOOT                      ; $FAEF  21 03 FA
        LD ($0001),HL                    ; $FAF2  22 01 00
        LD (BDOS_VEC),A                  ; $FAF5  32 05 00
        LD HL,BDOS_ENTRY_223             ; $FAF8  21 06 9C
        LD ($0006),HL                    ; $FAFB  22 06 00
        LD BC,$FF80                      ; $FAFE  01 80 FF
        RST $38                          ; $FB01  FF
        NOP                              ; $FB02  00
        NOP                              ; $FB03  00
        RST $38                          ; $FB04  FF
        RST $38                          ; $FB05  FF
        NOP                              ; $FB06  00
        NOP                              ; $FB07  00
        RST $38                          ; $FB08  FF
        RST $38                          ; $FB09  FF
        NOP                              ; $FB0A  00
        NOP                              ; $FB0B  00
        RST $38                          ; $FB0C  FF
        RST $38                          ; $FB0D  FF
        NOP                              ; $FB0E  00
        NOP                              ; $FB0F  00
; [AI] CONST implementation target; un-patched placeholder in the on-disk image, written by the
;       cold-boot generator that builds the live console routines.
CONST_IMPL:
        RST $30                          ; $FB10  F7
        RST $30                          ; $FB11  F7
        NOP                              ; $FB12  00
        NOP                              ; $FB13  00
        RST $30                          ; $FB14  F7
        RST $30                          ; $FB15  F7
        NOP                              ; $FB16  00
        NOP                              ; $FB17  00
        RST $30                          ; $FB18  F7
        RST $30                          ; $FB19  F7
; [AI] CONIN implementation target; un-patched placeholder filled in at cold boot with the real
;       console-input code.
CONIN_IMPL:
        NOP                              ; $FB1A  00
        NOP                              ; $FB1B  00
        RST $30                          ; $FB1C  F7
        RST $30                          ; $FB1D  F7
        NOP                              ; $FB1E  00
        NOP                              ; $FB1F  00
        RST $38                          ; $FB20  FF
        RST $38                          ; $FB21  FF
        NOP                              ; $FB22  00
        NOP                              ; $FB23  00
        RST $38                          ; $FB24  FF
        RST $38                          ; $FB25  FF
        NOP                              ; $FB26  00
        NOP                              ; $FB27  00
        RST $38                          ; $FB28  FF
        RST $38                          ; $FB29  FF
        NOP                              ; $FB2A  00
        NOP                              ; $FB2B  00
        RST $38                          ; $FB2C  FF
        RST $38                          ; $FB2D  FF
        NOP                              ; $FB2E  00
        NOP                              ; $FB2F  00
        RST $38                          ; $FB30  FF
CONIN_IMPL_1:
        RST $38                          ; $FB31  FF
        NOP                              ; $FB32  00
        NOP                              ; $FB33  00
        RST $38                          ; $FB34  FF
        RST $38                          ; $FB35  FF
        NOP                              ; $FB36  00
        NOP                              ; $FB37  00
        RST $38                          ; $FB38  FF
CONIN_IMPL_2:
        RST $38                          ; $FB39  FF
        NOP                              ; $FB3A  00
        NOP                              ; $FB3B  00
        RST $38                          ; $FB3C  FF
        RST $38                          ; $FB3D  FF
        NOP                              ; $FB3E  00
        NOP                              ; $FB3F  00
        RST $38                          ; $FB40  FF
        RST $38                          ; $FB41  FF
        NOP                              ; $FB42  00
        NOP                              ; $FB43  00
        RST $38                          ; $FB44  FF
; [AI] Helper that drives the 6502 side from Z-80 code (HL carries a 6502-side address/command);
;       the body is generated at runtime, so it is a stub here.
RPC_DISPATCH:
        RST $38                          ; $FB45  FF
        NOP                              ; $FB46  00
        NOP                              ; $FB47  00
        RST $38                          ; $FB48  FF
        RST $38                          ; $FB49  FF
        NOP                              ; $FB4A  00
        NOP                              ; $FB4B  00
        RST $38                          ; $FB4C  FF
; [AI] CONOUT implementation target; un-patched placeholder filled in at cold boot with the real
;       console-output code.
CONOUT_IMPL:
        RST $38                          ; $FB4D  FF
        NOP                              ; $FB4E  00
        NOP                              ; $FB4F  00
        RST $38                          ; $FB50  FF
        RST $38                          ; $FB51  FF
        NOP                              ; $FB52  00
        NOP                              ; $FB53  00
        RST $38                          ; $FB54  FF
        RST $38                          ; $FB55  FF
        NOP                              ; $FB56  00
        NOP                              ; $FB57  00
        RST $38                          ; $FB58  FF
        RST $38                          ; $FB59  FF
CONOUT_IMPL_1:
        NOP                              ; $FB5A  00
        NOP                              ; $FB5B  00
        RST $38                          ; $FB5C  FF
        RST $38                          ; $FB5D  FF
        NOP                              ; $FB5E  00
        NOP                              ; $FB5F  00
        RST $38                          ; $FB60  FF
        RST $38                          ; $FB61  FF
        NOP                              ; $FB62  00
        NOP                              ; $FB63  00
        RST $38                          ; $FB64  FF
        RST $38                          ; $FB65  FF
        NOP                              ; $FB66  00
        NOP                              ; $FB67  00
        RST $38                          ; $FB68  FF
        RST $38                          ; $FB69  FF
        NOP                              ; $FB6A  00
        NOP                              ; $FB6B  00
        RST $38                          ; $FB6C  FF
        RST $38                          ; $FB6D  FF
        NOP                              ; $FB6E  00
        NOP                              ; $FB6F  00
; [AI] LIST implementation target; un-patched placeholder for the printer-output routine, generated
;       at cold boot.
LIST_IMPL:
        RST $30                          ; $FB70  F7
        RST $30                          ; $FB71  F7
        NOP                              ; $FB72  00
        NOP                              ; $FB73  00
        RST $30                          ; $FB74  F7
        RST $30                          ; $FB75  F7
        NOP                              ; $FB76  00
        NOP                              ; $FB77  00
        RST $30                          ; $FB78  F7
        RST $30                          ; $FB79  F7
        NOP                              ; $FB7A  00
        NOP                              ; $FB7B  00
        RST $30                          ; $FB7C  F7
        RST $30                          ; $FB7D  F7
        NOP                              ; $FB7E  00
; [AI] PUNCH implementation target; un-patched placeholder, since the punch device is generated (or
;       stubbed) at cold boot.
PUNCH_IMPL:
        NOP                              ; $FB7F  00
        RST $38                          ; $FB80  FF
        RST $38                          ; $FB81  FF
        NOP                              ; $FB82  00
        NOP                              ; $FB83  00
        RST $38                          ; $FB84  FF
        RST $38                          ; $FB85  FF
        NOP                              ; $FB86  00
        NOP                              ; $FB87  00
        RST $38                          ; $FB88  FF
        RST $38                          ; $FB89  FF
        NOP                              ; $FB8A  00
        NOP                              ; $FB8B  00
        RST $38                          ; $FB8C  FF
        RST $38                          ; $FB8D  FF
        NOP                              ; $FB8E  00
        NOP                              ; $FB8F  00
        RST $38                          ; $FB90  FF
; [AI] READER implementation target; un-patched placeholder for the reader-input routine, generated
;       at cold boot.
READER_IMPL:
        RST $38                          ; $FB91  FF
        NOP                              ; $FB92  00
        NOP                              ; $FB93  00
        RST $38                          ; $FB94  FF
        RST $38                          ; $FB95  FF
        NOP                              ; $FB96  00
        NOP                              ; $FB97  00
        RST $38                          ; $FB98  FF
        RST $38                          ; $FB99  FF
        NOP                              ; $FB9A  00
        NOP                              ; $FB9B  00
        RST $38                          ; $FB9C  FF
        RST $38                          ; $FB9D  FF
        NOP                              ; $FB9E  00
        NOP                              ; $FB9F  00
        RST $38                          ; $FBA0  FF
        RST $38                          ; $FBA1  FF
        NOP                              ; $FBA2  00
        NOP                              ; $FBA3  00
        RST $38                          ; $FBA4  FF
        RST $38                          ; $FBA5  FF
        NOP                              ; $FBA6  00
        NOP                              ; $FBA7  00
        RST $38                          ; $FBA8  FF
        RST $38                          ; $FBA9  FF
        NOP                              ; $FBAA  00
        NOP                              ; $FBAB  00
        RST $38                          ; $FBAC  FF
        RST $38                          ; $FBAD  FF
        NOP                              ; $FBAE  00
        NOP                              ; $FBAF  00
        RST $38                          ; $FBB0  FF
        RST $38                          ; $FBB1  FF
        NOP                              ; $FBB2  00
        NOP                              ; $FBB3  00
        RST $38                          ; $FBB4  FF
        RST $38                          ; $FBB5  FF
        NOP                              ; $FBB6  00
        NOP                              ; $FBB7  00
        RST $38                          ; $FBB8  FF
        RST $38                          ; $FBB9  FF
        NOP                              ; $FBBA  00
        NOP                              ; $FBBB  00
        RST $38                          ; $FBBC  FF
        RST $38                          ; $FBBD  FF
        NOP                              ; $FBBE  00
        NOP                              ; $FBBF  00
        RST $38                          ; $FBC0  FF
        RST $38                          ; $FBC1  FF
        NOP                              ; $FBC2  00
        NOP                              ; $FBC3  00
READER_IMPL_1:
        RST $38                          ; $FBC4  FF
        RST $38                          ; $FBC5  FF
READER_IMPL_2:
        NOP                              ; $FBC6  00
        NOP                              ; $FBC7  00
        RST $38                          ; $FBC8  FF
        RST $38                          ; $FBC9  FF
        NOP                              ; $FBCA  00
        NOP                              ; $FBCB  00
        RST $38                          ; $FBCC  FF
        RST $38                          ; $FBCD  FF
        NOP                              ; $FBCE  00
        NOP                              ; $FBCF  00
READER_IMPL_3:
        RST $38                          ; $FBD0  FF
        RST $38                          ; $FBD1  FF
        NOP                              ; $FBD2  00
        NOP                              ; $FBD3  00
        RST $38                          ; $FBD4  FF
        RST $38                          ; $FBD5  FF
        NOP                              ; $FBD6  00
        NOP                              ; $FBD7  00
        RST $38                          ; $FBD8  FF
        RST $38                          ; $FBD9  FF
        NOP                              ; $FBDA  00
        NOP                              ; $FBDB  00
        RST $38                          ; $FBDC  FF
        RST $38                          ; $FBDD  FF
        NOP                              ; $FBDE  00
        NOP                              ; $FBDF  00
        RST $38                          ; $FBE0  FF
        RST $38                          ; $FBE1  FF
READER_IMPL_4:
        NOP                              ; $FBE2  00
        NOP                              ; $FBE3  00
        RST $38                          ; $FBE4  FF
        RST $38                          ; $FBE5  FF
        NOP                              ; $FBE6  00
        NOP                              ; $FBE7  00
        RST $38                          ; $FBE8  FF
        RST $38                          ; $FBE9  FF
        NOP                              ; $FBEA  00
        NOP                              ; $FBEB  00
        RST $38                          ; $FBEC  FF
        RST $38                          ; $FBED  FF
        NOP                              ; $FBEE  00
        NOP                              ; $FBEF  00
        RST $30                          ; $FBF0  F7
        RST $38                          ; $FBF1  FF
        NOP                              ; $FBF2  00
        NOP                              ; $FBF3  00
; [AI] SETSEC implementation target; un-patched stub that the cold-boot generator replaces with the
;       real sector-latch code.
SETSEC_IMPL:
        RST $38                          ; $FBF4  FF
        RST $38                          ; $FBF5  FF
        NOP                              ; $FBF6  00
        NOP                              ; $FBF7  00
        RST $38                          ; $FBF8  FF
; [AI] SETDMA implementation target; in the pristine image the body is an un-patched stub that the
;       6502 cold-boot generator fills in.
SETDMA_IMPL:
        RST $38                          ; $FBF9  FF
        NOP                              ; $FBFA  00
        NOP                              ; $FBFB  00
        RST $38                          ; $FBFC  FF
        RST $38                          ; $FBFD  FF
        NOP                              ; $FBFE  00
        NOP                              ; $FBFF  00
        NOP                              ; $FC00  00
        CALL SETDMA_IMPL                 ; $FC01  CD F9 FB
        LD A,$01                         ; $FC04  3E 01
        LD ($974E),A                     ; $FC06  32 4E 97
        LD A,(CDISK)                     ; $FC09  3A 04 00
        LD C,A                           ; $FC0C  4F
        JP $9300                         ; $FC0D  C3 00 93
        DEFB    $2A,$80,$F3,$E9,$3A,$00,$E0,$17,$9F,$C9,$CD      ; $FC10
        DEFW    CONOUT_IMPL_1            ; $FC1B
        DEFB    $E6,$7F,$21,$AB,$F3,$06,$06,$4F,$23,$7E,$23,$B7,$FA ; $FC1D
        DEFW    CONIN_IMPL_1             ; $FC2A
        DEFB    $B9,$7E,$C8,$10,$F4,$79,$C9,$11,$03,$00,$C3      ; $FC2C
        DEFW    CONIN_IMPL_2             ; $FC37
        DEFB    $3A,$00,$E0,$17                                  ; $FC39
        DEFW    SECTRAN                  ; $FC3D
        DEFB    $32,$10,$E0,$3F,$1F,$C9,$22,$D0,$F3,$32,$00,$00,$C9,$4F,$3A,$03 ; $FC3F
        DEFB    $00,$E6,$03,$FE,$02,$20,$4B,$2A,$92,$F3,$E9,$3A,$03,$00,$E6,$03 ; $FC4F
        DEFB    $FE,$02,$2A,$84,$F3,$28,$06,$30,$07,$2A,$82,$F3,$E9,$2A,$8A,$F3 ; $FC5F
        DEFB    $E9,$3A,$03,$00,$E6,$C0,$FE,$80,$38,$27,$28,$DB,$2A,$94,$F3,$E9 ; $FC6F
        DEFB    $3A,$03,$00,$E6,$30,$FE,$10,$38,$18,$2A,$8E,$F3,$28,$E2,$2A,$90 ; $FC7F
        DEFB    $F3,$E9,$3A,$03,$00,$E6,$0C,$FE,$08,$38,$CE,$28,$D0,$2A,$8C,$F3 ; $FC8F
        DEFB    $E9,$37,$9F,$21,$A2,$F3,$6E,$2C,$CA,$A4,$FC,$21,$CB,$FE,$77,$CB ; $FC9F
        DEFB    $B9,$23,$7E,$B7,$CA,$56,$FC,$35,$3A,$96,$F3,$21,$D4,$FE,$28,$0C ; $FCAF
        DEFB    $B7,$F2                                          ; $FCBF
        DEFW    READER_IMPL_2            ; $FCC1
        DEFB    $2B,$E6,$7F,$5F,$79,$93,$77,$C9,$B7,$FA          ; $FCC3
        DEFW    READER_IMPL_3            ; $FCCD
        DEFB    $2B,$CD                                          ; $FCCF
        DEFW    READER_IMPL_1            ; $FCD1
        DEFB    $2A,$D3,$FE,$3A,$A1,$F3,$B7,$F2                  ; $FCD3
        DEFW    READER_IMPL_4            ; $FCDB
        DEFB    $E6,$7F,$5D,$6C,$63,$5F,$84,$4F,$7B,$85,$F5,$06,$07,$CD,$A4,$FC ; $FCDD
        DEFB    $F1,$06,$0A,$4F,$C3,$A4,$FC,$79,$32,$D2,$FE,$C9,$ED,$43,$E1,$FE ; $FCED
        DEFB    $C9,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF ; $FCFD
        DEFB    $FF,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7 ; $FD0D
        DEFB    $F7,$10,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF ; $FD1D
        DEFB    $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF ; $FD2D
        DEFB    $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF ; $FD3D
        DEFB    $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF ; $FD4D
        DEFB    $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$00,$FF ; $FD5D
        DEFB    $FF,$10,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7,$F7,$00,$00,$F7 ; $FD6D
        DEFB    $F7,$00,$00,$FF,$FF,$00                          ; $FD7D
; [AI] Per-slot initializer for a card matching the Pascal 1.0 firmware-protocol device code; in
;       this pristine image its body is an un-patched placeholder filled at cold boot.
INIT_PASCAL_1_0:
        NOP                              ; $FD83  00
        RST $38                          ; $FD84  FF
        RST $38                          ; $FD85  FF
        NOP                              ; $FD86  00
        NOP                              ; $FD87  00
        RST $38                          ; $FD88  FF
        RST $38                          ; $FD89  FF
        NOP                              ; $FD8A  00
        NOP                              ; $FD8B  00
        RST $38                          ; $FD8C  FF
        RST $38                          ; $FD8D  FF
        NOP                              ; $FD8E  00
        NOP                              ; $FD8F  00
        RST $30                          ; $FD90  F7
        RST $30                          ; $FD91  F7
        NOP                              ; $FD92  00
        NOP                              ; $FD93  00
        RST $30                          ; $FD94  F7
        RST $30                          ; $FD95  F7
        NOP                              ; $FD96  00
        NOP                              ; $FD97  00
        RST $30                          ; $FD98  F7
        RST $30                          ; $FD99  F7
        NOP                              ; $FD9A  00
        NOP                              ; $FD9B  00
        RST $38                          ; $FD9C  FF
        RST $30                          ; $FD9D  F7
        NOP                              ; $FD9E  00
        NOP                              ; $FD9F  00
        RST $38                          ; $FDA0  FF
        RST $38                          ; $FDA1  FF
        NOP                              ; $FDA2  00
        NOP                              ; $FDA3  00
        RST $38                          ; $FDA4  FF
        RST $38                          ; $FDA5  FF
        NOP                              ; $FDA6  00
        NOP                              ; $FDA7  00
        RST $38                          ; $FDA8  FF
        RST $38                          ; $FDA9  FF
        NOP                              ; $FDAA  00
        NOP                              ; $FDAB  00
        RST $38                          ; $FDAC  FF
        RST $38                          ; $FDAD  FF
        NOP                              ; $FDAE  00
        NOP                              ; $FDAF  00
; [AI] Per-slot initializer for a card matching the Pascal 1.1 firmware-protocol device code; like
;       its sibling, an un-patched placeholder in the on-disk image.
INIT_PASCAL_1_1:
        RST $38                          ; $FDB0  FF
        RST $38                          ; $FDB1  FF
        NOP                              ; $FDB2  00
        NOP                              ; $FDB3  00
        RST $38                          ; $FDB4  FF
        RST $38                          ; $FDB5  FF
        NOP                              ; $FDB6  00
        NOP                              ; $FDB7  00
        RST $38                          ; $FDB8  FF
        RST $38                          ; $FDB9  FF
        NOP                              ; $FDBA  00
        NOP                              ; $FDBB  00
        RST $38                          ; $FDBC  FF
        RST $38                          ; $FDBD  FF
        NOP                              ; $FDBE  00
        NOP                              ; $FDBF  00
        RST $38                          ; $FDC0  FF
        RST $38                          ; $FDC1  FF
        NOP                              ; $FDC2  00
        NOP                              ; $FDC3  00
        RST $38                          ; $FDC4  FF
        RST $38                          ; $FDC5  FF
        NOP                              ; $FDC6  00
        NOP                              ; $FDC7  00
        RST $38                          ; $FDC8  FF
        RST $38                          ; $FDC9  FF
        NOP                              ; $FDCA  00
        NOP                              ; $FDCB  00
        RST $38                          ; $FDCC  FF
        RST $38                          ; $FDCD  FF
        NOP                              ; $FDCE  00
        NOP                              ; $FDCF  00
        RST $38                          ; $FDD0  FF
        RST $38                          ; $FDD1  FF
        NOP                              ; $FDD2  00
        NOP                              ; $FDD3  00
        RST $38                          ; $FDD4  FF
        RST $38                          ; $FDD5  FF
        NOP                              ; $FDD6  00
        NOP                              ; $FDD7  00
        RST $38                          ; $FDD8  FF
        RST $38                          ; $FDD9  FF
        NOP                              ; $FDDA  00
        NOP                              ; $FDDB  00
        RST $38                          ; $FDDC  FF
        RST $38                          ; $FDDD  FF
        NOP                              ; $FDDE  00
        NOP                              ; $FDDF  00
        RST $38                          ; $FDE0  FF
        RST $38                          ; $FDE1  FF
        NOP                              ; $FDE2  00
        NOP                              ; $FDE3  00
        RST $38                          ; $FDE4  FF
        RST $38                          ; $FDE5  FF
        NOP                              ; $FDE6  00
        NOP                              ; $FDE7  00
        RST $38                          ; $FDE8  FF
        RST $38                          ; $FDE9  FF
        NOP                              ; $FDEA  00
        NOP                              ; $FDEB  00
        RST $38                          ; $FDEC  FF
        RST $38                          ; $FDED  FF
        NOP                              ; $FDEE  00
        NOP                              ; $FDEF  00
        RST $30                          ; $FDF0  F7
        RST $30                          ; $FDF1  F7
        NOP                              ; $FDF2  00
        NOP                              ; $FDF3  00
        RST $30                          ; $FDF4  F7
        RST $30                          ; $FDF5  F7
        NOP                              ; $FDF6  00
        NOP                              ; $FDF7  00
        RST $30                          ; $FDF8  F7
        RST $30                          ; $FDF9  F7
        NOP                              ; $FDFA  00
        NOP                              ; $FDFB  00
        RST $30                          ; $FDFC  F7
        RST $30                          ; $FDFD  F7
        NOP                              ; $FDFE  00
        NOP                              ; $FDFF  00

    SAVEBIN "build/CPM223_BIOS_Disk.bin", $FA00, $0400
