; Generated by disasm_z80
; Range:  $FA00-$FFFF  (1536 bytes)
;
; ===========================================================================
; 60K BIOS  -- the UNPATCHED TEMPLATE as shipped inside CPM60.COM
; ===========================================================================
; This is the BIOS exactly as it sits in the CPM60.COM installer payload (COM
; offset 0x2600, ORG $FA00) and is written to the disk's system tracks. It is
; the canonical *source* form: assembling it reproduces those 1536 bytes
; byte-for-byte, and it is the BIOS input to the CPM60.COM build.
;
; It is NOT quite what runs. On cold boot the 6502 boot loader copies this
; image into the Language Card and applies 185 byte patches (see
; ../bios_boot_patches.json) -- most visibly NOP-ing the $FA00 cold-boot JP
; here (JP BIOS_BOOT, $FEEA), because on the 60K system cold start is handled
; 6502-side. derive_booted_bios() (cpm_pipeline.regenerate) applies that patch
; table to recover the running image. The BDOS and CCP are NOT patched this
; way (the BDOS is byte-identical in COM and booted; the CCP differs by 8
; install-time bytes only).
; ===========================================================================

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
IOBYTE               EQU $0003               ; I/O assignment byte — logical-to-physical device routing (CONSOLE/READER/PUNCH/LIST). 4 fields × 2 bits each.
CDISK                EQU $0004               ; Current drive (low nibble: 0=A, 1=B, ..., 15=P) and current user (high nibble, 0-15).
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).
TPA_START            EQU $0100               ; Start of Transient Program Area. .COM files load here and execute starting at $0100.
SLOT_INFO_BASE       EQU $F3B8               ; Slot-info table for cold-boot generator (F3B8+E = slot E's device code, E=1..7)

; -- Mid-instruction references (shown inline as cover+offset) --
;   $FB05 -> BIOS_WBOOT_3+1       z80 skip idiom: enters the operand of $3E at $FB04
;   $FB49 -> RPC_DISPATCH_1+1     shared instruction tail: $FB49 is reachable code inside the instruction at $FB48
;   $FEEB -> BIOS_BOOT+1          shared instruction tail: $FEEB is reachable code inside the instruction at $FEEA
;   $FEEC -> BIOS_BOOT+2          shared instruction tail: $FEEC is reachable code inside the instruction at $FEEA
;   $FEFA -> BIOS_BOOT_6+2        shared instruction tail: $FEFA is reachable code inside the instruction at $FEF8
;   $FEFC -> BIOS_BOOT_7+1        shared instruction tail: $FEFC is reachable code inside the instruction at $FEFB
;   $FF59 -> BIOS_BOOT_13+1       shared instruction tail: $FF59 is reachable code inside the instruction at $FF58

    ORG $FA00

BOOT:
        JP BIOS_BOOT                     ; $FA00  C3 EA FE
WBOOT:
        JP BIOS_WBOOT                    ; $FA03  C3 B8 FA
CONST:
        JP BIOS_CONST                    ; $FA06  C3 10 FB
CONIN:
        JP BIOS_CONIN                    ; $FA09  C3 1A FB
CONOUT:
        JP SUB_FB4C_1                    ; $FA0C  C3 4D FB
LIST:
        JP BIOS_LIST                     ; $FA0F  C3 70 FB
PUNCH:
        JP BIOS_PUNCH                    ; $FA12  C3 7F FB
READER:
        JP BIOS_READER                   ; $FA15  C3 91 FB
HOME:
        JP INIT_PASCAL_1_1_1             ; $FA18  C3 75 FE
SELDSK:
        JP SELDSK_IMPL_1                 ; $FA1B  C3 97 FE
SETTRK:
        JP INIT_PASCAL_1_1_4             ; $FA1E  C3 80 FE
SETSEC:
        JP BIOS_SETSEC                   ; $FA21  C3 F4 FB
SETDMA:
        JP BIOS_SETDMA                   ; $FA24  C3 F9 FB
READ:
        JP SELDSK_IMPL_3                 ; $FA27  C3 C6 FE
WRITE:
        JP SELDSK_IMPL_4                 ; $FA2A  C3 CC FE
LISTST:
        XOR A                            ; $FA2D  AF
        RET                              ; $FA2E  C9
        DEFB    $00                                              ; $FA2F
SECTRAN:
        LD H,B                           ; $FA30  60
        LD L,C                           ; $FA31  69
        RET                              ; $FA32  C9
L_FA33:
        DEFS    8, $00    ; $FA33  fill
        DEFB    $FD,$FE,$73,$FA,$C5,$FF                          ; $FA3B
        DEFW    BIOS_BOOT_17             ; $FA41
        DEFS    8, $00    ; $FA43  fill
        DEFB    $FD,$FE,$73,$FA,$D1,$FF,$8F,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; $FA4B
        DEFB    $FD,$FE,$73,$FA,$DD,$FF                          ; $FA5B
        DEFW    SUB_FF9D_2               ; $FA61
        DEFS    8, $00    ; $FA63  fill
        DEFB    $FD,$FE,$73,$FA,$E9,$FF                          ; $FA6B
        DEFW    SUB_FFA8_2               ; $FA71
        DEFB    $20,$00,$03,$07,$00,$8B,$00,$2F,$00,$C0,$00,$0C,$00,$03,$00 ; $FA73
SLOT_SCAN_INIT:
        LD DE,$0007                      ; $FA82  11 07 00
SLOT_SCAN_INIT_1:
        LD HL,SLOT_INFO_BASE             ; $FA85  21 B8 F3
        ADD HL,DE                        ; $FA88  19
        LD A,(HL)                        ; $FA89  7E
        SUB $03                          ; $FA8A  D6 03
        JR NZ,SLOT_SCAN_INIT_2           ; $FA8C  20 07
        CALL SLOT_IOBASE_8E              ; $FA8E  CD 8A FE
        LD (HL),$03                      ; $FA91  36 03
        LD (HL),$15                      ; $FA93  36 15
SLOT_SCAN_INIT_2:
        DEC A                            ; $FA95  3D
        JR NZ,SLOT_SCAN_INIT_3           ; $FA96  20 0B
        CALL INIT_PASCAL_1_0             ; $FA98  CD 83 FD
        LD HL,$C800                      ; $FA9B  21 00 C8
        CALL RPC_DISPATCH                ; $FA9E  CD 45 FB
        JR SLOT_SCAN_INIT_4              ; $FAA1  18 0A
SLOT_SCAN_INIT_3:
        CP $02                           ; $FAA3  FE 02
        JR NZ,SLOT_SCAN_INIT_4           ; $FAA5  20 06
        LD HL,$0DD0                      ; $FAA7  21 D0 0D
        CALL INIT_PASCAL_1_1             ; $FAAA  CD B0 FD
SLOT_SCAN_INIT_4:
        DEC E                            ; $FAAD  1D
        JR NZ,SLOT_SCAN_INIT_1           ; $FAAE  20 D5
        RET                              ; $FAB0  C9
SLOT_E000_ADDR:
        LD HL,$E000                      ; $FAB1  21 00 E0
        LD A,E                           ; $FAB4  7B
        OR H                             ; $FAB5  B4
        LD H,A                           ; $FAB6  67
RET_VECTOR:
        RET                              ; $FAB7  C9
BIOS_WBOOT:
        LD SP,DEFAULT_DMA                ; $FAB8  31 80 00
        LD A,($E051)                     ; $FABB  3A 51 E0
        LD HL,$0E00                      ; $FABE  21 00 0E
        CALL RPC_DISPATCH                ; $FAC1  CD 45 FB
        CALL SLOT_SCAN_INIT              ; $FAC4  CD 82 FA
        LD A,($DC08)                     ; $FAC7  3A 08 DC
        CP $DC                           ; $FACA  FE DC
        JR Z,BIOS_WBOOT_1                ; $FACC  28 11
        LD HL,BIOS_BOOT_13+1             ; $FACE  21 59 FF
        LD ($F3D0),HL                    ; $FAD1  22 D0 F3
        LD HL,($F3DE)                    ; $FAD4  2A DE F3
        LD A,$77                         ; $FAD7  3E 77
        LD ($000B),A                     ; $FAD9  32 0B 00
        JP $000B                         ; $FADC  C3 0B 00
BIOS_WBOOT_1:
        XOR A                            ; $FADF  AF
        LD ($D307),A                     ; $FAE0  32 07 D3
BIOS_WBOOT_2:
        XOR A                            ; $FAE3  AF
        LD (BIOS_BOOT_5),A               ; $FAE4  32 F6 FE
        LD (BIOS_BOOT_3),A               ; $FAE7  32 F1 FE
        LD A,$C3                         ; $FAEA  3E C3
        LD (WBOOT_VEC),A                 ; $FAEC  32 00 00
        LD HL,WBOOT                      ; $FAEF  21 03 FA
        LD ($0001),HL                    ; $FAF2  22 01 00
        LD (BDOS_VEC),A                  ; $FAF5  32 05 00
        LD HL,$DC06                      ; $FAF8  21 06 DC
        LD ($0006),HL                    ; $FAFB  22 06 00
        LD BC,DEFAULT_DMA                ; $FAFE  01 80 00
        CALL BIOS_SETDMA                 ; $FB01  CD F9 FB
BIOS_WBOOT_3:
        LD A,$01                         ; $FB04  3E 01
        LD ($D74E),A                     ; $FB06  32 4E D7
        LD A,(CDISK)                     ; $FB09  3A 04 00
        LD C,A                           ; $FB0C  4F
        JP $D300                         ; $FB0D  C3 00 D3
BIOS_CONST:
        LD HL,($F380)                    ; $FB10  2A 80 F3
        JP (HL)                          ; $FB13  E9
        DEFB    $3A                                              ; $FB14
L_FB15:
        DEFB    $00,$E0,$17,$9F,$C9                              ; $FB15
BIOS_CONIN:
        CALL SUB_FB5A                    ; $FB1A  CD 5A FB
        AND $7F                          ; $FB1D  E6 7F
        LD HL,$F3AB                      ; $FB1F  21 AB F3
        LD B,$06                         ; $FB22  06 06
        LD C,A                           ; $FB24  4F
KEY_TABLE_SCAN:
        INC HL                           ; $FB25  23
        LD A,(HL)                        ; $FB26  7E
        INC HL                           ; $FB27  23
        OR A                             ; $FB28  B7
        JP M,KBD_STROBE_CLEAR            ; $FB29  FA 31 FB
        CP C                             ; $FB2C  B9
        LD A,(HL)                        ; $FB2D  7E
        RET Z                            ; $FB2E  C8
        DJNZ KEY_TABLE_SCAN              ; $FB2F  10 F4
KBD_STROBE_CLEAR:
        LD A,C                           ; $FB31  79
        RET                              ; $FB32  C9
        DEFB    $11,$03,$00,$C3                                  ; $FB33
L_FB37:
        DEFB    $39,$FB,$3A,$00,$E0,$17                          ; $FB37
        DEFW    SECTRAN                  ; $FB3D
        DEFB    $32,$10,$E0,$3F,$1F,$C9                          ; $FB3F
RPC_DISPATCH:
        LD ($F3D0),HL                    ; $FB45  22 D0 F3
RPC_DISPATCH_1:
        LD (WBOOT_VEC),A                 ; $FB48  32 00 00
        RET                              ; $FB4B  C9
SUB_FB4C:
        LD C,A                           ; $FB4C  4F
SUB_FB4C_1:
        LD A,(IOBYTE)                    ; $FB4D  3A 03 00
        AND $03                          ; $FB50  E6 03
        CP $02                           ; $FB52  FE 02
        JR NZ,CONSOLE_WRITE_CHAR         ; $FB54  20 4B
SUB_FB4C_2:
        LD HL,($F392)                    ; $FB56  2A 92 F3
        JP (HL)                          ; $FB59  E9
SUB_FB5A:
        LD A,(IOBYTE)                    ; $FB5A  3A 03 00
        AND $03                          ; $FB5D  E6 03
        CP $02                           ; $FB5F  FE 02
        LD HL,($F384)                    ; $FB61  2A 84 F3
        JR Z,SUB_FB5A_2                  ; $FB64  28 06
        JR NC,SUB_FB5A_3                 ; $FB66  30 07
SUB_FB5A_1:
        LD HL,($F382)                    ; $FB68  2A 82 F3
        JP (HL)                          ; $FB6B  E9
SUB_FB5A_2:
        LD HL,($F38A)                    ; $FB6C  2A 8A F3
SUB_FB5A_3:
        JP (HL)                          ; $FB6F  E9
BIOS_LIST:
        LD A,(IOBYTE)                    ; $FB70  3A 03 00
        AND $C0                          ; $FB73  E6 C0
        CP $80                           ; $FB75  FE 80
        JR C,SUB_FB5A_7                  ; $FB77  38 27
        JR Z,SUB_FB4C_2                  ; $FB79  28 DB
        LD HL,($F394)                    ; $FB7B  2A 94 F3
        JP (HL)                          ; $FB7E  E9
BIOS_PUNCH:
        LD A,(IOBYTE)                    ; $FB7F  3A 03 00
        AND $30                          ; $FB82  E6 30
        CP $10                           ; $FB84  FE 10
        JR C,SUB_FB5A_7                  ; $FB86  38 18
        LD HL,($F38E)                    ; $FB88  2A 8E F3
        JR Z,SUB_FB5A_3                  ; $FB8B  28 E2
        LD HL,($F390)                    ; $FB8D  2A 90 F3
        JP (HL)                          ; $FB90  E9
BIOS_READER:
        LD A,(IOBYTE)                    ; $FB91  3A 03 00
        AND $0C                          ; $FB94  E6 0C
        CP $08                           ; $FB96  FE 08
        JR C,SUB_FB5A_1                  ; $FB98  38 CE
        JR Z,SUB_FB5A_2                  ; $FB9A  28 D0
        LD HL,($F38C)                    ; $FB9C  2A 8C F3
        JP (HL)                          ; $FB9F  E9
SUB_FB5A_7:
        SCF                              ; $FBA0  37
CONSOLE_WRITE_CHAR:
        SBC A,A                          ; $FBA1  9F
        LD HL,$F3A2                      ; $FBA2  21 A2 F3
        LD L,(HL)                        ; $FBA5  6E
        INC L                            ; $FBA6  2C
        JP Z,CONSOLE_PUT_CHAR            ; $FBA7  CA A4 FC
        LD HL,L_FEE4                     ; $FBAA  21 E4 FE
        LD (HL),A                        ; $FBAD  77
        RES 7,C                          ; $FBAE  CB B9
        INC HL                           ; $FBB0  23
        LD A,(HL)                        ; $FBB1  7E
        OR A                             ; $FBB2  B7
        JP Z,CHECK_UNIT_DEFAULT          ; $FBB3  CA 56 FC
        DEC (HL)                         ; $FBB6  35
        LD A,($F396)                     ; $FBB7  3A 96 F3
        LD HL,BIOS_BOOT_1                ; $FBBA  21 ED FE
        JR Z,SUB_FBC4_2                  ; $FBBD  28 0C
        OR A                             ; $FBBF  B7
        JP P,SUB_FBC4_1                  ; $FBC0  F2 C6 FB
        DEC HL                           ; $FBC3  2B
SUB_FBC4:
        AND $7F                          ; $FBC4  E6 7F
SUB_FBC4_1:
        LD E,A                           ; $FBC6  5F
        LD A,C                           ; $FBC7  79
        SUB E                            ; $FBC8  93
        LD (HL),A                        ; $FBC9  77
        RET                              ; $FBCA  C9
SUB_FBC4_2:
        OR A                             ; $FBCB  B7
        JP M,CURSOR_POSITION             ; $FBCC  FA D0 FB
        DEC HL                           ; $FBCF  2B
CURSOR_POSITION:
        CALL SUB_FBC4                    ; $FBD0  CD C4 FB
        LD HL,(BIOS_BOOT+2)              ; $FBD3  2A EC FE
        LD A,($F3A1)                     ; $FBD6  3A A1 F3
        OR A                             ; $FBD9  B7
        JP P,EMIT_CURSOR_MOVE            ; $FBDA  F2 E2 FB
        AND $7F                          ; $FBDD  E6 7F
        LD E,L                           ; $FBDF  5D
        LD L,H                           ; $FBE0  6C
        LD H,E                           ; $FBE1  63
EMIT_CURSOR_MOVE:
        LD E,A                           ; $FBE2  5F
        ADD A,H                          ; $FBE3  84
        LD C,A                           ; $FBE4  4F
        LD A,E                           ; $FBE5  7B
        ADD A,L                          ; $FBE6  85
        PUSH AF                          ; $FBE7  F5
        LD B,$07                         ; $FBE8  06 07
        CALL CONSOLE_PUT_CHAR            ; $FBEA  CD A4 FC
        POP AF                           ; $FBED  F1
        LD B,$0A                         ; $FBEE  06 0A
SUB_FBF0:
        LD C,A                           ; $FBF0  4F
        JP CONSOLE_PUT_CHAR              ; $FBF1  C3 A4 FC
BIOS_SETSEC:
        LD A,C                           ; $FBF4  79
        LD (BIOS_BOOT+1),A               ; $FBF5  32 EB FE
        RET                              ; $FBF8  C9
BIOS_SETDMA:
        LD (BIOS_BOOT_6+2),BC            ; $FBF9  ED 43 FA FE
        RET                              ; $FBFD  C9
        DEFS    88, $00    ; $FBFE  fill
CHECK_UNIT_DEFAULT:
        LD B,A                           ; $FC56  47
        LD HL,L_FEE6                     ; $FC57  21 E6 FE
        LD A,(HL)                        ; $FC5A  7E
        LD E,A                           ; $FC5B  5F
        OR A                             ; $FC5C  B7
        JR NZ,CHECK_UNIT_DEFAULT_2       ; $FC5D  20 12
        LD A,($F397)                     ; $FC5F  3A 97 F3
        OR A                             ; $FC62  B7
        JR Z,CHECK_UNIT_DEFAULT_1        ; $FC63  28 06
        CP C                             ; $FC65  B9
        JR NZ,CHECK_UNIT_DEFAULT_1       ; $FC66  20 03
        LD (HL),$80                      ; $FC68  36 80
        RET                              ; $FC6A  C9
CHECK_UNIT_DEFAULT_1:
        LD A,$1F                         ; $FC6B  3E 1F
        CP C                             ; $FC6D  B9
        JP C,CONSOLE_PUT_CHAR            ; $FC6E  DA A4 FC
CHECK_UNIT_DEFAULT_2:
        LD HL,$F3A0                      ; $FC71  21 A0 F3
        LD B,$09                         ; $FC74  06 09
CHECK_UNIT_DEFAULT_3:
        LD A,(HL)                        ; $FC76  7E
        OR A                             ; $FC77  B7
        JR Z,CHECK_UNIT_DEFAULT_4        ; $FC78  28 04
        XOR E                            ; $FC7A  AB
        CP C                             ; $FC7B  B9
        JR Z,CHECK_UNIT_DEFAULT_5        ; $FC7C  28 05
CHECK_UNIT_DEFAULT_4:
        DEC HL                           ; $FC7E  2B
        DJNZ CHECK_UNIT_DEFAULT_3        ; $FC7F  10 F5
        JR CONSOLE_PUT_CHAR              ; $FC81  18 21
CHECK_UNIT_DEFAULT_5:
        LD DE,$000B                      ; $FC83  11 0B 00
        ADD HL,DE                        ; $FC86  19
        LD A,(HL)                        ; $FC87  7E
        OR A                             ; $FC88  B7
        LD C,A                           ; $FC89  4F
        JP P,CHECK_UNIT_DEFAULT_6        ; $FC8A  F2 9A FC
        AND $7F                          ; $FC8D  E6 7F
        LD C,A                           ; $FC8F  4F
        PUSH BC                          ; $FC90  C5
        LD A,($F3A2)                     ; $FC91  3A A2 F3
        LD B,$07                         ; $FC94  06 07
        CALL SUB_FBF0                    ; $FC96  CD F0 FB
        POP BC                           ; $FC99  C1
CHECK_UNIT_DEFAULT_6:
        LD A,B                           ; $FC9A  78
        CP $07                           ; $FC9B  FE 07
        JR NZ,CONSOLE_PUT_CHAR           ; $FC9D  20 05
        LD A,$02                         ; $FC9F  3E 02
        LD (L_FEE5),A                    ; $FCA1  32 E5 FE
CONSOLE_PUT_CHAR:
        XOR A                            ; $FCA4  AF
        LD (L_FEE6),A                    ; $FCA5  32 E6 FE
        LD A,(L_FEE4)                    ; $FCA8  3A E4 FE
        OR A                             ; $FCAB  B7
        LD HL,($F388)                    ; $FCAC  2A 88 F3
        JR Z,SUB_FCA4_1                  ; $FCAF  28 03
        LD HL,($F386)                    ; $FCB1  2A 86 F3
SUB_FCA4_1:
        JP (HL)                          ; $FCB4  E9
        DEFB    $11,$03,$00,$C3                                  ; $FCB5
L_FCB9:
        DEFB    $BB,$FC,$2A,$E7,$FE,$3A,$E9,$FE,$77,$CD,$E2,$FC,$2A,$28,$F0,$3A ; $FCB9
        DEFB    $24,$F0,$5F,$16,$F0,$19,$22,$E7,$FE,$7E,$32,$E9  ; $FCC9
        DEFW    BIOS_BOOT_8              ; $FCD5
        DEFB    $E0,$38,$02,$EE,$20,$E6,$3F,$F6,$40,$77,$C9,$78,$B7,$28,$0B,$21 ; $FCD7
        DEFW    RPC_DISPATCH             ; $FCE7
        DEFB    $E5,$21,$66,$FD,$85,$6F,$6E,$E9                  ; $FCE9
        DEFW    INIT_PASCAL_1_1_2        ; $FCF1
        DEFB    $0D,$20,$05,$AF,$32,$24,$F0,$C9,$F6              ; $FCF3
        DEFW    INIT_PASCAL_1_1_4        ; $FCFC
        DEFB    $E0,$38,$04,$21,$DD,$F3,$AE,$32,$45,$F0,$21,$F0,$FD,$C3,$80,$FD ; $FCFE
        DEFB    $CD                                              ; $FD0E
        DEFW    SLOT_IOBASE_8E           ; $FD0F
        DEFB    $C6,$8F,$CB,$4E,$28,$FC,$21,$2F,$F0,$36,$60,$2B,$36,$C0,$2B,$77 ; $FD11
        DEFB    $2B,$36,$8D,$62,$C3,$7C,$FD,$3E,$FF,$01,$3E,$3F,$32,$32,$F0,$E1 ; $FD21
        DEFB    $C9,$21                                          ; $FD31
        DEFW    BIOS_SETSEC              ; $FD33
        DEFB    $C9,$AF,$6F,$67,$22,$24,$F0,$32,$45,$F0,$21,$C1,$FB,$C9,$2E,$42 ; $FD35
        DEFB    $01,$2E,$9C,$01,$2E,$1A,$01,$2E,$58,$26,$FC,$C9,$2A ; $FD45
        DEFW    BIOS_BOOT+2              ; $FD52
        DEFB    $7D,$FE,$28,$38,$02,$2E,$00,$7C,$FE,$18,$38,$02,$26,$00,$22,$24 ; $FD54
        DEFB    $F0,$18,$D5,$4C,$43,$46,$28,$2B,$36,$30,$49,$32,$51,$CD ; $FD64
        DEFW    INIT_PASCAL_1_0          ; $FD72
        DEFB    $21,$78,$F6,$19,$71,$21,$AA,$C9,$79,$32,$45,$F0,$C3 ; $FD74
        DEFW    RPC_DISPATCH             ; $FD81
INIT_PASCAL_1_0:
        CALL SLOT_IOBASE_80              ; $FD83  CD 85 FE
        LD ($F6F8),A                     ; $FD86  32 F8 F6
        LD ($F047),A                     ; $FD89  32 47 F0
        LD A,($EFFF)                     ; $FD8C  3A FF EF
        CALL SLOT_E000_ADDR              ; $FD8F  CD B1 FA
        SUB $20                          ; $FD92  D6 20
        LD ($F046),A                     ; $FD94  32 46 F0
        LD A,(HL)                        ; $FD97  7E
        RET                              ; $FD98  C9
L_FD99:
        DEFB    $21,$1D,$0E,$1E,$03,$3E,$01,$CD,$AD,$FD,$3A,$48,$F0,$1F,$9F,$C9 ; $FD99
        DEFB    $21,$E1,$0D,$79,$32,$45,$F0                      ; $FDA9
INIT_PASCAL_1_1:
        LD A,E                           ; $FDB0  7B
        LD ($F047),A                     ; $FDB1  32 47 F0
        JP RPC_DISPATCH                  ; $FDB4  C3 45 FB
        DEFB    $21,$0F,$0E,$CD                                  ; $FDB7
        DEFW    INIT_PASCAL_1_1          ; $FDBB
        DEFB    $3A,$45,$F0,$C9,$CD                              ; $FDBD
        DEFW    INIT_PASCAL_1_0          ; $FDC2
        DEFB    $21,$4D,$C8,$CD                                  ; $FDC4
        DEFW    RPC_DISPATCH             ; $FDC8
        DEFB    $21,$78,$F6,$19,$7E,$C9,$48,$20,$26,$0E,$A0,$0D,$B1,$F6,$85,$F6 ; $FDCA
        DEFB    $AC,$F8,$06,$68,$6C,$F6,$00,$48,$A9,$00,$20,$EF,$0D,$20,$26,$0E ; $FDDA
        DEFB    $A0,$0F,$4C,$D6,$0D,$84,$F5,$48,$20,$1D,$0E,$68,$A4,$F5,$90,$F5 ; $FDEA
        DEFB    $60,$00,$00,$00,$00,$00,$4C,$09,$0E,$8D,$8B,$C0,$4C,$13,$D4,$8D ; $FDFA
        DEFB    $8B,$C0,$4C,$F7,$D1,$A9,$01,$20,$EF,$0D,$20,$26,$0E,$48,$A0,$0E ; $FE0A
        DEFB    $4C,$D6,$0D,$48,$20,$26,$0E,$A0,$10,$4C,$D6,$0D,$98,$09,$C0,$AA ; $FE1A
        DEFB    $98,$0A,$0A,$0A,$0A,$A8,$8C,$F8,$06,$A9,$00,$85,$F6,$86,$F7 ; $FE2A
        DEFW    SUB_FFA8_1               ; $FE39
        DEFB    $CF,$B1,$F6,$60,$A5,$48,$48,$A5,$45,$A6,$46,$A4,$47,$28,$58,$60 ; $FE3B
        DEFB    $CD                                              ; $FE4B
        DEFW    SLOT_IOBASE_8E           ; $FE4C
        DEFB    $7E,$1F,$30,$FC,$2C,$7E,$C9,$11,$01,$00,$C3      ; $FE4E
L_FE59:
        DEFB    $68,$FE,$CD                                      ; $FE59
        DEFW    SLOT_E000_ADDR           ; $FE5C
        DEFB    $2E,$C1,$7E,$17,$38,$FC,$CD                      ; $FE5E
        DEFW    SLOT_IOBASE_80           ; $FE65
        DEFB    $71,$C9,$11,$02,$00,$C3                          ; $FE67
L_FE6D:
        DEFB    $68,$FE,$11,$02,$00                              ; $FE6D
L_FE72:
        DEFB    $C3                                              ; $FE72
L_FE73:
        DEFB    $00                                              ; $FE73
L_FE74:
        DEFB    $00                                              ; $FE74
INIT_PASCAL_1_1_1:
        LD A,(BIOS_BOOT_4)               ; $FE75  3A F2 FE
        OR A                             ; $FE78  B7
INIT_PASCAL_1_1_2:
        JR NZ,INIT_PASCAL_1_1_3          ; $FE79  20 03
        LD (BIOS_BOOT_3),A               ; $FE7B  32 F1 FE
INIT_PASCAL_1_1_3:
        LD C,$00                         ; $FE7E  0E 00
INIT_PASCAL_1_1_4:
        LD A,C                           ; $FE80  79
        LD (BIOS_BOOT),A                 ; $FE81  32 EA FE
        RET                              ; $FE84  C9
SLOT_IOBASE_80:
        LD HL,$E080                      ; $FE85  21 80 E0
        JR SLOT_IOBASE_8E_1              ; $FE88  18 03
SLOT_IOBASE_8E:
        LD HL,$E08E                      ; $FE8A  21 8E E0
SLOT_IOBASE_8E_1:
        LD A,E                           ; $FE8D  7B
SELDSK_IMPL:
        ADD A,A                          ; $FE8E  87
        ADD A,A                          ; $FE8F  87
        ADD A,A                          ; $FE90  87
        ADD A,A                          ; $FE91  87
        PUSH AF                          ; $FE92  F5
        ADD A,L                          ; $FE93  85
        LD L,A                           ; $FE94  6F
        POP AF                           ; $FE95  F1
        RET                              ; $FE96  C9
SELDSK_IMPL_1:
        LD DE,BIOS_BOOT_2                ; $FE97  11 EE FE
        LD HL,CDISK                      ; $FE9A  21 04 00
        LD A,(SLOT_INFO_BASE)            ; $FE9D  3A B8 F3
        DEC A                            ; $FEA0  3D
        CP C                             ; $FEA1  B9
        JR C,SELDSK_IMPL_2               ; $FEA2  38 1D
        LD A,(HL)                        ; $FEA4  7E
        LD (DE),A                        ; $FEA5  12
        INC DE                           ; $FEA6  13
        LD A,C                           ; $FEA7  79
        LD (DE),A                        ; $FEA8  12
        LD HL,L_FA33                     ; $FEA9  21 33 FA
        CALL SELDSK_IMPL                 ; $FEAC  CD 8E FE
        PUSH HL                          ; $FEAF  E5
        LD DE,$000A                      ; $FEB0  11 0A 00
        ADD HL,DE                        ; $FEB3  19
        LD E,(HL)                        ; $FEB4  5E
        INC HL                           ; $FEB5  23
        LD D,(HL)                        ; $FEB6  56
        LD HL,BDOS_VEC                   ; $FEB7  21 05 00
        ADD HL,DE                        ; $FEBA  19
        LD A,(HL)                        ; $FEBB  7E
        LD (BIOS_BOOT_7+1),A             ; $FEBC  32 FC FE
        POP HL                           ; $FEBF  E1
        RET                              ; $FEC0  C9
SELDSK_IMPL_2:
        LD A,(DE)                        ; $FEC1  1A
        LD (HL),A                        ; $FEC2  77
        LD L,$00                         ; $FEC3  2E 00
        RET                              ; $FEC5  C9
SELDSK_IMPL_3:
        LD ($E08B),A                     ; $FEC6  32 8B E0
        JP $B247                         ; $FEC9  C3 47 B2
SELDSK_IMPL_4:
        LD ($E08B),A                     ; $FECC  32 8B E0
        JP $B257                         ; $FECF  C3 57 B2
        DEFB    $CD                                              ; $FED2
        DEFW    RPC_DISPATCH             ; $FED3
        DEFB    $32,$8B,$E0,$C9,$32,$83,$E0,$2A,$0D,$DC,$E9,$32,$83,$E0,$C9 ; $FED5
L_FEE4:
        DEFB    $00                                              ; $FEE4
L_FEE5:
        DEFB    $00                                              ; $FEE5
L_FEE6:
        DEFB    $00,$E9,$FE,$00                                  ; $FEE6
BIOS_BOOT:
        LD SP,TPA_START                  ; $FEEA  31 00 01
BIOS_BOOT_1:
        XOR A                            ; $FEED  AF
BIOS_BOOT_2:
        LD HL,BOOT                       ; $FEEE  21 00 FA
BIOS_BOOT_3:
        LD (HL),A                        ; $FEF1  77
BIOS_BOOT_4:
        INC HL                           ; $FEF2  23
        LD (HL),A                        ; $FEF3  77
        INC HL                           ; $FEF4  23
        LD (HL),A                        ; $FEF5  77
BIOS_BOOT_5:
        LD A,$95                         ; $FEF6  3E 95
BIOS_BOOT_6:
        LD (IOBYTE),A                    ; $FEF8  32 03 00
BIOS_BOOT_7:
        LD HL,($F3DE)                    ; $FEFB  2A DE F3
BIOS_BOOT_8:
        LD (RPC_DISPATCH_1+1),HL         ; $FEFE  22 49 FB
        XOR A                            ; $FF01  AF
        LD (CDISK),A                     ; $FF02  32 04 00
        LD A,($F3BB)                     ; $FF05  3A BB F3
        CP $06                           ; $FF08  FE 06
        JR NZ,BIOS_BOOT_9                ; $FF0A  20 0A
        LD HL,L_FD99                     ; $FF0C  21 99 FD
        LD ($F380),HL                    ; $FF0F  22 80 F3
        SUB $03                          ; $FF12  D6 03
        JR BIOS_BOOT_10                  ; $FF14  18 13
BIOS_BOOT_9:
        CP $05                           ; $FF16  FE 05
        JR Z,BIOS_BOOT_11                ; $FF18  28 22
        SUB $03                          ; $FF1A  D6 03
        JR C,BIOS_BOOT_11                ; $FF1C  38 1E
        JR NZ,BIOS_BOOT_10               ; $FF1E  20 09
        LD HL,L_FB15                     ; $FF20  21 15 FB
        LD (HL),$BE                      ; $FF23  36 BE
        INC HL                           ; $FF25  23
        INC HL                           ; $FF26  23
        LD (HL),$1F                      ; $FF27  36 1F
BIOS_BOOT_10:
        PUSH AF                          ; $FF29  F5
        CALL SUB_FF9D                    ; $FF2A  CD 9D FF
        POP AF                           ; $FF2D  F1
        LD (L_FCB9),HL                   ; $FF2E  22 B9 FC
        CALL SUB_FF98                    ; $FF31  CD 98 FF
        LD (L_FB37),HL                   ; $FF34  22 37 FB
        LD A,$03                         ; $FF37  3E 03
        LD (BIOS_WBOOT_3+1),A            ; $FF39  32 05 FB
BIOS_BOOT_11:
        LD A,($F3B9)                     ; $FF3C  3A B9 F3
        SUB $03                          ; $FF3F  D6 03
        JR C,BIOS_BOOT_12                ; $FF41  38 06
        CALL SUB_FF9D                    ; $FF43  CD 9D FF
        LD (L_FE59),HL                   ; $FF46  22 59 FE
BIOS_BOOT_12:
        LD A,($F3BA)                     ; $FF49  3A BA F3
        SUB $03                          ; $FF4C  D6 03
        JR C,BIOS_BOOT_14                ; $FF4E  38 14
        PUSH AF                          ; $FF50  F5
        CALL SUB_FF9D                    ; $FF51  CD 9D FF
        LD (L_FE6D),HL                   ; $FF54  22 6D FE
        POP AF                           ; $FF57  F1
BIOS_BOOT_13:
        CP $02                           ; $FF58  FE 02
        JR Z,BIOS_BOOT_14                ; $FF5A  28 08
        CALL SUB_FF98                    ; $FF5C  CD 98 FF
        LD (L_FE73),HL                   ; $FF5F  22 73 FE
        JR BIOS_BOOT_15                  ; $FF62  18 0B
BIOS_BOOT_14:
        LD HL,$1A3E                      ; $FF64  21 3E 1A
        LD (L_FE72),HL                   ; $FF67  22 72 FE
        LD A,$C9                         ; $FF6A  3E C9
        LD (L_FE74),A                    ; $FF6C  32 74 FE
BIOS_BOOT_15:
        CALL SLOT_SCAN_INIT              ; $FF6F  CD 82 FA
        LD A,($F398)                     ; $FF72  3A 98 F3
        CALL SUB_FFA8                    ; $FF75  CD A8 FF
        LD HL,L_FFB7                     ; $FF78  21 B7 FF
BIOS_BOOT_16:
        LD A,(HL)                        ; $FF7B  7E
        OR A                             ; $FF7C  B7
BIOS_BOOT_17:
        JP Z,BIOS_WBOOT_2                ; $FF7D  CA E3 FA
        PUSH HL                          ; $FF80  E5
        CALL SUB_FB4C                    ; $FF81  CD 4C FB
        POP HL                           ; $FF84  E1
        INC HL                           ; $FF85  23
        JR BIOS_BOOT_16                  ; $FF86  18 F3
L_FF88:
        DEFB    $0E,$FD,$71,$FD,$5B,$FE,$A9,$FD                  ; $FF88
L_FF90:
        DEFB    $4B,$FE,$C1,$FD,$B7,$FD,$B7,$FD                  ; $FF90
SUB_FF98:
        LD HL,L_FF90                     ; $FF98  21 90 FF
        JR SUB_FF9D_1                    ; $FF9B  18 03
SUB_FF9D:
        LD HL,L_FF88                     ; $FF9D  21 88 FF
SUB_FF9D_1:
        ADD A,A                          ; $FFA0  87
SUB_FF9D_2:
        ADD A,L                          ; $FFA1  85
        LD L,A                           ; $FFA2  6F
        LD A,(HL)                        ; $FFA3  7E
        INC L                            ; $FFA4  2C
        LD H,(HL)                        ; $FFA5  66
        LD L,A                           ; $FFA6  6F
        RET                              ; $FFA7  C9
SUB_FFA8:
        OR A                             ; $FFA8  B7
        JP P,SUB_FFA8_3                  ; $FFA9  F2 B4 FF
        PUSH AF                          ; $FFAC  F5
SUB_FFA8_1:
        LD A,($F397)                     ; $FFAD  3A 97 F3
        CALL SUB_FB4C                    ; $FFB0  CD 4C FB
SUB_FFA8_2:
        POP AF                           ; $FFB3  F1
SUB_FFA8_3:
        JP SUB_FB4C                      ; $FFB4  C3 4C FB
L_FFB7:
        DEFB    $0D,$0A,$0A,$0A,$20,$20,$20,$20,$20,$53,$6F,$66,$74,$63,$61,$72 ; $FFB7
        DEFB    "d CP/M"    ; $FFC7  string
        DEFB    $0D    ; $FFCD  terminator
        DEFB    $0A,$20,$20,$20,$20,$20,$36,$30,$4B,$20,$56,$65,$72,$2E,$20,$32 ; $FFCE
        DEFB    $2E,$32,$33,$0D,$0A,$28,$63,$29,$20,$31,$39,$38,$30,$2C,$31,$39 ; $FFDE
        DEFB    "82 Microsoft"    ; $FFEE  string
        DEFB    $0D    ; $FFFA  terminator
        DEFB    $0A,$0D,$0A                                      ; $FFFB
        DEFW    BOOT                     ; $FFFE

    SAVEBIN "CPM_BIOS.bin", $FA00, $0600
