; Generated by disasm_z80
; Source: CPM_BIOS_60K
; Range:  $FA00-$FFFF  (1536 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
IOBYTE               EQU $0003               ; I/O assignment byte — logical-to-physical device routing (CONSOLE/READER/PUNCH/LIST). 4 fields × 2 bits each.
CDISK                EQU $0004               ; Current drive (low nibble: 0=A, 1=B, ..., 15=P) and current user (high nibble, 0-15).
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).
TPA_STATE_F397       EQU $F397               ; Read by preflight code at $FF17
DEVICE_TABLE_BASE    EQU $F3A0               ; Device-code table base (scanned by device-scan)
SLOT_INFO_BASE       EQU $F3B8               ; Slot-info table for cold-boot generator (F3B8+E = slot E's device code, E=1..7)

    ORG $FA00

BOOT:
        NOP                              ; $FA00  00
        NOP                              ; $FA01  00
        NOP                              ; $FA02  00
WBOOT:
        JP SUB_FAB1_1                    ; $FA03  C3 B8 FA
CONST:
        JP SUB_FAB1_3                    ; $FA06  C3 10 FB
CONIN:
        JP SUB_FAB1_4                    ; $FA09  C3 1A FB
CONOUT:
        JP RPC_DISPATCH_1                ; $FA0C  C3 4D FB
LIST:
        JP SUB_FB5A_4                    ; $FA0F  C3 70 FB
PUNCH:
        JP SUB_FB5A_5                    ; $FA12  C3 7F FB
READER:
        JP SUB_FB5A_6                    ; $FA15  C3 91 FB
HOME:
        JP INIT_PASCAL_1_1_1             ; $FA18  C3 75 FE
SELDSK:
        JP SELDSK_IMPL_1                 ; $FA1B  C3 97 FE
SETTRK:
        JP INIT_PASCAL_1_1_3             ; $FA1E  C3 80 FE
SETSEC:
        JP SUB_FBF0_1                    ; $FA21  C3 F4 FB
SETDMA:
        JP SUB_FBF9                      ; $FA24  C3 F9 FB
READ:
        JP SELDSK_IMPL_3                 ; $FA27  C3 C6 FE
WRITE:
        JP SELDSK_IMPL_4                 ; $FA2A  C3 CC FE
LISTST:
        XOR A                            ; $FA2D  AF
        RET                              ; $FA2E  C9
        DEFB    $00                                              ; $FA2F
SECTRAN:
        LD H,B                           ; $FA30  60
        LD L,C                           ; $FA31  69
        RET                              ; $FA32  C9
        DEFB    $00,$00,$19,$00,$00,$00,$00,$00,$FD,$FE,$73,$FA,$C5,$FF,$7D,$FF ; $FA33
        DEFS    8, $00    ; $FA43  fill
        DEFB    $FD,$FE,$73,$FA,$D1,$FF,$8F,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; $FA4B
        DEFB    $FD,$FE,$73,$FA,$DD,$FF,$A1,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; $FA5B
        DEFB    $FD,$FE,$73,$FA,$E9,$FF,$B3,$FF,$20,$00,$03,$07,$00,$8B,$00,$2F ; $FA6B
        DEFB    $00,$C0,$00,$0C,$00,$03,$00                      ; $FA7B
SUB_FA82:
        LD DE,$0007                      ; $FA82  11 07 00
SUB_FA82_1:
        LD HL,SLOT_INFO_BASE             ; $FA85  21 B8 F3
        ADD HL,DE                        ; $FA88  19
        LD A,(HL)                        ; $FA89  7E
        SUB $03                          ; $FA8A  D6 03
        JR NZ,SUB_FA82_2                 ; $FA8C  20 07
        CALL SUB_FE8A                    ; $FA8E  CD 8A FE
        LD (HL),$03                      ; $FA91  36 03
        LD (HL),$15                      ; $FA93  36 15
SUB_FA82_2:
        DEC A                            ; $FA95  3D
        JR NZ,SUB_FA82_3                 ; $FA96  20 0B
        CALL INIT_PASCAL_1_0             ; $FA98  CD 83 FD
        LD HL,$C800                      ; $FA9B  21 00 C8
        CALL RPC_DISPATCH                ; $FA9E  CD 45 FB
        JR SUB_FA82_4                    ; $FAA1  18 0A
SUB_FA82_3:
        CP $02                           ; $FAA3  FE 02
        JR NZ,SUB_FA82_4                 ; $FAA5  20 06
        LD HL,$0DD0                      ; $FAA7  21 D0 0D
        CALL INIT_PASCAL_1_1             ; $FAAA  CD B0 FD
SUB_FA82_4:
        DEC E                            ; $FAAD  1D
        JR NZ,SUB_FA82_1                 ; $FAAE  20 D5
        RET                              ; $FAB0  C9
SUB_FAB1:
        LD HL,$E000                      ; $FAB1  21 00 E0
        LD A,E                           ; $FAB4  7B
        OR H                             ; $FAB5  B4
        LD H,A                           ; $FAB6  67
        RET                              ; $FAB7  C9
SUB_FAB1_1:
        LD SP,DEFAULT_DMA                ; $FAB8  31 80 00
        LD A,($E051)                     ; $FABB  3A 51 E0
        LD HL,$0E00                      ; $FABE  21 00 0E
        CALL RPC_DISPATCH                ; $FAC1  CD 45 FB
        CALL SUB_FA82                    ; $FAC4  CD 82 FA
        LD A,($DC08)                     ; $FAC7  3A 08 DC
        CP $DC                           ; $FACA  FE DC
        JR Z,SUB_FAB1_2                  ; $FACC  28 11
        LD HL,$FF59                      ; $FACE  21 59 FF
        LD ($F3D0),HL                    ; $FAD1  22 D0 F3
        LD HL,($F3DE)                    ; $FAD4  2A DE F3
        LD A,$77                         ; $FAD7  3E 77
        LD ($000B),A                     ; $FAD9  32 0B 00
        JP $000B                         ; $FADC  C3 0B 00
SUB_FAB1_2:
        XOR A                            ; $FADF  AF
        LD ($D307),A                     ; $FAE0  32 07 D3
        XOR A                            ; $FAE3  AF
        LD ($FEF6),A                     ; $FAE4  32 F6 FE
        LD ($FEF1),A                     ; $FAE7  32 F1 FE
        LD A,$C3                         ; $FAEA  3E C3
        LD (WBOOT_VEC),A                 ; $FAEC  32 00 00
        LD HL,WBOOT                      ; $FAEF  21 03 FA
        LD ($0001),HL                    ; $FAF2  22 01 00
        LD (BDOS_VEC),A                  ; $FAF5  32 05 00
        LD HL,$DC06                      ; $FAF8  21 06 DC
        LD ($0006),HL                    ; $FAFB  22 06 00
        LD BC,DEFAULT_DMA                ; $FAFE  01 80 00
        CALL SUB_FBF9                    ; $FB01  CD F9 FB
        LD A,$03                         ; $FB04  3E 03
        LD ($D74E),A                     ; $FB06  32 4E D7
        LD A,(CDISK)                     ; $FB09  3A 04 00
        LD C,A                           ; $FB0C  4F
        JP $D300                         ; $FB0D  C3 00 D3
SUB_FAB1_3:
        LD HL,($F380)                    ; $FB10  2A 80 F3
        JP (HL)                          ; $FB13  E9
        DEFB    $3A,$00,$E0,$17,$9F,$C9                          ; $FB14
SUB_FAB1_4:
        CALL SUB_FB5A                    ; $FB1A  CD 5A FB
        AND $7F                          ; $FB1D  E6 7F
        LD HL,$F3AB                      ; $FB1F  21 AB F3
        LD B,$06                         ; $FB22  06 06
        LD C,A                           ; $FB24  4F
SUB_FAB1_5:
        INC HL                           ; $FB25  23
        LD A,(HL)                        ; $FB26  7E
        INC HL                           ; $FB27  23
        OR A                             ; $FB28  B7
        JP M,SUB_FAB1_6                  ; $FB29  FA 31 FB
        CP C                             ; $FB2C  B9
        LD A,(HL)                        ; $FB2D  7E
        RET Z                            ; $FB2E  C8
        DJNZ SUB_FAB1_5                  ; $FB2F  10 F4
SUB_FAB1_6:
        LD A,C                           ; $FB31  79
        RET                              ; $FB32  C9
        DEFB    $11,$03,$00,$C3,$B7,$FD,$3A,$00,$E0,$17,$30,$FA,$32,$10,$E0,$3F ; $FB33
        DEFB    $1F,$C9                                          ; $FB43
RPC_DISPATCH:
        LD ($F3D0),HL                    ; $FB45  22 D0 F3
        LD ($E700),A                     ; $FB48  32 00 E7
        RET                              ; $FB4B  C9
        DEFB    $4F                                              ; $FB4C
RPC_DISPATCH_1:
        LD A,(IOBYTE)                    ; $FB4D  3A 03 00
        AND $03                          ; $FB50  E6 03
        CP $02                           ; $FB52  FE 02
        JR NZ,SUB_FB5A_8                 ; $FB54  20 4B
RPC_DISPATCH_2:
        LD HL,($F392)                    ; $FB56  2A 92 F3
        JP (HL)                          ; $FB59  E9
SUB_FB5A:
        LD A,(IOBYTE)                    ; $FB5A  3A 03 00
        AND $03                          ; $FB5D  E6 03
        CP $02                           ; $FB5F  FE 02
        LD HL,($F384)                    ; $FB61  2A 84 F3
        JR Z,SUB_FB5A_2                  ; $FB64  28 06
        JR NC,SUB_FB5A_3                 ; $FB66  30 07
SUB_FB5A_1:
        LD HL,($F382)                    ; $FB68  2A 82 F3
        JP (HL)                          ; $FB6B  E9
SUB_FB5A_2:
        LD HL,($F38A)                    ; $FB6C  2A 8A F3
SUB_FB5A_3:
        JP (HL)                          ; $FB6F  E9
SUB_FB5A_4:
        LD A,(IOBYTE)                    ; $FB70  3A 03 00
        AND $C0                          ; $FB73  E6 C0
        CP $80                           ; $FB75  FE 80
        JR C,SUB_FB5A_7                  ; $FB77  38 27
        JR Z,RPC_DISPATCH_2              ; $FB79  28 DB
        LD HL,($F394)                    ; $FB7B  2A 94 F3
        JP (HL)                          ; $FB7E  E9
SUB_FB5A_5:
        LD A,(IOBYTE)                    ; $FB7F  3A 03 00
        AND $30                          ; $FB82  E6 30
        CP $10                           ; $FB84  FE 10
        JR C,SUB_FB5A_7                  ; $FB86  38 18
        LD HL,($F38E)                    ; $FB88  2A 8E F3
        JR Z,SUB_FB5A_3                  ; $FB8B  28 E2
        LD HL,($F390)                    ; $FB8D  2A 90 F3
        JP (HL)                          ; $FB90  E9
SUB_FB5A_6:
        LD A,(IOBYTE)                    ; $FB91  3A 03 00
        AND $0C                          ; $FB94  E6 0C
        CP $08                           ; $FB96  FE 08
        JR C,SUB_FB5A_1                  ; $FB98  38 CE
        JR Z,SUB_FB5A_2                  ; $FB9A  28 D0
        LD HL,($F38C)                    ; $FB9C  2A 8C F3
        JP (HL)                          ; $FB9F  E9
SUB_FB5A_7:
        SCF                              ; $FBA0  37
SUB_FB5A_8:
        SBC A,A                          ; $FBA1  9F
        LD HL,$F3A2                      ; $FBA2  21 A2 F3
        LD L,(HL)                        ; $FBA5  6E
        INC L                            ; $FBA6  2C
        JP Z,SUB_FCA4                    ; $FBA7  CA A4 FC
        LD HL,$FEE4                      ; $FBAA  21 E4 FE
        LD (HL),A                        ; $FBAD  77
        RES 7,C                          ; $FBAE  CB B9
        INC HL                           ; $FBB0  23
        LD A,(HL)                        ; $FBB1  7E
        OR A                             ; $FBB2  B7
        JP Z,SUB_FBF9_1                  ; $FBB3  CA 56 FC
        DEC (HL)                         ; $FBB6  35
        LD A,($F396)                     ; $FBB7  3A 96 F3
        LD HL,$FEED                      ; $FBBA  21 ED FE
        JR Z,SUB_FBC4_2                  ; $FBBD  28 0C
        OR A                             ; $FBBF  B7
        JP P,SUB_FBC4_1                  ; $FBC0  F2 C6 FB
        DEC HL                           ; $FBC3  2B
SUB_FBC4:
        AND $7F                          ; $FBC4  E6 7F
SUB_FBC4_1:
        LD E,A                           ; $FBC6  5F
        LD A,C                           ; $FBC7  79
        SUB E                            ; $FBC8  93
        LD (HL),A                        ; $FBC9  77
        RET                              ; $FBCA  C9
SUB_FBC4_2:
        OR A                             ; $FBCB  B7
        JP M,SUB_FBC4_3                  ; $FBCC  FA D0 FB
        DEC HL                           ; $FBCF  2B
SUB_FBC4_3:
        CALL SUB_FBC4                    ; $FBD0  CD C4 FB
        LD HL,($FEEC)                    ; $FBD3  2A EC FE
        LD A,($F3A1)                     ; $FBD6  3A A1 F3
        OR A                             ; $FBD9  B7
        JP P,SUB_FBC4_4                  ; $FBDA  F2 E2 FB
        AND $7F                          ; $FBDD  E6 7F
        LD E,L                           ; $FBDF  5D
        LD L,H                           ; $FBE0  6C
        LD H,E                           ; $FBE1  63
SUB_FBC4_4:
        LD E,A                           ; $FBE2  5F
        ADD A,H                          ; $FBE3  84
        LD C,A                           ; $FBE4  4F
        LD A,E                           ; $FBE5  7B
        ADD A,L                          ; $FBE6  85
        PUSH AF                          ; $FBE7  F5
        LD B,$07                         ; $FBE8  06 07
        CALL SUB_FCA4                    ; $FBEA  CD A4 FC
        POP AF                           ; $FBED  F1
        LD B,$0A                         ; $FBEE  06 0A
SUB_FBF0:
        LD C,A                           ; $FBF0  4F
        JP SUB_FCA4                      ; $FBF1  C3 A4 FC
SUB_FBF0_1:
        LD A,C                           ; $FBF4  79
        LD ($FEEB),A                     ; $FBF5  32 EB FE
        RET                              ; $FBF8  C9
SUB_FBF9:
        LD ($FEFA),BC                    ; $FBF9  ED 43 FA FE
        RET                              ; $FBFD  C9
        DEFS    88, $00    ; $FBFE  fill
SUB_FBF9_1:
        LD B,A                           ; $FC56  47
        LD HL,$FEE6                      ; $FC57  21 E6 FE
        LD A,(HL)                        ; $FC5A  7E
        LD E,A                           ; $FC5B  5F
        OR A                             ; $FC5C  B7
        JR NZ,SUB_FBF9_3                 ; $FC5D  20 12
        LD A,(TPA_STATE_F397)            ; $FC5F  3A 97 F3
        OR A                             ; $FC62  B7
        JR Z,SUB_FBF9_2                  ; $FC63  28 06
        CP C                             ; $FC65  B9
        JR NZ,SUB_FBF9_2                 ; $FC66  20 03
        LD (HL),$80                      ; $FC68  36 80
        RET                              ; $FC6A  C9
SUB_FBF9_2:
        LD A,$1F                         ; $FC6B  3E 1F
        CP C                             ; $FC6D  B9
        JP C,SUB_FCA4                    ; $FC6E  DA A4 FC
SUB_FBF9_3:
        LD HL,DEVICE_TABLE_BASE          ; $FC71  21 A0 F3
        LD B,$09                         ; $FC74  06 09
SUB_FBF9_4:
        LD A,(HL)                        ; $FC76  7E
        OR A                             ; $FC77  B7
        JR Z,SUB_FBF9_5                  ; $FC78  28 04
        XOR E                            ; $FC7A  AB
        CP C                             ; $FC7B  B9
        JR Z,SUB_FBF9_6                  ; $FC7C  28 05
SUB_FBF9_5:
        DEC HL                           ; $FC7E  2B
        DJNZ SUB_FBF9_4                  ; $FC7F  10 F5
        JR SUB_FCA4                      ; $FC81  18 21
SUB_FBF9_6:
        LD DE,$000B                      ; $FC83  11 0B 00
        ADD HL,DE                        ; $FC86  19
        LD A,(HL)                        ; $FC87  7E
        OR A                             ; $FC88  B7
        LD C,A                           ; $FC89  4F
        JP P,SUB_FBF9_7                  ; $FC8A  F2 9A FC
        AND $7F                          ; $FC8D  E6 7F
        LD C,A                           ; $FC8F  4F
        PUSH BC                          ; $FC90  C5
        LD A,($F3A2)                     ; $FC91  3A A2 F3
        LD B,$07                         ; $FC94  06 07
        CALL SUB_FBF0                    ; $FC96  CD F0 FB
        POP BC                           ; $FC99  C1
SUB_FBF9_7:
        LD A,B                           ; $FC9A  78
        CP $07                           ; $FC9B  FE 07
        JR NZ,SUB_FCA4                   ; $FC9D  20 05
        LD A,$02                         ; $FC9F  3E 02
        LD ($FEE5),A                     ; $FCA1  32 E5 FE
SUB_FCA4:
        XOR A                            ; $FCA4  AF
        LD ($FEE6),A                     ; $FCA5  32 E6 FE
        LD A,($FEE4)                     ; $FCA8  3A E4 FE
        OR A                             ; $FCAB  B7
        LD HL,($F388)                    ; $FCAC  2A 88 F3
        JR Z,SUB_FCA4_1                  ; $FCAF  28 03
        LD HL,($F386)                    ; $FCB1  2A 86 F3
SUB_FCA4_1:
        JP (HL)                          ; $FCB4  E9
        DEFB    $11,$03,$00,$C3,$A9,$FD,$2A,$E7,$FE,$3A,$E9,$FE,$77,$CD,$E2,$FC ; $FCB5
        DEFB    $2A,$28,$F0,$3A,$24,$F0,$5F,$16,$F0,$19,$22,$E7,$FE,$7E,$32,$E9 ; $FCC5
        DEFB    $FE,$FE,$E0,$38,$02,$EE,$20,$E6,$3F,$F6,$40,$77,$C9,$78,$B7,$28 ; $FCD5
        DEFB    $0B,$21,$45,$FB,$E5,$21,$66,$FD,$85,$6F,$6E,$E9,$79,$FE,$0D,$20 ; $FCE5
        DEFB    $05,$AF,$32,$24,$F0,$C9,$F6,$80,$FE,$E0,$38,$04,$21,$DD,$F3,$AE ; $FCF5
        DEFB    $32,$45,$F0,$21,$F0,$FD,$C3,$80                  ; $FD05  "2Ep!p}C"
        DEFB    $FD,$CD,$8A,$FE,$C6,$8F,$CB,$4E,$28,$FC,$21,$2F,$F0,$36,$60,$2B ; $FD0D
        DEFB    $36,$C0,$2B,$77,$2B,$36,$8D                      ; $FD1D  "6@+w+6"
        DEFB    $62,$C3,$7C,$FD,$3E,$FF,$01,$3E,$3F,$32,$32,$F0,$E1,$C9,$21,$F4 ; $FD24
        DEFB    $FB,$C9,$AF,$6F,$67,$22,$24,$F0,$32,$45,$F0,$21,$C1,$FB,$C9,$2E ; $FD34
        DEFB    $42,$01,$2E,$9C,$01,$2E,$1A,$01,$2E,$58,$26,$FC,$C9,$2A,$EC,$FE ; $FD44
        DEFB    $7D,$FE,$28,$38,$02,$2E,$00,$7C,$FE,$18,$38,$02,$26,$00,$22,$24 ; $FD54
        DEFB    $F0,$18,$D5,$4C,$43,$46,$28,$2B,$36,$30,$49,$32,$51,$CD,$83,$FD ; $FD64
        DEFB    $21,$78,$F6,$19,$71,$21,$AA,$C9,$79,$32,$45,$F0,$C3,$45,$FB ; $FD74
INIT_PASCAL_1_0:
        CALL SUB_FE85                    ; $FD83  CD 85 FE
        LD ($F6F8),A                     ; $FD86  32 F8 F6
        LD ($F047),A                     ; $FD89  32 47 F0
        LD A,($EFFF)                     ; $FD8C  3A FF EF
        CALL SUB_FAB1                    ; $FD8F  CD B1 FA
        SUB $20                          ; $FD92  D6 20
        LD ($F046),A                     ; $FD94  32 46 F0
        LD A,(HL)                        ; $FD97  7E
        RET                              ; $FD98  C9
        DEFB    $21,$1D,$0E,$1E,$03,$3E,$01,$CD,$AD,$FD,$3A,$48,$F0,$1F,$9F,$C9 ; $FD99
        DEFB    $21,$E1,$0D,$79,$32,$45,$F0                      ; $FDA9
INIT_PASCAL_1_1:
        LD A,E                           ; $FDB0  7B
        LD ($F047),A                     ; $FDB1  32 47 F0
        JP RPC_DISPATCH                  ; $FDB4  C3 45 FB
        DEFB    $21,$0F,$0E,$CD,$B0,$FD,$3A,$45,$F0,$C9,$CD,$83,$FD,$21,$4D,$C8 ; $FDB7
        DEFB    $CD,$45,$FB,$21,$78,$F6,$19,$7E,$C9,$48,$20,$26,$0E,$A0,$0D,$B1 ; $FDC7
        DEFB    $F6,$85,$F6,$AC,$F8,$06,$68,$6C,$F6,$00,$48,$A9,$00,$20,$EF,$0D ; $FDD7
        DEFB    $20,$26,$0E,$A0,$0F,$4C,$D6,$0D,$84,$F5,$48,$20,$1D,$0E,$68,$A4 ; $FDE7
        DEFB    $F5,$90,$F5,$60,$00,$00,$00,$00,$00,$4C,$09,$0E,$8D,$8B,$C0,$4C ; $FDF7
        DEFB    $13,$D4,$8D,$8B,$C0,$4C,$F7,$D1,$A9,$01,$20,$EF,$0D,$20,$26,$0E ; $FE07
        DEFB    $48,$A0,$0E,$4C,$D6,$0D,$48,$20,$26,$0E,$A0,$10,$4C,$D6,$0D,$98 ; $FE17
        DEFB    $09,$C0,$AA,$98,$0A,$0A,$0A,$0A,$A8,$8C,$F8,$06,$A9,$00,$85,$F6 ; $FE27
        DEFB    $86,$F7,$AD,$FF,$CF,$B1,$F6,$60,$A5,$48,$48,$A5,$45,$A6,$46,$A4 ; $FE37
        DEFB    $47,$28,$58,$60,$CD,$8A,$FE,$7E,$1F,$30,$FC,$2C,$7E,$C9,$11,$01 ; $FE47
        DEFB    $00,$C3,$68,$FE,$CD,$B1,$FA,$2E,$C1,$7E,$17,$38,$FC,$CD,$85,$FE ; $FE57
        DEFB    $71,$C9,$11,$02,$00,$C3,$68,$FE,$11,$02,$00,$3E,$1A,$C9 ; $FE67
INIT_PASCAL_1_1_1:
        LD A,($FEF2)                     ; $FE75  3A F2 FE
        OR A                             ; $FE78  B7
        JR NZ,INIT_PASCAL_1_1_2          ; $FE79  20 03
        LD ($FEF1),A                     ; $FE7B  32 F1 FE
INIT_PASCAL_1_1_2:
        LD C,$00                         ; $FE7E  0E 00
INIT_PASCAL_1_1_3:
        LD A,C                           ; $FE80  79
        LD ($FEEA),A                     ; $FE81  32 EA FE
        RET                              ; $FE84  C9
SUB_FE85:
        LD HL,$E080                      ; $FE85  21 80 E0
        JR SUB_FE8A_1                    ; $FE88  18 03
SUB_FE8A:
        LD HL,$E08E                      ; $FE8A  21 8E E0
SUB_FE8A_1:
        LD A,E                           ; $FE8D  7B
SELDSK_IMPL:
        ADD A,A                          ; $FE8E  87
        ADD A,A                          ; $FE8F  87
        ADD A,A                          ; $FE90  87
        ADD A,A                          ; $FE91  87
        PUSH AF                          ; $FE92  F5
        ADD A,L                          ; $FE93  85
        LD L,A                           ; $FE94  6F
        POP AF                           ; $FE95  F1
        RET                              ; $FE96  C9
SELDSK_IMPL_1:
        LD DE,$FEEE                      ; $FE97  11 EE FE
        LD HL,CDISK                      ; $FE9A  21 04 00
        LD A,(SLOT_INFO_BASE)            ; $FE9D  3A B8 F3
        DEC A                            ; $FEA0  3D
        CP C                             ; $FEA1  B9
        JR C,SELDSK_IMPL_2               ; $FEA2  38 1D
        LD A,(HL)                        ; $FEA4  7E
        LD (DE),A                        ; $FEA5  12
        INC DE                           ; $FEA6  13
        LD A,C                           ; $FEA7  79
        LD (DE),A                        ; $FEA8  12
        LD HL,$FA33                      ; $FEA9  21 33 FA
        CALL SELDSK_IMPL                 ; $FEAC  CD 8E FE
        PUSH HL                          ; $FEAF  E5
        LD DE,$000A                      ; $FEB0  11 0A 00
        ADD HL,DE                        ; $FEB3  19
        LD E,(HL)                        ; $FEB4  5E
        INC HL                           ; $FEB5  23
        LD D,(HL)                        ; $FEB6  56
        LD HL,BDOS_VEC                   ; $FEB7  21 05 00
        ADD HL,DE                        ; $FEBA  19
        LD A,(HL)                        ; $FEBB  7E
        LD ($FEFC),A                     ; $FEBC  32 FC FE
        POP HL                           ; $FEBF  E1
        RET                              ; $FEC0  C9
SELDSK_IMPL_2:
        LD A,(DE)                        ; $FEC1  1A
        LD (HL),A                        ; $FEC2  77
        LD L,$00                         ; $FEC3  2E 00
        RET                              ; $FEC5  C9
SELDSK_IMPL_3:
        LD ($E08B),A                     ; $FEC6  32 8B E0
        JP $B247                         ; $FEC9  C3 47 B2
SELDSK_IMPL_4:
        LD ($E08B),A                     ; $FECC  32 8B E0
        JP $B257                         ; $FECF  C3 57 B2
        DEFB    $CD,$45,$FB,$32,$8B,$E0,$C9,$32,$83,$E0,$2A,$0D,$DC,$E9,$32,$83 ; $FED2
        DEFB    $E0,$C9,$FF,$00,$00,$E9,$FE,$00,$03,$0B,$01,$AF,$00,$00,$00,$01 ; $FEE2
        DEFB    $00,$02,$02,$02,$00,$95,$32,$03,$80,$00,$8B,$E5,$E5,$E5,$E5,$E5 ; $FEF2
        DEFS    123, $E5    ; $FF02  fill
        DEFS    17, $FF    ; $FF7D  fill
        DEFB    $F0,$FD,$4B,$FE,$C1,$FD,$B7,$FD,$B7,$FD,$21,$90,$FF,$18,$03,$21 ; $FF8E
        DEFB    $88,$FF,$87,$85,$6F,$7E,$2C,$66,$6F,$C9,$B7,$F2,$B4,$FF,$F5,$3A ; $FF9E
        DEFB    $97,$F3,$CD,$4C,$FB,$F1,$C3,$4C,$FB,$0D,$0A,$0A,$0A,$20,$20,$20 ; $FFAE
        DEFB    $20,$20,$53,$6F,$66,$74,$63,$5C,$05,$45,$39,$AE,$90,$EF,$80,$80 ; $FFBE
        DEFB    $80,$80,$80,$20,$20,$20,$36,$30,$4B,$20,$56,$65,$72,$2E,$20,$32 ; $FFCE
        DEFB    $2E,$32,$33,$0D,$0A,$28,$63,$29,$20,$31,$39,$38,$30,$2C,$31,$39 ; $FFDE
        DEFB    "82 Microsoft"    ; $FFEE  string
        DEFB    $0D    ; $FFFA  terminator
        DEFB    $0A,$0D,$0A,$00,$FA                              ; $FFFB

    SAVEBIN "CPM_BIOS.bin", $FA00, $0600
