; Generated by disasm_z80
; Source: CPM_CCP_60K
; Range:  $D300-$DC05  (2310 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
IOBYTE               EQU $0003               ; I/O assignment byte — logical-to-physical device routing (CONSOLE/READER/PUNCH/LIST). 4 fields × 2 bits each.
CDISK                EQU $0004               ; Current drive (low nibble: 0=A, 1=B, ..., 15=P) and current user (high nibble, 0-15).
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_FCB          EQU $005C               ; Default File Control Block — populated by CCP from command-line argument 1. Standard 36-byte FCB structure (drive + filename + extents + record number).
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).
CMDLINE              EQU $0081               ; Command-line tail characters (uppercase, with leading space). Same buffer as DEFAULT_DMA.
TPA_START            EQU $0100               ; Start of Transient Program Area. .COM files load here and execute starting at $0100.

    ORG $D300

L_D300:
        JP SUB_D5E5_5                    ; $D300  C3 0C D6
        DEFB    $C3,$08,$D6,$7F,$00,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20 ; $D303
        DEFB    "     COPYRIGHT (C) 1979, DIGITAL RESEARCH  "    ; $D313  string
        DEFB    $00    ; $D33E  terminator
        DEFS    73, $00    ; $D33F  fill
        DEFB    $08,$D3,$00,$00                                  ; $D388
SUB_D38C:
        LD E,A                           ; $D38C  5F
        LD C,$02                         ; $D38D  0E 02
        JR SUB_D3B6_1                    ; $D38F  18 28
        DEFB    $3E,$20                                          ; $D391
SUB_D393:
        PUSH BC                          ; $D393  C5
        CALL SUB_D38C                    ; $D394  CD 8C D3
        POP BC                           ; $D397  C1
        RET                              ; $D398  C9
SUB_D399:
        LD A,$0D                         ; $D399  3E 0D
        CALL SUB_D393                    ; $D39B  CD 93 D3
        LD A,$0A                         ; $D39E  3E 0A
        JR SUB_D393                      ; $D3A0  18 F1
SUB_D3A2:
        PUSH BC                          ; $D3A2  C5
        CALL SUB_D399                    ; $D3A3  CD 99 D3
        POP HL                           ; $D3A6  E1
SUB_D3A7:
        LD A,(HL)                        ; $D3A7  7E
        OR A                             ; $D3A8  B7
        RET Z                            ; $D3A9  C8
        INC HL                           ; $D3AA  23
        PUSH HL                          ; $D3AB  E5
        CALL SUB_D38C                    ; $D3AC  CD 8C D3
        POP HL                           ; $D3AF  E1
        JR SUB_D3A7                      ; $D3B0  18 F5
SUB_D3B2:
        LD C,$0D                         ; $D3B2  0E 0D
        JR SUB_D3B6_1                    ; $D3B4  18 03
SUB_D3B6:
        LD E,A                           ; $D3B6  5F
        LD C,$0E                         ; $D3B7  0E 0E
SUB_D3B6_1:
        JP BDOS_VEC                      ; $D3B9  C3 05 00
SUB_D3BC:
        LD C,$10                         ; $D3BC  0E 10
SUB_D3BC_1:
        CALL BDOS_VEC                    ; $D3BE  CD 05 00
        LD ($DBA7),A                     ; $D3C1  32 A7 DB
        INC A                            ; $D3C4  3C
        RET                              ; $D3C5  C9
SUB_D3C6:
        XOR A                            ; $D3C6  AF
        LD ($DBA6),A                     ; $D3C7  32 A6 DB
        LD DE,$DB86                      ; $D3CA  11 86 DB
SUB_D3CD:
        LD C,$0F                         ; $D3CD  0E 0F
        JR SUB_D3BC_1                    ; $D3CF  18 ED
        DEFB    $11,$86,$DB,$0E,$11,$18,$E6,$0E,$12,$18,$E2      ; $D3D1
SUB_D3DC:
        LD C,$13                         ; $D3DC  0E 13
        JR SUB_D3B6_1                    ; $D3DE  18 D9
        DEFB    $11,$86,$DB                                      ; $D3E0
SUB_D3E3:
        LD C,$14                         ; $D3E3  0E 14
        CALL BDOS_VEC                    ; $D3E5  CD 05 00
        OR A                             ; $D3E8  B7
        RET                              ; $D3E9  C9
        DEFB    $0E,$15,$18,$F7,$0E,$16,$18,$CC,$0E,$17,$18,$C3  ; $D3EA
SUB_D3F6:
        LD E,$FF                         ; $D3F6  1E FF
SUB_D3F8:
        LD C,$20                         ; $D3F8  0E 20
        JR SUB_D3B6_1                    ; $D3FA  18 BD
SUB_D3FC:
        CALL SUB_D3F6                    ; $D3FC  CD F6 D3
        ADD A,A                          ; $D3FF  87
        ADD A,A                          ; $D400  87
        ADD A,A                          ; $D401  87
        ADD A,A                          ; $D402  87
        LD HL,$DBA8                      ; $D403  21 A8 DB
        OR (HL)                          ; $D406  B6
        LD (CDISK),A                     ; $D407  32 04 00
        RET                              ; $D40A  C9
SUB_D40B:
        LD A,($DBA8)                     ; $D40B  3A A8 DB
        LD (CDISK),A                     ; $D40E  32 04 00
        RET                              ; $D411  C9
SUB_D412:
        CP $61                           ; $D412  FE 61
        RET C                            ; $D414  D8
        CP $7B                           ; $D415  FE 7B
        RET NC                           ; $D417  D0
        AND $5F                          ; $D418  E6 5F
        RET                              ; $D41A  C9
SUB_D41B:
        LD A,($DB64)                     ; $D41B  3A 64 DB
        OR A                             ; $D41E  B7
        JR Z,SUB_D41B_1                  ; $D41F  28 52
        LD A,($DBA8)                     ; $D421  3A A8 DB
        OR A                             ; $D424  B7
        LD A,$00                         ; $D425  3E 00
        CALL NZ,SUB_D3B6                 ; $D427  C4 B6 D3
        LD DE,$DB65                      ; $D42A  11 65 DB
        CALL SUB_D3CD                    ; $D42D  CD CD D3
        JR Z,SUB_D41B_1                  ; $D430  28 41
        LD A,($DB74)                     ; $D432  3A 74 DB
        DEC A                            ; $D435  3D
        LD ($DB85),A                     ; $D436  32 85 DB
        LD DE,$DB65                      ; $D439  11 65 DB
        CALL SUB_D3E3                    ; $D43C  CD E3 D3
        JR NZ,SUB_D41B_1                 ; $D43F  20 32
        LD DE,$D307                      ; $D441  11 07 D3
        LD HL,DEFAULT_DMA                ; $D444  21 80 00
        LD BC,DEFAULT_DMA                ; $D447  01 80 00
        LDIR                             ; $D44A  ED B0
        LD HL,$DB73                      ; $D44C  21 73 DB
        LD (HL),$00                      ; $D44F  36 00
        INC HL                           ; $D451  23
        DEC (HL)                         ; $D452  35
        LD DE,$DB65                      ; $D453  11 65 DB
        CALL SUB_D3BC                    ; $D456  CD BC D3
        JR Z,SUB_D41B_1                  ; $D459  28 18
        LD A,($DBA8)                     ; $D45B  3A A8 DB
        OR A                             ; $D45E  B7
        CALL NZ,SUB_D3B6                 ; $D45F  C4 B6 D3
        LD HL,$D308                      ; $D462  21 08 D3
        CALL SUB_D3A7                    ; $D465  CD A7 D3
        CALL SUB_D49A                    ; $D468  CD 9A D4
        JR Z,SUB_D41B_2                  ; $D46B  28 14
        CALL SUB_D4B5                    ; $D46D  CD B5 D4
        JP SUB_D5E5_6                    ; $D470  C3 31 D6
SUB_D41B_1:
        CALL SUB_D4B5                    ; $D473  CD B5 D4
        CALL SUB_D3FC                    ; $D476  CD FC D3
        LD C,$0A                         ; $D479  0E 0A
        LD DE,$D306                      ; $D47B  11 06 D3
        CALL BDOS_VEC                    ; $D47E  CD 05 00
SUB_D41B_2:
        LD HL,$D307                      ; $D481  21 07 D3
        LD B,(HL)                        ; $D484  46
SUB_D41B_3:
        INC HL                           ; $D485  23
        LD A,B                           ; $D486  78
        OR A                             ; $D487  B7
        JR Z,SUB_D41B_4                  ; $D488  28 08
        LD A,(HL)                        ; $D48A  7E
        CALL SUB_D412                    ; $D48B  CD 12 D4
        LD (HL),A                        ; $D48E  77
        DEC B                            ; $D48F  05
        JR SUB_D41B_3                    ; $D490  18 F3
SUB_D41B_4:
        LD (HL),A                        ; $D492  77
        LD HL,$D308                      ; $D493  21 08 D3
        LD ($D388),HL                    ; $D496  22 88 D3
        RET                              ; $D499  C9
SUB_D49A:
        LD C,$0B                         ; $D49A  0E 0B
        CALL BDOS_VEC                    ; $D49C  CD 05 00
        OR A                             ; $D49F  B7
        RET Z                            ; $D4A0  C8
        LD C,$01                         ; $D4A1  0E 01
        CALL BDOS_VEC                    ; $D4A3  CD 05 00
        OR A                             ; $D4A6  B7
        RET                              ; $D4A7  C9
SUB_D4A8:
        LD C,$19                         ; $D4A8  0E 19
        JP BDOS_VEC                      ; $D4AA  C3 05 00
SUB_D4AD:
        LD DE,DEFAULT_DMA                ; $D4AD  11 80 00
SUB_D4B0:
        LD C,$1A                         ; $D4B0  0E 1A
        JP BDOS_VEC                      ; $D4B2  C3 05 00
SUB_D4B5:
        LD HL,$DB64                      ; $D4B5  21 64 DB
        LD A,(HL)                        ; $D4B8  7E
        OR A                             ; $D4B9  B7
        RET Z                            ; $D4BA  C8
        LD (HL),$00                      ; $D4BB  36 00
        XOR A                            ; $D4BD  AF
        CALL SUB_D3B6                    ; $D4BE  CD B6 D3
        LD DE,$DB65                      ; $D4C1  11 65 DB
        CALL SUB_D3DC                    ; $D4C4  CD DC D3
        LD A,($DBA8)                     ; $D4C7  3A A8 DB
        JP SUB_D3B6                      ; $D4CA  C3 B6 D3
SUB_D4CD:
        LD DE,$D5DF                      ; $D4CD  11 DF D5
        LD HL,$DC00                      ; $D4D0  21 00 DC
        LD B,$06                         ; $D4D3  06 06
SUB_D4CD_1:
        LD A,(DE)                        ; $D4D5  1A
        CP (HL)                          ; $D4D6  BE
        JP NZ,SUB_D5E5_8                 ; $D4D7  C2 7E D6
        INC DE                           ; $D4DA  13
        INC HL                           ; $D4DB  23
        DJNZ SUB_D4CD_1                  ; $D4DC  10 F7
        RET                              ; $D4DE  C9
SUB_D4DF:
        CALL SUB_D399                    ; $D4DF  CD 99 D3
        LD HL,($D38A)                    ; $D4E2  2A 8A D3
SUB_D4DF_1:
        LD A,(HL)                        ; $D4E5  7E
        CP $20                           ; $D4E6  FE 20
        JR Z,SUB_D4DF_2                  ; $D4E8  28 0B
        OR A                             ; $D4EA  B7
        JR Z,SUB_D4DF_2                  ; $D4EB  28 08
        PUSH HL                          ; $D4ED  E5
        CALL SUB_D38C                    ; $D4EE  CD 8C D3
        POP HL                           ; $D4F1  E1
        INC HL                           ; $D4F2  23
        JR SUB_D4DF_1                    ; $D4F3  18 F0
SUB_D4DF_2:
        LD A,$3F                         ; $D4F5  3E 3F
        CALL SUB_D38C                    ; $D4F7  CD 8C D3
        CALL SUB_D399                    ; $D4FA  CD 99 D3
        CALL SUB_D4B5                    ; $D4FD  CD B5 D4
        JP SUB_D5E5_6                    ; $D500  C3 31 D6
SUB_D503:
        LD A,(DE)                        ; $D503  1A
        OR A                             ; $D504  B7
        RET Z                            ; $D505  C8
        CP $20                           ; $D506  FE 20
        JR C,SUB_D4DF                    ; $D508  38 D5
        RET Z                            ; $D50A  C8
        CP $3D                           ; $D50B  FE 3D
        RET Z                            ; $D50D  C8
        CP $5F                           ; $D50E  FE 5F
        RET Z                            ; $D510  C8
        CP $2E                           ; $D511  FE 2E
        RET Z                            ; $D513  C8
        CP $3A                           ; $D514  FE 3A
        RET Z                            ; $D516  C8
        CP $3B                           ; $D517  FE 3B
        RET Z                            ; $D519  C8
        CP $3C                           ; $D51A  FE 3C
        RET Z                            ; $D51C  C8
        CP $3E                           ; $D51D  FE 3E
        RET Z                            ; $D51F  C8
        RET                              ; $D520  C9
SUB_D521:
        LD A,(DE)                        ; $D521  1A
        OR A                             ; $D522  B7
        RET Z                            ; $D523  C8
        CP $20                           ; $D524  FE 20
        RET NZ                           ; $D526  C0
        INC DE                           ; $D527  13
        JR SUB_D521                      ; $D528  18 F7
SUB_D52A:
        ADD A,L                          ; $D52A  85
        LD L,A                           ; $D52B  6F
        RET NC                           ; $D52C  D0
        INC H                            ; $D52D  24
        RET                              ; $D52E  C9
SUB_D52F:
        LD A,$00                         ; $D52F  3E 00
SUB_D531:
        LD HL,$DB86                      ; $D531  21 86 DB
        CALL SUB_D52A                    ; $D534  CD 2A D5
        PUSH HL                          ; $D537  E5
        PUSH HL                          ; $D538  E5
        XOR A                            ; $D539  AF
        LD ($DBA9),A                     ; $D53A  32 A9 DB
        LD HL,($D388)                    ; $D53D  2A 88 D3
        EX DE,HL                         ; $D540  EB
        CALL SUB_D521                    ; $D541  CD 21 D5
        EX DE,HL                         ; $D544  EB
        LD ($D38A),HL                    ; $D545  22 8A D3
        EX DE,HL                         ; $D548  EB
        POP HL                           ; $D549  E1
        LD A,(DE)                        ; $D54A  1A
        OR A                             ; $D54B  B7
        JR Z,SUB_D531_1                  ; $D54C  28 0A
        SBC A,$40                        ; $D54E  DE 40
        LD B,A                           ; $D550  47
        INC DE                           ; $D551  13
        LD A,(DE)                        ; $D552  1A
        CP $3A                           ; $D553  FE 3A
        JR Z,SUB_D531_2                  ; $D555  28 07
        DEC DE                           ; $D557  1B
SUB_D531_1:
        LD A,($DBA8)                     ; $D558  3A A8 DB
        LD (HL),A                        ; $D55B  77
        JR SUB_D531_3                    ; $D55C  18 06
SUB_D531_2:
        LD A,B                           ; $D55E  78
        LD ($DBA9),A                     ; $D55F  32 A9 DB
        LD (HL),B                        ; $D562  70
        INC DE                           ; $D563  13
SUB_D531_3:
        LD B,$08                         ; $D564  06 08
SUB_D531_4:
        CALL SUB_D503                    ; $D566  CD 03 D5
        JR Z,SUB_D531_8                  ; $D569  28 15
        INC HL                           ; $D56B  23
        CP $2A                           ; $D56C  FE 2A
        JR NZ,SUB_D531_5                 ; $D56E  20 04
        LD (HL),$3F                      ; $D570  36 3F
        JR SUB_D531_6                    ; $D572  18 02
SUB_D531_5:
        LD (HL),A                        ; $D574  77
        INC DE                           ; $D575  13
SUB_D531_6:
        DJNZ SUB_D531_4                  ; $D576  10 EE
SUB_D531_7:
        CALL SUB_D503                    ; $D578  CD 03 D5
        JR Z,SUB_D531_9                  ; $D57B  28 08
        INC DE                           ; $D57D  13
        JR SUB_D531_7                    ; $D57E  18 F8
SUB_D531_8:
        INC HL                           ; $D580  23
        LD (HL),$20                      ; $D581  36 20
        DJNZ SUB_D531_8                  ; $D583  10 FB
SUB_D531_9:
        LD B,$03                         ; $D585  06 03
        CP $2E                           ; $D587  FE 2E
        JR NZ,SUB_D531_14                ; $D589  20 1B
        INC DE                           ; $D58B  13
SUB_D531_10:
        CALL SUB_D503                    ; $D58C  CD 03 D5
        JR Z,SUB_D531_14                 ; $D58F  28 15
        INC HL                           ; $D591  23
        CP $2A                           ; $D592  FE 2A
        JR NZ,SUB_D531_11                ; $D594  20 04
        LD (HL),$3F                      ; $D596  36 3F
        JR SUB_D531_12                   ; $D598  18 02
SUB_D531_11:
        LD (HL),A                        ; $D59A  77
        INC DE                           ; $D59B  13
SUB_D531_12:
        DJNZ SUB_D531_10                 ; $D59C  10 EE
SUB_D531_13:
        CALL SUB_D503                    ; $D59E  CD 03 D5
        JR Z,SUB_D531_15                 ; $D5A1  28 08
        INC DE                           ; $D5A3  13
        JR SUB_D531_13                   ; $D5A4  18 F8
SUB_D531_14:
        INC HL                           ; $D5A6  23
        LD (HL),$20                      ; $D5A7  36 20
        DJNZ SUB_D531_14                 ; $D5A9  10 FB
SUB_D531_15:
        LD B,$03                         ; $D5AB  06 03
SUB_D531_16:
        INC HL                           ; $D5AD  23
        LD (HL),$00                      ; $D5AE  36 00
        DJNZ SUB_D531_16                 ; $D5B0  10 FB
        EX DE,HL                         ; $D5B2  EB
        LD ($D388),HL                    ; $D5B3  22 88 D3
        POP HL                           ; $D5B6  E1
        LD BC,$000B                      ; $D5B7  01 0B 00
SUB_D531_17:
        INC HL                           ; $D5BA  23
        LD A,(HL)                        ; $D5BB  7E
        CP $3F                           ; $D5BC  FE 3F
        JR NZ,SUB_D531_18                ; $D5BE  20 01
        INC B                            ; $D5C0  04
SUB_D531_18:
        DEC C                            ; $D5C1  0D
        JR NZ,SUB_D531_17                ; $D5C2  20 F6
        LD A,B                           ; $D5C4  78
        OR A                             ; $D5C5  B7
        RET                              ; $D5C6  C9
        DEFB    $44,$49,$52,$20,$45,$52,$41,$20,$54,$59,$50,$45,$53,$41,$56,$45 ; $D5C7
        DEFB    $52,$45,$4E,$20,$55,$53,$45,$52,$BD,$16,$00,$01,$4D,$40 ; $D5D7
SUB_D5E5:
        LD HL,$D5C7                      ; $D5E5  21 C7 D5
        LD C,$00                         ; $D5E8  0E 00
SUB_D5E5_1:
        LD A,C                           ; $D5EA  79
        CP $06                           ; $D5EB  FE 06
        RET NC                           ; $D5ED  D0
        LD DE,$DB87                      ; $D5EE  11 87 DB
        LD B,$04                         ; $D5F1  06 04
SUB_D5E5_2:
        LD A,(DE)                        ; $D5F3  1A
        CP (HL)                          ; $D5F4  BE
        JR NZ,SUB_D5E5_3                 ; $D5F5  20 0B
        INC DE                           ; $D5F7  13
        INC HL                           ; $D5F8  23
        DJNZ SUB_D5E5_2                  ; $D5F9  10 F8
        LD A,(DE)                        ; $D5FB  1A
        CP $20                           ; $D5FC  FE 20
        JR NZ,SUB_D5E5_4                 ; $D5FE  20 05
        LD A,C                           ; $D600  79
        RET                              ; $D601  C9
SUB_D5E5_3:
        INC HL                           ; $D602  23
        DJNZ SUB_D5E5_3                  ; $D603  10 FD
SUB_D5E5_4:
        INC C                            ; $D605  0C
        JR SUB_D5E5_1                    ; $D606  18 E2
        DEFB    $AF,$32,$07,$D3                                  ; $D608
SUB_D5E5_5:
        LD SP,$DB64                      ; $D60C  31 64 DB
        PUSH BC                          ; $D60F  C5
        LD A,C                           ; $D610  79
        RRA                              ; $D611  1F
        RRA                              ; $D612  1F
        RRA                              ; $D613  1F
        RRA                              ; $D614  1F
        AND $0F                          ; $D615  E6 0F
        LD E,A                           ; $D617  5F
        CALL SUB_D3F8                    ; $D618  CD F8 D3
        CALL SUB_D3B2                    ; $D61B  CD B2 D3
        LD ($DB64),A                     ; $D61E  32 64 DB
        POP BC                           ; $D621  C1
        LD A,C                           ; $D622  79
        AND $0F                          ; $D623  E6 0F
        LD ($DBA8),A                     ; $D625  32 A8 DB
        CALL SUB_D3B6                    ; $D628  CD B6 D3
        LD A,($D307)                     ; $D62B  3A 07 D3
        OR A                             ; $D62E  B7
        JR NZ,SUB_D5E5_7                 ; $D62F  20 16
SUB_D5E5_6:
        LD SP,$DB64                      ; $D631  31 64 DB
        CALL SUB_D399                    ; $D634  CD 99 D3
        CALL SUB_D4A8                    ; $D637  CD A8 D4
        ADD A,$41                        ; $D63A  C6 41
        CALL SUB_D38C                    ; $D63C  CD 8C D3
        LD A,$3E                         ; $D63F  3E 3E
        CALL SUB_D38C                    ; $D641  CD 8C D3
        CALL SUB_D41B                    ; $D644  CD 1B D4
SUB_D5E5_7:
        LD DE,DEFAULT_DMA                ; $D647  11 80 00
        CALL SUB_D4B0                    ; $D64A  CD B0 D4
        CALL SUB_D4A8                    ; $D64D  CD A8 D4
        LD ($DBA8),A                     ; $D650  32 A8 DB
        CALL SUB_D52F                    ; $D653  CD 2F D5
        CALL NZ,SUB_D4DF                 ; $D656  C4 DF D4
        LD A,($DBA9)                     ; $D659  3A A9 DB
        OR A                             ; $D65C  B7
        JP NZ,SUB_D707_1                 ; $D65D  C2 26 D9
        CALL SUB_D5E5                    ; $D660  CD E5 D5
        LD HL,$D670                      ; $D663  21 70 D6
        LD E,A                           ; $D666  5F
        LD D,$00                         ; $D667  16 00
        ADD HL,DE                        ; $D669  19
        ADD HL,DE                        ; $D66A  19
        LD A,(HL)                        ; $D66B  7E
        INC HL                           ; $D66C  23
        LD H,(HL)                        ; $D66D  66
        LD L,A                           ; $D66E  6F
        JP (HL)                          ; $D66F  E9
        DEFB    $18,$D7,$B1,$D7,$EE,$D7,$3A,$D8,$98,$D8,$0F,$D9,$26,$D9 ; $D670
SUB_D5E5_8:
        LD HL,$76F3                      ; $D67E  21 F3 76
        LD (L_D300),HL                   ; $D681  22 00 D3
        LD HL,L_D300                     ; $D684  21 00 D3
        JP (HL)                          ; $D687  E9
        DEFB    $01,$8E,$D6,$C3,$A2,$D3,$52,$65,$61,$64,$20,$65,$72,$72,$6F,$72 ; $D688
        DEFB    $00,$01,$9F,$D6,$C3,$A2,$D3,$4E,$6F,$20,$66,$69,$6C,$65,$00,$CD ; $D698
        DEFB    $2F,$D5,$3A,$A9,$DB,$B7,$C2,$DF,$D4,$21,$87,$DB,$01,$0B,$00,$7E ; $D6A8
        DEFB    $FE,$20,$28,$24,$23,$D6,$30,$FE,$0A,$D2,$DF,$D4,$57,$78,$E6,$E0 ; $D6B8
        DEFB    $C2,$DF,$D4,$78,$07,$07,$07,$80,$DA,$DF,$D4,$80,$DA,$DF,$D4,$82 ; $D6C8
        DEFB    $DA,$DF,$D4,$47,$0D                              ; $D6D8  "Z_TG"
        DEFB    $20,$D8,$C9,$7E,$FE,$20,$C2,$DF,$D4,$23,$0D      ; $D6DD  " XI~~ B_T#"
        DEFB    $20,$F6,$78,$C9,$21,$80                          ; $D6E8  " vxI!"
        DEFB    $00,$81,$CD,$2A,$D5,$7E,$C9                      ; $D6EE
SUB_D6F5:
        XOR A                            ; $D6F5  AF
        LD ($DB86),A                     ; $D6F6  32 86 DB
        LD A,($DBA9)                     ; $D6F9  3A A9 DB
        OR A                             ; $D6FC  B7
        RET Z                            ; $D6FD  C8
        DEC A                            ; $D6FE  3D
        LD HL,$DBA8                      ; $D6FF  21 A8 DB
        CP (HL)                          ; $D702  BE
        RET Z                            ; $D703  C8
        JP SUB_D3B6                      ; $D704  C3 B6 D3
SUB_D707:
        LD A,($DBA9)                     ; $D707  3A A9 DB
        OR A                             ; $D70A  B7
        RET Z                            ; $D70B  C8
        DEC A                            ; $D70C  3D
        LD HL,$DBA8                      ; $D70D  21 A8 DB
        CP (HL)                          ; $D710  BE
        RET Z                            ; $D711  C8
        LD A,($DBA8)                     ; $D712  3A A8 DB
        JP SUB_D3B6                      ; $D715  C3 B6 D3
        DEFB    $CD,$2F,$D5,$CD,$F5,$D6,$21,$87,$DB,$7E,$FE,$20,$20,$07,$06,$0B ; $D718
        DEFB    $36,$3F,$23,$10,$FB,$1E,$00,$D5,$CD,$D1,$D3,$CC,$99,$D6,$28,$75 ; $D728
        DEFB    $3A,$A7,$DB,$0F,$0F,$0F,$E6,$60,$4F,$3E,$0A,$CD,$EC,$D6,$17,$38 ; $D738
        DEFB    $5A,$D1,$7B,$1C,$D5,$E6,$03,$F5,$20,$14,$CD,$99,$D3,$C5,$CD,$A8 ; $D748
        DEFB    $D4,$C1,$C6,$41,$CD,$93,$D3,$3E,$3A,$CD,$93,$D3,$18,$08,$CD,$91 ; $D758
        DEFB    $D3,$3E,$3A,$CD,$93,$D3,$CD,$91,$D3,$06,$01,$78,$CD,$EC,$D6,$E6 ; $D768
        DEFB    $7F,$FE,$20,$20,$13,$F1,$F5,$FE,$03,$20,$0B,$3E,$09,$CD,$EC,$D6 ; $D778
        DEFB    $E6,$7F,$FE,$20,$28,$14,$3E,$20,$CD,$93,$D3,$04,$78,$FE,$0C,$30 ; $D788
        DEFB    $09,$FE,$09,$20,$D6,$CD,$91,$D3,$18,$D1,$F1,$CD,$9A,$D4,$20,$05 ; $D798
        DEFB    $CD,$D8,$D3,$18,$89,$D1,$C3,$38,$DA,$CD,$2F,$D5,$FE,$0B,$20,$1B ; $D7A8
        DEFB    $01,$E3,$D7,$CD,$A2,$D3,$CD,$1B,$D4,$21,$07,$D3,$35,$C2,$31,$D6 ; $D7B8
        DEFB    $23,$7E,$FE,$59,$C2,$31,$D6,$23,$22,$88,$D3,$CD,$F5,$D6,$11,$86 ; $D7C8
        DEFB    $DB,$CD,$DC,$D3,$3C,$CC,$99,$D6,$C3,$38,$DA,$41,$6C,$6C,$20,$28 ; $D7D8
        DEFB    "y/n)?"    ; $D7E8  string
        DEFB    $00    ; $D7ED  terminator
        DEFB    $CD,$2F,$D5,$C2,$DF,$D4,$CD,$F5,$D6,$CD,$C6,$D3,$28,$38,$CD,$99 ; $D7EE
        DEFB    $D3,$21,$AA,$DB,$36,$FF,$21,$AA,$DB,$7E,$FE,$80,$38,$09,$E5,$CD ; $D7FE
        DEFB    $E0,$D3,$E1,$20,$1A,$AF,$77,$34,$21,$80,$00,$CD,$2A,$D5,$7E,$FE ; $D80E
        DEFB    $1A,$CA,$38,$DA,$CD,$8C,$D3,$CD,$9A,$D4,$C2,$38,$DA,$18,$D7,$3D ; $D81E
        DEFB    $CA,$38,$DA,$CD,$88,$D6,$CD,$07,$D7,$C3,$DF,$D4,$CD,$A7,$D6,$F5 ; $D82E
        DEFB    $CD,$2F,$D5,$C2,$DF,$D4,$CD,$F5,$D6,$11,$86,$DB,$D5,$CD,$DC,$D3 ; $D83E
        DEFB    $D1,$CD,$EE,$D3,$28,$2F,$AF,$32,$A6,$DB,$F1,$6F,$26,$00 ; $D84E  "QMnS(//2&[qo&"
        DEFB    $29,$11,$00,$01,$7C,$B5,$28,$16,$2B,$E5,$21,$80,$00,$19,$E5,$CD ; $D85C
        DEFB    $B0,$D4,$11,$86,$DB,$CD,$EA,$D3,$D1,$E1,$20,$0B,$18,$E6,$11,$86 ; $D86C
        DEFB    $DB,$CD,$BC,$D3,$3C,$20,$06,$01,$8F,$D8,$CD,$A2,$D3,$CD,$AD,$D4 ; $D87C
        DEFB    $C3,$38,$DA,$4E,$6F,$20,$73,$70,$61,$63,$65,$00  ; $D88C  "C8ZNo space"
        DEFB    $CD,$2F,$D5,$C2,$DF,$D4,$3A,$A9,$DB,$F5,$CD,$F5,$D6,$CD,$D1,$D3 ; $D898
        DEFB    $20,$50,$21,$86,$DB,$11,$96,$DB,$01,$10,$00,$ED,$B0,$2A,$88,$D3 ; $D8A8
        DEFB    $EB,$CD,$21,$D5,$FE,$3D,$28,$04,$FE,$5F,$20,$30,$EB,$23,$22,$88 ; $D8B8
        DEFB    $D3,$CD,$2F,$D5,$20,$26,$F1,$47,$21,$A9,$DB,$7E,$B7,$28,$04,$B8 ; $D8C8
        DEFB    $70,$20,$19,$70,$AF,$32,$86,$DB,$CD,$D1,$D3,$28,$09,$11,$86,$DB ; $D8D8
        DEFB    $CD,$F2,$D3,$C3,$38,$DA,$CD,$99,$D6,$C3,$38,$DA,$CD,$07,$D7,$C3 ; $D8E8
        DEFB    $DF,$D4,$01,$03,$D9,$CD,$A2,$D3,$C3,$38,$DA,$46,$69,$6C,$65,$20 ; $D8F8
        DEFB    "exists"    ; $D908  string
        DEFB    $00    ; $D90E  terminator
        DEFB    $CD,$A7,$D6,$FE,$10,$D2,$DF,$D4,$5F,$3A,$87,$DB,$FE,$20,$CA,$DF ; $D90F
        DEFB    $D4,$CD,$F8,$D3,$C3,$3B,$DA                      ; $D91F
SUB_D707_1:
        CALL SUB_D4CD                    ; $D926  CD CD D4
        LD A,($DB87)                     ; $D929  3A 87 DB
        CP $20                           ; $D92C  FE 20
        JR NZ,SUB_D707_2                 ; $D92E  20 16
        LD A,($DBA9)                     ; $D930  3A A9 DB
        OR A                             ; $D933  B7
        JP Z,SUB_D707_17                 ; $D934  CA 3B DA
        DEC A                            ; $D937  3D
        PUSH AF                          ; $D938  F5
        CALL SUB_D3B6                    ; $D939  CD B6 D3
        POP AF                           ; $D93C  F1
        LD ($DBA8),A                     ; $D93D  32 A8 DB
        CALL SUB_D40B                    ; $D940  CD 0B D4
        JP SUB_D707_17                   ; $D943  C3 3B DA
SUB_D707_2:
        CALL SUB_D3F6                    ; $D946  CD F6 D3
        LD ($DB43),A                     ; $D949  32 43 DB
        LD DE,$DB8F                      ; $D94C  11 8F DB
        LD A,(DE)                        ; $D94F  1A
        CP $20                           ; $D950  FE 20
        JP NZ,SUB_D4DF                   ; $D952  C2 DF D4
        PUSH DE                          ; $D955  D5
        CALL SUB_D6F5                    ; $D956  CD F5 D6
        POP DE                           ; $D959  D1
        LD HL,$DA35                      ; $D95A  21 35 DA
        LD BC,IOBYTE                     ; $D95D  01 03 00
        LDIR                             ; $D960  ED B0
SUB_D707_3:
        CALL SUB_D3C6                    ; $D962  CD C6 D3
        JR NZ,SUB_D707_4                 ; $D965  20 0D
        CALL SUB_D3F6                    ; $D967  CD F6 D3
        OR A                             ; $D96A  B7
        JP Z,SUB_D707_14                 ; $D96B  CA 1B DA
        XOR A                            ; $D96E  AF
        CALL SUB_DA50                    ; $D96F  CD 50 DA
        JR SUB_D707_3                    ; $D972  18 EE
SUB_D707_4:
        LD A,($DB86)                     ; $D974  3A 86 DB
        OR A                             ; $D977  B7
        JR Z,SUB_D707_5                  ; $D978  28 04
        DEC A                            ; $D97A  3D
        CALL SUB_D3B6                    ; $D97B  CD B6 D3
SUB_D707_5:
        LD C,$1F                         ; $D97E  0E 1F
        CALL BDOS_VEC                    ; $D980  CD 05 00
        INC HL                           ; $D983  23
        INC HL                           ; $D984  23
        LD A,(HL)                        ; $D985  7E
        CP $03                           ; $D986  FE 03
        JR NZ,SUB_D707_6                 ; $D988  20 09
        INC HL                           ; $D98A  23
        INC HL                           ; $D98B  23
        INC HL                           ; $D98C  23
        LD A,(HL)                        ; $D98D  7E
        CP $8B                           ; $D98E  FE 8B
        JP Z,SUB_DA50_1                  ; $D990  CA 54 DA
SUB_D707_6:
        LD HL,TPA_START                  ; $D993  21 00 01
SUB_D707_7:
        PUSH HL                          ; $D996  E5
        EX DE,HL                         ; $D997  EB
        CALL SUB_D4B0                    ; $D998  CD B0 D4
        LD DE,$DB86                      ; $D99B  11 86 DB
        CALL SUB_D3E3                    ; $D99E  CD E3 D3
        JR NZ,SUB_D707_8                 ; $D9A1  20 11
        POP HL                           ; $D9A3  E1
        LD DE,DEFAULT_DMA                ; $D9A4  11 80 00
        ADD HL,DE                        ; $D9A7  19
        LD DE,L_D300                     ; $D9A8  11 00 D3
        OR A                             ; $D9AB  B7
        PUSH HL                          ; $D9AC  E5
        SBC HL,DE                        ; $D9AD  ED 52
        POP HL                           ; $D9AF  E1
        JR NC,SUB_D707_15                ; $D9B0  30 72
        JR SUB_D707_7                    ; $D9B2  18 E2
SUB_D707_8:
        POP HL                           ; $D9B4  E1
        DEC A                            ; $D9B5  3D
        JR NZ,SUB_D707_15                ; $D9B6  20 6C
SUB_D707_9:
        CALL SUB_DA4D                    ; $D9B8  CD 4D DA
        CALL SUB_D707                    ; $D9BB  CD 07 D7
        CALL SUB_D52F                    ; $D9BE  CD 2F D5
        LD HL,$DBA9                      ; $D9C1  21 A9 DB
        PUSH HL                          ; $D9C4  E5
        LD A,(HL)                        ; $D9C5  7E
        LD ($DB86),A                     ; $D9C6  32 86 DB
        LD A,$10                         ; $D9C9  3E 10
        CALL SUB_D531                    ; $D9CB  CD 31 D5
        POP HL                           ; $D9CE  E1
        LD A,(HL)                        ; $D9CF  7E
        LD ($DB96),A                     ; $D9D0  32 96 DB
        XOR A                            ; $D9D3  AF
        LD ($DBA6),A                     ; $D9D4  32 A6 DB
        LD DE,DEFAULT_FCB                ; $D9D7  11 5C 00
        LD HL,$DB86                      ; $D9DA  21 86 DB
        LD BC,$0021                      ; $D9DD  01 21 00
        LDIR                             ; $D9E0  ED B0
        LD HL,$D308                      ; $D9E2  21 08 D3
SUB_D707_10:
        LD A,(HL)                        ; $D9E5  7E
        OR A                             ; $D9E6  B7
        JR Z,SUB_D707_11                 ; $D9E7  28 07
        CP $20                           ; $D9E9  FE 20
        JR Z,SUB_D707_11                 ; $D9EB  28 03
        INC HL                           ; $D9ED  23
        JR SUB_D707_10                   ; $D9EE  18 F5
SUB_D707_11:
        LD B,$00                         ; $D9F0  06 00
        LD DE,CMDLINE                    ; $D9F2  11 81 00
SUB_D707_12:
        LD A,(HL)                        ; $D9F5  7E
        LD (DE),A                        ; $D9F6  12
        OR A                             ; $D9F7  B7
        JR Z,SUB_D707_13                 ; $D9F8  28 05
        INC B                            ; $D9FA  04
        INC HL                           ; $D9FB  23
        INC DE                           ; $D9FC  13
        JR SUB_D707_12                   ; $D9FD  18 F6
SUB_D707_13:
        LD A,B                           ; $D9FF  78
        LD (DEFAULT_DMA),A               ; $DA00  32 80 00
        CALL SUB_D399                    ; $DA03  CD 99 D3
        CALL SUB_D4AD                    ; $DA06  CD AD D4
        CALL SUB_D3FC                    ; $DA09  CD FC D3
        CALL TPA_START                   ; $DA0C  CD 00 01
        LD SP,$DB64                      ; $DA0F  31 64 DB
        CALL SUB_D40B                    ; $DA12  CD 0B D4
        CALL SUB_D3B6                    ; $DA15  CD B6 D3
        JP SUB_D5E5_6                    ; $DA18  C3 31 D6
SUB_D707_14:
        CALL SUB_DA4D                    ; $DA1B  CD 4D DA
        CALL SUB_D707                    ; $DA1E  CD 07 D7
        JP SUB_D4DF                      ; $DA21  C3 DF D4
SUB_D707_15:
        LD BC,$DA2C                      ; $DA24  01 2C DA
        CALL SUB_D3A2                    ; $DA27  CD A2 D3
        JR SUB_D707_16                   ; $DA2A  18 0C
        DEFB    "Bad load"    ; $DA2C  string
        DEFB    $00    ; $DA34  terminator
        DEFB    $43,$4F,$4D                                      ; $DA35
SUB_D707_16:
        CALL SUB_D707                    ; $DA38  CD 07 D7
SUB_D707_17:
        CALL SUB_D52F                    ; $DA3B  CD 2F D5
        LD A,($DB87)                     ; $DA3E  3A 87 DB
        SUB $20                          ; $DA41  D6 20
        LD HL,$DBA9                      ; $DA43  21 A9 DB
        OR (HL)                          ; $DA46  B6
        JP NZ,SUB_D4DF                   ; $DA47  C2 DF D4
        JP SUB_D5E5_6                    ; $DA4A  C3 31 D6
SUB_DA4D:
        LD A,($DB43)                     ; $DA4D  3A 43 DB
SUB_DA50:
        LD E,A                           ; $DA50  5F
        JP SUB_D3F8                      ; $DA51  C3 F8 D3
SUB_DA50_1:
        LD HL,($F3DE)                    ; $DA54  2A DE F3
        LD ($DB26),HL                    ; $DA57  22 26 DB
        XOR A                            ; $DA5A  AF
        LD ($DB92),A                     ; $DA5B  32 92 DB
        LD A,$11                         ; $DA5E  3E 11
        LD ($DB41),A                     ; $DA60  32 41 DB
        LD DE,$D2FF                      ; $DA63  11 FF D2
SUB_DA50_2:
        XOR A                            ; $DA66  AF
        LD ($DBA6),A                     ; $DA67  32 A6 DB
        LD HL,$DB96                      ; $DA6A  21 96 DB
SUB_DA50_3:
        LD A,(HL)                        ; $DA6D  7E
        OR A                             ; $DA6E  B7
        JR Z,SUB_DA50_4                  ; $DA6F  28 06
        CALL SUB_DA8D                    ; $DA71  CD 8D DA
        INC HL                           ; $DA74  23
        JR SUB_DA50_3                    ; $DA75  18 F6
SUB_DA50_4:
        LD A,$A6                         ; $DA77  3E A6
        CP L                             ; $DA79  BD
        JP NZ,SUB_DA50_5                 ; $DA7A  C2 82 DA
        CALL SUB_DAC8                    ; $DA7D  CD C8 DA
        JR NZ,SUB_DA50_2                 ; $DA80  20 E4
SUB_DA50_5:
        XOR A                            ; $DA82  AF
        LD (DE),A                        ; $DA83  12
        CALL SUB_DAD4                    ; $DA84  CD D4 DA
        CALL SUB_DB06                    ; $DA87  CD 06 DB
        JP SUB_D707_9                    ; $DA8A  C3 B8 D9
SUB_DA8D:
        PUSH HL                          ; $DA8D  E5
        PUSH AF                          ; $DA8E  F5
        SRL A                            ; $DA8F  CB 3F
        SRL A                            ; $DA91  CB 3F
        ADD A,$03                        ; $DA93  C6 03
        LD ($DB42),A                     ; $DA95  32 42 DB
        POP AF                           ; $DA98  F1
        AND $03                          ; $DA99  E6 03
        ADD A,A                          ; $DA9B  87
        ADD A,A                          ; $DA9C  87
        LD HL,$DB31                      ; $DA9D  21 31 DB
        ADD A,L                          ; $DAA0  85
        LD L,A                           ; $DAA1  6F
        JR NC,SUB_DA8D_1                 ; $DAA2  30 01
        INC H                            ; $DAA4  24
SUB_DA8D_1:
        LD B,$04                         ; $DAA5  06 04
SUB_DA8D_2:
        LD A,($DB42)                     ; $DAA7  3A 42 DB
        LD (DE),A                        ; $DAAA  12
        DEC DE                           ; $DAAB  1B
        LD A,(HL)                        ; $DAAC  7E
        INC HL                           ; $DAAD  23
        LD (DE),A                        ; $DAAE  12
        DEC DE                           ; $DAAF  1B
        LD A,($DB41)                     ; $DAB0  3A 41 DB
        CP $F0                           ; $DAB3  FE F0
        JP Z,SUB_D707_15                 ; $DAB5  CA 24 DA
        CP $C0                           ; $DAB8  FE C0
        JR NZ,SUB_DA8D_3                 ; $DABA  20 02
        LD A,$D0                         ; $DABC  3E D0
SUB_DA8D_3:
        LD (DE),A                        ; $DABE  12
        INC A                            ; $DABF  3C
        DEC DE                           ; $DAC0  1B
        LD ($DB41),A                     ; $DAC1  32 41 DB
        DJNZ SUB_DA8D_2                  ; $DAC4  10 E1
        POP HL                           ; $DAC6  E1
        RET                              ; $DAC7  C9
SUB_DAC8:
        PUSH HL                          ; $DAC8  E5
        PUSH DE                          ; $DAC9  D5
        LD HL,$DB92                      ; $DACA  21 92 DB
        INC (HL)                         ; $DACD  34
        CALL SUB_D3C6                    ; $DACE  CD C6 D3
        POP DE                           ; $DAD1  D1
        POP HL                           ; $DAD2  E1
        RET                              ; $DAD3  C9
SUB_DAD4:
        LD HL,$D2FF                      ; $DAD4  21 FF D2
SUB_DAD4_1:
        LD D,H                           ; $DAD7  54
        LD E,L                           ; $DAD8  5D
SUB_DAD4_2:
        DEC DE                           ; $DAD9  1B
        DEC DE                           ; $DADA  1B
        DEC DE                           ; $DADB  1B
        LD A,(DE)                        ; $DADC  1A
        OR A                             ; $DADD  B7
        JR Z,SUB_DAD4_5                  ; $DADE  28 1E
        CP (HL)                          ; $DAE0  BE
        JR C,SUB_DAD4_3                  ; $DAE1  38 0A
        JR NZ,SUB_DAD4_2                 ; $DAE3  20 F4
        DEC DE                           ; $DAE5  1B
        LD A,(DE)                        ; $DAE6  1A
        INC DE                           ; $DAE7  13
        DEC HL                           ; $DAE8  2B
        CP (HL)                          ; $DAE9  BE
        INC HL                           ; $DAEA  23
        JR NC,SUB_DAD4_2                 ; $DAEB  30 EC
SUB_DAD4_3:
        PUSH HL                          ; $DAED  E5
        PUSH DE                          ; $DAEE  D5
        LD B,$03                         ; $DAEF  06 03
SUB_DAD4_4:
        LD A,(DE)                        ; $DAF1  1A
        LD C,(HL)                        ; $DAF2  4E
        LD (HL),A                        ; $DAF3  77
        LD A,C                           ; $DAF4  79
        LD (DE),A                        ; $DAF5  12
        DEC HL                           ; $DAF6  2B
        DEC DE                           ; $DAF7  1B
        DJNZ SUB_DAD4_4                  ; $DAF8  10 F7
        POP DE                           ; $DAFA  D1
        POP HL                           ; $DAFB  E1
        JR SUB_DAD4_2                    ; $DAFC  18 DB
SUB_DAD4_5:
        DEC HL                           ; $DAFE  2B
        DEC HL                           ; $DAFF  2B
        DEC HL                           ; $DB00  2B
        LD A,(HL)                        ; $DB01  7E
        OR A                             ; $DB02  B7
        JR NZ,SUB_DAD4_1                 ; $DB03  20 D2
        RET                              ; $DB05  C9
SUB_DB06:
        LD DE,$D2FF                      ; $DB06  11 FF D2
SUB_DB06_1:
        LD A,(DE)                        ; $DB09  1A
        OR A                             ; $DB0A  B7
        RET Z                            ; $DB0B  C8
        LD ($F3E0),A                     ; $DB0C  32 E0 F3
        DEC DE                           ; $DB0F  1B
        LD A,(DE)                        ; $DB10  1A
        LD ($F3E1),A                     ; $DB11  32 E1 F3
        DEC DE                           ; $DB14  1B
        LD A,(DE)                        ; $DB15  1A
        LD ($F3E9),A                     ; $DB16  32 E9 F3
        DEC DE                           ; $DB19  1B
        LD A,$01                         ; $DB1A  3E 01
        LD ($F3EB),A                     ; $DB1C  32 EB F3
        LD HL,$0E03                      ; $DB1F  21 03 0E
        LD ($F3D0),HL                    ; $DB22  22 D0 F3
        LD (WBOOT_VEC),A                 ; $DB25  32 00 00
        LD A,($F3EA)                     ; $DB28  3A EA F3
        OR A                             ; $DB2B  B7
        JR Z,SUB_DB06_1                  ; $DB2C  28 DB
        JP SUB_D707_6                    ; $DB2E  C3 93 D9
        DEFB    $00,$09,$03,$0C,$06,$0F,$01,$0A,$04,$0D,$07,$08,$02,$0B,$05,$0E ; $DB31
        DEFS    27, $00    ; $DB41  fill
        DEFB    $97,$D3,$FF,$D3,$81,$D4,$47,$D6,$00,$00,$24,$24,$24,$20,$20,$20 ; $DB5C
        DEFB    "  SUB"    ; $DB6C  string
        DEFB    $00    ; $DB71  terminator
        DEFS    142, $00    ; $DB72  fill
        DEFB    $BD,$16,$00,$01,$4D,$40                          ; $DC00

    SAVEBIN "CPM_CCP.bin", $D300, $0906
