;==============================================================================
; Microsoft SoftCard CP/M 2.23 -- Console Command Processor (CCP)
;
; SHARED SOURCE. This one file assembles to BOTH the 44K and the 60K CCP,
; byte-for-byte, selected entirely by the two symbols below. The 60K values are
; the defaults; build the 44K CCP by overriding both on the command line:
;       sjasmplus os/CPM_CCP.asm                                     ; 60K
;       sjasmplus -DSYS_BASE=0x9300 -DMEMTOP_PAGE=0xA1 os/CPM_CCP.asm ; 44K
;
; ---------------------------------------------------------------------------
; SYS_BASE  -- WHERE the resident system loads.  (the only address knob)
; ---------------------------------------------------------------------------
;   The ORG of the CCP. The 60K conversion lifts the resident system (CCP+BDOS)
;   up by $4000, out of main RAM and into the Apple Language Card, so the CCP
;   base moves $9300 -> $D300. Because every internal reference in this module is
;   a label or a SYS_BASE-relative expression, changing this one ORG relocates
;   the ENTIRE module automatically: all code/data addresses and the
;   dispatch/pointer tables (emitted as DEFW <label>) move with it. No operand is
;   hand-patched for the address shift.
;     The only non-label SYS_BASE expression is "SYS_BASE-1" (see its 3 use
;     sites). The byte just below the CCP is the TOP OF THE TPA -- the highest
;     transient-program RAM byte, since the CCP sits at the top of the TPA -- and
;     the sysgen / disk-write routines use it as the top of a buffer they fill
;     and read DOWNWARD. Being CCP-base-relative it tracks the ORG: it is $92FF
;     in the 44K build, $D2FF in the 60K build.
;
; ---------------------------------------------------------------------------
; MEMTOP_PAGE  -- HOW MUCH RAM the machine has.  (a separate, independent axis)
; ---------------------------------------------------------------------------
;   The high byte of the top of usable RAM = the memory size. This is NOT a
;   function of SYS_BASE: SYS_BASE says where the system loads; MEMTOP_PAGE says
;   how big memory is. They co-vary with the 44K/60K choice but are independent
;   causes -- the system was relocated *because* memory grew, not the reverse, so
;   no formula recovers one from the other ($F0-$A1 = $4F, while SYS_BASE shifts
;   by $40). It has exactly one use site ("CP MEMTOP_PAGE"): the sysgen page-list
;   builder counts Apple RAM pages upward from $11, skipping the $C0-$CF I/O hole,
;   and stops when it reaches MEMTOP_PAGE -- so this value is literally the first
;   page past the top of writable RAM.
;       44K -> $A1   (top of RAM at $A100)
;       60K -> $F0   (top of RAM at $F000)
;==============================================================================
    IFNDEF SYS_BASE
SYS_BASE    EQU $D300        ; load ORG: 44K=$9300, 60K=$D300  (override -D for 44K)
    ENDIF
    IFNDEF MEMTOP_PAGE
MEMTOP_PAGE EQU $F0          ; top RAM page = memory size: 44K=$A1, 60K=$F0
    ENDIF
; Generated by disasm_z80
; Source: CPM_CCP
; Range:  $D300-$DC05  (2310 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
IOBYTE               EQU $0003               ; I/O assignment byte — logical-to-physical device routing (CONSOLE/READER/PUNCH/LIST). 4 fields × 2 bits each.
CDISK                EQU $0004               ; Current drive (low nibble: 0=A, 1=B, ..., 15=P) and current user (high nibble, 0-15).
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
RST2_VEC             EQU $0010               ; Z-80 RST 2 ($10) restart vector — 8 bytes. Available for application/debugger use.
DEFAULT_FCB          EQU $005C               ; Default File Control Block — populated by CCP from command-line argument 1. Standard 36-byte FCB structure (drive + filename + extents + record number).
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).
CMDLINE              EQU $0081               ; Command-line tail characters (uppercase, with leading space). Same buffer as DEFAULT_DMA.
TPA_START            EQU $0100               ; Start of Transient Program Area. .COM files load here and execute starting at $0100.

; -- Mid-instruction references (shown inline as cover+offset) --
;   $DB26 -> SUB_DB06_2+1         shared instruction tail: $DB26 is reachable code inside the instruction at $DB25

    ORG SYS_BASE

L_D300:
        JP SUB_D5E5_6                    ; $D300  C3 0C D6
L_D303:
        JP SUB_D5E5_5                    ; $D303  C3 08 D6
L_D306:
        DEFB    $7F                                              ; $D306
L_D307:
        DEFB    $00                                              ; $D307
L_D308:
        DEFS    16, $20    ; $D308  fill
        DEFB    "COPYRIGHT (C) 1979, DIGITAL RESEARCH  "    ; $D318  string
        DEFB    $00    ; $D33E  terminator
        DEFS    73, $00    ; $D33F  fill
L_D388:
        DEFW    L_D308                   ; $D388
L_D38A:
        DEFB    $00,$00                                          ; $D38A
SUB_D38C:
        LD E,A                           ; $D38C  5F
        LD C,$02                         ; $D38D  0E 02
        JR SUB_D3B6_1                    ; $D38F  18 28
SUB_D391:
        LD A,$20                         ; $D391  3E 20
SUB_D393:
        PUSH BC                          ; $D393  C5
        CALL SUB_D38C                    ; $D394  CD 8C D3
SUB_D393_1:
        POP BC                           ; $D397  C1
        RET                              ; $D398  C9
SUB_D399:
        LD A,$0D                         ; $D399  3E 0D
        CALL SUB_D393                    ; $D39B  CD 93 D3
        LD A,$0A                         ; $D39E  3E 0A
        JR SUB_D393                      ; $D3A0  18 F1
SUB_D3A2:
        PUSH BC                          ; $D3A2  C5
        CALL SUB_D399                    ; $D3A3  CD 99 D3
        POP HL                           ; $D3A6  E1
SUB_D3A7:
        LD A,(HL)                        ; $D3A7  7E
        OR A                             ; $D3A8  B7
        RET Z                            ; $D3A9  C8
        INC HL                           ; $D3AA  23
        PUSH HL                          ; $D3AB  E5
        CALL SUB_D38C                    ; $D3AC  CD 8C D3
        POP HL                           ; $D3AF  E1
        JR SUB_D3A7                      ; $D3B0  18 F5
SUB_D3B2:
        LD C,$0D                         ; $D3B2  0E 0D
        JR SUB_D3B6_1                    ; $D3B4  18 03
SUB_D3B6:
        LD E,A                           ; $D3B6  5F
        LD C,$0E                         ; $D3B7  0E 0E
SUB_D3B6_1:
        JP BDOS_VEC                      ; $D3B9  C3 05 00
SUB_D3BC:
        LD C,$10                         ; $D3BC  0E 10
SUB_D3BC_1:
        CALL BDOS_VEC                    ; $D3BE  CD 05 00
        LD (SUB_DB06_18),A               ; $D3C1  32 A7 DB
        INC A                            ; $D3C4  3C
        RET                              ; $D3C5  C9
SUB_D3C6:
        XOR A                            ; $D3C6  AF
        LD (SUB_DB06_17),A               ; $D3C7  32 A6 DB
        LD DE,SUB_DB06_12                ; $D3CA  11 86 DB
SUB_D3CD:
        LD C,$0F                         ; $D3CD  0E 0F
        JR SUB_D3BC_1                    ; $D3CF  18 ED
SUB_D3D1:
        LD DE,SUB_DB06_12                ; $D3D1  11 86 DB
        LD C,$11                         ; $D3D4  0E 11
        JR SUB_D3BC_1                    ; $D3D6  18 E6
SUB_D3D8:
        LD C,$12                         ; $D3D8  0E 12
        JR SUB_D3BC_1                    ; $D3DA  18 E2
SUB_D3DC:
        LD C,$13                         ; $D3DC  0E 13
        JR SUB_D3B6_1                    ; $D3DE  18 D9
SUB_D3E0:
        LD DE,SUB_DB06_12                ; $D3E0  11 86 DB
SUB_D3E3:
        LD C,$14                         ; $D3E3  0E 14
SUB_D3E3_1:
        CALL BDOS_VEC                    ; $D3E5  CD 05 00
        OR A                             ; $D3E8  B7
        RET                              ; $D3E9  C9
SUB_D3EA:
        LD C,$15                         ; $D3EA  0E 15
        JR SUB_D3E3_1                    ; $D3EC  18 F7
SUB_D3EE:
        LD C,$16                         ; $D3EE  0E 16
        JR SUB_D3BC_1                    ; $D3F0  18 CC
SUB_D3F2:
        LD C,$17                         ; $D3F2  0E 17
        JR SUB_D3B6_1                    ; $D3F4  18 C3
SUB_D3F6:
        LD E,$FF                         ; $D3F6  1E FF
SUB_D3F8:
        LD C,$20                         ; $D3F8  0E 20
        JR SUB_D3B6_1                    ; $D3FA  18 BD
SUB_D3FC:
        CALL SUB_D3F6                    ; $D3FC  CD F6 D3
SUB_D3FC_1:
        ADD A,A                          ; $D3FF  87
        ADD A,A                          ; $D400  87
        ADD A,A                          ; $D401  87
        ADD A,A                          ; $D402  87
        LD HL,SUB_DB06_19                ; $D403  21 A8 DB
        OR (HL)                          ; $D406  B6
        LD (CDISK),A                     ; $D407  32 04 00
        RET                              ; $D40A  C9
SUB_D40B:
        LD A,(SUB_DB06_19)               ; $D40B  3A A8 DB
        LD (CDISK),A                     ; $D40E  32 04 00
        RET                              ; $D411  C9
SUB_D412:
        CP $61                           ; $D412  FE 61
        RET C                            ; $D414  D8
        CP $7B                           ; $D415  FE 7B
        RET NC                           ; $D417  D0
        AND $5F                          ; $D418  E6 5F
        RET                              ; $D41A  C9
SUB_D41B:
        LD A,(SUB_DB06_7)                ; $D41B  3A 64 DB
        OR A                             ; $D41E  B7
        JR Z,SUB_D41B_1                  ; $D41F  28 52
        LD A,(SUB_DB06_19)               ; $D421  3A A8 DB
        OR A                             ; $D424  B7
        LD A,$00                         ; $D425  3E 00
        CALL NZ,SUB_D3B6                 ; $D427  C4 B6 D3
        LD DE,SUB_DB06_8                 ; $D42A  11 65 DB
        CALL SUB_D3CD                    ; $D42D  CD CD D3
        JR Z,SUB_D41B_1                  ; $D430  28 41
        LD A,(SUB_DB06_10)               ; $D432  3A 74 DB
        DEC A                            ; $D435  3D
        LD (SUB_DB06_11),A               ; $D436  32 85 DB
        LD DE,SUB_DB06_8                 ; $D439  11 65 DB
        CALL SUB_D3E3                    ; $D43C  CD E3 D3
        JR NZ,SUB_D41B_1                 ; $D43F  20 32
        LD DE,L_D307                     ; $D441  11 07 D3
        LD HL,DEFAULT_DMA                ; $D444  21 80 00
        LD BC,DEFAULT_DMA                ; $D447  01 80 00
        LDIR                             ; $D44A  ED B0
        LD HL,SUB_DB06_9                 ; $D44C  21 73 DB
        LD (HL),$00                      ; $D44F  36 00
        INC HL                           ; $D451  23
        DEC (HL)                         ; $D452  35
        LD DE,SUB_DB06_8                 ; $D453  11 65 DB
        CALL SUB_D3BC                    ; $D456  CD BC D3
        JR Z,SUB_D41B_1                  ; $D459  28 18
        LD A,(SUB_DB06_19)               ; $D45B  3A A8 DB
        OR A                             ; $D45E  B7
        CALL NZ,SUB_D3B6                 ; $D45F  C4 B6 D3
        LD HL,L_D308                     ; $D462  21 08 D3
        CALL SUB_D3A7                    ; $D465  CD A7 D3
        CALL SUB_D49A                    ; $D468  CD 9A D4
        JR Z,SUB_D41B_2                  ; $D46B  28 14
        CALL SUB_D4B5                    ; $D46D  CD B5 D4
        JP SUB_D5E5_7                    ; $D470  C3 31 D6
SUB_D41B_1:
        CALL SUB_D4B5                    ; $D473  CD B5 D4
        CALL SUB_D3FC                    ; $D476  CD FC D3
        LD C,$0A                         ; $D479  0E 0A
        LD DE,L_D306                     ; $D47B  11 06 D3
        CALL BDOS_VEC                    ; $D47E  CD 05 00
SUB_D41B_2:
        LD HL,L_D307                     ; $D481  21 07 D3
        LD B,(HL)                        ; $D484  46
SUB_D41B_3:
        INC HL                           ; $D485  23
        LD A,B                           ; $D486  78
        OR A                             ; $D487  B7
        JR Z,SUB_D41B_4                  ; $D488  28 08
        LD A,(HL)                        ; $D48A  7E
        CALL SUB_D412                    ; $D48B  CD 12 D4
        LD (HL),A                        ; $D48E  77
        DEC B                            ; $D48F  05
        JR SUB_D41B_3                    ; $D490  18 F3
SUB_D41B_4:
        LD (HL),A                        ; $D492  77
        LD HL,L_D308                     ; $D493  21 08 D3
        LD (L_D388),HL                   ; $D496  22 88 D3
        RET                              ; $D499  C9
SUB_D49A:
        LD C,$0B                         ; $D49A  0E 0B
        CALL BDOS_VEC                    ; $D49C  CD 05 00
        OR A                             ; $D49F  B7
        RET Z                            ; $D4A0  C8
        LD C,$01                         ; $D4A1  0E 01
        CALL BDOS_VEC                    ; $D4A3  CD 05 00
        OR A                             ; $D4A6  B7
        RET                              ; $D4A7  C9
SUB_D4A8:
        LD C,$19                         ; $D4A8  0E 19
        JP BDOS_VEC                      ; $D4AA  C3 05 00
SUB_D4AD:
        LD DE,DEFAULT_DMA                ; $D4AD  11 80 00
SUB_D4B0:
        LD C,$1A                         ; $D4B0  0E 1A
        JP BDOS_VEC                      ; $D4B2  C3 05 00
SUB_D4B5:
        LD HL,SUB_DB06_7                 ; $D4B5  21 64 DB
        LD A,(HL)                        ; $D4B8  7E
        OR A                             ; $D4B9  B7
        RET Z                            ; $D4BA  C8
        LD (HL),$00                      ; $D4BB  36 00
        XOR A                            ; $D4BD  AF
        CALL SUB_D3B6                    ; $D4BE  CD B6 D3
        LD DE,SUB_DB06_8                 ; $D4C1  11 65 DB
        CALL SUB_D3DC                    ; $D4C4  CD DC D3
        LD A,(SUB_DB06_19)               ; $D4C7  3A A8 DB
        JP SUB_D3B6                      ; $D4CA  C3 B6 D3
SUB_D4CD:
        LD DE,SUB_D531_20                ; $D4CD  11 DF D5
        LD HL,SUB_DB06_22                ; $D4D0  21 00 DC
        LD B,$06                         ; $D4D3  06 06
SUB_D4CD_1:
        LD A,(DE)                        ; $D4D5  1A
        CP (HL)                          ; $D4D6  BE
        JP NZ,SUB_D5E5_10                ; $D4D7  C2 7E D6
        INC DE                           ; $D4DA  13
        INC HL                           ; $D4DB  23
        DJNZ SUB_D4CD_1                  ; $D4DC  10 F7
        RET                              ; $D4DE  C9
SUB_D4DF:
        CALL SUB_D399                    ; $D4DF  CD 99 D3
        LD HL,(L_D38A)                   ; $D4E2  2A 8A D3
SUB_D4DF_1:
        LD A,(HL)                        ; $D4E5  7E
        CP $20                           ; $D4E6  FE 20
        JR Z,SUB_D4DF_2                  ; $D4E8  28 0B
        OR A                             ; $D4EA  B7
        JR Z,SUB_D4DF_2                  ; $D4EB  28 08
        PUSH HL                          ; $D4ED  E5
        CALL SUB_D38C                    ; $D4EE  CD 8C D3
        POP HL                           ; $D4F1  E1
        INC HL                           ; $D4F2  23
        JR SUB_D4DF_1                    ; $D4F3  18 F0
SUB_D4DF_2:
        LD A,$3F                         ; $D4F5  3E 3F
        CALL SUB_D38C                    ; $D4F7  CD 8C D3
        CALL SUB_D399                    ; $D4FA  CD 99 D3
        CALL SUB_D4B5                    ; $D4FD  CD B5 D4
        JP SUB_D5E5_7                    ; $D500  C3 31 D6
SUB_D503:
        LD A,(DE)                        ; $D503  1A
        OR A                             ; $D504  B7
        RET Z                            ; $D505  C8
        CP $20                           ; $D506  FE 20
        JR C,SUB_D4DF                    ; $D508  38 D5
        RET Z                            ; $D50A  C8
        CP $3D                           ; $D50B  FE 3D
        RET Z                            ; $D50D  C8
        CP $5F                           ; $D50E  FE 5F
        RET Z                            ; $D510  C8
        CP $2E                           ; $D511  FE 2E
        RET Z                            ; $D513  C8
        CP $3A                           ; $D514  FE 3A
        RET Z                            ; $D516  C8
        CP $3B                           ; $D517  FE 3B
        RET Z                            ; $D519  C8
        CP $3C                           ; $D51A  FE 3C
        RET Z                            ; $D51C  C8
        CP $3E                           ; $D51D  FE 3E
        RET Z                            ; $D51F  C8
        RET                              ; $D520  C9
SUB_D521:
        LD A,(DE)                        ; $D521  1A
        OR A                             ; $D522  B7
        RET Z                            ; $D523  C8
        CP $20                           ; $D524  FE 20
        RET NZ                           ; $D526  C0
        INC DE                           ; $D527  13
        JR SUB_D521                      ; $D528  18 F7
SUB_D52A:
        ADD A,L                          ; $D52A  85
        LD L,A                           ; $D52B  6F
        RET NC                           ; $D52C  D0
        INC H                            ; $D52D  24
        RET                              ; $D52E  C9
SUB_D52F:
        LD A,$00                         ; $D52F  3E 00
SUB_D531:
        LD HL,SUB_DB06_12                ; $D531  21 86 DB
        CALL SUB_D52A                    ; $D534  CD 2A D5
        PUSH HL                          ; $D537  E5
        PUSH HL                          ; $D538  E5
        XOR A                            ; $D539  AF
        LD (SUB_DB06_20),A               ; $D53A  32 A9 DB
        LD HL,(L_D388)                   ; $D53D  2A 88 D3
        EX DE,HL                         ; $D540  EB
        CALL SUB_D521                    ; $D541  CD 21 D5
        EX DE,HL                         ; $D544  EB
        LD (L_D38A),HL                   ; $D545  22 8A D3
        EX DE,HL                         ; $D548  EB
        POP HL                           ; $D549  E1
        LD A,(DE)                        ; $D54A  1A
        OR A                             ; $D54B  B7
        JR Z,SUB_D531_1                  ; $D54C  28 0A
        SBC A,$40                        ; $D54E  DE 40
        LD B,A                           ; $D550  47
        INC DE                           ; $D551  13
        LD A,(DE)                        ; $D552  1A
        CP $3A                           ; $D553  FE 3A
        JR Z,SUB_D531_2                  ; $D555  28 07
        DEC DE                           ; $D557  1B
SUB_D531_1:
        LD A,(SUB_DB06_19)               ; $D558  3A A8 DB
        LD (HL),A                        ; $D55B  77
        JR SUB_D531_3                    ; $D55C  18 06
SUB_D531_2:
        LD A,B                           ; $D55E  78
        LD (SUB_DB06_20),A               ; $D55F  32 A9 DB
        LD (HL),B                        ; $D562  70
        INC DE                           ; $D563  13
SUB_D531_3:
        LD B,$08                         ; $D564  06 08
SUB_D531_4:
        CALL SUB_D503                    ; $D566  CD 03 D5
        JR Z,SUB_D531_8                  ; $D569  28 15
        INC HL                           ; $D56B  23
        CP $2A                           ; $D56C  FE 2A
        JR NZ,SUB_D531_5                 ; $D56E  20 04
        LD (HL),$3F                      ; $D570  36 3F
        JR SUB_D531_6                    ; $D572  18 02
SUB_D531_5:
        LD (HL),A                        ; $D574  77
        INC DE                           ; $D575  13
SUB_D531_6:
        DJNZ SUB_D531_4                  ; $D576  10 EE
SUB_D531_7:
        CALL SUB_D503                    ; $D578  CD 03 D5
        JR Z,SUB_D531_9                  ; $D57B  28 08
        INC DE                           ; $D57D  13
        JR SUB_D531_7                    ; $D57E  18 F8
SUB_D531_8:
        INC HL                           ; $D580  23
        LD (HL),$20                      ; $D581  36 20
        DJNZ SUB_D531_8                  ; $D583  10 FB
SUB_D531_9:
        LD B,$03                         ; $D585  06 03
        CP $2E                           ; $D587  FE 2E
        JR NZ,SUB_D531_14                ; $D589  20 1B
        INC DE                           ; $D58B  13
SUB_D531_10:
        CALL SUB_D503                    ; $D58C  CD 03 D5
        JR Z,SUB_D531_14                 ; $D58F  28 15
        INC HL                           ; $D591  23
        CP $2A                           ; $D592  FE 2A
        JR NZ,SUB_D531_11                ; $D594  20 04
        LD (HL),$3F                      ; $D596  36 3F
        JR SUB_D531_12                   ; $D598  18 02
SUB_D531_11:
        LD (HL),A                        ; $D59A  77
        INC DE                           ; $D59B  13
SUB_D531_12:
        DJNZ SUB_D531_10                 ; $D59C  10 EE
SUB_D531_13:
        CALL SUB_D503                    ; $D59E  CD 03 D5
        JR Z,SUB_D531_15                 ; $D5A1  28 08
        INC DE                           ; $D5A3  13
        JR SUB_D531_13                   ; $D5A4  18 F8
SUB_D531_14:
        INC HL                           ; $D5A6  23
        LD (HL),$20                      ; $D5A7  36 20
        DJNZ SUB_D531_14                 ; $D5A9  10 FB
SUB_D531_15:
        LD B,$03                         ; $D5AB  06 03
SUB_D531_16:
        INC HL                           ; $D5AD  23
        LD (HL),$00                      ; $D5AE  36 00
        DJNZ SUB_D531_16                 ; $D5B0  10 FB
        EX DE,HL                         ; $D5B2  EB
        LD (L_D388),HL                   ; $D5B3  22 88 D3
        POP HL                           ; $D5B6  E1
        LD BC,$000B                      ; $D5B7  01 0B 00
SUB_D531_17:
        INC HL                           ; $D5BA  23
        LD A,(HL)                        ; $D5BB  7E
        CP $3F                           ; $D5BC  FE 3F
        JR NZ,SUB_D531_18                ; $D5BE  20 01
        INC B                            ; $D5C0  04
SUB_D531_18:
        DEC C                            ; $D5C1  0D
        JR NZ,SUB_D531_17                ; $D5C2  20 F6
        LD A,B                           ; $D5C4  78
        OR A                             ; $D5C5  B7
        RET                              ; $D5C6  C9
SUB_D531_19:
        DEFB    $44,$49,$52,$20,$45,$52,$41,$20,$54,$59,$50,$45,$53,$41,$56,$45 ; $D5C7
        DEFB    $52,$45,$4E,$20,$55,$53,$45,$52                  ; $D5D7
SUB_D531_20:
        DEFB    $BD,$16,$00,$01,$4D,$40                          ; $D5DF
SUB_D5E5:
        LD HL,SUB_D531_19                ; $D5E5  21 C7 D5
        LD C,$00                         ; $D5E8  0E 00
SUB_D5E5_1:
        LD A,C                           ; $D5EA  79
        CP $06                           ; $D5EB  FE 06
        RET NC                           ; $D5ED  D0
        LD DE,SUB_DB06_13                ; $D5EE  11 87 DB
        LD B,$04                         ; $D5F1  06 04
SUB_D5E5_2:
        LD A,(DE)                        ; $D5F3  1A
        CP (HL)                          ; $D5F4  BE
        JR NZ,SUB_D5E5_3                 ; $D5F5  20 0B
        INC DE                           ; $D5F7  13
        INC HL                           ; $D5F8  23
        DJNZ SUB_D5E5_2                  ; $D5F9  10 F8
        LD A,(DE)                        ; $D5FB  1A
        CP $20                           ; $D5FC  FE 20
        JR NZ,SUB_D5E5_4                 ; $D5FE  20 05
        LD A,C                           ; $D600  79
        RET                              ; $D601  C9
SUB_D5E5_3:
        INC HL                           ; $D602  23
        DJNZ SUB_D5E5_3                  ; $D603  10 FD
SUB_D5E5_4:
        INC C                            ; $D605  0C
        JR SUB_D5E5_1                    ; $D606  18 E2
SUB_D5E5_5:
        XOR A                            ; $D608  AF
        LD (L_D307),A                    ; $D609  32 07 D3
SUB_D5E5_6:
        LD SP,SUB_DB06_7                 ; $D60C  31 64 DB
        PUSH BC                          ; $D60F  C5
        LD A,C                           ; $D610  79
        RRA                              ; $D611  1F
        RRA                              ; $D612  1F
        RRA                              ; $D613  1F
        RRA                              ; $D614  1F
        AND $0F                          ; $D615  E6 0F
        LD E,A                           ; $D617  5F
        CALL SUB_D3F8                    ; $D618  CD F8 D3
        CALL SUB_D3B2                    ; $D61B  CD B2 D3
        LD (SUB_DB06_7),A                ; $D61E  32 64 DB
        POP BC                           ; $D621  C1
        LD A,C                           ; $D622  79
        AND $0F                          ; $D623  E6 0F
        LD (SUB_DB06_19),A               ; $D625  32 A8 DB
        CALL SUB_D3B6                    ; $D628  CD B6 D3
        LD A,(L_D307)                    ; $D62B  3A 07 D3
        OR A                             ; $D62E  B7
        JR NZ,SUB_D5E5_8                 ; $D62F  20 16
SUB_D5E5_7:
        LD SP,SUB_DB06_7                 ; $D631  31 64 DB
        CALL SUB_D399                    ; $D634  CD 99 D3
        CALL SUB_D4A8                    ; $D637  CD A8 D4
        ADD A,$41                        ; $D63A  C6 41
        CALL SUB_D38C                    ; $D63C  CD 8C D3
        LD A,$3E                         ; $D63F  3E 3E
        CALL SUB_D38C                    ; $D641  CD 8C D3
        CALL SUB_D41B                    ; $D644  CD 1B D4
SUB_D5E5_8:
        LD DE,DEFAULT_DMA                ; $D647  11 80 00
        CALL SUB_D4B0                    ; $D64A  CD B0 D4
        CALL SUB_D4A8                    ; $D64D  CD A8 D4
        LD (SUB_DB06_19),A               ; $D650  32 A8 DB
        CALL SUB_D52F                    ; $D653  CD 2F D5
        CALL NZ,SUB_D4DF                 ; $D656  C4 DF D4
        LD A,(SUB_DB06_20)               ; $D659  3A A9 DB
        OR A                             ; $D65C  B7
        JP NZ,SUB_D707_35                ; $D65D  C2 26 D9
        CALL SUB_D5E5                    ; $D660  CD E5 D5
        LD HL,SUB_D5E5_9                 ; $D663  21 70 D6
        LD E,A                           ; $D666  5F
        LD D,$00                         ; $D667  16 00
        ADD HL,DE                        ; $D669  19
        ADD HL,DE                        ; $D66A  19
        LD A,(HL)                        ; $D66B  7E
        INC HL                           ; $D66C  23
        LD H,(HL)                        ; $D66D  66
        LD L,A                           ; $D66E  6F
        JP (HL)                          ; $D66F  E9
SUB_D5E5_9:
        DEFW    SUB_D707_1               ; $D670
        DEFW    SUB_D707_13              ; $D672
        DEFW    SUB_D707_16              ; $D674
        DEFW    SUB_D707_21              ; $D676
        DEFW    SUB_D707_27              ; $D678
        DEFW    SUB_D707_34              ; $D67A
        DEFW    SUB_D707_35              ; $D67C
SUB_D5E5_10:
        LD HL,$76F3                      ; $D67E  21 F3 76
        LD (L_D300),HL                   ; $D681  22 00 D3
        LD HL,L_D300                     ; $D684  21 00 D3
        JP (HL)                          ; $D687  E9
SUB_D688:
        LD BC,SUB_D688_1                 ; $D688  01 8E D6
        JP SUB_D3A2                      ; $D68B  C3 A2 D3
SUB_D688_1:
        DEFB    "Read error"    ; $D68E  string
        DEFB    $00    ; $D698  terminator
SUB_D699:
        LD BC,SUB_D699_1                 ; $D699  01 9F D6
        JP SUB_D3A2                      ; $D69C  C3 A2 D3
SUB_D699_1:
        DEFB    "No file"    ; $D69F  string
        DEFB    $00    ; $D6A6  terminator
SUB_D6A7:
        CALL SUB_D52F                    ; $D6A7  CD 2F D5
        LD A,(SUB_DB06_20)               ; $D6AA  3A A9 DB
        OR A                             ; $D6AD  B7
        JP NZ,SUB_D4DF                   ; $D6AE  C2 DF D4
        LD HL,SUB_DB06_13                ; $D6B1  21 87 DB
        LD BC,$000B                      ; $D6B4  01 0B 00
SUB_D6A7_1:
        LD A,(HL)                        ; $D6B7  7E
        CP $20                           ; $D6B8  FE 20
        JR Z,SUB_D6A7_2                  ; $D6BA  28 24
        INC HL                           ; $D6BC  23
        SUB $30                          ; $D6BD  D6 30
        CP $0A                           ; $D6BF  FE 0A
        JP NC,SUB_D4DF                   ; $D6C1  D2 DF D4
        LD D,A                           ; $D6C4  57
        LD A,B                           ; $D6C5  78
        AND $E0                          ; $D6C6  E6 E0
        JP NZ,SUB_D4DF                   ; $D6C8  C2 DF D4
        LD A,B                           ; $D6CB  78
        RLCA                             ; $D6CC  07
        RLCA                             ; $D6CD  07
        RLCA                             ; $D6CE  07
        ADD A,B                          ; $D6CF  80
        JP C,SUB_D4DF                    ; $D6D0  DA DF D4
        ADD A,B                          ; $D6D3  80
        JP C,SUB_D4DF                    ; $D6D4  DA DF D4
        ADD A,D                          ; $D6D7  82
        JP C,SUB_D4DF                    ; $D6D8  DA DF D4
        LD B,A                           ; $D6DB  47
        DEC C                            ; $D6DC  0D
        JR NZ,SUB_D6A7_1                 ; $D6DD  20 D8
        RET                              ; $D6DF  C9
SUB_D6A7_2:
        LD A,(HL)                        ; $D6E0  7E
        CP $20                           ; $D6E1  FE 20
        JP NZ,SUB_D4DF                   ; $D6E3  C2 DF D4
        INC HL                           ; $D6E6  23
        DEC C                            ; $D6E7  0D
        JR NZ,SUB_D6A7_2                 ; $D6E8  20 F6
        LD A,B                           ; $D6EA  78
        RET                              ; $D6EB  C9
SUB_D6EC:
        LD HL,DEFAULT_DMA                ; $D6EC  21 80 00
        ADD A,C                          ; $D6EF  81
        CALL SUB_D52A                    ; $D6F0  CD 2A D5
        LD A,(HL)                        ; $D6F3  7E
        RET                              ; $D6F4  C9
SUB_D6F5:
        XOR A                            ; $D6F5  AF
        LD (SUB_DB06_12),A               ; $D6F6  32 86 DB
        LD A,(SUB_DB06_20)               ; $D6F9  3A A9 DB
        OR A                             ; $D6FC  B7
        RET Z                            ; $D6FD  C8
        DEC A                            ; $D6FE  3D
        LD HL,SUB_DB06_19                ; $D6FF  21 A8 DB
        CP (HL)                          ; $D702  BE
        RET Z                            ; $D703  C8
        JP SUB_D3B6                      ; $D704  C3 B6 D3
SUB_D707:
        LD A,(SUB_DB06_20)               ; $D707  3A A9 DB
        OR A                             ; $D70A  B7
        RET Z                            ; $D70B  C8
        DEC A                            ; $D70C  3D
        LD HL,SUB_DB06_19                ; $D70D  21 A8 DB
        CP (HL)                          ; $D710  BE
        RET Z                            ; $D711  C8
        LD A,(SUB_DB06_19)               ; $D712  3A A8 DB
        JP SUB_D3B6                      ; $D715  C3 B6 D3
SUB_D707_1:
        CALL SUB_D52F                    ; $D718  CD 2F D5
        CALL SUB_D6F5                    ; $D71B  CD F5 D6
        LD HL,SUB_DB06_13                ; $D71E  21 87 DB
        LD A,(HL)                        ; $D721  7E
        CP $20                           ; $D722  FE 20
        JR NZ,SUB_D707_3                 ; $D724  20 07
        LD B,$0B                         ; $D726  06 0B
SUB_D707_2:
        LD (HL),$3F                      ; $D728  36 3F
        INC HL                           ; $D72A  23
        DJNZ SUB_D707_2                  ; $D72B  10 FB
SUB_D707_3:
        LD E,$00                         ; $D72D  1E 00
        PUSH DE                          ; $D72F  D5
        CALL SUB_D3D1                    ; $D730  CD D1 D3
        CALL Z,SUB_D699                  ; $D733  CC 99 D6
SUB_D707_4:
        JR Z,SUB_D707_12                 ; $D736  28 75
        LD A,(SUB_DB06_18)               ; $D738  3A A7 DB
        RRCA                             ; $D73B  0F
        RRCA                             ; $D73C  0F
        RRCA                             ; $D73D  0F
        AND $60                          ; $D73E  E6 60
        LD C,A                           ; $D740  4F
        LD A,$0A                         ; $D741  3E 0A
        CALL SUB_D6EC                    ; $D743  CD EC D6
        RLA                              ; $D746  17
        JR C,SUB_D707_11                 ; $D747  38 5A
        POP DE                           ; $D749  D1
        LD A,E                           ; $D74A  7B
        INC E                            ; $D74B  1C
        PUSH DE                          ; $D74C  D5
        AND $03                          ; $D74D  E6 03
        PUSH AF                          ; $D74F  F5
        JR NZ,SUB_D707_5                 ; $D750  20 14
        CALL SUB_D399                    ; $D752  CD 99 D3
        PUSH BC                          ; $D755  C5
        CALL SUB_D4A8                    ; $D756  CD A8 D4
        POP BC                           ; $D759  C1
        ADD A,$41                        ; $D75A  C6 41
        CALL SUB_D393                    ; $D75C  CD 93 D3
        LD A,$3A                         ; $D75F  3E 3A
        CALL SUB_D393                    ; $D761  CD 93 D3
        JR SUB_D707_6                    ; $D764  18 08
SUB_D707_5:
        CALL SUB_D391                    ; $D766  CD 91 D3
        LD A,$3A                         ; $D769  3E 3A
        CALL SUB_D393                    ; $D76B  CD 93 D3
SUB_D707_6:
        CALL SUB_D391                    ; $D76E  CD 91 D3
        LD B,$01                         ; $D771  06 01
SUB_D707_7:
        LD A,B                           ; $D773  78
        CALL SUB_D6EC                    ; $D774  CD EC D6
        AND $7F                          ; $D777  E6 7F
        CP $20                           ; $D779  FE 20
        JR NZ,SUB_D707_9                 ; $D77B  20 13
        POP AF                           ; $D77D  F1
        PUSH AF                          ; $D77E  F5
        CP $03                           ; $D77F  FE 03
        JR NZ,SUB_D707_8                 ; $D781  20 0B
        LD A,$09                         ; $D783  3E 09
        CALL SUB_D6EC                    ; $D785  CD EC D6
        AND $7F                          ; $D788  E6 7F
        CP $20                           ; $D78A  FE 20
        JR Z,SUB_D707_10                 ; $D78C  28 14
SUB_D707_8:
        LD A,$20                         ; $D78E  3E 20
SUB_D707_9:
        CALL SUB_D393                    ; $D790  CD 93 D3
        INC B                            ; $D793  04
        LD A,B                           ; $D794  78
        CP $0C                           ; $D795  FE 0C
        JR NC,SUB_D707_10                ; $D797  30 09
        CP $09                           ; $D799  FE 09
        JR NZ,SUB_D707_7                 ; $D79B  20 D6
        CALL SUB_D391                    ; $D79D  CD 91 D3
        JR SUB_D707_7                    ; $D7A0  18 D1
SUB_D707_10:
        POP AF                           ; $D7A2  F1
SUB_D707_11:
        CALL SUB_D49A                    ; $D7A3  CD 9A D4
        JR NZ,SUB_D707_12                ; $D7A6  20 05
        CALL SUB_D3D8                    ; $D7A8  CD D8 D3
        JR SUB_D707_4                    ; $D7AB  18 89
SUB_D707_12:
        POP DE                           ; $D7AD  D1
        JP SUB_D707_52                   ; $D7AE  C3 38 DA
SUB_D707_13:
        CALL SUB_D52F                    ; $D7B1  CD 2F D5
        CP $0B                           ; $D7B4  FE 0B
        JR NZ,SUB_D707_14                ; $D7B6  20 1B
        LD BC,SUB_D707_15                ; $D7B8  01 E3 D7
        CALL SUB_D3A2                    ; $D7BB  CD A2 D3
        CALL SUB_D41B                    ; $D7BE  CD 1B D4
        LD HL,L_D307                     ; $D7C1  21 07 D3
        DEC (HL)                         ; $D7C4  35
        JP NZ,SUB_D5E5_7                 ; $D7C5  C2 31 D6
        INC HL                           ; $D7C8  23
        LD A,(HL)                        ; $D7C9  7E
        CP $59                           ; $D7CA  FE 59
        JP NZ,SUB_D5E5_7                 ; $D7CC  C2 31 D6
        INC HL                           ; $D7CF  23
        LD (L_D388),HL                   ; $D7D0  22 88 D3
SUB_D707_14:
        CALL SUB_D6F5                    ; $D7D3  CD F5 D6
        LD DE,SUB_DB06_12                ; $D7D6  11 86 DB
        CALL SUB_D3DC                    ; $D7D9  CD DC D3
        INC A                            ; $D7DC  3C
        CALL Z,SUB_D699                  ; $D7DD  CC 99 D6
        JP SUB_D707_52                   ; $D7E0  C3 38 DA
SUB_D707_15:
        DEFB    "All (y/n)?"    ; $D7E3  string
        DEFB    $00    ; $D7ED  terminator
SUB_D707_16:
        CALL SUB_D52F                    ; $D7EE  CD 2F D5
        JP NZ,SUB_D4DF                   ; $D7F1  C2 DF D4
        CALL SUB_D6F5                    ; $D7F4  CD F5 D6
        CALL SUB_D3C6                    ; $D7F7  CD C6 D3
        JR Z,SUB_D707_20                 ; $D7FA  28 38
        CALL SUB_D399                    ; $D7FC  CD 99 D3
        LD HL,SUB_DB06_21                ; $D7FF  21 AA DB
        LD (HL),$FF                      ; $D802  36 FF
SUB_D707_17:
        LD HL,SUB_DB06_21                ; $D804  21 AA DB
        LD A,(HL)                        ; $D807  7E
        CP $80                           ; $D808  FE 80
        JR C,SUB_D707_18                 ; $D80A  38 09
        PUSH HL                          ; $D80C  E5
        CALL SUB_D3E0                    ; $D80D  CD E0 D3
        POP HL                           ; $D810  E1
        JR NZ,SUB_D707_19                ; $D811  20 1A
        XOR A                            ; $D813  AF
        LD (HL),A                        ; $D814  77
SUB_D707_18:
        INC (HL)                         ; $D815  34
        LD HL,DEFAULT_DMA                ; $D816  21 80 00
        CALL SUB_D52A                    ; $D819  CD 2A D5
        LD A,(HL)                        ; $D81C  7E
        CP $1A                           ; $D81D  FE 1A
        JP Z,SUB_D707_52                 ; $D81F  CA 38 DA
        CALL SUB_D38C                    ; $D822  CD 8C D3
        CALL SUB_D49A                    ; $D825  CD 9A D4
        JP NZ,SUB_D707_52                ; $D828  C2 38 DA
        JR SUB_D707_17                   ; $D82B  18 D7
SUB_D707_19:
        DEC A                            ; $D82D  3D
        JP Z,SUB_D707_52                 ; $D82E  CA 38 DA
        CALL SUB_D688                    ; $D831  CD 88 D6
SUB_D707_20:
        CALL SUB_D707                    ; $D834  CD 07 D7
        JP SUB_D4DF                      ; $D837  C3 DF D4
SUB_D707_21:
        CALL SUB_D6A7                    ; $D83A  CD A7 D6
        PUSH AF                          ; $D83D  F5
        CALL SUB_D52F                    ; $D83E  CD 2F D5
        JP NZ,SUB_D4DF                   ; $D841  C2 DF D4
        CALL SUB_D6F5                    ; $D844  CD F5 D6
        LD DE,SUB_DB06_12                ; $D847  11 86 DB
        PUSH DE                          ; $D84A  D5
        CALL SUB_D3DC                    ; $D84B  CD DC D3
        POP DE                           ; $D84E  D1
        CALL SUB_D3EE                    ; $D84F  CD EE D3
        JR Z,SUB_D707_24                 ; $D852  28 2F
        XOR A                            ; $D854  AF
        LD (SUB_DB06_17),A               ; $D855  32 A6 DB
        POP AF                           ; $D858  F1
        LD L,A                           ; $D859  6F
        LD H,$00                         ; $D85A  26 00
        ADD HL,HL                        ; $D85C  29
        LD DE,TPA_START                  ; $D85D  11 00 01
SUB_D707_22:
        LD A,H                           ; $D860  7C
        OR L                             ; $D861  B5
        JR Z,SUB_D707_23                 ; $D862  28 16
        DEC HL                           ; $D864  2B
        PUSH HL                          ; $D865  E5
        LD HL,DEFAULT_DMA                ; $D866  21 80 00
        ADD HL,DE                        ; $D869  19
        PUSH HL                          ; $D86A  E5
        CALL SUB_D4B0                    ; $D86B  CD B0 D4
        LD DE,SUB_DB06_12                ; $D86E  11 86 DB
        CALL SUB_D3EA                    ; $D871  CD EA D3
        POP DE                           ; $D874  D1
        POP HL                           ; $D875  E1
        JR NZ,SUB_D707_24                ; $D876  20 0B
        JR SUB_D707_22                   ; $D878  18 E6
SUB_D707_23:
        LD DE,SUB_DB06_12                ; $D87A  11 86 DB
        CALL SUB_D3BC                    ; $D87D  CD BC D3
        INC A                            ; $D880  3C
        JR NZ,SUB_D707_25                ; $D881  20 06
SUB_D707_24:
        LD BC,SUB_D707_26                ; $D883  01 8F D8
        CALL SUB_D3A2                    ; $D886  CD A2 D3
SUB_D707_25:
        CALL SUB_D4AD                    ; $D889  CD AD D4
        JP SUB_D707_52                   ; $D88C  C3 38 DA
SUB_D707_26:
        DEFB    "No space"    ; $D88F  string
        DEFB    $00    ; $D897  terminator
SUB_D707_27:
        CALL SUB_D52F                    ; $D898  CD 2F D5
        JP NZ,SUB_D4DF                   ; $D89B  C2 DF D4
        LD A,(SUB_DB06_20)               ; $D89E  3A A9 DB
        PUSH AF                          ; $D8A1  F5
        CALL SUB_D6F5                    ; $D8A2  CD F5 D6
        CALL SUB_D3D1                    ; $D8A5  CD D1 D3
        JR NZ,SUB_D707_32                ; $D8A8  20 50
        LD HL,SUB_DB06_12                ; $D8AA  21 86 DB
        LD DE,SUB_DB06_16                ; $D8AD  11 96 DB
        LD BC,RST2_VEC                   ; $D8B0  01 10 00
        LDIR                             ; $D8B3  ED B0
        LD HL,(L_D388)                   ; $D8B5  2A 88 D3
        EX DE,HL                         ; $D8B8  EB
        CALL SUB_D521                    ; $D8B9  CD 21 D5
        CP $3D                           ; $D8BC  FE 3D
        JR Z,SUB_D707_28                 ; $D8BE  28 04
        CP $5F                           ; $D8C0  FE 5F
        JR NZ,SUB_D707_31                ; $D8C2  20 30
SUB_D707_28:
        EX DE,HL                         ; $D8C4  EB
        INC HL                           ; $D8C5  23
        LD (L_D388),HL                   ; $D8C6  22 88 D3
        CALL SUB_D52F                    ; $D8C9  CD 2F D5
        JR NZ,SUB_D707_31                ; $D8CC  20 26
        POP AF                           ; $D8CE  F1
        LD B,A                           ; $D8CF  47
        LD HL,SUB_DB06_20                ; $D8D0  21 A9 DB
        LD A,(HL)                        ; $D8D3  7E
        OR A                             ; $D8D4  B7
        JR Z,SUB_D707_29                 ; $D8D5  28 04
        CP B                             ; $D8D7  B8
        LD (HL),B                        ; $D8D8  70
        JR NZ,SUB_D707_31                ; $D8D9  20 19
SUB_D707_29:
        LD (HL),B                        ; $D8DB  70
        XOR A                            ; $D8DC  AF
        LD (SUB_DB06_12),A               ; $D8DD  32 86 DB
        CALL SUB_D3D1                    ; $D8E0  CD D1 D3
        JR Z,SUB_D707_30                 ; $D8E3  28 09
        LD DE,SUB_DB06_12                ; $D8E5  11 86 DB
        CALL SUB_D3F2                    ; $D8E8  CD F2 D3
        JP SUB_D707_52                   ; $D8EB  C3 38 DA
SUB_D707_30:
        CALL SUB_D699                    ; $D8EE  CD 99 D6
        JP SUB_D707_52                   ; $D8F1  C3 38 DA
SUB_D707_31:
        CALL SUB_D707                    ; $D8F4  CD 07 D7
        JP SUB_D4DF                      ; $D8F7  C3 DF D4
SUB_D707_32:
        LD BC,SUB_D707_33                ; $D8FA  01 03 D9
        CALL SUB_D3A2                    ; $D8FD  CD A2 D3
        JP SUB_D707_52                   ; $D900  C3 38 DA
SUB_D707_33:
        DEFB    "File exists"    ; $D903  string
        DEFB    $00    ; $D90E  terminator
SUB_D707_34:
        CALL SUB_D6A7                    ; $D90F  CD A7 D6
        CP $10                           ; $D912  FE 10
        JP NC,SUB_D4DF                   ; $D914  D2 DF D4
        LD E,A                           ; $D917  5F
        LD A,(SUB_DB06_13)               ; $D918  3A 87 DB
        CP $20                           ; $D91B  FE 20
        JP Z,SUB_D4DF                    ; $D91D  CA DF D4
        CALL SUB_D3F8                    ; $D920  CD F8 D3
        JP SUB_D707_53                   ; $D923  C3 3B DA
SUB_D707_35:
        CALL SUB_D4CD                    ; $D926  CD CD D4
        LD A,(SUB_DB06_13)               ; $D929  3A 87 DB
        CP $20                           ; $D92C  FE 20
        JR NZ,SUB_D707_36                ; $D92E  20 16
        LD A,(SUB_DB06_20)               ; $D930  3A A9 DB
        OR A                             ; $D933  B7
        JP Z,SUB_D707_53                 ; $D934  CA 3B DA
        DEC A                            ; $D937  3D
        PUSH AF                          ; $D938  F5
        CALL SUB_D3B6                    ; $D939  CD B6 D3
        POP AF                           ; $D93C  F1
        LD (SUB_DB06_19),A               ; $D93D  32 A8 DB
        CALL SUB_D40B                    ; $D940  CD 0B D4
        JP SUB_D707_53                   ; $D943  C3 3B DA
SUB_D707_36:
        CALL SUB_D3F6                    ; $D946  CD F6 D3
        LD (SUB_DB06_6),A                ; $D949  32 43 DB
        LD DE,SUB_DB06_14                ; $D94C  11 8F DB
        LD A,(DE)                        ; $D94F  1A
        CP $20                           ; $D950  FE 20
        JP NZ,SUB_D4DF                   ; $D952  C2 DF D4
        PUSH DE                          ; $D955  D5
        CALL SUB_D6F5                    ; $D956  CD F5 D6
        POP DE                           ; $D959  D1
        LD HL,SUB_D707_51                ; $D95A  21 35 DA
        LD BC,IOBYTE                     ; $D95D  01 03 00
        LDIR                             ; $D960  ED B0
SUB_D707_37:
        CALL SUB_D3C6                    ; $D962  CD C6 D3
        JR NZ,SUB_D707_38                ; $D965  20 0D
        CALL SUB_D3F6                    ; $D967  CD F6 D3
        OR A                             ; $D96A  B7
        JP Z,SUB_D707_48                 ; $D96B  CA 1B DA
        XOR A                            ; $D96E  AF
        CALL SUB_DA50                    ; $D96F  CD 50 DA
        JR SUB_D707_37                   ; $D972  18 EE
SUB_D707_38:
        LD A,(SUB_DB06_12)               ; $D974  3A 86 DB
        OR A                             ; $D977  B7
        JR Z,SUB_D707_39                 ; $D978  28 04
        DEC A                            ; $D97A  3D
        CALL SUB_D3B6                    ; $D97B  CD B6 D3
SUB_D707_39:
        LD C,$1F                         ; $D97E  0E 1F
        CALL BDOS_VEC                    ; $D980  CD 05 00
        INC HL                           ; $D983  23
        INC HL                           ; $D984  23
        LD A,(HL)                        ; $D985  7E
        CP $03                           ; $D986  FE 03
        JR NZ,SUB_D707_40                ; $D988  20 09
        INC HL                           ; $D98A  23
        INC HL                           ; $D98B  23
        INC HL                           ; $D98C  23
        LD A,(HL)                        ; $D98D  7E
        CP $8B                           ; $D98E  FE 8B
        JP Z,SUB_DA50_1                  ; $D990  CA 54 DA
SUB_D707_40:
        LD HL,TPA_START                  ; $D993  21 00 01
SUB_D707_41:
        PUSH HL                          ; $D996  E5
        EX DE,HL                         ; $D997  EB
        CALL SUB_D4B0                    ; $D998  CD B0 D4
        LD DE,SUB_DB06_12                ; $D99B  11 86 DB
        CALL SUB_D3E3                    ; $D99E  CD E3 D3
        JR NZ,SUB_D707_42                ; $D9A1  20 11
        POP HL                           ; $D9A3  E1
        LD DE,DEFAULT_DMA                ; $D9A4  11 80 00
        ADD HL,DE                        ; $D9A7  19
        LD DE,L_D300                     ; $D9A8  11 00 D3
        OR A                             ; $D9AB  B7
        PUSH HL                          ; $D9AC  E5
        SBC HL,DE                        ; $D9AD  ED 52
        POP HL                           ; $D9AF  E1
        JR NC,SUB_D707_49                ; $D9B0  30 72
        JR SUB_D707_41                   ; $D9B2  18 E2
SUB_D707_42:
        POP HL                           ; $D9B4  E1
        DEC A                            ; $D9B5  3D
        JR NZ,SUB_D707_49                ; $D9B6  20 6C
SUB_D707_43:
        CALL SUB_DA4D                    ; $D9B8  CD 4D DA
        CALL SUB_D707                    ; $D9BB  CD 07 D7
        CALL SUB_D52F                    ; $D9BE  CD 2F D5
        LD HL,SUB_DB06_20                ; $D9C1  21 A9 DB
        PUSH HL                          ; $D9C4  E5
        LD A,(HL)                        ; $D9C5  7E
        LD (SUB_DB06_12),A               ; $D9C6  32 86 DB
        LD A,$10                         ; $D9C9  3E 10
        CALL SUB_D531                    ; $D9CB  CD 31 D5
        POP HL                           ; $D9CE  E1
        LD A,(HL)                        ; $D9CF  7E
        LD (SUB_DB06_16),A               ; $D9D0  32 96 DB
        XOR A                            ; $D9D3  AF
        LD (SUB_DB06_17),A               ; $D9D4  32 A6 DB
        LD DE,DEFAULT_FCB                ; $D9D7  11 5C 00
        LD HL,SUB_DB06_12                ; $D9DA  21 86 DB
        LD BC,$0021                      ; $D9DD  01 21 00
        LDIR                             ; $D9E0  ED B0
        LD HL,L_D308                     ; $D9E2  21 08 D3
SUB_D707_44:
        LD A,(HL)                        ; $D9E5  7E
        OR A                             ; $D9E6  B7
        JR Z,SUB_D707_45                 ; $D9E7  28 07
        CP $20                           ; $D9E9  FE 20
        JR Z,SUB_D707_45                 ; $D9EB  28 03
        INC HL                           ; $D9ED  23
        JR SUB_D707_44                   ; $D9EE  18 F5
SUB_D707_45:
        LD B,$00                         ; $D9F0  06 00
        LD DE,CMDLINE                    ; $D9F2  11 81 00
SUB_D707_46:
        LD A,(HL)                        ; $D9F5  7E
        LD (DE),A                        ; $D9F6  12
        OR A                             ; $D9F7  B7
        JR Z,SUB_D707_47                 ; $D9F8  28 05
        INC B                            ; $D9FA  04
        INC HL                           ; $D9FB  23
        INC DE                           ; $D9FC  13
        JR SUB_D707_46                   ; $D9FD  18 F6
SUB_D707_47:
        LD A,B                           ; $D9FF  78
        LD (DEFAULT_DMA),A               ; $DA00  32 80 00
        CALL SUB_D399                    ; $DA03  CD 99 D3
        CALL SUB_D4AD                    ; $DA06  CD AD D4
        CALL SUB_D3FC                    ; $DA09  CD FC D3
        CALL TPA_START                   ; $DA0C  CD 00 01
        LD SP,SUB_DB06_7                 ; $DA0F  31 64 DB
        CALL SUB_D40B                    ; $DA12  CD 0B D4
        CALL SUB_D3B6                    ; $DA15  CD B6 D3
        JP SUB_D5E5_7                    ; $DA18  C3 31 D6
SUB_D707_48:
        CALL SUB_DA4D                    ; $DA1B  CD 4D DA
        CALL SUB_D707                    ; $DA1E  CD 07 D7
        JP SUB_D4DF                      ; $DA21  C3 DF D4
SUB_D707_49:
        LD BC,SUB_D707_50                ; $DA24  01 2C DA
        CALL SUB_D3A2                    ; $DA27  CD A2 D3
        JR SUB_D707_52                   ; $DA2A  18 0C
SUB_D707_50:
        DEFB    "Bad load"    ; $DA2C  string
        DEFB    $00    ; $DA34  terminator
SUB_D707_51:
        DEFB    $43,$4F,$4D                                      ; $DA35
SUB_D707_52:
        CALL SUB_D707                    ; $DA38  CD 07 D7
SUB_D707_53:
        CALL SUB_D52F                    ; $DA3B  CD 2F D5
        LD A,(SUB_DB06_13)               ; $DA3E  3A 87 DB
        SUB $20                          ; $DA41  D6 20
        LD HL,SUB_DB06_20                ; $DA43  21 A9 DB
        OR (HL)                          ; $DA46  B6
        JP NZ,SUB_D4DF                   ; $DA47  C2 DF D4
        JP SUB_D5E5_7                    ; $DA4A  C3 31 D6
SUB_DA4D:
        LD A,(SUB_DB06_6)                ; $DA4D  3A 43 DB
SUB_DA50:
        LD E,A                           ; $DA50  5F
        JP SUB_D3F8                      ; $DA51  C3 F8 D3
SUB_DA50_1:
        LD HL,($F3DE)                    ; $DA54  2A DE F3
        LD (SUB_DB06_2+1),HL             ; $DA57  22 26 DB
        XOR A                            ; $DA5A  AF
        LD (SUB_DB06_15),A               ; $DA5B  32 92 DB
        LD A,$11                         ; $DA5E  3E 11
        LD (SUB_DB06_4),A                ; $DA60  32 41 DB
        ; SYS_BASE-1 = top of the TPA (the byte just below the CCP). Point DE at
        ; the top of the sysgen buffer, which is filled/read downward from here.
        LD DE,SYS_BASE-1                      ; $DA63  11 FF D2
SUB_DA50_2:
        XOR A                            ; $DA66  AF
        LD (SUB_DB06_17),A               ; $DA67  32 A6 DB
        LD HL,SUB_DB06_16                ; $DA6A  21 96 DB
SUB_DA50_3:
        LD A,(HL)                        ; $DA6D  7E
        OR A                             ; $DA6E  B7
        JR Z,SUB_DA50_4                  ; $DA6F  28 06
        CALL SUB_DA8D                    ; $DA71  CD 8D DA
        INC HL                           ; $DA74  23
        JR SUB_DA50_3                    ; $DA75  18 F6
SUB_DA50_4:
        LD A,$A6                         ; $DA77  3E A6
        CP L                             ; $DA79  BD
        JP NZ,SUB_DA50_5                 ; $DA7A  C2 82 DA
        CALL SUB_DAC8                    ; $DA7D  CD C8 DA
        JR NZ,SUB_DA50_2                 ; $DA80  20 E4
SUB_DA50_5:
        XOR A                            ; $DA82  AF
        LD (DE),A                        ; $DA83  12
        CALL SUB_DAD4                    ; $DA84  CD D4 DA
        CALL SUB_DB06                    ; $DA87  CD 06 DB
        JP SUB_D707_43                   ; $DA8A  C3 B8 D9
SUB_DA8D:
        PUSH HL                          ; $DA8D  E5
        PUSH AF                          ; $DA8E  F5
        SRL A                            ; $DA8F  CB 3F
        SRL A                            ; $DA91  CB 3F
        ADD A,$03                        ; $DA93  C6 03
        LD (SUB_DB06_5),A                ; $DA95  32 42 DB
        POP AF                           ; $DA98  F1
        AND $03                          ; $DA99  E6 03
        ADD A,A                          ; $DA9B  87
        ADD A,A                          ; $DA9C  87
        LD HL,SUB_DB06_3                 ; $DA9D  21 31 DB
        ADD A,L                          ; $DAA0  85
        LD L,A                           ; $DAA1  6F
        JR NC,SUB_DA8D_1                 ; $DAA2  30 01
        INC H                            ; $DAA4  24
SUB_DA8D_1:
        LD B,$04                         ; $DAA5  06 04
SUB_DA8D_2:
        LD A,(SUB_DB06_5)                ; $DAA7  3A 42 DB
        LD (DE),A                        ; $DAAA  12
        DEC DE                           ; $DAAB  1B
        LD A,(HL)                        ; $DAAC  7E
        INC HL                           ; $DAAD  23
        LD (DE),A                        ; $DAAE  12
        DEC DE                           ; $DAAF  1B
        LD A,(SUB_DB06_4)                ; $DAB0  3A 41 DB
        ; Reached the top of RAM? MEMTOP_PAGE is the first page past writable RAM.
        ; This loop builds the system-image page list ($11 upward, skipping the
        ; $C0-$CF I/O hole) and exits once the running page reaches MEMTOP_PAGE.
        CP MEMTOP_PAGE                           ; $DAB3  FE F0
        JP Z,SUB_D707_49                 ; $DAB5  CA 24 DA
        CP $C0                           ; $DAB8  FE C0
        JR NZ,SUB_DA8D_3                 ; $DABA  20 02
        LD A,$D0                         ; $DABC  3E D0
SUB_DA8D_3:
        LD (DE),A                        ; $DABE  12
        INC A                            ; $DABF  3C
        DEC DE                           ; $DAC0  1B
        LD (SUB_DB06_4),A                ; $DAC1  32 41 DB
        DJNZ SUB_DA8D_2                  ; $DAC4  10 E1
        POP HL                           ; $DAC6  E1
        RET                              ; $DAC7  C9
SUB_DAC8:
        PUSH HL                          ; $DAC8  E5
        PUSH DE                          ; $DAC9  D5
        LD HL,SUB_DB06_15                ; $DACA  21 92 DB
        INC (HL)                         ; $DACD  34
        CALL SUB_D3C6                    ; $DACE  CD C6 D3
        POP DE                           ; $DAD1  D1
        POP HL                           ; $DAD2  E1
        RET                              ; $DAD3  C9
SUB_DAD4:
        ; top-of-TPA pointer (SYS_BASE-1); copied to DE and walked DOWNWARD (the
        ; DEC DE / LD A,(DE) sequence below reads the buffer high address-to-low).
        LD HL,SYS_BASE-1                      ; $DAD4  21 FF D2
SUB_DAD4_1:
        LD D,H                           ; $DAD7  54
        LD E,L                           ; $DAD8  5D
SUB_DAD4_2:
        DEC DE                           ; $DAD9  1B
        DEC DE                           ; $DADA  1B
        DEC DE                           ; $DADB  1B
        LD A,(DE)                        ; $DADC  1A
        OR A                             ; $DADD  B7
        JR Z,SUB_DAD4_5                  ; $DADE  28 1E
        CP (HL)                          ; $DAE0  BE
        JR C,SUB_DAD4_3                  ; $DAE1  38 0A
        JR NZ,SUB_DAD4_2                 ; $DAE3  20 F4
        DEC DE                           ; $DAE5  1B
        LD A,(DE)                        ; $DAE6  1A
        INC DE                           ; $DAE7  13
        DEC HL                           ; $DAE8  2B
        CP (HL)                          ; $DAE9  BE
        INC HL                           ; $DAEA  23
        JR NC,SUB_DAD4_2                 ; $DAEB  30 EC
SUB_DAD4_3:
        PUSH HL                          ; $DAED  E5
        PUSH DE                          ; $DAEE  D5
        LD B,$03                         ; $DAEF  06 03
SUB_DAD4_4:
        LD A,(DE)                        ; $DAF1  1A
        LD C,(HL)                        ; $DAF2  4E
        LD (HL),A                        ; $DAF3  77
        LD A,C                           ; $DAF4  79
        LD (DE),A                        ; $DAF5  12
        DEC HL                           ; $DAF6  2B
        DEC DE                           ; $DAF7  1B
        DJNZ SUB_DAD4_4                  ; $DAF8  10 F7
        POP DE                           ; $DAFA  D1
        POP HL                           ; $DAFB  E1
        JR SUB_DAD4_2                    ; $DAFC  18 DB
SUB_DAD4_5:
        DEC HL                           ; $DAFE  2B
        DEC HL                           ; $DAFF  2B
        DEC HL                           ; $DB00  2B
        LD A,(HL)                        ; $DB01  7E
        OR A                             ; $DB02  B7
        JR NZ,SUB_DAD4_1                 ; $DB03  20 D2
        RET                              ; $DB05  C9
SUB_DB06:
        ; SUB_DB06 (sysgen / disk-write): scan the SYS_BASE-1 buffer DOWNWARD,
        ; feeding each byte to the RWTS bridge ($F3E0 = sector, below) to write
        ; the system image onto the disk's system tracks.
        LD DE,SYS_BASE-1                      ; $DB06  11 FF D2
SUB_DB06_1:
        LD A,(DE)                        ; $DB09  1A
        OR A                             ; $DB0A  B7
        RET Z                            ; $DB0B  C8
        LD ($F3E0),A                     ; $DB0C  32 E0 F3
        DEC DE                           ; $DB0F  1B
        LD A,(DE)                        ; $DB10  1A
        LD ($F3E1),A                     ; $DB11  32 E1 F3
        DEC DE                           ; $DB14  1B
        LD A,(DE)                        ; $DB15  1A
        LD ($F3E9),A                     ; $DB16  32 E9 F3
        DEC DE                           ; $DB19  1B
        LD A,$01                         ; $DB1A  3E 01
        LD ($F3EB),A                     ; $DB1C  32 EB F3
        LD HL,$0E03                      ; $DB1F  21 03 0E
        LD ($F3D0),HL                    ; $DB22  22 D0 F3
SUB_DB06_2:
        LD (WBOOT_VEC),A                 ; $DB25  32 00 00
        LD A,($F3EA)                     ; $DB28  3A EA F3
        OR A                             ; $DB2B  B7
        JR Z,SUB_DB06_1                  ; $DB2C  28 DB
        JP SUB_D707_40                   ; $DB2E  C3 93 D9
SUB_DB06_3:
        DEFB    $00,$09,$03,$0C,$06,$0F,$01,$0A,$04,$0D,$07,$08,$02,$0B,$05,$0E ; $DB31
SUB_DB06_4:
        DEFB    $00                                              ; $DB41
SUB_DB06_5:
        DEFB    $00                                              ; $DB42
SUB_DB06_6:
        DEFS    25, $00    ; $DB43  fill
CCP_STACK:
        DEFS    8, $00     ; SYS_BASE+$0B5C  top 8 bytes of the CCP private stack (base = $DB64/
                           ;        $9B64, 'LD SP,..'). Ships as ZERO scratch; PUSH/CALL grow the stack
                           ;        down into here at run time. A booted snapshot captures leftover
                           ;        return addresses here -- stack contents, NOT a pointer table.
SUB_DB06_7:
        DEFB    $00                                              ; $DB64
SUB_DB06_8:
        DEFB    $00,$24,$24,$24,$20,$20,$20,$20,$20,$53,$55,$42,$00,$00 ; $DB65
SUB_DB06_9:
        DEFB    $00                                              ; $DB73
SUB_DB06_10:
        DEFS    17, $00    ; $DB74  fill
SUB_DB06_11:
        DEFB    $00                                              ; $DB85
SUB_DB06_12:
        DEFB    $00                                              ; $DB86
SUB_DB06_13:
        DEFS    8, $00    ; $DB87  fill
SUB_DB06_14:
        DEFB    $00,$00,$00                                      ; $DB8F
SUB_DB06_15:
        DEFB    $00,$00,$00,$00                                  ; $DB92
SUB_DB06_16:
        DEFS    16, $00    ; $DB96  fill
SUB_DB06_17:
        DEFB    $00                                              ; $DBA6
SUB_DB06_18:
        DEFB    $00                                              ; $DBA7
SUB_DB06_19:
        DEFB    $00                                              ; $DBA8
SUB_DB06_20:
        DEFB    $00                                              ; $DBA9
SUB_DB06_21:
        DEFS    86, $00    ; $DBAA  fill
SUB_DB06_22:
        DEFB    $BD,$16,$00,$01,$4D,$40                          ; $DC00

    SAVEBIN "{out_bin}", SYS_BASE, $0906
