; ============================================================================
; Microsoft SoftCard CP/M 2.20 -- 6502 Boot Loader (integrated source)
; Annotated disassembly of the loader as it exists in Apple ][ RAM
; after the boot stub completes.
;
; The loader occupies $0800-$13FF in Apple ][ RAM. Loaded by the Disk II
; P6 PROM (sector 0 -> $0800) and the boot stub itself (10 more sectors
; of track 0 -> $0A00-$1300, in CP/M sector skew order).
;
; THIS FILE COVERS
;   $0800-$08FF  Boot stub (sector 0; 60 bytes of code, BYTE-IDENTICAL
;                to 2.23; rest is sector skew table and old/new copyright
;                strings)
;   $1000-$11FF  Stage-2 entry, install loops, slot scanner, dispatch,
;                boot-finalization. NOTE: 74% of stage-2 bytes differ
;                from 2.23. Same overall structure but different
;                addresses and code shape.
;
; KEY DIFFERENCES FROM 2.23
;   - Z-80 BIOS at $DACC (vs 2.23's $FAB8); reset vector planted as
;     "JP $DA00" not "JP $FA00"
;   - BDOS final position $CC06 (vs 2.23's $9C06)
;   - LOAD_CPM at Apple $0E10 (vs $0BEB / $BBEB in 2.23)
;   - Main load reads 28 sectors (LDA #$1C) vs 2.23's 29 (LDA #$1D)
;   - 11-byte Pascal 1.1 detection branch ABSENT (the Videx-fix delta;
;     see CPM_Videx_Difference.md and Part 1 of the article series)
;   - Install copy loops at $1041, $104C, $10E9 (vs $1044, $104F, $10F1)
;   - Warm-boot routine bytes at $13C0+ have STA $C400 + JSR $1010
;     instead of 2.23's STA $FFFF + JSR $0E36 -- different CPU-switch
;     mechanism (slot-4 I/O vs Z-80-byte fetch)
;   - No copyright string at $0860 (zero-filled in 2.20)
;
; COMPANION FILES
;   CPM220_InstallFragments.asm  ORG $0200, runtime view of the bytes
;                                 sourced from $1200-$13FF (different
;                                 from 2.23's install fragments).
;   CPM220_RWTS.asm              ORG $0A00, disk-routine block.
;
; The companion narrative is the cpm-videx article series and
; docs/CPM_Videx_Difference.md.
; ============================================================================

; ----------------------------------------------------------------------------
; Symbols (same set as 2.23 since the underlying Apple platform is the same)
; ----------------------------------------------------------------------------
zp_ptr_lo       = $3C        ; 16-bit pointer / slot ROM base
zp_ptr_hi       = $3D
zp_jmp_lo       = $3E        ; indirect-JMP target
zp_jmp_hi       = $3F
zp_count        = $00
zp_p6_count     = $27

dev_count_d2    = $03B8
dev_table       = $03B9
warm_boot       = $03C0

TEXT            = $FB2F
SETVID          = $FE93
SETKBD          = $FE89
COUT            = $FDED
IORTS           = $FF58
SAVE            = $FF4A
RESTORE         = $FF3F
MONITOR         = $FF65

KBD             = $C000
LC_RD_RAM       = $C081
LC_WR_RAM       = $C083
DISK_MOTOR_OFF  = $C088


; ============================================================================
; SECTION 1 -- Boot stub (sector 0, $0800-$08FF)
;
; 60 bytes of code at $0801-$083C. BYTE-IDENTICAL to 2.23's boot stub.
; Loads 10 more sectors of track 0 in CP/M skew order, then JMP $1000.
; ============================================================================

.setcpu "6502X"
.segment "CODE"
            .org $0800

; The boot-stub bytes are BYTE-IDENTICAL to 2.23 (see CPM223_BootLoader.asm
; for the per-instruction annotation of the 60-byte code at $0801-$082C,
; followed by the sector-skew table, the 1980 Microsoft copyright, and the
; trailing zero pad to $08FF). Then the disk I/O block + GCR tables fill
; $0900-$0FFF (per-instruction in CPM220_RWTS.asm). INCBIN'd here to
; preserve byte-identical round-trip.

            .incbin "cpm-investigation/loader_220.bin", $0, $800


; ============================================================================
; SECTION 3 -- Stage-2 loader ($1000-$11FF)
;
; Entry point reached via JMP $1000 from the boot stub. Sets up Apple
; ][ environment, runs install loops, runs the slot scanner, sets up
; the device-code table, runs LOAD_CPM, then runs boot-finalization
; that sets up the Z-80 reset vector and triggers the SoftCard switch.
; ============================================================================

            ; .org $1000   ; (implicit; preceding incbin lands at $1000)

; The 2.20 stage-2 prose annotations were generated by an early version of
; the disassembler that had several off-by-one errors (one example: the
; boot-stub prose at $0800 was decoded starting from the count byte instead
; of $0801, producing entirely-wrong instructions). For now, INCBIN the
; whole stage-2 + install-fragments-source region ($1000-$13FF) to
; preserve the round-trip property. Per-byte annotations live in the 2.23
; analog (CPM223_BootLoader.asm) where the structures are nearly identical
; minus the Pascal-1.1 detection branch.

            .incbin "cpm-investigation/loader_220.bin", $800, $400


_STAGE2_PROSE_DETACHED_BELOW:    ; pseudo-label so original prose lines parse;
                                 ; the actual bytes for $1000-$13FF come from
                                 ; the .incbin above. Lines below are
                                 ; documentation-only and emit nothing
                                 ; (they're inside a `.if 0` block).
            .if 0
STAGE2_ENTRY:
          LDA $C081                       ; $1000 AD 81 C0
          LDA $C081                       ; $1003 AD 81 C0
          JSR $0F7D                       ; $1006 20 7D 0F
          PHA                             ; $1009 48
          STA $C088,X                     ; $100A 9D 88 C0
          LDA #$00                        ; $100D A9 00
          STA $0478,Y                     ; $100F 99 78 04
          STA $04F8,Y                     ; $1012 99 F8 04
          JSR $FB2F                       ; $1015 20 2F FB
          JSR $FE93                       ; $1018 20 93 FE - OUTPORT
          JSR $FE89                       ; $101B 20 89 FE - INPORT
          PLA                             ; $101E 68
          LDX #$FF                        ; $101F A2 FF
          TXS                             ; $1021 9A
          CMP #$06                        ; $1022 C9 06
          BEQ $1036                       ; $1024 F0 10
          LDY #$00                        ; $1026 A0 00
          LDA $114A,Y                     ; $1028 B9 4A 11
          BEQ $1033                       ; $102B F0 06
          JSR $FDED                       ; $102D 20 ED FD - COUT (print character)
          INY                             ; $1030 C8
          BNE $1028                       ; $1031 D0 F5
          JMP $FF65                       ; $1033 4C 65 FF
          LDY #$0E                        ; $1036 A0 0E
          LDA $1168,Y                     ; $1038 B9 68 11
          STA $0FFF,Y                     ; $103B 99 FF 0F
          DEY                             ; $103E 88
          BNE $1038                       ; $103F D0 F7
          LDA $1200,Y                     ; $1041 B9 00 12
          STA $0200,Y                     ; $1044 99 00 02
          DEY                             ; $1047 88
          BNE $1041                       ; $1048 D0 F7
          LDY #$F1                        ; $104A A0 F1
          LDA $12FF,Y                     ; $104C B9 FF 12
          STA $02FF,Y                     ; $104F 99 FF 02
          DEY                             ; $1052 88
          BNE $104C                       ; $1053 D0 F7
          STY $03B8                       ; $1055 8C B8 03
          STY $3C                         ; $1058 84 3C
          DEY                             ; $105A 88
          STY $3E                         ; $105B 84 3E
          LDY #$C7                        ; $105D A0 C7
          JSR $1180                       ; $105F 20 80 11
          NOP                             ; $1062 EA
          LDA $3E                         ; $1063 A5 3E
          BEQ $107F                       ; $1065 F0 18
          JSR $1117                       ; $1067 20 17 11
          STA $40                         ; $106A 85 40
          STX $41                         ; $106C 86 41
          JSR $1117                       ; $106E 20 17 11
          CPX #$00                        ; $1071 E0 00
          BEQ $1093                       ; $1073 F0 1E
          CMP $40                         ; $1075 C5 40
          BNE $1093                       ; $1077 D0 1A
          CPX $41                         ; $1079 E4 41
          BEQ $1097                       ; $107B F0 1A
          BNE $1093                       ; $107D D0 14
          INC $3E                         ; $107F E6 3E
          STY $03C8                       ; $1081 8C C8 03
          LDA #$00                        ; $1084 A9 00
          STA $03C7                       ; $1086 8D C7 03
          STA $03DE                       ; $1089 8D DE 03
          TYA                             ; $108C 98
          CLC                             ; $108D 18
          ADC #$20                        ; $108E 69 20
          STA $03DF                       ; $1090 8D DF 03
          LDX #$00                        ; $1093 A2 00
          BEQ $10B6                       ; $1095 F0 1F
          LDX #$04                        ; $1097 A2 04
          LDY #$05                        ; $1099 A0 05
          LDA ($3C),Y                     ; $109B B1 3C
          CMP $1176,X                     ; $109D DD 76 11
          BNE $10AB                       ; $10A0 D0 09
          LDY #$07                        ; $10A2 A0 07
          LDA ($3C),Y                     ; $10A4 B1 3C
          CMP $117A,X                     ; $10A6 DD 7A 11
          BEQ $10AE                       ; $10A9 F0 03
          DEX                             ; $10AB CA
          BNE $1099                       ; $10AC D0 EB
          INX                             ; $10AE E8
          CPX #$02                        ; $10AF E0 02
          BNE $10B6                       ; $10B1 D0 03
          INC $03B8                       ; $10B3 EE B8 03
          LDY $3D                         ; $10B6 A4 3D
          TXA                             ; $10B8 8A
          STA $02F8,Y                     ; $10B9 99 F8 02
          DEY                             ; $10BC 88
          CPY #$C0                        ; $10BD C0 C0
          BNE $105F                       ; $10BF D0 9E
          ASL $03B8                       ; $10C1 0E B8 03
          LDA $3E                         ; $10C4 A5 3E
          CMP #$01                        ; $10C6 C9 01
          BEQ $10E7                       ; $10C8 F0 1D
          STY $3D                         ; $10CA 84 3D
          LDA #$85                        ; $10CC A9 85
          STA $3C                         ; $10CE 85 3C
          STA $C085                       ; $10D0 8D 85 C0
          LDA $3E                         ; $10D3 A5 3E
          BEQ $10E7                       ; $10D5 F0 10
          LDY #$00                        ; $10D7 A0 00
          LDA $112B,Y                     ; $10D9 B9 2B 11
          BEQ $10E4                       ; $10DC F0 06
          JSR $FDED                       ; $10DE 20 ED FD - COUT (print character)
          INY                             ; $10E1 C8
          BNE $10D9                       ; $10E2 D0 F5
          JMP $FF65                       ; $10E4 4C 65 FF
          LDY #$10                        ; $10E7 A0 10
          LDA $13EF,Y                     ; $10E9 B9 EF 13
          STA $03EF,Y                     ; $10EC 99 EF 03
          DEY                             ; $10EF 88
          BNE $10E9                       ; $10F0 D0 F7
          LDA #$C3                        ; $10F2 A9 C3
          STA $1000                       ; $10F4 8D 00 10
          LDA #$00                        ; $10F7 A9 00
          STA $1001                       ; $10F9 8D 01 10
          LDA #$DA                        ; $10FC A9 DA
          STA $1002                       ; $10FE 8D 02 10
          JSR $0FAD                       ; $1101 20 AD 0F
          LDA #$16                        ; $1104 A9 16
          STA $0FCC                       ; $1106 8D CC 0F
          LDY #$06                        ; $1109 A0 06
          LDA $1124,Y                     ; $110B B9 24 11
          STA $FFF9,Y                     ; $110E 99 F9 FF
          DEY                             ; $1111 88
          BNE $110B                       ; $1112 D0 F7
          JMP $03D2                       ; $1114 4C D2 03
          LDA #$00                        ; $1117 A9 00
          TAX                             ; $1119 AA
          TAY                             ; $111A A8
          CLC                             ; $111B 18
          ADC ($3C),Y                     ; $111C 71 3C
          BCC $1121                       ; $111E 90 01
          INX                             ; $1120 E8
          INY                             ; $1121 C8
          BNE $111B                       ; $1122 D0 F7
          RTS                             ; $1124 60
          CPY #$03                        ; $1125 C0 03
          CPY #$03                        ; $1127 C0 03
          CPY #$03                        ; $1129 C0 03
          STA $8D8D                       ; $112B 8D 8D 8D
          STA $C1C3                       ; $112E 8D C3 C1
          DEC $D4A7                       ; $1131 CE A7 D4
          LDY #$C6                        ; $1134 A0 C6
          CMP #$CE                        ; $1136 C9 CE
          CPY $A0                         ; $1138 C4 A0
          NOP                             ; $113A DA
          CLV                             ; $113B B8
          BCS $10DE                       ; $113C B0 A0
          DCP ($CF),Y                     ; $113E D3 CF
          DEC $D4                         ; $1140 C6 D4
          DCP ($C1,X)                     ; $1142 C3 C1
          .byte $D2    ; $1144 was KIL
          CPY $8D                         ; $1145 C4 8D
          STA $008D                       ; $1147 8D 8D 00
          STA $8D8D                       ; $114A 8D 8D 8D
          STA $D5CD                       ; $114D 8D CD D5
          DCP ($D4),Y                     ; $1150 D3 D4
          LDY #$C2                        ; $1152 A0 C2
          DCP $D4CF                       ; $1154 CF CF D4
          LDY #$C6                        ; $1157 A0 C6
          .byte $D2    ; $1159 was KIL
          DCP $A0CD                       ; $115A CF CD A0
          DCP ($CC),Y                     ; $115D D3 CC
          DCP $A0D4                       ; $115F CF D4 A0
          DCP ($C9),Y                     ; $1162 D3 C9
          CLD                             ; $1164 D8
          STA $8D8D                       ; $1165 8D 8D 8D
          BRK                             ; $1168 00
          LAX $3E32                       ; $1169 AF 32 3E
          BEQ $11DD                       ; $116C F0 6F
          NOP                             ; $116E 3A
          AND $C6F0,X                     ; $116F 3D F0 C6
          JSR $7767                       ; $1172 20 67 77
          CLC                             ; $1175 18
          .byte $F2    ; $1176 was KIL
          SLO ($18,X)                     ; $1177 03 18
          SEC                             ; $1179 38
          PHA                             ; $117A 48
          NOP $1838,X                     ; $117B 3C 38 18
          PHA                             ; $117E 48
          ISC $3D84,X                     ; $117F FF 84 3D
          STY $1187                       ; $1182 8C 87 11
          STA $0000                       ; $1185 8D 00 00
          RTS                             ; $1188 60
          ISC $FFFF,X                     ; $1189 FF FF FF
          ISC $FFFF,X                     ; $118C FF FF FF
          ISC $FFFF,X                     ; $118F FF FF FF
          ISC $FFFF,X                     ; $1192 FF FF FF
          ISC $FFFF,X                     ; $1195 FF FF FF
          ISC $FFFF,X                     ; $1198 FF FF FF
          ISC $FFFF,X                     ; $119B FF FF FF
          ISC $FFFF,X                     ; $119E FF FF FF
          ISC $FFFF,X                     ; $11A1 FF FF FF
          ISC $FFFF,X                     ; $11A4 FF FF FF
          ISC $FFFF,X                     ; $11A7 FF FF FF
          ISC $FFFF,X                     ; $11AA FF FF FF
          ISC $FFFF,X                     ; $11AD FF FF FF
          ISC $FFFF,X                     ; $11B0 FF FF FF
          ISC $FFFF,X                     ; $11B3 FF FF FF
          ISC $FFFF,X                     ; $11B6 FF FF FF
          ISC $FFFF,X                     ; $11B9 FF FF FF
          ISC $FFFF,X                     ; $11BC FF FF FF
          ISC $FFFF,X                     ; $11BF FF FF FF
          ISC $FFFF,X                     ; $11C2 FF FF FF
          ISC $FFFF,X                     ; $11C5 FF FF FF
          ISC $FFFF,X                     ; $11C8 FF FF FF
          ISC $FFFF,X                     ; $11CB FF FF FF
          ISC $FFFF,X                     ; $11CE FF FF FF
          ISC $FFFF,X                     ; $11D1 FF FF FF
          ISC $FFFF,X                     ; $11D4 FF FF FF
          ISC $FFFF,X                     ; $11D7 FF FF FF
          ISC $FFFF,X                     ; $11DA FF FF FF
          ISC $FFFF,X                     ; $11DD FF FF FF
          ISC $FFFF,X                     ; $11E0 FF FF FF
          ISC $FFFF,X                     ; $11E3 FF FF FF
          ISC $FFFF,X                     ; $11E6 FF FF FF
          ISC $FFFF,X                     ; $11E9 FF FF FF
          ISC $FFFF,X                     ; $11EC FF FF FF
          ISC $FFFF,X                     ; $11EF FF FF FF
          ISC $FFFF,X                     ; $11F2 FF FF FF
          ISC $FFFF,X                     ; $11F5 FF FF FF
          ISC $FFFF,X                     ; $11F8 FF FF FF
          ISC $FFFF,X                     ; $11FB FF FF FF
          ISC $00FF,X                     ; $11FE FF FF 00


; ============================================================================
; SECTION 4 -- Page-2 install image source ($1200-$12FF, source-only)
;
; This 256-byte block gets copied to Apple $0200-$02FF by the install
; loop at $1041. The runtime form is in CPM220_InstallFragments.asm.
; The bytes here are the SOURCE; they're meaningless to 6502 disasm at
; $12xx because they execute as 6502 (or are read as data) at $02xx.
; ============================================================================


; ============================================================================
; SECTION 5 -- Page-3 install image source ($1300-$13FF, source-only)
;
; Copied to $0300-$03FF by the install loops at $104C (most of it) and
; $10E9 (last 16 bytes). Includes the warm-boot routine source bytes
; at $13C0-$13DC. Runtime form is in CPM220_InstallFragments.asm.
; ============================================================================

            .endif    ; close documentation-only stage-2 prose block
