"""sjasmplus-compatible output formatter.

Produces a single .asm file that reassembles to byte-identical bytes via:
    sjasmplus OUT.asm
    cmp INPUT.bin OUT.bin

sjasmplus syntax notes
----------------------
  * Comments:        ; ...
  * Label:           Name:                  (colon optional but kept for clarity)
  * Constant define: Name EQU $XXXX
  * Origin:          ORG $XXXX
  * Output binary:   SAVEBIN "out.bin", $start, $length
  * Data:            DEFB $XX,$YY    DEFW $XXYY    DEFS N,fill
  * Device:          DEVICE NOSLOT64K  -- gives a 64K flat address space
                                          (required before ORG outside ROM areas)
  * Hex literal:     $XXXX  or  XXXXh

The walker only substitutes label names into JP/CALL/JR/DJNZ/RST targets
(the decoder embeds the raw immediate into the mnemonic for everything else,
since e.g. LD HL,$nnnn is rarely a code-pointer).
"""

import re
import sys
from pathlib import Path

# Allow `from disasm_common import ...` regardless of how this module is loaded.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from disasm_common.analyzer import classify_data, DataKind  # noqa: E402

from .opcodes import decode_at, ControlFlow


# Match a hex constant in a mnemonic: $XXXX or $XX (4 or 2 digits exact).
# We use this to substitute a label name when the operand of a JP/CALL/JR/RST
# resolves to an address with a known label.
_HEX_LITERAL_RE = re.compile(r'\$([0-9A-Fa-f]{2,4})')


def _resolve_label(addr, symbols, labels):
    if addr in labels and labels[addr]:
        return labels[addr]
    if symbols is not None:
        n = symbols.name_for(addr)
        if n:
            return n
    return None


class SjasmFormatter:
    """Emit sjasmplus source from a Walker result."""

    def __init__(self, mem, walker, symbols=None, *,
                 origin=None, length=None, source_name=""):
        self.mem = mem
        self.walker = walker
        self.symbols = symbols
        self.origin = origin if origin is not None else walker.start
        self.length = length if length is not None else (walker.end - self.origin)
        self.source_name = source_name

    def emit_source(self):
        body_lines, referenced, placed_labels = self._emit_body()
        out = []
        out.append(f"; Generated by disasm_z80")
        if self.source_name:
            out.append(f"; Source: {self.source_name}")
        out.append(f"; Range:  ${self.origin:04X}-${self.origin + self.length - 1:04X}  "
                   f"({self.length} bytes)")
        out.append("")
        out.append("    DEVICE NOSLOT64K")
        out.append("")
        out.extend(self._emit_symbol_block(referenced))
        out.extend(self._emit_overlap_equates(placed_labels))
        out.extend(body_lines)
        out.append("")
        out.append(f'    SAVEBIN "{{out_bin}}", ${self.origin:04X}, ${self.length:04X}')
        return "\n".join(out) + "\n"

    def _emit_overlap_equates(self, placed_labels):
        """Emit EQU constants for in-range labels that couldn't be placed
        inline because they fall in the middle of a multi-byte instruction
        (a deliberate Z-80 code-overlap idiom). sjasmplus treats EQU values
        as numeric constants -- they can be used as JP/CALL targets without
        needing a corresponding label declaration."""
        body_start = self.origin
        body_end = self.origin + self.length
        unplaced = []
        for addr in sorted(self.walker.labels.keys()):
            if not (body_start <= addr < body_end):
                continue
            if addr in placed_labels:
                continue
            name = self.walker.labels[addr]
            if not name:
                continue
            unplaced.append((addr, name))
        if not unplaced:
            return []
        out = ["; -- Code-overlap labels (target falls inside another instruction) --"]
        for addr, name in unplaced:
            out.append(f"{name:<20} EQU ${addr:04X}")
        out.append("")
        return out

    def _emit_symbol_block(self, referenced):
        if self.symbols is None or not referenced:
            return []
        body_start = self.origin
        body_end = self.origin + self.length
        used = []
        for addr in sorted(referenced):
            if body_start <= addr < body_end:
                continue
            sym = self.symbols.get(addr)
            if sym is None:
                continue
            name, comment = sym
            used.append((addr, name, comment))
        if not used:
            return []
        out = ["; -- External symbols --"]
        for addr, name, comment in used:
            line = f"{name:<20} EQU ${addr:04X}"
            if comment:
                line = f"{line:<44} ; {comment}"
            out.append(line)
        out.append("")
        return out

    def _emit_body(self):
        out = []
        referenced = set()
        placed = set()
        out.append(f"    ORG ${self.origin:04X}")
        out.append("")
        body_end = self.origin + self.length
        # Pre-classify all non-code regions in one pass, so the formatter
        # can iterate code byte-by-byte and consult the run for each
        # data position.
        runs = classify_data(
            self.mem, self.origin, body_end,
            code_set=self.walker.code,
            labels=self.walker.labels,
            symbols=self.symbols,
            cpu="z80",
            body_start=self.origin, body_end=body_end,
        )
        runs_by_addr = {r.addr: r for r in runs}
        addr = self.origin
        while addr < body_end:
            label_name = self.walker.labels.get(addr)
            if label_name:
                out.append(f"{label_name}:")
                placed.add(addr)
            if addr in self.walker.code:
                line, refs = self._fmt_code_line(addr)
                out.append(line)
                referenced.update(refs)
                addr += decode_at(self.mem, addr).size
            else:
                run = runs_by_addr.get(addr)
                if run is None:
                    # Should not happen -- classify_data covers every non-
                    # code address. Fall back to a single byte.
                    out.append(f"        DEFB    ${self.mem[addr]:02X}    ; ${addr:04X}")
                    addr += 1
                    continue
                lines, refs = self._render_data_run(run)
                out.extend(lines)
                referenced.update(refs)
                addr = run.end
        return out, referenced, placed

    def _render_data_run(self, run):
        """Format one DataRun. Returns (lines, referenced_addrs)."""
        if run.kind == DataKind.FILL:
            return ([f"        DEFS    {len(run.raw)}, ${run.metadata['value']:02X}"
                     f"    ; ${run.addr:04X}  fill"], set())

        if run.kind == DataKind.STRING:
            return (self._render_string(run), set())

        if run.kind == DataKind.JUMP_TABLE:
            lines, refs = self._render_jump_table(run)
            return (lines, refs)

        if run.kind == DataKind.POINTER_TABLE:
            lines, refs = self._render_pointer_table(run)
            return (lines, refs)

        # MIXED
        return (self._emit_defb_bytes(run.raw, run.addr), set())

    # Assemblers cap a single DEFB/DC at 128 values; chunk long runs so the
    # emitted bytes are identical but every directive stays assembler-legal.
    _DEFB_PER_LINE = 16
    _STRING_PER_LINE = 56

    def _emit_defb_bytes(self, raw, addr, comment=""):
        """Emit one or more DEFB lines, at most _DEFB_PER_LINE bytes each."""
        lines = []
        for i in range(0, len(raw), self._DEFB_PER_LINE):
            chunk = raw[i:i + self._DEFB_PER_LINE]
            bytes_str = ",".join(f"${b:02X}" for b in chunk)
            tag = f"  {comment}" if (comment and i == 0) else ""
            lines.append(f"        DEFB    {bytes_str:<48} ; ${addr + i:04X}{tag}")
        return lines or [f"        DEFB    $00 ; ${addr:04X}"]

    def _render_string(self, run):
        chars = run.metadata["chars"]
        term = run.metadata["terminator"]
        addr = run.addr
        # Quoted form only when every char is plain ASCII needing no escaping
        # (no quote/backslash), chunked so no DEFB exceeds the per-line cap.
        if all(0x20 <= b <= 0x7E and b not in (0x22, 0x5C) for b in chars):
            lines = []
            n = self._STRING_PER_LINE
            for i in range(0, len(chars), n):
                piece = chars[i:i + n].decode("ascii")
                tag = "  string" if i == 0 else ""
                lines.append(f'        DEFB    "{piece}"    ; ${addr + i:04X}{tag}')
            lines.append(f'        DEFB    ${term:02X}'
                         f'    ; ${addr + len(chars):04X}  terminator')
            return lines
        # High-bit / special chars: emit as chunked bytes + a decoded comment.
        decoded = "".join(
            chr(b & 0x7F) if 0x20 <= (b & 0x7F) <= 0x7E else "." for b in chars
        )
        return self._emit_defb_bytes(run.raw, addr, comment=f'"{decoded[:32]}"')

    def _render_jump_table(self, run):
        lines = ["        ; jump table"]
        refs = set()
        for i, target in enumerate(run.metadata["targets"]):
            label = self._resolve_label_for(target)
            target_str = label if label else f"${target:04X}"
            lines.append(f"        JP      {target_str:<24} ; ${run.addr + i*3:04X}")
            if label and self.symbols and self.symbols.name_for(target):
                refs.add(target)
        return lines, refs

    def _render_pointer_table(self, run):
        lines = []
        refs = set()
        for i, target in enumerate(run.metadata["targets"]):
            label = self._resolve_label_for(target)
            target_str = label if label else f"${target:04X}"
            lines.append(f"        DEFW    {target_str:<24} ; ${run.addr + i*2:04X}")
            if label and self.symbols and self.symbols.name_for(target):
                refs.add(target)
        return lines, refs

    def _resolve_label_for(self, addr):
        if addr in self.walker.labels and self.walker.labels[addr]:
            return self.walker.labels[addr]
        if self.symbols is not None:
            return self.symbols.name_for(addr)
        return None

    def _fmt_code_line(self, addr):
        instr = decode_at(self.mem, addr)
        mnem = instr.mnemonic
        refs = set()
        # Substitute labels into JP/CALL/JR/DJNZ targets.
        if instr.target is not None:
            label = _resolve_label(instr.target, self.symbols, self.walker.labels)
            if label:
                mnem = self._substitute_target(mnem, instr.target, label)
                if (self.symbols is not None
                        and self.symbols.name_for(instr.target) is not None
                        and not (self.origin <= instr.target < self.origin + self.length
                                 and self.walker.labels.get(instr.target))):
                    refs.add(instr.target)
        raw = " ".join(f"{b:02X}" for b in instr.raw)
        return f"        {mnem:<32} ; ${addr:04X}  {raw}", refs

    def _substitute_target(self, mnemonic, target, label):
        """Replace the $XXXX literal in `mnemonic` corresponding to `target`."""
        target_str_4 = f"${target:04X}"
        if target_str_4 in mnemonic:
            return mnemonic.replace(target_str_4, label, 1)
        return mnemonic

