"""sjasmplus-compatible output formatter.

Produces a single .asm file that reassembles to byte-identical bytes via:
    sjasmplus OUT.asm
    cmp INPUT.bin OUT.bin

sjasmplus syntax notes
----------------------
  * Comments:        ; ...
  * Label:           Name:                  (colon optional but kept for clarity)
  * Constant define: Name EQU $XXXX
  * Origin:          ORG $XXXX
  * Output binary:   SAVEBIN "out.bin", $start, $length
  * Data:            DEFB $XX,$YY    DEFW $XXYY    DEFS N,fill
  * Device:          DEVICE NOSLOT64K  -- gives a 64K flat address space
                                          (required before ORG outside ROM areas)
  * Hex literal:     $XXXX  or  XXXXh

The walker only substitutes label names into JP/CALL/JR/DJNZ/RST targets
(the decoder embeds the raw immediate into the mnemonic for everything else,
since e.g. LD HL,$nnnn is rarely a code-pointer).
"""

import re
import sys
from pathlib import Path

# Allow `from disasm_common import ...` regardless of how this module is loaded.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from disasm_common.analyzer import (  # noqa: E402
    classify_data, DataKind, classify_overlap, overlap_expr,
)

from .opcodes import decode_at, ControlFlow


# Match a hex constant in a mnemonic: $XXXX or $XX (4 or 2 digits exact).
# We use this to substitute a label name when the operand of a JP/CALL/JR/RST
# resolves to an address with a known label.
_HEX_LITERAL_RE = re.compile(r'\$([0-9A-Fa-f]{2,4})')

# Auto label names the walker mints (anonymous); anything else is a semantic
# routine name worth preserving even when it lands mid-instruction.
_AUTO_BRANCH_RE = re.compile(r'^L_[0-9A-Fa-f]{4}$')
_AUTO_SUB_RE = re.compile(r'^SUB_[0-9A-Fa-f]{4}$')


def _resolve_label(addr, symbols, labels):
    if addr in labels and labels[addr]:
        return labels[addr]
    if symbols is not None:
        n = symbols.name_for(addr)
        if n:
            return n
    return None


class SjasmFormatter:
    """Emit sjasmplus source from a Walker result."""

    def __init__(self, mem, walker, symbols=None, *,
                 origin=None, length=None, source_name=""):
        self.mem = mem
        self.walker = walker
        self.symbols = symbols
        self.origin = origin if origin is not None else walker.start
        self.length = length if length is not None else (walker.end - self.origin)
        self.source_name = source_name
        # Mid-instruction reference state (populated by _prepare_overlap_labels):
        #   _overlap_covers[addr] = (cover, offset)  anonymous -> inline cover+offset
        #   _overlap_named[addr]  = (name, cover, offset)  named -> equate, keep name
        self._overlap_covers = {}
        self._overlap_named = {}
        self._overlap_notes = []
        self._overlap_addrs = set()

    def emit_source(self):
        # Classify every in-range label that lands mid-instruction and mint a
        # label on each covering instruction BEFORE emitting the body, so the
        # operand site can reference it inline as `cover+offset` (no equate).
        self._prepare_overlap_labels()
        body_lines, referenced, placed_labels = self._emit_body()
        out = []
        out.append(f"; Generated by disasm_z80")
        if self.source_name:
            out.append(f"; Source: {self.source_name}")
        out.append(f"; Range:  ${self.origin:04X}-${self.origin + self.length - 1:04X}  "
                   f"({self.length} bytes)")
        out.append("")
        out.append("    DEVICE NOSLOT64K")
        out.append("")
        out.extend(self._emit_symbol_block(referenced))
        out.extend(self._emit_overlap_notes())
        out.extend(body_lines)
        out.append("")
        out.append(f'    SAVEBIN "{{out_bin}}", ${self.origin:04X}, ${self.length:04X}')
        return "\n".join(out) + "\n"

    # Assembler keyword for a constant definition (sjasmplus EQU; ca65 uses =).
    _EQU = "EQU"

    def _sym(self, addr):
        """Resolve `addr` to operand text. A NAMED mid-instruction routine keeps
        its semantic name (defined by an equate). An anonymous mid-instruction
        target resolves to `cover_label+offset` inline (or None -> literal when
        it falls inside a data run). Otherwise fall back to the normal lookup."""
        if addr in self._overlap_named:
            return self._overlap_named[addr][0]
        if addr in self._overlap_covers:
            cover_start, offset = self._overlap_covers[addr]
            cover_name = self.walker.labels.get(cover_start)
            if cover_name:
                return overlap_expr(cover_name, offset)
            return None
        return _resolve_label(addr, self.symbols, self.walker.labels)

    def _decode_size(self, addr):
        return decode_at(self.mem, addr).size

    def _build_instr_index(self):
        """Mirror how `_emit_body` steps through the image and return
        (instr_starts, byte_to_start): the set of code-instruction start
        addresses and a map from each interior code byte to its instruction
        start. Computed purely from `walker.code` + decode sizes, so it does
        not depend on (and is unaffected by) labels or data classification."""
        instr_starts = set()
        byte_to_start = {}
        addr = self.origin
        body_end = self.origin + self.length
        while addr < body_end:
            if addr in self.walker.code:
                size = self._decode_size(addr)
                if size <= 0:
                    addr += 1
                    continue
                instr_starts.add(addr)
                for i in range(1, size):
                    if addr + i < body_end:
                        byte_to_start[addr + i] = addr
                addr += size
            else:
                addr += 1
        return instr_starts, byte_to_start

    def _prepare_overlap_labels(self):
        """Find in-range walker labels that land mid-instruction and record how
        each should be referenced.

        A NAMED routine (curated symbol, hand-curated, or AI semantic name) that
        falls mid-instruction keeps its name, defined by an equate
        ``NAME EQU cover+offset`` so the meaning is preserved (the body can't
        place a label there). An ANONYMOUS ``L_xxxx``/``SUB_xxxx`` overlap is
        referenced inline at its use site as ``cover+offset`` with no equate. A
        target with no covering instruction (inside a data run) falls back to a
        literal. In every case the mid-instruction walker label is removed (it
        can never sit on a byte boundary), and the covering instruction gets a
        minted label so the expression has something to anchor to."""
        instr_starts, byte_to_start = self._build_instr_index()
        body_start = self.origin
        body_end = self.origin + self.length
        self._overlap_covers = {}
        self._overlap_named = {}
        self._overlap_notes = []
        self._overlap_addrs = set()
        minted = False
        for addr in sorted(self.walker.labels.keys()):
            if not (body_start <= addr < body_end):
                continue
            name = self.walker.labels[addr]
            if not name:
                continue
            if addr in instr_starts:
                continue  # starts an instruction -> placed inline normally
            if addr not in byte_to_start:
                continue  # not interior to code -> data-run label, handled later
            res = classify_overlap(
                self.mem, addr,
                byte_to_start=byte_to_start,
                code_set=self.walker.code,
                decode_size=self._decode_size,
                cpu="z80",
            )
            semantic = not _AUTO_BRANCH_RE.match(name) and not _AUTO_SUB_RE.match(name)
            self._overlap_addrs.add(addr)
            self._overlap_notes.append(
                (addr, res.kind, res.cover_start, res.offset, res.reason,
                 name if semantic else None))
            del self.walker.labels[addr]   # never sits on a boundary
            if res.cover_start is not None and not self.walker.labels.get(res.cover_start):
                self.walker.add_label(res.cover_start)
                minted = True
            if semantic:
                self._overlap_named[addr] = (name, res.cover_start, res.offset)
            elif res.cover_start is not None:
                self._overlap_covers[addr] = (res.cover_start, res.offset)
        if minted:
            self.walker.name_labels(self.symbols)
        # Rename branch-only labels to <enclosing routine>_<n> for readability
        # (byte-identical; resolved lazily so cover+offset picks up new names).
        self.walker.localize_labels(self.symbols)

    def _overlap_expr_for(self, cover, offset, addr):
        """The cover+offset expression for an overlap, or a literal if no cover."""
        if cover is None:
            return f"${addr:04X}"
        return overlap_expr(self.walker.labels.get(cover, f"${cover:04X}"), offset)

    def _emit_overlap_notes(self):
        """Emit equates for NAMED mid-instruction routines (preserving their
        semantic names) plus an informational comment block for the anonymous
        ones (which are referenced inline as cover+offset)."""
        out = []
        if self._overlap_named:
            out.append("; -- Named mid-instruction routines (kept as cover+offset equates) --")
            for addr in sorted(self._overlap_named):
                name, cover, offset = self._overlap_named[addr]
                expr = self._overlap_expr_for(cover, offset, addr)
                out.append(f"{name:<20} {self._EQU} {expr:<18} ; ${addr:04X}")
            out.append("")
        if self._overlap_notes:
            out.append("; -- Mid-instruction references (shown inline as cover+offset) --")
            for addr, kind, cover, offset, reason, name in self._overlap_notes:
                expr = name if name else self._overlap_expr_for(cover, offset, addr)
                flag = "" if kind == "IDIOM" else "  [SUSPECTED MISFRAME -- review]"
                out.append(f";   ${addr:04X} -> {expr:<20} {reason}{flag}")
            out.append("")
        return out

    def _emit_symbol_block(self, referenced):
        if self.symbols is None or not referenced:
            return []
        body_start = self.origin
        body_end = self.origin + self.length
        used = []
        for addr in sorted(referenced):
            # An inline walker label already defines this address; an EQU would
            # duplicate it. (Out-of-range and label-less in-range symbols both
            # need the EQU so substituted operands resolve.)
            if self.walker.labels.get(addr):
                continue
            sym = self.symbols.get(addr)
            if sym is None:
                continue
            name, comment = sym
            used.append((addr, name, comment))
        if not used:
            return []
        out = ["; -- External symbols --"]
        for addr, name, comment in used:
            line = f"{name:<20} EQU ${addr:04X}"
            if comment:
                line = f"{line:<44} ; {comment}"
            out.append(line)
        out.append("")
        return out

    def _emit_body(self):
        out = []
        referenced = set()
        placed = set()
        out.append(f"    ORG ${self.origin:04X}")
        out.append("")
        body_end = self.origin + self.length
        # Pre-classify all non-code regions in one pass, so the formatter
        # can iterate code byte-by-byte and consult the run for each
        # data position.
        runs = classify_data(
            self.mem, self.origin, body_end,
            code_set=self.walker.code,
            labels=self.walker.labels,
            symbols=self.symbols,
            cpu="z80",
            body_start=self.origin, body_end=body_end,
        )
        runs_by_addr = {r.addr: r for r in runs}
        addr = self.origin
        while addr < body_end:
            label_name = self.walker.labels.get(addr)
            if label_name:
                out.append(f"{label_name}:")
                placed.add(addr)
            if addr in self.walker.code:
                line, refs = self._fmt_code_line(addr)
                out.append(line)
                referenced.update(refs)
                addr += decode_at(self.mem, addr).size
            else:
                run = runs_by_addr.get(addr)
                if run is None:
                    # Should not happen -- classify_data covers every non-
                    # code address. Fall back to a single byte.
                    out.append(f"        DEFB    ${self.mem[addr]:02X}    ; ${addr:04X}")
                    addr += 1
                    continue
                lines, refs = self._render_data_run(run)
                out.extend(lines)
                referenced.update(refs)
                addr = run.end
        return out, referenced, placed

    def _render_data_run(self, run):
        """Format one DataRun. Returns (lines, referenced_addrs)."""
        if run.kind == DataKind.FILL:
            return ([f"        DEFS    {len(run.raw)}, ${run.metadata['value']:02X}"
                     f"    ; ${run.addr:04X}  fill"], set())

        if run.kind == DataKind.STRING:
            return (self._render_string(run), set())

        if run.kind == DataKind.JUMP_TABLE:
            lines, refs = self._render_jump_table(run)
            return (lines, refs)

        if run.kind == DataKind.POINTER_TABLE:
            lines, refs = self._render_pointer_table(run)
            return (lines, refs)

        # MIXED
        return (self._emit_defb_bytes(run.raw, run.addr), set())

    # Assemblers cap a single DEFB/DC at 128 values; chunk long runs so the
    # emitted bytes are identical but every directive stays assembler-legal.
    _DEFB_PER_LINE = 16
    _STRING_PER_LINE = 56

    def _emit_defb_bytes(self, raw, addr, comment=""):
        """Emit one or more DEFB lines, at most _DEFB_PER_LINE bytes each."""
        lines = []
        for i in range(0, len(raw), self._DEFB_PER_LINE):
            chunk = raw[i:i + self._DEFB_PER_LINE]
            bytes_str = ",".join(f"${b:02X}" for b in chunk)
            tag = f"  {comment}" if (comment and i == 0) else ""
            lines.append(f"        DEFB    {bytes_str:<48} ; ${addr + i:04X}{tag}")
        return lines or [f"        DEFB    $00 ; ${addr:04X}"]

    def _render_string(self, run):
        chars = run.metadata["chars"]
        term = run.metadata["terminator"]
        addr = run.addr
        # Quoted form only when every char is plain ASCII needing no escaping
        # (no quote/backslash), chunked so no DEFB exceeds the per-line cap.
        if all(0x20 <= b <= 0x7E and b not in (0x22, 0x5C) for b in chars):
            lines = []
            n = self._STRING_PER_LINE
            for i in range(0, len(chars), n):
                piece = chars[i:i + n].decode("ascii")
                tag = "  string" if i == 0 else ""
                lines.append(f'        DEFB    "{piece}"    ; ${addr + i:04X}{tag}')
            lines.append(f'        DEFB    ${term:02X}'
                         f'    ; ${addr + len(chars):04X}  terminator')
            return lines
        # High-bit / special chars: emit as chunked bytes + a decoded comment.
        decoded = "".join(
            chr(b & 0x7F) if 0x20 <= (b & 0x7F) <= 0x7E else "." for b in chars
        )
        return self._emit_defb_bytes(run.raw, addr, comment=f'"{decoded[:32]}"')

    def _render_jump_table(self, run):
        lines = ["        ; jump table"]
        refs = set()
        for i, target in enumerate(run.metadata["targets"]):
            label = self._resolve_label_for(target)
            target_str = label if label else f"${target:04X}"
            lines.append(f"        JP      {target_str:<24} ; ${run.addr + i*3:04X}")
            if (label and target not in self._overlap_addrs
                    and self.symbols and self.symbols.name_for(target)):
                refs.add(target)
        return lines, refs

    def _render_pointer_table(self, run):
        lines = []
        refs = set()
        for i, target in enumerate(run.metadata["targets"]):
            label = self._resolve_label_for(target)
            target_str = label if label else f"${target:04X}"
            lines.append(f"        DEFW    {target_str:<24} ; ${run.addr + i*2:04X}")
            if (label and target not in self._overlap_addrs
                    and self.symbols and self.symbols.name_for(target)):
                refs.add(target)
        return lines, refs

    def _resolve_label_for(self, addr):
        # Overlap-aware: a mid-instruction target renders as its semantic name
        # (named overlap) or cover+offset (anonymous), defined elsewhere.
        return self._sym(addr)

    def _fmt_code_line(self, addr):
        instr = decode_at(self.mem, addr)
        mnem = instr.mnemonic
        refs = set()
        # Substitute labels into JP/CALL/JR/DJNZ targets.
        if instr.target is not None:
            label = self._sym(instr.target)
            if label:
                mnem = self._substitute_target(mnem, instr.target, label)
                self._note_symbol_ref(instr.target, refs)
        # Substitute symbolic names for any other 16-bit address operand
        # (immediate loads, memory references) that resolves to a known in-range
        # label or a curated symbol -- so addresses read as the item they point
        # at. A value with no label/symbol is left as a literal, so a genuine
        # constant is never mistaken for an address.
        mnem, op_refs = self._substitute_operand_symbols(mnem)
        refs |= op_refs
        raw = " ".join(f"{b:02X}" for b in instr.raw)
        return f"        {mnem:<32} ; ${addr:04X}  {raw}", refs

    def _note_symbol_ref(self, val, refs):
        """Mark a substituted address as needing an EQU: it carries a curated
        symbol name but no inline walker label (so nothing else defines it).
        Mid-instruction overlap targets are excluded -- they are referenced
        inline as `cover+offset` and need no equate."""
        if val in self._overlap_addrs:
            return
        if (not self.walker.labels.get(val)
                and self.symbols is not None
                and self.symbols.name_for(val) is not None):
            refs.add(val)

    def _substitute_operand_symbols(self, mnem):
        """Replace remaining 4-hex `$XXXX` operands with their label/symbol
        (or `cover+offset` for a mid-instruction target)."""
        refs = set()
        seen = []
        for m in _HEX_LITERAL_RE.finditer(mnem):
            if len(m.group(1)) == 4:
                seen.append((m.group(0), int(m.group(1), 16)))
        for literal, val in seen:
            if literal not in mnem:                  # already substituted
                continue
            label = self._sym(val)
            if not label:
                continue
            mnem = mnem.replace(literal, label, 1)
            self._note_symbol_ref(val, refs)
        return mnem, refs

    def _substitute_target(self, mnemonic, target, label):
        """Replace the $XXXX literal in `mnemonic` corresponding to `target`."""
        target_str_4 = f"${target:04X}"
        if target_str_4 in mnemonic:
            return mnemonic.replace(target_str_4, label, 1)
        return mnemonic

