; NOTE: comments marked [AI] are machine-generated by claude-opus-4-8 and may be
; inaccurate; treat them as hints, not verified annotation.

; Generated by disasm_z80
; Source: CPM60
; Range:  $0100-$2CFF  (11264 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
RST2_VEC             EQU $0010               ; Z-80 RST 2 ($10) restart vector — 8 bytes. Available for application/debugger use.
DEFAULT_FCB          EQU $005C               ; Default File Control Block — populated by CCP from command-line argument 1. Standard 36-byte FCB structure (drive + filename + extents + record number).

    ORG $0100

; [AI] Program entry/main driver. Determines the target drive (from the command-tail FCB drive
;       byte, or BDOS fn 25 current disk), selects it (fn 14), deletes any existing cp/m.sys and
;       reserves its directory entry plus 12 allocation blocks via delete/make/close (fns 19/22/16)
;       after checking the allocation vector (fn 27) for free space, then runs the 48-pass loop that
;       hands the new OS image to the 6502 side through the $F3Ex mailbox, prints the appropriate
;       result message, and on success waits for RETURN and warm-boots through the slot-6 ($C600)
;       boot path.
MAIN:
        LD C,$20                         ; $0100  0E 20
MAIN_1:
        LD E,$1F                         ; $0102  1E 1F
; [AI] BDOS fn 32 (set/get user code): E=$1F is a get, returns the current user number in A.
MAIN_2:
        CALL BDOS_VEC                    ; $0104  CD 05 00
MAIN_3:
        LD A,(DEFAULT_FCB)               ; $0107  3A 5C 00
MAIN_4:
        OR A                             ; $010A  B7
MAIN_5:
        JP NZ,MAIN_9                     ; $010B  C2 14 01
MAIN_6:
        LD C,$19                         ; $010E  0E 19
; [AI] BDOS fn 25 (return current disk): A = default drive number (0=A:); used when no drive was
;       given on the command line.
MAIN_7:
        CALL BDOS_VEC                    ; $0110  CD 05 00
MAIN_8:
        INC A                            ; $0113  3C
MAIN_9:
        LD C,A                           ; $0114  4F
MAIN_10:
        AND $03                          ; $0115  E6 03
; [AI] Store (drive & 3) into the $F3E4 mailbox -- the 6502 side reads this to know which physical
;       drive to write the OS image to.
MAIN_11:
        LD ($F3E4),A                     ; $0117  32 E4 F3
MAIN_12:
        DEC C                            ; $011A  0D
MAIN_13:
        PUSH BC                          ; $011B  C5
MAIN_14:
        LD E,C                           ; $011C  59
MAIN_15:
        LD C,$0E                         ; $011D  0E 0E
; [AI] BDOS fn 14 (select disk): E = target drive index; makes the chosen drive current for all
;       following file ops.
MAIN_16:
        CALL BDOS_VEC                    ; $011F  CD 05 00
MAIN_17:
        LD C,$13                         ; $0122  0E 13
MAIN_18:
        LD DE,PRINT_STRING_1_9           ; $0124  11 55 03
; [AI] BDOS fn 13 (reset disk system) with DE=$0355 (the cp/m.sys FCB); re-logs the drive and
;       prepares the FCB for use.
MAIN_19:
        CALL BDOS_VEC                    ; $0127  CD 05 00
MAIN_20:
        LD C,$1B                         ; $012A  0E 1B
; [AI] BDOS fn 27 (get allocation vector): returns HL -> the drive's allocation bitmap, used next
;       to test free space.
MAIN_21:
        CALL BDOS_VEC                    ; $012C  CD 05 00
MAIN_22:
        LD DE,RST2_VEC                   ; $012F  11 10 00
; [AI] Index 16 bytes into the allocation vector and check the first two bitmap bytes are zero --
;       verifies the data area the OS image needs is still free.
MAIN_23:
        ADD HL,DE                        ; $0132  19
MAIN_24:
        LD A,(HL)                        ; $0133  7E
MAIN_25:
        OR A                             ; $0134  B7
MAIN_26:
        JP NZ,MAIN_72                    ; $0135  C2 ED 01
MAIN_27:
        INC HL                           ; $0138  23
MAIN_28:
        LD A,(HL)                        ; $0139  7E
MAIN_29:
        AND $F0                          ; $013A  E6 F0
MAIN_30:
        OR A                             ; $013C  B7
; [AI] If those allocation bits are already set, branch to the 'Disk space already in use' error
;       path (TPA_START_72).
MAIN_31:
        JP NZ,MAIN_72                    ; $013D  C2 ED 01
; [AI] BDOS fn 22 (make file) with the cp/m.sys FCB at $0355 -- creates a fresh directory entry
;       reserving the file.
MAIN_32:
        LD C,$16                         ; $0140  0E 16
MAIN_33:
        LD DE,PRINT_STRING_1_9           ; $0142  11 55 03
MAIN_34:
        CALL BDOS_VEC                    ; $0145  CD 05 00
MAIN_35:
        INC A                            ; $0148  3C
; [AI] Make-file returned $FF (no free directory slot): jump to the 'Not enough directory space'
;       error (TPA_START_73).
MAIN_36:
        JP Z,MAIN_73                     ; $0149  CA F3 01
MAIN_37:
        LD HL,PRINT_STRING_1_12          ; $014C  21 65 03
MAIN_38:
        LD C,$80                         ; $014F  0E 80
MAIN_39:
        LD B,$0C                         ; $0151  06 0C
; [AI] Fill FCB record-map bytes (12 entries starting at $0365) with consecutive block numbers
;       $80..$8B, hard-allocating the contiguous blocks that hold the OS image.
MAIN_40:
        LD (HL),C                        ; $0153  71
MAIN_41:
        INC C                            ; $0154  0C
MAIN_42:
        INC HL                           ; $0155  23
MAIN_43:
        DEC B                            ; $0156  05
MAIN_44:
        JP NZ,MAIN_40                    ; $0157  C2 53 01
MAIN_45:
        LD A,$60                         ; $015A  3E 60
; [AI] Set FCB extent ($0364)=$60 and record count ($0363)=0 so the closed directory entry
;       describes the full reserved image size.
MAIN_46:
        LD (PRINT_STRING_1_11),A         ; $015C  32 64 03
MAIN_47:
        XOR A                            ; $015F  AF
MAIN_48:
        LD (PRINT_STRING_1_10),A         ; $0160  32 63 03
; [AI] BDOS fn 16 (close file) with FCB $0355 -- flushes the hand-built directory entry so cp/m.sys
;       now exists on disk.
MAIN_49:
        LD C,$10                         ; $0163  0E 10
MAIN_50:
        LD DE,PRINT_STRING_1_9           ; $0165  11 55 03
MAIN_51:
        CALL BDOS_VEC                    ; $0168  CD 05 00
MAIN_52:
        POP BC                           ; $016B  C1
MAIN_53:
        LD A,C                           ; $016C  79
MAIN_54:
        AND $0E                          ; $016D  E6 0E
MAIN_55:
        ADD A,A                          ; $016F  87
MAIN_56:
        ADD A,A                          ; $0170  87
MAIN_57:
        ADD A,A                          ; $0171  87
MAIN_58:
        CPL                              ; $0172  2F
MAIN_59:
        ADD A,$61                        ; $0173  C6 61
; [AI] Compute and store the 6502-side track/sector mailbox seed at $F3E6 from the drive number
;       (geometry the 6502 loader uses).
MAIN_60:
        LD ($F3E6),A                     ; $0175  32 E6 F3
MAIN_61:
        LD A,C                           ; $0178  79
MAIN_62:
        ADD A,$41                        ; $0179  C6 41
; [AI] Patch the drive letter (drive+'A') into the 'drive Z:' prompt string so the printed message
;       names the actual target drive.
MAIN_63:
        LD (PRINT_STRING_1_2),A          ; $017B  32 84 02
MAIN_64:
        LD DE,PRINT_STRING_1_1           ; $017E  11 12 02
MAIN_65:
        CALL PRINT_STRING                ; $0181  CD 0D 02
MAIN_66:
        CALL WAIT_KEYPRESS               ; $0184  CD 01 02
        LD A,$02                         ; $0187  3E 02
        LD ($F3EB),A                     ; $0189  32 EB F3
        LD A,$14                         ; $018C  3E 14
        LD ($F3E9),A                     ; $018E  32 E9 F3
        LD HL,WBOOT_VEC                  ; $0191  21 00 00
        LD B,$30                         ; $0194  06 30
; [AI] Top of the image-streaming loop: write the current source pointer HL into the $F3E0 mailbox
;       so the 6502 knows the next address to pull.
MAIN_67:
        LD ($F3E0),HL                    ; $0196  22 E0 F3
        PUSH BC                          ; $0199  C5
        PUSH HL                          ; $019A  E5
        LD HL,PRINT_STRING_1_13          ; $019B  21 03 0E
        CALL MAILBOX_PUT_BYTE            ; $019E  CD F9 01
        LD A,($F3EA)                     ; $01A1  3A EA F3
        OR A                             ; $01A4  B7
        JP Z,MAIN_69                     ; $01A5  CA B9 01
        LD DE,PRINT_STRING_1_5           ; $01A8  11 E4 02
        CP $10                           ; $01AB  FE 10
        JP NZ,MAIN_68                    ; $01AD  C2 B3 01
MAIN_67_1:
        LD DE,PRINT_STRING_1_6           ; $01B0  11 F9 02
MAIN_68:
        CALL PRINT_STRING                ; $01B3  CD 0D 02
        JP MAIN_71                       ; $01B6  C3 D2 01
; [AI] Success path: bump the sector counter at $F3E9 and advance HL by one page (256 bytes) to the
;       next OS-image chunk.
MAIN_69:
        LD HL,$F3E9                      ; $01B9  21 E9 F3
        INC (HL)                         ; $01BC  34
        POP HL                           ; $01BD  E1
        INC H                            ; $01BE  24
MAIN_69_1:
        LD A,H                           ; $01BF  7C
        SUB $10                          ; $01C0  D6 10
        JP NZ,MAIN_70                    ; $01C2  C2 C7 01
        INC L                            ; $01C5  2C
        LD H,A                           ; $01C6  67
MAIN_70:
        POP BC                           ; $01C7  C1
MAIN_70_1:
        DEC B                            ; $01C8  05
MAIN_70_2:
        JP NZ,MAIN_67                    ; $01C9  C2 96 01
        LD DE,PRINT_STRING_1_3           ; $01CC  11 9F 02
        CALL PRINT_STRING                ; $01CF  CD 0D 02
MAIN_71:
        LD DE,PRINT_STRING_1_4           ; $01D2  11 C0 02
        CALL PRINT_STRING                ; $01D5  CD 0D 02
        CALL WAIT_KEYPRESS               ; $01D8  CD 01 02
MAIN_71_1:
        LD HL,$C777                      ; $01DB  21 77 C7
        LD ($000B),HL                    ; $01DE  22 0B 00
MAIN_71_2:
        LD HL,$C600                      ; $01E1  21 00 C6
        LD ($F3D0),HL                    ; $01E4  22 D0 F3
        LD HL,($F3DE)                    ; $01E7  2A DE F3
        JP $000B                         ; $01EA  C3 0B 00
; [AI] Error label (TPA_START_72): point DE at the 'Disk space already in use' message ($0314)
;       before the shared print-and-exit tail.
MAIN_72:
        LD DE,PRINT_STRING_1_7           ; $01ED  11 14 03
        JP MAIN_68                       ; $01F0  C3 B3 01
; [AI] Error label (TPA_START_73): point DE at the 'Not enough directory space' message ($0334)
;       before the shared print-and-exit tail.
MAIN_73:
        LD DE,PRINT_STRING_1_8           ; $01F3  11 34 03
        JP MAIN_68                       ; $01F6  C3 B3 01
; [AI] Hands one byte to the 6502 side through the SoftCard shared-memory mailbox: stores the
;       16-bit target pointer in HL to $F3D0, then writes A to the byte whose address is held at
;       $F3DE. This is the Z-80-to-6502 request mechanism used to stream the OS-image bytes during
;       the disk rewrite.
MAILBOX_PUT_BYTE:
        LD ($F3D0),HL                    ; $01F9  22 D0 F3
        LD HL,($F3DE)                    ; $01FC  2A DE F3
MAILBOX_PUT_BYTE_1:
        LD (HL),A                        ; $01FF  77
MAILBOX_PUT_BYTE_2:
        RET                              ; $0200  C9
; [AI] Blocks until the user presses a key, using BDOS direct console I/O (fn 6, E=$FF) and looping
;       while the returned character is zero. Backs the interactive 'Press RETURN to begin' and
;       'Press RETURN to re-boot system' prompts.
WAIT_KEYPRESS:
        LD C,$06                         ; $0201  0E 06
WAIT_KEYPRESS_1:
        LD E,$FF                         ; $0203  1E FF
WAIT_KEYPRESS_2:
        CALL BDOS_VEC                    ; $0205  CD 05 00
WAIT_KEYPRESS_3:
        OR A                             ; $0208  B7
WAIT_KEYPRESS_4:
        JP Z,WAIT_KEYPRESS               ; $0209  CA 01 02
        RET                              ; $020C  C9
; [AI] Prints the '$'-terminated message string pointed to by DE via BDOS fn 9 (print string). Uses
;       JP to BDOS so its RET returns directly to PRINT_STRING's caller; the program's banner,
;       prompt, and error messages all go through here.
PRINT_STRING:
        LD C,$09                         ; $020D  0E 09
PRINT_STRING_1:
        JP BDOS_VEC                      ; $020F  C3 05 00
PRINT_STRING_1_1:
        DEFB    $0D,$0A,$0D,$0A,$20,$20,$20,$20,$20,$20,$53,$6F,$66,$74,$63,$61 ; $0212
        DEFB    "rd CP/M"    ; $0222  string
        DEFB    $0D    ; $0229  terminator
        DEFB    $0A,$36,$30,$4B,$20,$43,$50,$2F,$4D,$20,$44,$69,$73,$6B,$20,$75 ; $022A
        DEFB    "pdate program"    ; $023A  string
        DEFB    $0D    ; $0247  terminator
        DEFB    $0A,$20,$20,$20,$20,$28,$43,$29,$20,$31,$39,$38,$32,$20,$4D,$69 ; $0248
        DEFB    "crosoft"    ; $0258  string
        DEFB    $0D    ; $025F  terminator
        DEFB    $0A,$0D,$0A,$49,$6E,$73,$65,$72,$74,$20,$31,$36,$20,$73,$65,$63 ; $0260
        DEFB    $74,$6F,$72,$20,$64,$69,$73,$6B,$20,$69,$6E,$74,$6F,$20,$64,$72 ; $0270
        DEFB    $69,$76,$65,$20                                  ; $0280
PRINT_STRING_1_2:
        DEFB    $5A,$3A,$0D,$0A,$50,$72,$65,$73,$73,$20,$52,$45,$54,$55,$52,$4E ; $0284
        DEFB    $20,$74,$6F,$20,$62,$65,$67,$69,$6E,$20,$24      ; $0294
PRINT_STRING_1_3:
        DEFB    $0D,$0A,$0D,$0A,$44,$69,$73,$6B,$20,$68,$61,$73,$20,$62,$65,$65 ; $029F
        DEFB    $6E,$20,$75,$70,$64,$61,$74,$65,$64,$20,$74,$6F,$20,$36,$30,$4B ; $02AF
        DEFB    $24                                              ; $02BF
PRINT_STRING_1_4:
        DEFB    $0D,$0A,$0D,$0A,$50,$72,$65,$73,$73,$20,$52,$45,$54,$55,$52,$4E ; $02C0
        DEFB    $20,$74,$6F,$20,$72,$65,$2D,$62,$6F,$6F,$74,$20,$73,$79,$73,$74 ; $02D0
        DEFB    $65,$6D,$20,$24                                  ; $02E0
PRINT_STRING_1_5:
        DEFB    $0D,$0A,$0D,$0A,$44,$69,$73,$6B,$20,$49,$2F,$4F,$20,$65,$72,$72 ; $02E4
        DEFB    $6F,$72,$0D,$0A,$24                              ; $02F4
PRINT_STRING_1_6:
        DEFB    $0D,$0A,$0D,$0A,$44,$69,$73,$6B,$20,$77,$72,$69,$74,$65,$20,$70 ; $02F9
        DEFB    "rotected"    ; $0309  string
        DEFB    $0D    ; $0311  terminator
        DEFB    $0A,$24                                          ; $0312
PRINT_STRING_1_7:
        DEFB    $0D,$0A,$0D,$0A,$44,$69,$73,$6B,$20,$73,$70,$61,$63,$65,$20,$61 ; $0314
        DEFB    "lready in use"    ; $0324  string
        DEFB    $0D    ; $0331  terminator
        DEFB    $0A,$24                                          ; $0332
PRINT_STRING_1_8:
        DEFB    $0D,$0A,$0D,$0A,$4E,$6F,$74,$20,$65,$6E,$6F,$75,$67,$68,$20,$64 ; $0334
        DEFB    "irectory space"    ; $0344  string
        DEFB    $0D    ; $0352  terminator
        DEFB    $0A,$24                                          ; $0353
PRINT_STRING_1_9:
        DEFB    $00,$63,$70,$2F,$6D,$20,$20,$20,$20,$73,$79,$73,$00,$00 ; $0355
PRINT_STRING_1_10:
        DEFB    $00                                              ; $0363
PRINT_STRING_1_11:
        DEFB    $00                                              ; $0364
PRINT_STRING_1_12:
        DEFS    154, $00    ; $0365  fill
        DEFW    MAIN                     ; $03FF
        DEFB    $A5,$27,$C9,$09,$D0,$13,$8A,$4A,$4A,$4A,$4A,$09,$C0,$85,$3F,$A9 ; $0401
        DEFB    $5C,$85,$3E,$A9,$00,$85,$00,$E6,$27,$E6,$00,$A4,$00,$C0,$0B,$D0 ; $0411
        DEFB    $03,$4C,$00,$10,$B9,$2D,$08,$85,$3D,$6C,$3E,$00  ; $0421
        DEFW    MAILBOX_PUT_BYTE_2       ; $042D
        DEFB    $04,$06,$08,$0A,$0C                              ; $042F
        DEFW    MAIN_6                   ; $0434
        DEFB    $03,$05,$07,$09,$0B,$0D,$0F,$A0,$C3,$CF,$D0,$D9,$D2,$C9,$C7,$C8 ; $0436
        DEFB    $D4,$A0,$A8,$C3,$A9,$A0,$B1,$B9,$B8,$B0,$A0,$CD,$C9,$C3,$D2,$CF ; $0446  "T (C) 1980 MICROSOFT - NK  COPYR"
        DEFB    $D3,$CF,$C6,$D4,$A0,$AD,$A0,$CE,$CB,$A0,$20,$43,$4F,$50,$59,$52 ; $0456
        DEFB    $49,$47,$48,$54,$20,$28,$43,$29,$20,$31,$39,$38,$32,$20,$4D,$49 ; $0466
        DEFB    $43,$52,$4F,$53,$4F,$46,$54,$20,$2D,$20,$43,$50,$20,$A0,$00 ; $0476
        DEFB    $A2,$56,$CA,$30,$FB,$B9,$00                      ; $0485  ""VJ0{9"
        DEFB    $09,$5E,$00,$0C,$2A,$5E,$00,$0C,$2A,$91,$3E,$C8,$D0,$ED,$60,$00 ; $048C
        DEFS    100, $00    ; $049C  fill
        DEFB    $38,$86,$27,$8E,$78,$06,$BD,$8D,$C0,$BD,$8E,$C0,$30,$7C,$AD,$00 ; $0500
        DEFB    $0C,$85,$26,$A9,$FF,$9D,$8F,$C0,$1D,$8C,$C0,$48,$68,$EA,$A0,$04 ; $0510
        DEFB    $48,$68,$20,$90,$D0,$88,$D0,$F8,$A9,$D5,$20,$8F,$D0,$A9,$AA,$20 ; $0520
        DEFB    $8F,$D0,$A9,$AD,$20,$8F,$D0,$98,$A0,$56,$D0,$03,$B9,$00,$0C,$59 ; $0530
        DEFB    $FF,$0B,$AA,$BD,$69,$D3,$A6,$27,$9D,$8D,$C0,$BD,$8C,$C0,$88,$D0 ; $0540
        DEFB    $EB,$A5,$26,$EA,$59,$00                          ; $0550  "k%&jY"
        DEFB    $09,$AA,$BD,$69,$D3,$AE,$78,$06,$9D,$8D,$C0,$BD,$8C,$C0,$B9,$00 ; $0556
        DEFB    $09,$C8,$D0,$EA,$AA,$BD,$69,$D3,$A6,$27,$20,$92,$D0,$A9,$DE,$20 ; $0566
        DEFB    $8F,$D0,$A9,$AA,$20,$8F,$D0,$A9,$EB,$20,$8F,$D0,$A9,$FF,$20,$8F ; $0576
        DEFB    $D0,$BD,$8E,$C0,$BD,$8C,$C0,$60,$EA,$18,$48,$68,$9D,$8D,$C0,$1D ; $0586
        DEFB    $8C,$C0,$60,$A0,$20,$88,$F0,$63,$BD,$8C,$C0,$10,$FB,$49,$D5,$D0 ; $0596
        DEFB    $F4,$EA,$BD,$8C,$C0,$10,$FB,$C9,$AA,$D0,$F2,$A0,$56,$BD,$8C,$C0 ; $05A6
        DEFB    $10,$FB,$C9,$AD,$D0,$E7,$EA,$EA,$A9,$00,$88,$84,$26,$BC,$8C,$C0 ; $05B6
        DEFB    $10,$FB,$59,$13,$D3,$A4,$26,$99,$00,$0C,$D0,$EE,$84,$26,$BC,$8C ; $05C6
        DEFB    $C0,$10,$FB,$59,$13,$D3,$A4,$26,$99,$00,$09,$C8,$D0,$EE,$BC,$8C ; $05D6
        DEFB    $C0,$10,$FB,$D9,$13,$D3,$D0,$13,$BD,$8C,$C0,$10,$FB,$C9,$DE,$D0 ; $05E6
        DEFB    $0A,$EA,$BD,$8C,$C0,$10,$FB,$C9,$AA,$F0,$5C,$38,$60,$A0,$FC,$84 ; $05F6
        DEFB    $26,$C8,$D0,$04,$E6,$26,$F0,$F3,$BD,$8C,$C0,$10,$FB,$C9,$D5,$D0 ; $0606
        DEFB    $F0,$EA,$BD,$8C,$C0,$10,$FB,$C9,$AA,$D0,$F2,$A0,$03,$BD,$8C,$C0 ; $0616
        DEFB    $10,$FB,$C9,$96,$D0,$E7,$A9,$00,$85,$27,$BD,$8C,$C0,$10,$FB,$2A ; $0626
        DEFB    $85,$26,$BD,$8C,$C0,$10,$FB,$25,$26,$99,$2C,$00,$45,$27,$88,$10 ; $0636
        DEFB    $E7,$A8,$D0,$B7,$BD,$8C,$C0,$10,$FB,$C9,$DE,$D0,$AE,$EA,$BD,$8C ; $0646
        DEFB    $C0,$10,$FB,$C9,$AA,$D0,$A4,$18,$60,$A2,$55,$A9,$00,$9D,$00,$0C ; $0656
        DEFB    $CA,$10,$FA,$A8,$4C,$AC,$FF,$86,$2B,$85,$2A,$CD,$78,$04,$F0,$53 ; $0666
        DEFB    $A9,$00,$85,$26,$AD,$78,$04,$85,$27,$38,$E5,$2A,$F0,$33,$B0,$07 ; $0676
        DEFB    $49,$FF,$EE,$78,$04,$90,$05,$69,$FE,$CE,$78,$04,$C5,$26,$90,$02 ; $0686
        DEFB    $A5,$26,$C9,$0C                                  ; $0696
        DEFW    MAIN_67_1                ; $069A
        DEFB    $A8,$38,$20,$BB,$D1,$B9,$DF,$D1,$20,$CA,$D1,$A5,$27,$18,$20,$BE ; $069C
        DEFB    $D1,$B9,$EB,$D1,$20,$CA,$D1,$E6,$26,$D0,$C3,$20,$CA,$D1,$18,$AD ; $06AC
        DEFB    $78,$04,$29,$03,$2A,$05,$2B,$AA,$BD,$80,$C0,$A6,$2B,$60,$A2,$11 ; $06BC
        DEFB    $CA,$D0,$FD,$E6,$46,$D0,$06,$E6,$47,$D0,$02,$C6,$47,$38,$E9,$01 ; $06CC
        DEFB    $D0,$EC                                          ; $06DC
        DEFW    MAIN_48                  ; $06DE
        DEFB    $30,$28,$24,$20,$1E,$1D,$1C,$1C,$1C,$1C,$1C,$70,$2C,$26,$22,$1F ; $06E0
        DEFB    $1E,$1D,$1C,$1C,$1C,$1C,$1C,$A9,$F3,$8D,$E9,$03,$A0,$00,$8C,$E8 ; $06F0
        DEFB    $03,$8C,$E0,$03,$C8,$8C,$E4,$03,$8C,$EB,$03,$A9,$60,$8D,$E6,$03 ; $0700
        DEFB    $A9,$0B,$8D,$E1,$03,$A9,$1E,$48,$08,$78,$20,$20,$D4,$90,$08,$20 ; $0710
        DEFB    $2D,$FF,$28,$68,$4C,$F7,$D1,$28,$EE,$E9,$03,$AE,$E1,$03,$E8,$E0 ; $0720
        DEFB    $10,$D0,$05,$A2,$00,$EE,$E0,$03,$8E,$E1,$03,$68,$38,$E9,$01,$D0 ; $0730
        DEFB    $D6,$A9,$08,$8D,$E9,$03,$60,$AF,$32,$F6,$FE,$3E,$02,$21,$F3,$FE ; $0740
        DEFB    $77,$23,$77,$23,$77,$18,$48,$61,$2E,$00,$22,$F3,$FE,$79,$FE,$02 ; $0750
        DEFB    $20,$0F,$2E,$08,$3A,$EF,$FE,$67,$22,$F6,$FE,$2A,$EA,$FE,$22,$F8 ; $0760
        DEFB    $FE,$21,$F6,$FE,$7E,$B7,$28,$21,$35,$3A,$EF,$FE,$23,$BE,$20,$19 ; $0770
        DEFB    $3A,$EA,$FE,$2A,$F8,$FE,$BD,$20,$10,$3A,$EB,$FE,$BC,$20,$0A,$24 ; $0780
        DEFB    $22,$F8,$FE,$AF,$32,$F5,$FE,$18,$06,$21,$01,$00,$22,$F5,$FE,$3A ; $0790
        DEFB    $EB,$FE,$5F,$B7,$1F,$21,$59,$B3,$85,$6F,$4E,$21,$F1,$FE,$7E,$36 ; $07A0
        DEFB    $01,$B7,$28,$1B,$2A,$EF,$FE,$7D,$BC,$20,$0D,$2A,$E0,$F3,$3A,$EA ; $07B0
        DEFB    $FE,$BD,$20,$04,$79,$BC,$28,$42,$3A,$F2,$FE,$B7,$C4,$34,$B3,$3A ; $07C0
        DEFB    $EF,$FE,$32,$F0,$FE,$47,$E6,$01,$3C,$32,$E4,$F3,$78,$E6,$0E,$87 ; $07D0
        DEFB    $87,$87,$2F,$C6,$61,$32,$E6,$F3,$3A,$EA,$FE,$FE,$23,$38,$0B,$6F ; $07E0
        DEFB    $3A,$FC,$FE,$FE,$8B,$20,$04,$7D,$D6,$23,$6F,$61,$22,$E0,$F3,$3A ; $07F0
        DEFB    $F5,$FE,$B7,$C4,$3B,$B3,$AF,$32,$F2,$FE,$7B,$21,$00 ; $0800  "u~7D;3/2r~{!"
        DEFB    $F8,$1F,$CB,$1D,$ED,$5B,$FA,$FE,$01,$80,$00,$3A,$F3,$FE,$B7,$20 ; $080D
        DEFB    $05,$3C,$32,$F2,$FE,$EB,$CD,$3C,$DF,$3A,$F4,$FE,$1F,$3E,$00,$30 ; $081D
        DEFB    $03,$CD,$34,$B3,$C3,$E0,$FE,$AF,$32,$F2,$FE,$3E,$02,$21,$3E,$01 ; $082D
        DEFB    $32,$EB,$F3,$21,$00                              ; $083D  "2ks!"
        DEFB    $08,$22,$E8,$F3,$21                              ; $0842
        DEFW    PRINT_STRING_1_13        ; $0847
        DEFB    $CD,$D2,$FE,$3A,$EA,$F3,$B7,$C8,$D1,$FE,$10,$20,$DB,$C3,$D9,$FE ; $0849
        DEFB    $00,$09,$03,$0C,$06,$0F,$01,$0A,$04,$0D,$07      ; $0859
        DEFW    WAIT_KEYPRESS_3          ; $0864
        DEFB    $0B,$05,$0E,$96,$97,$9A,$9B,$9D,$9E,$9F,$A6,$A7,$AB,$AC,$AD,$AE ; $0866
        DEFB    $AF,$B2,$B3,$B4,$B5,$B6,$B7,$B9,$BA,$BB,$BC,$BD,$BE,$BF,$CB,$CD ; $0876
        DEFB    $CE,$CF,$D3,$D6,$D7,$D9,$DA,$DB,$DC,$DD,$DE,$DF,$E5,$E6,$E7,$E9 ; $0886
        DEFB    $EA,$EB,$EC,$ED,$EE,$EF,$F2,$F3,$F4,$F5,$F6,$F7,$F9,$FA,$FB,$FC ; $0896
        DEFB    $FD,$FE,$FF                                      ; $08A6
        DEFW    MAIN                     ; $08A9
        DEFB    $98,$99,$02,$03,$9C,$04,$05,$06,$A0,$A1,$A2,$A3,$A4,$A5,$07,$08 ; $08AB
        DEFB    $A8,$A9,$AA,$09,$0A,$0B,$0C,$0D,$B0,$B1,$0E,$0F,$10,$11,$12,$13 ; $08BB
        DEFB    $B8,$14,$15,$16,$17,$18,$19,$1A,$C0,$C1,$C2,$C3,$C4,$C5,$C6,$C7 ; $08CB
        DEFB    $C8,$C9,$CA,$1B,$CC,$1C,$1D,$1E,$D0,$D1,$D2,$1F,$D4,$D5,$20,$21 ; $08DB
        DEFB    $D8,$22,$23,$24,$25,$26,$27,$28,$E0,$E1,$E2,$E3,$E4,$29,$2A,$2B ; $08EB
        DEFB    $E8,$2C,$2D,$2E,$2F,$30,$31,$32,$F0,$F1,$33,$34,$35,$36,$37,$38 ; $08FB
        DEFB    $F8,$39,$3A,$3B,$3C,$3D,$3E,$3F,$AD,$8B,$C0,$08,$78,$20,$20,$D4 ; $090B
        DEFB    $AD,$8B,$C0,$28,$60,$A0,$02,$8C,$F8,$06,$A0,$04,$8C,$F8,$04,$AD ; $091B
        DEFB    $E6,$03,$AA,$CD,$E7,$03,$F0,$1D,$8A,$A8,$AD,$E7,$03,$AA,$98,$48 ; $092B
        DEFB    $8D,$E7,$03,$BD,$8E,$C0,$A0,$08,$BD,$8C,$C0,$DD,$8C,$C0,$D0,$F6 ; $093B
        DEFB    $88,$D0,$F8,$68,$AA,$BD,$8E,$C0,$BD,$8C,$C0,$A0,$08,$BD,$8C,$C0 ; $094B
        DEFB    $48,$68,$48,$68,$8E,$F8,$05,$DD,$8C,$C0,$D0,$03,$88,$D0,$EE,$08 ; $095B
        DEFB    $BD,$89,$C0,$AD,$E8,$03,$85,$3E,$AD,$E9,$03,$85,$3F,$A9,$EF,$85 ; $096B
        DEFB    $46,$A9,$D8,$85,$47,$AD,$E4,$03,$CD,$E5,$03,$F0,$07,$8D,$E5,$03 ; $097B
        DEFB    $28,$A0,$00,$08,$6A,$90,$05,$BD,$8A,$C0,$B0,$03,$BD,$8B,$C0,$66 ; $098B
        DEFB    $35,$28,$08,$D0,$0B,$A0,$07,$20,$CA,$D1,$88,$D0,$FA,$AE,$F8,$05 ; $099B
        DEFB    $AD,$E0,$03,$20,$62,$D5,$AD,$EB,$03,$28,$D0,$11  ; $09AB
        DEFW    MAIN_70_2                ; $09B7
        DEFB    $F0,$0D,$A0,$12,$88,$D0,$FD,$E6,$46,$D0,$F7,$E6,$47,$D0,$F3,$6A ; $09B9
        DEFB    $08,$B0,$03,$20,$5F,$D1,$A0,$30,$8C,$78,$05,$AE,$F8,$05,$20,$03 ; $09C9
        DEFB    $D1,$90,$24,$CE,$78,$05,$10,$F3,$AD,$78,$04,$48,$A9,$60,$20,$94 ; $09D9
        DEFB    $D5,$CE,$F8,$06,$F0,$28,$A9,$04,$8D,$F8,$04,$A9,$00,$20,$62,$D5 ; $09E9
        DEFB    $68,$20,$62,$D5,$4C,$CF,$D4,$A4,$2E,$CC,$78,$04,$F0,$19,$AD,$78 ; $09F9
        DEFB    $04,$48,$98,$20,$94,$D5,$68,$CE,$F8,$04,$D0,$E5,$F0,$CA,$68,$A9 ; $0A09
        DEFB    $40,$28,$4C,$4E,$D5,$F0,$2A,$A5,$2F,$8D          ; $0A19  "@(LNUp*%/"
        DEFB    $E3,$03,$AD,$E2,$03,$F0,$08,$C5,$2F,$F0,$04,$A9,$20,$D0,$E8,$AD ; $0A23
        DEFB    $E1,$03,$A8,$B9,$AD,$D5,$C5,$2D,$D0,$9F,$28,$90,$19,$20,$99,$D0 ; $0A33
        DEFB    $08,$B0,$96,$28,$20,$83,$08,$18,$A9,$00,$24,$38,$8D,$EA,$03,$AE ; $0A43
        DEFB    $F8,$05,$BD,$88,$C0,$60,$20,$00,$D0,$90,$EC,$A9,$10,$D0,$EC,$0A ; $0A53
        DEFB    $20,$6A,$D5,$4E,$78,$04,$60,$85,$2E,$20,$8D,$D5,$B9,$78,$04,$24 ; $0A63
        DEFB    $35,$30,$03,$B9,$F8,$04,$8D,$78,$04,$A5,$2E,$24,$35,$30,$05,$99 ; $0A73
        DEFB    $F8,$04,$10,$03,$99,$78,$04,$4C,$6D,$D1,$8A,$4A,$4A,$4A,$4A,$A8 ; $0A83
        DEFB    $60,$48,$AD,$E4,$03,$6A,$66,$35,$20,$8D,$D5,$68,$0A,$24,$35,$30 ; $0A93
        DEFB    $05,$99,$F8,$04,$10,$03,$99,$78,$04,$60          ; $0AA3
        DEFW    MAILBOX_PUT_BYTE_2       ; $0AAD
        DEFB    $04,$06,$08,$0A,$0C                              ; $0AAF
        DEFW    MAIN_6                   ; $0AB4
        DEFB    $03,$05,$07,$09,$0B,$0D,$0F,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $0AB6
        DEFS    58, $00    ; $0AC6  fill
        DEFB    $AD,$81,$C0,$AD,$81,$C0,$8A,$4A,$4A,$4A,$4A,$A8,$48,$9D,$88,$C0 ; $0B00
        DEFB    $A9,$00,$99,$78,$04,$99,$F8,$04,$20,$2F,$FB,$20,$93,$FE,$20,$89 ; $0B10
        DEFB    $FE,$68,$A2,$FF,$9A,$C9,$06,$F0,$10,$A0,$00,$B9,$BD,$11,$F0,$06 ; $0B20
        DEFB    $20,$ED,$FD,$C8,$D0,$F5,$4C,$65,$FF,$A0,$0E,$B9,$DB,$11,$99,$FF ; $0B30
        DEFB    $0F,$88,$D0,$F7,$B9,$00,$12,$99                  ; $0B40
        DEFW    MAILBOX_PUT_BYTE_2       ; $0B48
        DEFB    $88,$D0,$F7,$A0,$F1,$B9,$FF,$12,$99,$FF,$02,$88,$D0,$F7,$8C,$B8 ; $0B4A
        DEFB    $03,$84,$3C,$88,$84,$3E,$A0,$C7,$84,$3D,$8C,$69,$10,$8D,$00,$C0 ; $0B5A
        DEFB    $A5,$3E,$F0,$18,$20,$79,$11,$85,$40,$86,$41,$20,$79,$11,$E0,$00 ; $0B6A
        DEFB    $F0,$1E,$C5,$40,$D0,$1A,$E4,$41,$F0,$1A,$D0,$14,$E6,$3E,$8C,$C8 ; $0B7A
        DEFB    $03,$A9,$00,$8D,$C7,$03,$8D,$DE,$03,$98,$18,$69,$20,$8D,$DF,$03 ; $0B8A
        DEFB    $A2,$00,$F0,$2D,$A2,$04,$A0,$05,$B1,$3C,$DD,$E9,$11,$D0,$09,$A0 ; $0B9A
        DEFB    $07,$B1,$3C,$DD,$ED,$11,$F0,$03,$CA,$D0,$EB,$E8,$E0,$02,$D0,$03 ; $0BAA
        DEFB    $EE,$B8,$03,$E0,$04,$D0,$0A,$A0,$0B,$B1,$3C      ; $0BBA
        DEFW    MAIN_70_2                ; $0BC5
        DEFB    $D0,$02,$A2,$06,$A4,$3D,$8A,$99,$F8,$02,$88,$C0,$C0,$D0,$8C,$0E ; $0BC7
        DEFB    $B8,$03,$A5,$3E                                  ; $0BD7
        DEFW    MAIN_70_2                ; $0BDB
        DEFB    $F0,$10,$A0,$00,$B9,$9E,$11,$F0,$06,$20,$ED,$FD,$C8,$D0,$F5,$4C ; $0BDD
        DEFB    $65,$FF,$A0,$10,$B9,$EF,$13,$99,$EF,$03,$88,$D0,$F7,$A9,$C3,$8D ; $0BED
        DEFB    $00,$10,$A9,$00,$8D,$01,$10,$A9,$FA,$8D,$02,$10,$8D,$8B,$C0,$A9 ; $0BFD
        DEFB    $0A,$85,$53,$A9,$D0,$85,$51,$A9,$00,$85,$52,$85,$50,$A2,$06,$20 ; $0C0D
        DEFB    $87,$11,$A9,$80,$20,$F9,$D1,$A9,$0A,$8D,$16,$D2,$A9,$FF,$8D,$49 ; $0C1D
        DEFB    $D5,$A9,$CB,$8D,$48,$D5,$A9,$98,$85,$53,$A9,$0A,$85,$51,$A2,$06 ; $0C2D
        DEFB    $20,$87,$11,$AD,$00,$89,$18,$69,$8F,$8D,$76,$11,$A9,$8D,$85,$53 ; $0C3D
        DEFB    $A9,$D5,$85,$51,$A9,$C0,$85,$50,$A2,$0B,$20,$87,$11,$A9,$80,$85 ; $0C4D
        DEFB    $53,$A9,$F3,$85,$51,$A9,$00,$85,$50,$A2,$0D,$20,$87,$11,$A0,$06 ; $0C5D
        DEFB    $B9,$97,$11,$99,$F9,$FF,$88,$D0,$F7,$98,$D2,$03,$A9,$00,$AA,$A8 ; $0C6D
        DEFB    $18,$71,$3C,$90,$01,$E8,$C8,$D0,$F7,$60,$A0,$00,$B1,$52,$91,$50 ; $0C7D
        DEFB    $88,$D0,$F9,$E6,$53,$E6,$51,$CA,$D0,$F0,$60,$C0,$03,$C0,$03,$C0 ; $0C8D
        DEFB    $03,$8D,$8D,$8D,$8D,$C3,$C1,$CE,$A7,$D4,$A0,$C6,$C9,$CE,$C4,$A0 ; $0C9D
        DEFB    $DA,$B8,$B0,$A0,$D3,$CF,$C6,$D4,$C3,$C1,$D2,$C4,$8D ; $0CAD  "Z80 SOFTCARD"
        DEFB    $8D,$8D,$00,$8D,$8D,$8D,$8D,$CD,$D5,$D3,$D4,$A0,$C2,$CF,$CF,$D4 ; $0CBA
        DEFB    $A0,$C6,$D2,$CF,$CD,$A0,$D3,$CC,$CF,$D4,$A0,$D3,$C9,$D8,$8D ; $0CCA  " FROM SLOT SIX"
        DEFB    $8D,$8D,$00,$AF,$32,$3E,$F0,$6F,$3A,$3D,$F0,$C6,$20,$67,$77,$18 ; $0CD9
        DEFB    $F2,$03,$18,$38,$48,$3C,$38,$18,$48,$00,$00,$00,$00,$00,$00,$00 ; $0CE9
        DEFS    266, $00    ; $0CF9  fill
PRINT_STRING_1_13:
        DEFS    125, $00    ; $0E03  fill
        DEFB    $14,$FB,$33,$FB,$33,$FB,$B5,$FC,$B5,$FC,$6F,$FE,$6F,$FE,$69,$FE ; $0E80
        DEFB    $69,$FE,$55,$FE,$55,$FE,$20,$1B,$AA,$D9,$D4,$A9,$A8,$1E,$BD,$0B ; $0E90
        DEFB    $0C,$A0,$00,$0C,$0B,$1D,$0E,$0F,$19,$1E,$1F,$1C,$0B,$5B,$00,$7F ; $0EA0
        DEFB    $02,$5C,$15,$09,$FF,$FF,$FF,$FF,$00,$00,$00,$00,$00,$00,$00,$00 ; $0EB0
        DEFB    $AD,$83,$C0,$AD,$83,$C0,$8D,$FF,$FF,$AD,$81,$C0,$20,$3F,$0E,$20 ; $0EC0
        DEFB    $58,$FF,$8D,$81,$C0,$78,$20,$4A,$FF,$4C,$C0,$03,$00,$20,$00,$00 ; $0ED0
        DEFB    $00,$00,$00,$00,$00,$00,$00,$60,$00,$00,$00,$00,$00,$00,$00,$00 ; $0EE0
        DEFB    $C0,$03,$C0,$03,$A6,$4C,$C0,$03,$4C,$C0,$03,$4C,$C0,$03,$C0,$03 ; $0EF0
        DEFB    $C3,$0C,$D6,$C3,$08,$D6,$7F,$00,$20,$20,$20,$20,$20,$20,$20,$20 ; $0F00
        DEFS    8, $20    ; $0F10  fill
        DEFB    "COPYRIGHT (C) 1979, DIGITAL RESEARCH  "    ; $0F18  string
        DEFB    $00    ; $0F3E  terminator
        DEFS    73, $00    ; $0F3F  fill
        DEFB    $08,$D3,$00,$00,$5F,$0E,$02,$18,$28,$3E,$20,$C5,$CD,$8C,$D3,$C1 ; $0F88
        DEFB    $C9,$3E,$0D,$CD,$93,$D3,$3E,$0A,$18,$F1,$C5,$CD,$99,$D3,$E1,$7E ; $0F98
        DEFB    $B7,$C8,$23,$E5,$CD,$8C,$D3,$E1,$18,$F5,$0E,$0D,$18,$03,$5F,$0E ; $0FA8
        DEFB    $0E,$C3,$05,$00,$0E,$10,$CD,$05,$00,$32,$A7,$DB,$3C,$C9,$AF,$32 ; $0FB8
        DEFB    $A6,$DB,$11,$86,$DB,$0E,$0F,$18,$ED,$11,$86,$DB,$0E,$11,$18,$E6 ; $0FC8
        DEFB    $0E,$12,$18,$E2,$0E,$13,$18,$D9,$11,$86,$DB,$0E,$14,$CD,$05,$00 ; $0FD8
        DEFB    $B7,$C9,$0E,$15,$18,$F7,$0E,$16,$18,$CC,$0E,$17,$18,$C3,$1E,$FF ; $0FE8
        DEFB    $0E,$20,$18,$BD,$CD,$F6,$D3,$87,$87,$87,$87,$21,$A8,$DB,$B6,$32 ; $0FF8
        DEFB    $04,$00,$C9,$3A,$A8,$DB,$32,$04,$00,$C9,$FE,$61,$D8,$FE,$7B,$D0 ; $1008
        DEFB    $E6,$5F,$C9,$3A,$64,$DB,$B7,$28,$52,$3A,$A8,$DB,$B7,$3E,$00 ; $1018  "f_I:d[7(R:([7>"
        DEFB    $C4,$B6,$D3,$11,$65,$DB,$CD,$CD,$D3,$28,$41,$3A,$74,$DB,$3D,$32 ; $1027
        DEFB    $85,$DB,$11,$65,$DB,$CD,$E3,$D3,$20,$32,$11,$07,$D3,$21,$80 ; $1037
        DEFW    MAIN                     ; $1046
        DEFB    $80,$00,$ED,$B0,$21,$73,$DB,$36,$00,$23,$35,$11,$65,$DB,$CD,$BC ; $1048
        DEFB    $D3,$28,$18,$3A,$A8,$DB,$B7,$C4,$B6,$D3,$21,$08,$D3,$CD,$A7,$D3 ; $1058
        DEFB    $CD,$9A,$D4,$28,$14,$CD,$B5,$D4,$C3,$31,$D6,$CD,$B5,$D4,$CD,$FC ; $1068
        DEFB    $D3,$0E,$0A,$11,$06,$D3,$CD,$05,$00,$21,$07,$D3,$46,$23,$78,$B7 ; $1078
        DEFB    $28,$08,$7E,$CD,$12,$D4,$77,$05,$18,$F3,$77,$21,$08,$D3,$22,$88 ; $1088
        DEFB    $D3,$C9,$0E,$0B,$CD,$05,$00,$B7,$C8              ; $1098
        DEFW    MAIN_6                   ; $10A1
        DEFB    $CD,$05,$00,$B7,$C9,$0E,$19,$C3,$05,$00,$11,$80,$00,$0E,$1A,$C3 ; $10A3
        DEFB    $05,$00,$21,$64,$DB,$7E,$B7,$C8,$36,$00,$AF,$CD,$B6,$D3,$11,$65 ; $10B3
        DEFB    $DB,$CD,$DC,$D3,$3A,$A8,$DB,$C3,$B6,$D3,$11,$DF,$D5,$21,$00,$DC ; $10C3
        DEFB    $06,$06,$1A,$BE,$C2,$7E,$D6,$13,$23,$10,$F7,$C9,$CD,$99,$D3,$2A ; $10D3
        DEFB    $8A,$D3,$7E,$FE,$20,$28,$0B,$B7,$28,$08,$E5,$CD,$8C,$D3,$E1,$23 ; $10E3
        DEFB    $18,$F0,$3E,$3F,$CD,$8C,$D3,$CD,$99,$D3,$CD,$B5,$D4,$C3,$31,$D6 ; $10F3
        DEFB    $1A,$B7,$C8,$FE,$20,$38,$D5,$C8,$FE,$3D,$C8,$FE,$5F,$C8,$FE,$2E ; $1103
        DEFB    $C8,$FE,$3A,$C8,$FE,$3B,$C8,$FE,$3C,$C8,$FE,$3E,$C8,$C9,$1A,$B7 ; $1113
        DEFB    $C8,$FE,$20,$C0,$13,$18,$F7,$85,$6F,$D0,$24,$C9,$3E,$00,$21,$86 ; $1123
        DEFB    $DB,$CD,$2A,$D5,$E5,$E5,$AF,$32,$A9,$DB,$2A,$88,$D3,$EB,$CD,$21 ; $1133
        DEFB    $D5,$EB,$22,$8A,$D3,$EB,$E1,$1A,$B7,$28,$0A,$DE,$40,$47,$13,$1A ; $1143
        DEFB    $FE,$3A,$28,$07,$1B,$3A,$A8,$DB,$77,$18,$06,$78,$32,$A9,$DB,$70 ; $1153
        DEFB    $13,$06,$08,$CD,$03,$D5,$28,$15,$23,$FE,$2A,$20,$04,$36,$3F,$18 ; $1163
        DEFB    $02,$77,$13,$10,$EE,$CD,$03,$D5,$28,$08,$13,$18,$F8,$23,$36,$20 ; $1173
        DEFB    $10,$FB,$06,$03,$FE,$2E,$20,$1B,$13,$CD,$03,$D5,$28,$15,$23,$FE ; $1183
        DEFB    $2A,$20,$04,$36,$3F,$18,$02,$77,$13,$10,$EE,$CD,$03,$D5,$28,$08 ; $1193
        DEFB    $13,$18,$F8,$23,$36,$20,$10,$FB,$06,$03,$23,$36,$00,$10,$FB,$EB ; $11A3
        DEFB    $22,$88,$D3                                      ; $11B3
        DEFW    MAIN_71_2                ; $11B6
        DEFB    $0B,$00,$23,$7E,$FE,$3F,$20,$01,$04,$0D,$20,$F6,$78,$B7,$C9,$44 ; $11B8
        DEFB    $49,$52,$20,$45,$52,$41,$20,$54,$59,$50,$45,$53,$41,$56,$45,$52 ; $11C8
        DEFB    $45,$4E,$20,$55,$53,$45,$52,$BD,$16              ; $11D8
        DEFW    MAIN                     ; $11E1
        DEFB    $4D,$40,$21,$C7,$D5,$0E,$00,$79,$FE,$06,$D0,$11,$87,$DB,$06,$04 ; $11E3
        DEFB    $1A,$BE,$20,$0B,$13,$23,$10,$F8,$1A,$FE,$20,$20,$05,$79,$C9,$23 ; $11F3
        DEFB    $10,$FD,$0C,$18,$E2,$AF,$32,$07,$D3,$31,$64,$DB,$C5,$79,$1F,$1F ; $1203
        DEFB    $1F,$1F,$E6,$0F,$5F,$CD,$F8,$D3,$CD,$B2,$D3,$32,$64,$DB,$C1,$79 ; $1213
        DEFB    $E6,$0F,$32,$A8,$DB,$CD,$B6,$D3,$3A,$07,$D3,$B7,$20,$16,$31,$64 ; $1223
        DEFB    $DB,$CD,$99,$D3,$CD,$A8,$D4,$C6,$41,$CD,$8C,$D3,$3E,$3E,$CD,$8C ; $1233
        DEFB    $D3,$CD,$1B,$D4,$11,$80,$00,$CD,$B0,$D4,$CD,$A8,$D4,$32,$A8,$DB ; $1243
        DEFB    $CD,$2F,$D5,$C4,$DF,$D4,$3A,$A9,$DB,$B7,$C2,$26,$D9,$CD,$E5,$D5 ; $1253
        DEFB    $21,$70,$D6,$5F,$16,$00,$19,$19,$7E,$23,$66,$6F,$E9,$18,$D7,$B1 ; $1263
        DEFB    $D7,$EE,$D7,$3A,$D8,$98,$D8,$0F,$D9,$26,$D9,$21,$F3,$76,$22,$00 ; $1273
        DEFB    $D3,$21,$00,$D3,$E9,$01,$8E,$D6,$C3,$A2,$D3,$52,$65,$61,$64,$20 ; $1283
        DEFB    $65,$72,$72,$6F,$72                              ; $1293
        DEFW    MAIN                     ; $1298
        DEFB    $9F,$D6,$C3,$A2,$D3,$4E,$6F,$20,$66,$69,$6C,$65,$00,$CD,$2F,$D5 ; $129A
        DEFB    $3A,$A9,$DB,$B7,$C2,$DF,$D4,$21,$87              ; $12AA
        DEFW    MAIN_71_1                ; $12B3
        DEFB    $0B,$00,$7E,$FE,$20,$28,$24,$23,$D6,$30,$FE,$0A,$D2,$DF,$D4,$57 ; $12B5
        DEFB    $78,$E6,$E0,$C2,$DF,$D4,$78,$07,$07,$07,$80,$DA,$DF,$D4,$80,$DA ; $12C5
        DEFB    $DF,$D4,$82,$DA,$DF,$D4,$47,$0D,$20,$D8,$C9,$7E,$FE,$20,$C2,$DF ; $12D5
        DEFB    $D4,$23,$0D,$20,$F6,$78,$C9,$21,$80,$00,$81,$CD,$2A,$D5,$7E,$C9 ; $12E5
        DEFB    $AF,$32,$86,$DB,$3A,$A9,$DB,$B7,$C8,$3D,$21,$A8,$DB,$BE,$C8,$C3 ; $12F5
        DEFB    $B6,$D3,$3A,$A9,$DB,$B7,$C8,$3D,$21,$A8,$DB,$BE,$C8,$3A,$A8,$DB ; $1305
        DEFB    $C3,$B6,$D3,$CD,$2F,$D5,$CD,$F5,$D6,$21,$87,$DB,$7E,$FE,$20,$20 ; $1315
        DEFB    $07,$06,$0B,$36,$3F,$23,$10,$FB,$1E,$00,$D5,$CD,$D1,$D3,$CC,$99 ; $1325
        DEFB    $D6,$28,$75,$3A,$A7,$DB,$0F,$0F,$0F,$E6,$60,$4F,$3E,$0A,$CD,$EC ; $1335
        DEFB    $D6,$17,$38,$5A,$D1,$7B,$1C,$D5,$E6,$03,$F5,$20,$14,$CD,$99,$D3 ; $1345
        DEFB    $C5,$CD,$A8,$D4,$C1,$C6,$41,$CD,$93,$D3,$3E,$3A,$CD,$93,$D3,$18 ; $1355
        DEFB    $08,$CD,$91,$D3,$3E,$3A,$CD,$93,$D3,$CD,$91,$D3,$06,$01,$78,$CD ; $1365
        DEFB    $EC,$D6,$E6,$7F,$FE,$20,$20,$13,$F1,$F5,$FE,$03,$20,$0B,$3E,$09 ; $1375
        DEFB    $CD,$EC,$D6,$E6,$7F,$FE,$20,$28,$14,$3E,$20,$CD,$93,$D3,$04,$78 ; $1385
        DEFB    $FE,$0C,$30,$09,$FE,$09,$20,$D6,$CD,$91,$D3,$18,$D1,$F1,$CD,$9A ; $1395
        DEFB    $D4,$20,$05,$CD,$D8,$D3,$18,$89,$D1,$C3,$38,$DA,$CD,$2F,$D5,$FE ; $13A5
        DEFB    $0B,$20                                          ; $13B5
        DEFW    MAIN_13                  ; $13B7
        DEFB    $E3,$D7,$CD,$A2,$D3,$CD,$1B,$D4,$21,$07,$D3,$35,$C2,$31,$D6,$23 ; $13B9
        DEFB    $7E,$FE,$59,$C2,$31,$D6,$23,$22,$88,$D3,$CD,$F5,$D6,$11,$86,$DB ; $13C9
        DEFB    $CD,$DC,$D3,$3C,$CC,$99,$D6,$C3,$38,$DA,$41,$6C,$6C,$20,$28,$79 ; $13D9
        DEFB    "/n)?"    ; $13E9  string
        DEFB    $00    ; $13ED  terminator
        DEFB    $CD,$2F,$D5,$C2,$DF,$D4,$CD,$F5,$D6,$CD,$C6,$D3,$28,$38,$CD,$99 ; $13EE
        DEFB    $D3,$21,$AA,$DB,$36,$FF,$21,$AA,$DB,$7E,$FE,$80,$38,$09,$E5,$CD ; $13FE
        DEFB    $E0,$D3,$E1,$20,$1A,$AF,$77,$34,$21,$80,$00,$CD,$2A,$D5,$7E,$FE ; $140E
        DEFB    $1A,$CA,$38,$DA,$CD,$8C,$D3,$CD,$9A,$D4,$C2,$38,$DA,$18,$D7,$3D ; $141E
        DEFB    $CA,$38,$DA,$CD,$88,$D6,$CD,$07,$D7,$C3,$DF,$D4,$CD,$A7,$D6,$F5 ; $142E
        DEFB    $CD,$2F,$D5,$C2,$DF,$D4,$CD,$F5,$D6,$11,$86,$DB,$D5,$CD,$DC,$D3 ; $143E
        DEFB    $D1,$CD,$EE,$D3,$28,$2F,$AF,$32,$A6,$DB,$F1,$6F,$26,$00 ; $144E  "QMnS(//2&[qo&"
        DEFB    $29,$11                                          ; $145C
        DEFW    MAIN                     ; $145E
        DEFB    $7C,$B5,$28,$16,$2B,$E5,$21,$80,$00,$19,$E5,$CD,$B0,$D4,$11,$86 ; $1460
        DEFB    $DB,$CD,$EA,$D3,$D1,$E1,$20,$0B,$18,$E6,$11,$86,$DB,$CD,$BC,$D3 ; $1470
        DEFB    $3C,$20,$06,$01,$8F,$D8,$CD,$A2,$D3,$CD,$AD,$D4,$C3,$38,$DA,$4E ; $1480
        DEFB    "o space"    ; $1490  string
        DEFB    $00    ; $1497  terminator
        DEFB    $CD,$2F,$D5,$C2,$DF,$D4,$3A,$A9,$DB,$F5,$CD,$F5,$D6,$CD,$D1,$D3 ; $1498
        DEFB    $20,$50,$21,$86,$DB,$11,$96                      ; $14A8
        DEFW    MAIN_71_1                ; $14AF
        DEFB    $10,$00,$ED,$B0,$2A,$88,$D3,$EB,$CD,$21,$D5,$FE,$3D,$28,$04,$FE ; $14B1
        DEFB    $5F,$20,$30,$EB,$23,$22,$88,$D3,$CD,$2F,$D5,$20,$26,$F1,$47,$21 ; $14C1
        DEFB    $A9,$DB,$7E,$B7,$28,$04,$B8,$70,$20,$19,$70,$AF,$32,$86,$DB,$CD ; $14D1
        DEFB    $D1,$D3,$28,$09,$11,$86,$DB,$CD,$F2,$D3,$C3,$38,$DA,$CD,$99,$D6 ; $14E1
        DEFB    $C3,$38,$DA,$CD,$07,$D7,$C3,$DF,$D4,$01,$03,$D9,$CD,$A2,$D3,$C3 ; $14F1
        DEFB    $38,$DA,$46,$69,$6C,$65,$20,$65,$78,$69,$73,$74,$73,$00 ; $1501  "8ZFile exists"
        DEFB    $CD,$A7,$D6,$FE,$10,$D2,$DF,$D4,$5F,$3A,$87,$DB,$FE,$20,$CA,$DF ; $150F
        DEFB    $D4,$CD,$F8,$D3,$C3,$3B,$DA,$CD,$CD,$D4,$3A,$87,$DB,$FE,$20,$20 ; $151F
        DEFB    $16,$3A,$A9,$DB,$B7,$CA,$3B,$DA,$3D,$F5,$CD,$B6,$D3,$F1,$32,$A8 ; $152F
        DEFB    $DB,$CD,$0B,$D4,$C3,$3B,$DA,$CD,$F6,$D3,$32,$43,$DB,$11,$8F,$DB ; $153F
        DEFB    $1A,$FE,$20,$C2,$DF,$D4,$D5,$CD,$F5,$D6,$D1,$21,$35,$DA,$01,$03 ; $154F
        DEFB    $00,$ED,$B0,$CD,$C6,$D3,$20,$0D,$CD,$F6,$D3,$B7,$CA,$1B,$DA,$AF ; $155F
        DEFB    $CD,$50,$DA,$18,$EE,$3A,$86,$DB,$B7,$28,$04,$3D,$CD,$B6,$D3,$0E ; $156F
        DEFB    $1F,$CD,$05,$00,$23,$23,$7E,$FE,$03,$20,$09,$23,$23,$23,$7E,$FE ; $157F
        DEFB    $8B,$CA,$54,$DA,$21                              ; $158F
        DEFW    MAIN                     ; $1594
        DEFB    $E5,$EB,$CD,$B0,$D4,$11,$86,$DB,$CD,$E3,$D3,$20,$11,$E1,$11,$80 ; $1596
        DEFB    $00,$19,$11,$00,$D3,$B7,$E5,$ED,$52,$E1,$30,$72,$18,$E2,$E1,$3D ; $15A6
        DEFB    $20,$6C,$CD,$4D,$DA,$CD,$07,$D7,$CD,$2F,$D5,$21,$A9,$DB,$E5,$7E ; $15B6
        DEFB    $32,$86,$DB,$3E,$10,$CD,$31,$D5,$E1,$7E,$32,$96,$DB,$AF,$32,$A6 ; $15C6
        DEFB    $DB,$11,$5C,$00,$21,$86                          ; $15D6
        DEFW    MAIN_71_1                ; $15DC
        DEFB    $21,$00,$ED,$B0,$21,$08,$D3,$7E,$B7,$28,$07,$FE,$20,$28,$03,$23 ; $15DE
        DEFB    $18,$F5,$06,$00,$11,$81,$00,$7E,$12,$B7,$28,$05,$04,$23,$13,$18 ; $15EE
        DEFB    $F6,$78,$32,$80,$00,$CD,$99,$D3,$CD,$AD,$D4,$CD,$FC,$D3,$CD ; $15FE
        DEFW    MAIN                     ; $160D
        DEFB    $31,$64,$DB,$CD,$0B,$D4,$CD,$B6,$D3,$C3,$31,$D6,$CD,$4D,$DA,$CD ; $160F
        DEFB    $07,$D7,$C3,$DF,$D4,$01,$2C,$DA,$CD,$A2,$D3,$18,$0C,$42,$61,$64 ; $161F
        DEFB    " load"    ; $162F  string
        DEFB    $00    ; $1634  terminator
        DEFB    $43,$4F,$4D,$CD,$07,$D7,$CD,$2F,$D5,$3A,$87,$DB,$D6,$20,$21,$A9 ; $1635
        DEFB    $DB,$B6,$C2,$DF,$D4,$C3,$31,$D6,$3A,$43,$DB,$5F,$C3,$F8,$D3,$2A ; $1645
        DEFB    $DE,$F3,$22,$26,$DB,$AF,$32,$92,$DB,$3E,$11,$32,$41,$DB,$11,$FF ; $1655
        DEFB    $D2,$AF,$32,$A6,$DB,$21,$96,$DB,$7E,$B7,$28,$06,$CD,$8D,$DA,$23 ; $1665
        DEFB    $18,$F6,$3E,$A6,$BD,$C2,$82,$DA,$CD,$C8,$DA,$20,$E4,$AF,$12,$CD ; $1675
        DEFB    $D4,$DA,$CD,$06,$DB,$C3,$B8,$D9,$E5,$F5,$CB,$3F,$CB,$3F,$C6,$03 ; $1685
        DEFB    $32,$42,$DB,$F1,$E6,$03,$87,$87,$21,$31,$DB,$85,$6F,$30,$01,$24 ; $1695
        DEFB    $06,$04,$3A,$42,$DB,$12,$1B,$7E,$23,$12,$1B,$3A,$41,$DB,$FE,$F0 ; $16A5
        DEFB    $CA,$24,$DA,$FE,$C0,$20,$02,$3E,$D0,$12,$3C,$1B,$32,$41,$DB,$10 ; $16B5
        DEFB    $E1,$E1,$C9,$E5,$D5,$21,$92,$DB,$34,$CD,$C6,$D3,$D1,$E1,$C9,$21 ; $16C5
        DEFB    $FF,$D2,$54,$5D,$1B,$1B,$1B,$1A,$B7,$28,$1E,$BE,$38,$0A,$20,$F4 ; $16D5
        DEFB    $1B,$1A,$13,$2B,$BE,$23,$30,$EC,$E5,$D5,$06,$03,$1A,$4E,$77,$79 ; $16E5
        DEFB    $12,$2B,$1B,$10,$F7,$D1,$E1,$18,$DB,$2B,$2B,$2B,$7E,$B7,$20,$D2 ; $16F5
        DEFB    $C9,$11,$FF,$D2,$1A,$B7,$C8,$32,$E0,$F3,$1B,$1A,$32,$E1,$F3,$1B ; $1705
        DEFB    $1A,$32,$E9,$F3,$1B,$3E,$01,$32,$EB,$F3,$21      ; $1715
        DEFW    PRINT_STRING_1_13        ; $1720
        DEFB    $22,$D0,$F3,$32,$00                              ; $1722  ""Ps2"
        DEFB    $00,$3A,$EA,$F3,$B7,$28,$DB,$C3,$93,$D9,$00,$09,$03,$0C,$06,$0F ; $1727
        DEFB    $01,$0A,$04,$0D,$07                              ; $1737
        DEFW    WAIT_KEYPRESS_3          ; $173C
        DEFB    $0B,$05,$0E,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $173E
        DEFS    24, $00    ; $174E  fill
        DEFB    "$$$     SUB"    ; $1766  string
        DEFB    $00    ; $1771  terminator
        DEFS    142, $00    ; $1772  fill
        DEFB    $BD,$16                                          ; $1800
        DEFW    MAIN                     ; $1802
        DEFB    $4D,$40,$C3,$11,$DC,$A5,$DC,$B2,$DC,$B7,$DC,$BC,$DC,$32,$8B,$E0 ; $1804
        DEFB    $ED,$53,$11,$DF,$7B,$32,$E3,$BF,$21,$00,$00,$22,$13,$DF,$ED,$73 ; $1814
        DEFB    $DD,$DE,$31,$0F,$DF,$AF,$32,$ED,$BF,$32,$EB,$BF,$32,$87,$DF,$21 ; $1824
        DEFB    $45,$DF,$E5,$79,$FE,$29,$D0,$FE,$0C,$30,$03,$32,$83,$E0,$4B,$21 ; $1834
        DEFB    $53,$DC,$5F,$16,$00,$19,$19,$5E,$23,$56,$2A,$11,$DF,$EB,$E9,$03 ; $1844
        DEFB    $FA,$9C,$DE,$7D,$DD,$A1,$DE,$12,$FA,$0F,$FA,$A6,$DE,$BD,$DE,$C2 ; $1854
        DEFB    $DE,$C7,$DE,$C9,$DD,$CD,$DE,$A3,$BE,$A8,$BE,$47,$BE,$C0,$BE,$C6 ; $1864
        DEFB    $BE,$CC,$BE,$EB,$BE,$FC,$BE,$05,$BF,$0B,$BF,$11,$BF,$17,$BF,$20 ; $1874
        DEFB    $BF,$25,$BF,$2B,$BF,$32,$BF,$9B,$B7,$37,$BF,$3C,$BF,$45,$BF,$4C ; $1884
        DEFB    $BF,$5F,$BF,$65,$BF,$6B,$BF,$31,$BE,$71,$BF,$D3,$DE,$D3,$DE,$92 ; $1894
        DEFB    $BF,$21,$D5,$DC,$CD,$F0,$DC,$FE,$03,$C2,$41,$DF,$18,$10,$21,$E0 ; $18A4
        DEFB    $DC,$18,$08,$21,$EC,$DC,$18,$03,$21,$E7,$DC,$CD,$F0,$DC,$C3,$00 ; $18B4
        DEFB    $00,$42,$64,$6F,$73,$20,$45,$72,$72,$20,$4F,$6E,$20,$20,$3A,$20 ; $18C4
        DEFB    $24,$42,$61,$64,$20,$53,$65,$63,$74,$6F,$72,$24,$53,$65,$6C,$65 ; $18D4
        DEFB    $63,$74,$24,$46,$69,$6C,$65,$20,$52,$2F,$4F,$24,$E5,$CD,$B3,$DD ; $18E4
        DEFB    $3A,$10,$DF,$C6,$41,$32,$D1,$DC,$01,$C5,$DC,$CD,$BC,$DD,$C1,$CD ; $18F4
        DEFB    $BC,$DD,$21,$DC,$DE,$7E,$36,$00                  ; $1904  "<]!\^~6"
        DEFB    $B7,$C0,$C3,$09,$FA,$CD,$06,$DD,$CD,$36,$DF,$D8,$F5,$4F,$CD,$7D ; $190C
        DEFB    $DD,$F1,$C9,$3A,$DC,$DE,$B7,$20,$1A,$CD,$06,$FA,$E6,$01,$C8,$CD ; $191C
        DEFB    $09,$FA,$FE,$13,$20,$0A,$CD,$09,$FA,$FE,$03,$CA,$00,$00,$AF,$C9 ; $192C
        DEFB    $32,$DC,$DE,$3E,$01,$C9,$3A,$D8,$DE,$B7,$20,$13,$C5,$CD,$1F,$DD ; $193C
        DEFB    $C1,$C5,$CD,$0C,$FA,$C1,$C5,$3A,$DB,$DE,$B7,$C4,$0F,$FA,$C1,$32 ; $194C
        DEFB    $8B,$E0,$CD,$D5,$B5,$C3,$81,$DF,$32,$83,$E0,$FE,$0A,$C0,$36,$00 ; $195C
        DEFB    $C9,$79,$CD,$36,$DF,$30,$0A,$F5,$0E,$5E,$CD,$42,$DD,$F1,$F6,$40 ; $196C
        DEFB    $4F,$79,$FE,$09,$20,$C0,$0E,$20,$CD,$42,$DD,$3A,$DA,$DE,$E6,$07 ; $197C
        DEFB    $20,$F4,$C9,$CD,$97,$DD,$0E,$20,$CD,$0C,$FA,$0E,$08,$C3,$0C,$FA ; $198C
        DEFB    $0E,$23,$CD,$42,$DD,$CD,$B3,$DD,$3A,$DA,$DE,$21,$D9,$DE,$BE,$D0 ; $199C
        DEFB    $0E,$20,$CD,$42,$DD,$18,$F1,$0E,$0D,$CD,$42,$DD,$0E,$0A,$18,$86 ; $19AC
        DEFB    $0A,$FE,$24,$C8,$03,$C5,$4F,$CD,$7D,$DD,$C1,$18,$F3,$3A,$DA,$DE ; $19BC
        DEFB    $32,$D9,$DE,$2A,$11,$DF,$4E,$23,$E5,$06,$00,$C5,$E5,$CD,$06,$DD ; $19CC
        DEFB    $E6,$7F,$E1,$C1,$FE,$0D,$CA,$95,$DE,$FE,$0A,$CA,$95,$DE,$FE,$08 ; $19DC
        DEFB    $20,$0D,$78,$B7,$28,$E5,$05,$3A,$DA,$DE,$32,$D8,$DE,$18,$4D,$FE ; $19EC
        DEFB    $7F,$20,$09,$78,$B7,$28,$D4,$7E,$05,$2B,$18,$76,$FE,$05,$20,$0B ; $19FC
        DEFB    $C5,$E5,$CD,$B3,$DD,$AF,$32,$D9,$DE,$18,$C2,$FE,$10,$20,$0B,$E5 ; $1A0C
        DEFB    $21,$DB,$DE,$3E,$01,$96,$77,$E1,$18,$B1,$FE,$18,$20,$10,$E1,$3A ; $1A1C
        DEFB    $D9,$DE,$21,$DA,$DE,$BE,$30,$95,$35,$CD,$8F,$DD,$18,$F1,$FE,$15 ; $1A2C
        DEFB    $20,$06,$CD,$9C,$DD,$E1,$18,$85,$FE,$12,$20,$33,$C5,$CD,$9C,$DD ; $1A3C
        DEFB    $C1,$E1,$E5,$C5,$78,$B7,$28,$0C,$23,$4E,$05,$C5,$E5,$CD,$6D,$DD ; $1A4C
        DEFB    $E1,$C1,$18,$F0,$E5,$3A,$D8,$DE,$B7,$CA,$D9,$DD,$21,$DA,$DE,$96 ; $1A5C
        DEFB    $32,$D8,$DE,$CD,$8F,$DD,$21,$D8,$DE,$35,$20,$F7,$C3,$D9,$DD,$23 ; $1A6C
        DEFB    $77,$04,$C5,$E5,$4F,$CD,$6D,$DD,$E1,$C1,$7E,$FE,$03,$78,$20,$05 ; $1A7C
        DEFB    $FE,$01,$CA,$00,$00,$B9,$DA,$D7,$DD,$E1,$70,$0E,$0D,$C3,$42,$DD ; $1A8C
        DEFB    $CD,$11,$DD,$18,$2F,$CD,$15,$FA,$18,$2A,$79,$3C,$28,$07,$3C,$CA ; $1A9C
        DEFB    $06,$FA,$C3,$0C,$FA,$CD,$06,$FA,$B7,$CA,$63,$DF,$CD,$09,$FA,$18 ; $1AAC
        DEFB    $13,$3A,$03,$00,$18,$0E,$21,$03,$00,$71,$C9,$EB,$4D,$44,$C3,$BC ; $1ABC
        DEFB    $DD,$CD,$1F,$DD,$32,$13,$DF,$C9,$3E,$01,$18,$F8,$00,$00,$00,$00 ; $1ACC
        DEFS    57, $00    ; $1ADC  fill
        DEFB    $21,$0B,$DC,$5E,$23,$56,$EB,$32,$83,$E0,$E9,$32,$83,$E0,$CD,$27 ; $1B15
        DEFB    $FA,$18,$06,$32,$83,$E0,$CD,$2A,$FA,$B7,$28,$10,$21,$09,$DC,$18 ; $1B25
        DEFB    $E2,$32,$8B,$E0,$C3,$C0,$B5,$32,$83,$E0,$ED,$B0,$32,$8B,$E0,$C9 ; $1B35
        DEFB    $32,$8B,$E0,$3A,$EB,$BF,$B7,$28,$15,$2A,$11,$DF,$36,$00,$3A,$ED ; $1B45
        DEFB    $BF,$B7,$28,$0A,$77,$3A,$EC,$BF,$32,$E3,$BF,$CD,$47,$BE,$32,$83 ; $1B55
        DEFB    $E0,$3A,$87,$DF,$B7,$28,$0C,$ED,$5B,$85,$DF,$21,$88,$DF,$01,$24 ; $1B65
        DEFB    $00,$ED,$B0,$2A,$13,$DF,$7D,$44,$ED,$7B,$DD,$DE,$32,$83,$E0,$C9 ; $1B75
        DEFS    39, $00    ; $1B85  fill
        DEFB    $8D,$83,$C0,$A2,$AC,$2C,$A2,$AA,$88,$B1,$3E,$4A,$3E,$56,$0B,$4A ; $1BAC
        DEFB    $3E,$56,$0B,$99,$00,$09,$E8,$D0,$EF,$98,$D0,$EA,$4C,$E5,$FF,$8D ; $1BBC
        DEFB    $83,$C0,$A0,$00,$A2,$56,$CA,$30,$FB,$B9,$00,$09,$5E,$00,$0C,$2A ; $1BCC
        DEFB    $5E,$00,$0C,$2A,$91,$3E,$C8,$D0,$ED,$8D,$8B,$C0,$60,$00,$00,$00 ; $1BDC
        DEFS    20, $00    ; $1BEC  fill
        DEFB    $FE,$0D,$28,$0E,$FE,$0A,$28,$0A,$FE,$09,$28,$06,$FE,$08,$28,$02 ; $1C00
        DEFB    $FE,$20,$C3,$81,$DF,$79,$21,$DA,$DE,$FE,$7F,$C8,$34,$FE,$20,$D0 ; $1C10
        DEFB    $35,$7E,$B7,$C8,$79,$FE,$08,$C2,$64,$DD,$35,$C9,$3A,$10,$DF,$4F ; $1C20
        DEFB    $CD,$1B,$FA,$7C,$B5,$C8,$5E,$23,$56,$23,$22,$C0,$BF,$23,$23,$22 ; $1C30
        DEFB    $C2,$BF,$23,$23,$22,$C4,$BF,$23,$23,$ED,$53,$DD,$BF,$11,$C6 ; $1C40
        DEFW    MAIN_69_1                ; $1C4F
        DEFB    $08,$00,$ED,$B0,$2A,$C8,$BF,$11,$CE              ; $1C51
        DEFW    MAIN_69_1                ; $1C5A
        DEFB    $0F,$00,$ED,$B0,$2A,$D3,$BF,$7C,$21,$EA,$BF,$36,$FF,$B7,$28,$02 ; $1C5C
        DEFB    $36,$00,$3E,$FF,$B7,$C9,$CD,$18,$FA,$AF,$2A,$C2,$BF,$77,$23,$77 ; $1C6C
        DEFB    $2A,$C4,$BF,$77,$23,$77,$C9,$2A,$F7,$BF,$0E,$02,$CD,$5F,$B7,$22 ; $1C7C
        DEFB    $F2,$BF,$22,$F9,$BF,$21,$F2,$BF,$4E,$23,$46,$2A,$C4,$BF,$5E,$23 ; $1C8C
        DEFB    $56,$2A,$C2,$BF,$7E,$23,$66,$6F,$79,$93,$78,$9A,$30,$0E,$E5,$2A ; $1C9C
        DEFB    $CE,$BF,$7B,$95,$5F,$7A,$9C,$57,$E1,$2B,$18,$EC,$E5,$2A,$CE,$BF ; $1CAC
        DEFB    $19,$38,$0B,$79,$95,$78,$9C,$38,$05,$EB,$E1,$23,$18,$EE,$E1,$C5 ; $1CBC
        DEFB    $D5,$E5,$EB,$2A,$DB,$BF,$19,$44,$4D,$CD,$1E,$FA,$D1,$2A,$C2,$BF ; $1CCC
        DEFB    $73,$23,$72,$D1,$2A,$C4,$BF,$73,$23,$72,$C1,$79,$93,$4F,$78,$9A ; $1CDC
        DEFB    $47,$2A,$DD,$BF,$EB,$CD,$30,$FA,$4D,$44,$C3,$21,$FA,$21,$D0,$BF ; $1CEC
        DEFB    $4E,$3A,$F0,$BF,$B7,$1F,$0D,$20,$FB,$47,$3E,$08,$96,$4F,$3A,$EF ; $1CFC
        DEFB    $BF,$0D,$28,$04,$B7,$17,$18,$F9,$80,$C9,$2A,$11,$DF,$11,$10,$00 ; $1D0C
        DEFB    $19,$09,$3A,$EA,$BF,$B7,$28,$04,$6E,$26,$00,$C9,$09,$5E,$23,$56 ; $1D1C
        DEFB    $EB,$C9,$CD,$B9,$B6,$4F,$06,$00,$CD,$D6,$B6,$22,$F2,$BF,$C9,$2A ; $1D2C
        DEFB    $F2,$BF,$7D,$B4,$C9,$3A,$D0,$BF,$2A,$F2,$BF,$29,$3D,$20,$FC,$22 ; $1D3C
        DEFB    $F4,$BF,$3A,$D1,$BF,$4F,$3A,$F0,$BF,$A1,$B5,$6F,$22,$F2,$BF,$C9 ; $1D4C
        DEFB    $2A,$11,$DF,$11,$0C,$00,$19,$C9,$2A,$11,$DF,$11,$0F,$00,$19,$EB ; $1D5C
        DEFB    $21,$11,$00,$19,$C9,$CD,$24,$B7,$7E,$32,$F0,$BF,$EB,$7E,$32,$EE ; $1D6C
        DEFB    $BF,$CD,$1C,$B7,$3A,$D2,$BF,$A6,$32,$EF,$BF,$C9,$CD,$24,$B7,$3A ; $1D7C
        DEFB    $E2,$BF,$FE,$02,$20,$01,$AF,$4F,$3A,$F0,$BF,$81,$77,$EB,$3A,$EE ; $1D8C
        DEFB    $BF,$77,$C9,$0C,$0D,$C8,$CB,$3C,$CB,$1D,$18,$F8,$0E,$80,$2A,$C6 ; $1D9C
        DEFB    $BF,$AF,$86,$23,$0D,$20,$FB,$C9,$0C,$0D,$C8,$29,$18,$FB,$C5,$3A ; $1DAC
        DEFB    $10,$DF,$4F,$21,$01,$00,$CD,$74,$B7,$C1,$79,$B5,$6F,$78,$B4,$67 ; $1DBC
        DEFB    $C9,$2A,$BA,$BF,$3A,$10,$DF,$4F,$CD,$5F,$B7,$7D,$E6,$01,$C9,$21 ; $1DCC
        DEFB    $BA,$BF,$4E,$23,$46,$CD,$7A,$B7,$22,$BA,$BF,$2A,$D5,$BF,$23,$EB ; $1DDC
        DEFB    $2A,$C0,$BF,$73,$23,$72,$C9,$CD,$CD,$B7,$11,$09,$00,$19,$7E,$17 ; $1DEC
        DEFB    $D0,$21,$0F,$DC,$C3,$18,$DF,$CD,$8D,$B7,$C8,$21,$0D,$DC,$C3,$18 ; $1DFC
        DEFB    $DF,$2A,$C6,$BF,$3A,$F6,$BF,$85,$6F,$D0,$24,$C9,$2A,$11,$DF,$11 ; $1E0C
        DEFB    $0E,$00,$19,$7E,$C9,$CD,$A3,$BF,$CD,$EB,$B7,$CD,$77,$BE,$C9,$CD ; $1E1C
        DEFB    $D8,$B7,$36,$00,$C9,$CD,$D8,$B7,$F6,$80,$77,$C9,$2A,$F7,$BF,$EB ; $1E2C
        DEFB    $2A,$C0,$BF,$7B,$96,$23,$7A,$9E,$C9,$CD,$F8,$B7,$D8,$13,$72,$2B ; $1E3C
        DEFB    $73,$C9,$EB,$B7,$ED,$52,$C9,$0E,$FF,$2A,$F9,$BF,$EB,$2A,$D9,$BF ; $1E4C
        DEFB    $CD,$0E,$B8,$D0,$C5,$CD,$68,$B7,$2A,$CA,$BF,$EB,$2A,$F9,$BF,$19 ; $1E5C
        DEFB    $C1,$0C,$28,$0A,$BE,$C8,$CD,$F8,$B7,$D0,$CD,$9B,$B7,$C9,$77,$C9 ; $1E6C
        DEFB    $CD,$13,$B8,$CD,$54,$B8                          ; $1E7C
        DEFW    MAIN_6                   ; $1E82
        DEFB    $CD,$28,$DF,$18,$06,$CD,$54,$B8,$CD,$20,$DF,$21,$BE,$BF,$18,$03 ; $1E84
        DEFB    $21,$C6,$BF,$4E,$23,$46,$C3,$24,$FA,$2A,$C6,$BF,$ED,$5B,$BE ; $1E94
        DEFW    MAIN_69_1                ; $1EA3
        DEFB    $80,$00,$CD,$3C,$DF,$C9,$21,$F7,$BF,$7E,$23,$BE,$C0,$3C,$C9,$21 ; $1EA5
        DEFB    $FF,$FF,$22,$F7,$BF,$C9,$2A,$D5,$BF,$EB,$2A,$F7,$BF,$23,$22,$F7 ; $1EB5
        DEFB    $BF,$CD,$0E,$B8,$30,$02,$18,$E7,$3A,$F7,$BF,$E6,$03,$06,$05,$87 ; $1EC5
        DEFB    $10,$FD,$32,$F6,$BF,$B7,$C0,$C5,$CD,$43,$B6,$CD,$49,$B8,$C1,$C3 ; $1ED5
        DEFB    $15,$B8,$79,$E6,$07,$3C,$5F,$57,$79,$0F,$0F,$0F,$E6,$1F,$4F,$78 ; $1EE5
        DEFB    $87,$87,$87,$87,$87,$B1,$4F,$78,$0F,$0F,$0F,$E6,$1F,$47,$2A,$CC ; $1EF5
        DEFB    $BF,$09,$7E,$07,$1D,$20,$FC,$C9,$D5,$CD,$A7,$B8,$E6,$FE,$C1,$B1 ; $1F05
        DEFB    $0F,$15,$20,$FC,$77,$C9,$CD,$CD,$B7,$11,$10,$00,$19,$C5,$0E,$11 ; $1F15
        DEFB    $D1,$0D,$C8,$D5,$3A,$EA,$BF,$B7,$28,$07,$C5,$E5,$4E,$06,$00,$18 ; $1F25
        DEFB    $06,$0D,$C5,$4E,$23,$46,$E5,$79,$B0,$28,$0A,$2A,$D3,$BF,$7D,$91 ; $1F35
        DEFB    $7C,$98,$D4,$CD,$B8,$E1,$23,$C1,$18,$D6,$2A,$D3,$BF,$0E,$03,$CD ; $1F45
        DEFB    $5F,$B7,$23,$44,$4D,$2A,$CC,$BF,$36,$00          ; $1F55  "_7#DM*L?6"
        DEFB    $23,$0B,$78,$B1,$20,$F8,$2A,$D7,$BF,$EB,$2A,$CC,$BF,$73,$23,$72 ; $1F5F
        DEFB    $CD,$32,$B6,$2A,$C0,$BF,$36,$03,$23,$36,$00,$CD,$74,$B8,$0E,$FF ; $1F6F
        DEFB    $CD,$7B,$B8,$CD,$6B,$B8,$C8,$CD,$CD,$B7,$3E,$E5,$BE,$28,$EF,$3A ; $1F7F
        DEFB    $0F,$DF,$BE,$20,$0A,$23,$7E,$D6,$24,$20,$04,$3D,$32,$13,$DF ; $1F8F
        DEFW    MAIN_6                   ; $1F9E
        DEFB    $CD,$DB,$B8,$CD,$05,$B8,$C3,$3D,$B9,$3A,$E1,$BF,$C3,$D0,$DE,$C5 ; $1FA0
        DEFB    $F5,$3A,$D2,$BF,$2F,$47,$79,$A0,$4F,$F1,$A0,$91,$E6,$1F,$C1,$C9 ; $1FB0
        DEFB    $3E,$FF,$32,$E1,$BF,$21,$E5,$BF,$71,$2A,$11,$DF,$22,$E6,$BF,$CD ; $1FC0
        DEFB    $74,$B8,$CD,$32,$B6,$0E,$00,$CD,$7B,$B8,$CD,$6B,$B8,$28,$52,$2A ; $1FD0
        DEFB    $E6,$BF,$EB,$1A,$FE,$E5,$28,$07,$D5,$CD,$F8,$B7,$D1,$30,$42,$CD ; $1FE0
        DEFB    $CD,$B7,$3A,$E5,$BF,$4F,$06,$00,$79,$B7,$28,$24,$1A,$FE,$3F,$28 ; $1FF0
        DEFB    $19,$78,$FE,$0D,$28,$14,$FE,$0C,$1A,$28,$07,$96,$E6,$7F,$20,$C5 ; $2000
        DEFB    $18,$08,$C5,$4E,$CD,$6F,$B9,$C1,$20,$BB,$13,$23,$04,$0D,$18,$D8 ; $2010
        DEFB    $3A,$F7,$BF,$E6,$03,$32,$13,$DF,$21,$E1,$BF,$7E,$17,$D0,$AF,$77 ; $2020
        DEFB    $C9,$CD,$74,$B8,$3E,$FF,$C3,$D0,$DE,$CD,$C3,$B7,$0E,$0C,$CD,$80 ; $2030
        DEFB    $B9,$CD,$6B,$B8,$C8,$CD,$B3,$B7,$CD,$CD,$B7,$36,$E5,$0E,$00,$CD ; $2040
        DEFB    $DB,$B8,$CD,$3C,$B8,$CD,$95,$B9,$18,$E7,$50,$59,$79,$B0,$28,$0B ; $2050
        DEFB    $0B,$D5,$C5,$CD,$A7,$B8,$1F,$30,$1A,$C1,$D1,$2A,$D3,$BF,$7B,$95 ; $2060
        DEFB    $7A,$9C,$30,$17,$13,$C5,$D5,$42,$4B,$CD,$A7,$B8,$1F,$30,$04,$D1 ; $2070
        DEFB    $C1,$18,$D9,$17,$3C,$CD,$D5,$B8,$E1,$D1,$C9,$79,$B0,$20,$CD,$21 ; $2080
        DEFB    $00,$00,$C9,$0E,$00,$1E,$20,$D5,$06,$00,$2A,$11,$DF,$09,$EB,$CD ; $2090
        DEFB    $CD,$B7,$C1,$06,$00,$EB,$ED,$B0,$CD,$43,$B6,$C3,$3C,$B8,$CD,$C3 ; $20A0
        DEFB    $B7,$0E,$0C,$CD,$80,$B9,$2A,$11,$DF,$7E,$11,$10,$00,$19,$77,$CD ; $20B0
        DEFB    $6B,$B8,$C8,$CD,$B3,$B7,$0E,$10,$1E,$0C,$CD,$57,$BA,$CD,$95,$B9 ; $20C0
        DEFB    $18,$ED,$0E,$0C,$CD,$80,$B9,$CD,$6B,$B8,$C8,$0E,$00,$1E,$0C,$CD ; $20D0
        DEFB    $57,$BA,$CD,$95,$B9,$18,$F0,$0E,$0F,$CD,$80,$B9,$CD,$6B,$B8,$C8 ; $20E0
        DEFB    $CD,$1C,$B7,$7E,$F5,$E5,$CD,$CD,$B7,$ED,$5B,$11,$DF,$01,$20,$00 ; $20F0
        DEFB    $D5,$ED,$B0,$CD,$F1,$B7,$D1,$21,$0C,$00,$19,$4E,$21,$0F,$00,$19 ; $2100
        DEFB    $46,$E1,$F1,$77,$79,$BE,$78,$28,$06,$3E,$00,$38,$02,$3E,$80,$2A ; $2110
        DEFB    $11,$DF,$11,$0F,$00,$19,$77,$C9,$7E,$23,$B6,$2B,$C0,$1A,$77,$13 ; $2120
        DEFB    $23,$1A,$77,$1B,$2B,$C9,$AF,$32,$13,$DF,$32,$F7,$BF,$32,$F8,$BF ; $2130
        DEFB    $CD,$8D,$B7,$C0,$CD,$D8,$B7,$E6,$80,$C0,$0E,$0F,$CD,$80,$B9,$CD ; $2140
        DEFB    $6B,$B8                                          ; $2150
        DEFW    MAIN_70_1                ; $2152
        DEFB    $10,$00,$CD,$CD,$B7,$09,$EB,$2A,$11,$DF,$09,$0E,$10,$3A,$EA,$BF ; $2154
        DEFB    $B7,$28,$10,$7E,$B7,$1A,$20,$01,$77,$B7,$20,$02,$7E,$12,$BE,$20 ; $2164
        DEFB    $35,$18,$13,$CD,$E8,$BA,$EB,$CD,$E8,$BA,$EB,$1A,$BE,$20,$27,$13 ; $2174
        DEFB    $23,$1A,$BE,$20,$21,$0D,$13,$23,$0D,$20          ; $2184
        DEFW    MAIN_71                  ; $218E
        DEFB    $EC,$FF,$09,$EB,$09,$1A,$BE,$38,$09,$77,$01,$03,$00,$09,$EB,$09 ; $2190
        DEFB    $7E,$12,$3E,$FF,$32,$DF,$BF,$C3,$68,$BA,$21,$13,$DF,$35,$C9,$CD ; $21A0
        DEFB    $C3,$B7,$2A,$11,$DF,$E5,$21,$B9,$BF,$22,$11,$DF  ; $21B0
        DEFW    MAIN_6                   ; $21BC
        DEFB    $CD,$80,$B9,$CD,$6B,$B8,$E1,$22,$11,$DF,$C8,$EB,$21,$0F,$00,$19 ; $21BE
        DEFB    $0E,$11,$AF,$77,$23,$0D,$20,$FB,$21,$0D,$00,$19,$77,$CD,$05,$B8 ; $21CE
        DEFB    $CD,$53,$BA,$C3,$F1,$B7,$AF,$32,$DF,$BF,$CD,$F6,$BA,$CD,$6B,$B8 ; $21DE
        DEFB    $C8,$2A,$11,$DF,$01,$0C,$00,$09,$7E,$3C,$E6,$1F,$77,$28,$0D,$47 ; $21EE
        DEFB    $3A,$D2,$BF,$A0,$21,$DF,$BF,$A6,$28,$0C,$18      ; $21FE
        DEFW    MAIN_18                  ; $2209
        DEFB    $02,$00,$09,$34,$7E,$E6,$0F,$28,$24,$0E,$0F,$CD,$80,$B9,$CD,$6B ; $220B
        DEFB    $B8,$20,$10,$3A,$E0,$BF,$3C,$28,$14,$CD,$6F,$BB,$CD,$6B,$B8,$28 ; $221B
        DEFB    $0C,$18,$03,$CD,$B0,$BA,$CD,$31,$B7,$AF,$C3,$D0,$DE,$CD,$D4,$DE ; $222B
        DEFB    $C3,$F1,$B7,$3E,$01,$32,$E2,$BF,$3E,$FF,$32,$E0,$BF,$CD,$31,$B7 ; $223B
        DEFB    $3A,$F0,$BF,$21,$EE,$BF,$BE,$38,$11,$FE,$80,$20,$21,$CD,$A4,$BB ; $224B
        DEFB    $AF,$32,$F0,$BF,$3A,$13,$DF,$B7,$20,$14,$CD,$EE,$B6,$CD,$FB,$B6 ; $225B
        DEFB    $28,$0C,$CD,$01,$B7,$CD,$51,$B6,$CD,$20,$DF,$C3,$48,$B7,$C3,$D4 ; $226B
        DEFB    $DE,$3E,$01,$32,$E2,$BF,$3E,$00,$32,$E0,$BF,$CD,$C3,$B7,$2A,$11 ; $227B
        DEFB    $DF,$CD,$B6,$B7,$CD,$31,$B7,$3A,$F0,$BF,$FE,$80  ; $228B  "_M67M17:p?~"
        DEFB    $D2,$D4,$DE,$CD,$EE,$B6,$CD,$FB,$B6,$0E,$00,$20,$43,$CD,$B9,$B6 ; $2297
        DEFB    $32,$E4                                          ; $22A7
        DEFW    MAIN_69_1                ; $22A9
        DEFB    $00,$00,$B7,$28,$07,$4F,$0B,$CD,$D6,$B6,$44,$4D,$CD,$1A,$BA,$7D ; $22AB
        DEFB    $B4,$20,$05,$3E,$02,$C3,$D0,$DE,$22,$F2,$BF,$EB,$2A,$11,$DF,$01 ; $22BB
        DEFB    $10,$00,$09,$3A,$EA,$BF,$B7,$3A,$E4,$BF,$28,$06,$CD,$D3,$B7,$73 ; $22CB
        DEFB    $18,$08,$4F,$06,$00,$09,$09,$73,$23,$72,$0E,$02,$3A,$13,$DF,$B7 ; $22DB
        DEFB    $C0,$C5,$CD,$01,$B7,$3A,$E2,$BF,$3D,$3D,$20,$3A,$C1,$C5,$79,$3D ; $22EB
        DEFB    $3D,$20,$33,$E5,$2A,$C6,$BF,$57,$77,$23,$14,$F2,$C3,$BC,$CD,$54 ; $22FB
        DEFB    $B8,$2A,$F4,$BF,$0E,$02,$22,$F2,$BF,$C5,$CD,$51,$B6,$C1,$CD,$28 ; $230B
        DEFB    $DF,$2A,$F2,$BF,$0E,$00,$3A,$D1,$BF,$47,$A5,$B8,$23,$20,$E7,$E1 ; $231B
        DEFB    $22,$F2,$BF,$CD,$4F,$B8,$CD,$51,$B6,$C1,$C5,$CD,$28,$DF,$C1,$3A ; $232B
        DEFB    $F0,$BF,$21,$EE,$BF,$BE,$38,$04,$77,$34,$0E,$02,$F5,$CD,$D8,$B7 ; $233B
        DEFB    $E6,$7F,$77,$F1,$FE,$7F,$20,$1A,$3A,$E2,$BF,$FE,$01,$20,$13,$CD ; $234B
        DEFB    $48,$B7,$CD,$A4,$BB,$21,$13,$DF,$7E,$B7,$20,$04,$3D,$32,$F0,$BF ; $235B
        DEFB    $36,$00,$C3,$48,$B7,$AF,$32,$E2,$BF,$C5,$2A,$11,$DF,$EB,$21,$21 ; $236B
        DEFB    $00,$19,$7E,$E6,$7F,$F5,$7E,$17,$23,$7E,$17,$E6,$1F,$4F,$7E,$1F ; $237B
        DEFB    $1F,$1F,$1F,$E6,$0F,$47,$F1,$23,$6E,$2C,$2D,$2E,$06,$20,$57,$21 ; $238B
        DEFB    $20,$00,$19,$77,$21,$0C,$00,$19,$79,$96,$20,$0A,$21,$0E,$00,$19 ; $239B
        DEFB    $78,$96,$E6,$7F,$28,$34,$C5,$D5,$CD,$F6,$BA,$D1,$C1,$2E,$03,$3A ; $23AB
        DEFB    $13,$DF,$3C,$28,$2A,$21,$0C,$00,$19,$71,$21,$0E,$00,$19,$70,$CD ; $23BB
        DEFB    $A7,$BA,$3A,$13,$DF,$3C,$20,$12,$C1,$C5,$2E,$04,$0C,$28,$10,$CD ; $23CB
        DEFB    $6F,$BB,$2E,$05,$3A,$13,$DF,$3C,$28,$05,$C1,$AF,$C3,$D0,$DE,$E5 ; $23DB
        DEFB    $CD,$D8,$B7,$36,$C0,$E1,$C1,$7D,$32,$13,$DF,$C3,$F1,$B7,$0E,$FF ; $23EB
        DEFB    $CD,$30,$BD,$CC,$03,$BC,$C9,$0E,$00,$CD,$30,$BD,$CC,$41,$BC,$C9 ; $23FB
        DEFB    $EB,$19,$4E,$06,$00,$21,$0C,$00,$19,$7E,$0F,$E6,$80,$81,$4F,$3E ; $240B
        DEFB    $00,$88,$47,$7E,$0F,$E6,$0F,$80,$47,$21,$0E,$00,$19,$7E,$87,$87 ; $241B
        DEFB    $87,$87,$F5,$80,$47,$F5,$E1,$7D,$E1,$B5,$E6,$01,$C9,$0E,$0C,$CD ; $242B
        DEFB    $80,$B9,$2A,$11,$DF,$11,$21,$00,$19,$E5,$72,$23,$72,$23,$72,$CD ; $243B
        DEFB    $6B,$B8,$28,$20,$CD,$CD,$B7,$11,$0F,$00,$CD,$CB,$BD,$E1,$E5,$5F ; $244B
        DEFB    $79,$96,$23,$78,$9E,$23,$7B,$9E,$38,$05,$73,$2B,$70,$2B,$71,$CD ; $245B
        DEFB    $95,$B9,$18,$DB,$E1,$C9,$CD,$A3,$BF,$2A,$11,$DF,$11,$20,$00,$CD ; $246B
        DEFB    $CB,$BD,$21,$21,$00                              ; $247B  "K=!!"
        DEFB    $19,$71,$23,$70,$23,$77,$C9,$3A,$E3,$BF,$21,$10,$DF,$BE,$C8,$77 ; $2480
        DEFB    $2A,$BC,$BF,$3A,$10,$DF,$4F,$CD,$5F,$B7,$E5,$EB,$CD,$EC,$B5,$E1 ; $2490
        DEFB    $CC,$15,$DF,$7D,$1F,$D8,$2A,$BC,$BF,$4D,$44,$CD,$7A,$B7,$22,$BC ; $24A0
        DEFB    $BF,$C3,$0F,$B9,$CD,$A3,$BF,$3E,$FF,$32,$EB,$BF,$2A,$11,$DF,$7E ; $24B0
        DEFB    $E6,$1F,$3D,$32,$E3,$BF,$FE,$1E,$30,$10,$3A,$10,$DF,$32,$EC,$BF ; $24C0
        DEFB    $7E,$32,$ED,$BF,$E6,$E0,$77,$CD,$47,$BE,$3A,$0F,$DF,$2A,$11,$DF ; $24D0
        DEFB    $B6,$77,$C9,$3E,$22,$C3,$D0,$DE,$21,$00          ; $24E0  "6wI>"CP^!"
        DEFB    $00,$22,$BA,$BF,$22,$BC,$BF,$AF,$32,$10,$DF,$21,$80,$00,$22,$BE ; $24EA
        DEFB    $BF,$CD,$4F,$B8,$18,$90,$CD,$E1,$B7,$C3,$A7,$BA,$CD,$74,$BE,$C3 ; $24FA
        DEFB    $F6,$BA,$CD,$A3,$BF,$0E,$00,$EB,$7E,$FE,$3F,$28,$0E,$CD,$1C,$B7 ; $250A
        DEFB    $7E,$FE,$3F,$C4,$EB,$B7,$CD,$77,$BE,$0E,$0F,$CD,$80,$B9,$C3,$5D ; $251A
        DEFB    $B8,$ED,$5B,$85,$DF,$CD,$A3,$BF,$EB,$CD,$77,$BE,$CD,$95,$B9,$C3 ; $252A
        DEFB    $5D,$B8,$CD,$74,$BE,$CD,$F9,$B9,$C3,$69,$B9,$CD,$74,$BE,$C3,$FE ; $253A
        DEFB    $BB,$CD,$74,$BE,$C3,$3C,$BC,$CD,$E1,$B7,$C3,$6F,$BB,$CD,$74,$BE ; $254A
        DEFB    $CD,$6E,$BA,$C3,$69,$B9,$2A,$BC,$BF,$18,$23,$3A,$10,$DF,$C3,$D0 ; $255A
        DEFB    $DE,$EB,$22,$BE,$BF,$C3,$4F,$B8,$2A,$CC,$BF,$18,$11,$2A,$BA,$BF ; $256A
        DEFB    $18,$0C,$CD,$74,$BE,$CD,$92,$BA,$C3,$69,$B9,$2A,$C8,$BF,$22,$13 ; $257A
        DEFB    $DF,$C9,$3A,$E3,$BF,$FE,$FF,$20,$06,$3A,$0F,$DF,$C3,$D0,$DE,$E6 ; $258A
        DEFB    $1F,$32,$0F,$DF,$C9,$CD,$74,$BE,$C3,$B9,$BD,$CD,$74,$BE,$C3,$C2 ; $259A
        DEFB    $BD,$CD,$74,$BE,$C3,$F8,$BD,$2A,$11,$DF,$7D,$2F,$5F,$7C,$2F,$2A ; $25AA
        DEFB    $BC,$BF,$A4,$57,$7D,$A3,$5F,$2A,$BA,$BF,$EB,$22,$BC,$BF,$7D,$A3 ; $25BA
        DEFB    $6F,$7C,$A2,$67,$22,$BA,$BF,$C9,$CD,$74,$BE,$3E,$02,$32,$E2,$BF ; $25CA
        DEFB    $0E,$00,$CD,$34,$BD,$CC,$41,$BC,$C9,$21,$87,$DF,$34,$23,$22,$11 ; $25DA
        DEFB    $DF,$EB,$22,$85,$DF,$01,$24,$00,$CD,$3C,$DF,$11,$88,$DF,$C9,$E5 ; $25EA
        DEFB    $00,$00,$00,$00,$80,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00 ; $25FA
        DEFS    246, $00    ; $260A  fill
        DEFB    $C3,$EA,$FE,$C3,$B8,$FA,$C3,$10,$FB,$C3,$1A,$FB,$C3,$4D,$FB,$C3 ; $2700
        DEFB    $70,$FB,$C3,$7F,$FB,$C3,$91,$FB,$C3,$75,$FE,$C3,$97,$FE,$C3,$80 ; $2710
        DEFB    $FE,$C3,$F4,$FB,$C3,$F9,$FB,$C3,$C6,$FE,$C3,$CC,$FE,$AF,$C9,$00 ; $2720  "~Ct{Cy{CF~CL~/I"
        DEFB    $60,$69,$C9,$00,$00,$00,$00,$00,$00,$00,$00,$FD,$FE,$73,$FA,$C5 ; $2730
        DEFB    $FF,$7D,$FF,$00,$00,$00,$00,$00,$00,$00,$00,$FD,$FE,$73,$FA,$D1 ; $2740
        DEFB    $FF,$8F,$FF,$00,$00,$00,$00,$00,$00,$00,$00,$FD,$FE,$73,$FA,$DD ; $2750
        DEFB    $FF,$A1,$FF,$00,$00,$00,$00,$00,$00,$00,$00,$FD,$FE,$73,$FA,$E9 ; $2760
        DEFB    $FF,$B3,$FF,$20,$00,$03,$07,$00,$8B,$00,$2F,$00,$C0,$00,$0C,$00 ; $2770
        DEFB    $03,$00,$11,$07,$00,$21,$B8,$F3,$19,$7E,$D6,$03,$20,$07,$CD,$8A ; $2780
        DEFB    $FE,$36,$03,$36,$15,$3D,$20,$0B,$CD,$83,$FD,$21,$00,$C8,$CD,$45 ; $2790
        DEFB    $FB,$18,$0A,$FE,$02,$20,$06,$21,$D0,$0D,$CD,$B0,$FD,$1D,$20,$D5 ; $27A0
        DEFB    $C9,$21,$00,$E0,$7B,$B4,$67,$C9,$31,$80,$00,$3A,$51,$E0,$21,$00 ; $27B0
        DEFB    $0E,$CD,$45,$FB,$CD,$82,$FA,$3A,$08,$DC,$FE,$DC,$28,$11,$21,$59 ; $27C0
        DEFB    $FF,$22,$D0,$F3,$2A,$DE,$F3,$3E,$77,$32,$0B,$00,$C3,$0B,$00,$AF ; $27D0
        DEFB    $32,$07,$D3,$AF,$32,$F6,$FE,$32,$F1,$FE,$3E,$C3,$32,$00,$00,$21 ; $27E0
        DEFB    $03,$FA                                          ; $27F0
        DEFW    MAIN_17                  ; $27F2
        DEFB    $00,$32,$05,$00,$21,$06,$DC,$22,$06              ; $27F4
        DEFW    MAIN                     ; $27FD
        DEFB    $80,$00,$CD,$F9,$FB,$3E,$01,$32,$4E,$D7,$3A,$04,$00,$4F,$C3,$00 ; $27FF
        DEFB    $D3,$2A,$80,$F3,$E9,$3A,$00,$E0,$17,$9F,$C9,$CD,$5A,$FB,$E6,$7F ; $280F
        DEFB    $21,$AB,$F3,$06,$06,$4F,$23,$7E,$23,$B7,$FA,$31,$FB,$B9,$7E,$C8 ; $281F
        DEFB    $10,$F4,$79,$C9,$11,$03,$00,$C3,$39,$FB,$3A,$00,$E0,$17,$30,$FA ; $282F
        DEFB    $32,$10,$E0,$3F,$1F,$C9,$22,$D0,$F3,$32,$00,$00,$C9,$4F,$3A,$03 ; $283F
        DEFB    $00,$E6,$03,$FE,$02,$20,$4B,$2A,$92,$F3,$E9,$3A,$03,$00,$E6,$03 ; $284F
        DEFB    $FE,$02,$2A,$84,$F3,$28,$06,$30,$07,$2A,$82,$F3,$E9,$2A,$8A,$F3 ; $285F
        DEFB    $E9,$3A,$03,$00,$E6,$C0,$FE,$80,$38,$27,$28,$DB,$2A,$94,$F3,$E9 ; $286F
        DEFB    $3A,$03,$00,$E6,$30,$FE,$10,$38,$18,$2A,$8E,$F3,$28,$E2,$2A,$90 ; $287F
        DEFB    $F3,$E9,$3A,$03,$00,$E6,$0C,$FE,$08,$38,$CE,$28,$D0,$2A,$8C,$F3 ; $288F
        DEFB    $E9,$37,$9F,$21,$A2,$F3,$6E,$2C,$CA,$A4,$FC,$21,$E4,$FE,$77,$CB ; $289F
        DEFB    $B9,$23,$7E,$B7,$CA,$56,$FC,$35,$3A,$96,$F3,$21,$ED,$FE,$28,$0C ; $28AF
        DEFB    $B7,$F2,$C6,$FB,$2B,$E6,$7F,$5F,$79,$93,$77,$C9,$B7,$FA,$D0,$FB ; $28BF
        DEFB    $2B,$CD,$C4,$FB,$2A,$EC,$FE,$3A,$A1,$F3,$B7,$F2,$E2,$FB,$E6,$7F ; $28CF
        DEFB    $5D,$6C,$63,$5F,$84,$4F,$7B,$85,$F5,$06,$07,$CD,$A4,$FC,$F1,$06 ; $28DF
        DEFB    $0A,$4F,$C3,$A4,$FC,$79,$32,$EB,$FE,$C9,$ED,$43,$FA,$FE,$C9,$00 ; $28EF
        DEFS    87, $00    ; $28FF  fill
        DEFB    $47,$21,$E6,$FE,$7E,$5F,$B7,$20,$12,$3A,$97,$F3,$B7,$28,$06,$B9 ; $2956
        DEFB    $20,$03,$36,$80,$C9,$3E,$1F,$B9,$DA,$A4,$FC,$21,$A0,$F3,$06,$09 ; $2966
        DEFB    $7E,$B7,$28,$04,$AB,$B9,$28,$05,$2B,$10,$F5,$18,$21,$11,$0B,$00 ; $2976
        DEFB    $19,$7E,$B7,$4F,$F2,$9A,$FC,$E6,$7F,$4F,$C5,$3A,$A2,$F3,$06,$07 ; $2986
        DEFB    $CD,$F0,$FB,$C1,$78,$FE,$07,$20,$05,$3E,$02,$32,$E5,$FE,$AF,$32 ; $2996
        DEFB    $E6,$FE,$3A,$E4,$FE,$B7,$2A,$88,$F3,$28,$03,$2A,$86,$F3,$E9,$11 ; $29A6
        DEFB    $03,$00,$C3,$BB,$FC,$2A,$E7,$FE,$3A,$E9,$FE,$77,$CD,$E2,$FC,$2A ; $29B6
        DEFB    $28,$F0,$3A,$24,$F0,$5F,$16,$F0,$19,$22,$E7,$FE,$7E,$32,$E9,$FE ; $29C6
        DEFB    $FE,$E0,$38,$02,$EE,$20,$E6,$3F,$F6,$40,$77,$C9,$78,$B7,$28,$0B ; $29D6
        DEFB    $21,$45,$FB,$E5,$21,$66,$FD,$85,$6F,$6E,$E9,$79,$FE,$0D,$20,$05 ; $29E6
        DEFB    $AF,$32,$24,$F0,$C9,$F6,$80                      ; $29F6  "/2$pIv"
        DEFB    $FE,$E0,$38,$04,$21,$DD,$F3,$AE,$32,$45,$F0,$21,$F0,$FD,$C3,$80 ; $29FD
        DEFB    $FD,$CD,$8A,$FE,$C6,$8F,$CB,$4E,$28,$FC,$21,$2F,$F0,$36,$60,$2B ; $2A0D
        DEFB    $36,$C0,$2B,$77,$2B,$36,$8D                      ; $2A1D  "6@+w+6"
        DEFB    $62,$C3,$7C,$FD,$3E                              ; $2A24
        DEFW    MAILBOX_PUT_BYTE_1       ; $2A29
        DEFB    $3E,$3F,$32,$32,$F0,$E1,$C9,$21,$F4,$FB,$C9,$AF,$6F,$67,$22,$24 ; $2A2B
        DEFB    $F0,$32,$45,$F0,$21,$C1,$FB,$C9,$2E              ; $2A3B
        DEFW    MAIN_33                  ; $2A44
        DEFB    $2E,$9C,$01,$2E                                  ; $2A46
        DEFW    MAIN_12                  ; $2A4A
        DEFB    $2E,$58,$26,$FC,$C9,$2A,$EC,$FE,$7D,$FE,$28,$38,$02,$2E,$00,$7C ; $2A4C
        DEFB    $FE,$18,$38,$02,$26,$00,$22,$24,$F0,$18,$D5,$4C,$43,$46,$28,$2B ; $2A5C
        DEFB    $36,$30,$49,$32,$51,$CD,$83,$FD,$21,$78,$F6,$19,$71,$21,$AA,$C9 ; $2A6C
        DEFB    $79,$32,$45,$F0,$C3,$45,$FB,$CD,$85,$FE,$32,$F8,$F6,$32,$47,$F0 ; $2A7C
        DEFB    $3A,$FF,$EF,$CD,$B1,$FA,$D6,$20,$32,$46,$F0,$7E,$C9,$21,$1D,$0E ; $2A8C
        DEFB    $1E,$03,$3E,$01,$CD,$AD,$FD,$3A,$48,$F0,$1F,$9F,$C9,$21,$E1,$0D ; $2A9C
        DEFB    $79,$32,$45,$F0,$7B,$32,$47,$F0,$C3,$45,$FB,$21,$0F,$0E,$CD,$B0 ; $2AAC
        DEFB    $FD,$3A,$45,$F0,$C9,$CD,$83,$FD,$21,$4D,$C8,$CD,$45,$FB,$21,$78 ; $2ABC
        DEFB    $F6,$19,$7E,$C9,$48,$20,$26,$0E,$A0,$0D,$B1,$F6,$85,$F6,$AC,$F8 ; $2ACC
        DEFB    $06,$68,$6C,$F6,$00,$48,$A9,$00,$20,$EF,$0D,$20,$26,$0E,$A0,$0F ; $2ADC
        DEFB    $4C,$D6,$0D,$84,$F5,$48,$20,$1D,$0E,$68,$A4,$F5,$90,$F5,$60,$00 ; $2AEC
        DEFB    $00,$00,$00,$00,$4C,$09,$0E,$8D,$8B,$C0,$4C,$13,$D4,$8D,$8B,$C0 ; $2AFC
        DEFB    $4C,$F7,$D1,$A9,$01,$20,$EF,$0D,$20,$26,$0E,$48,$A0,$0E,$4C,$D6 ; $2B0C
        DEFB    $0D,$48,$20,$26,$0E,$A0,$10,$4C,$D6,$0D,$98,$09,$C0,$AA,$98,$0A ; $2B1C
        DEFB    $0A,$0A,$0A,$A8,$8C,$F8,$06,$A9,$00,$85,$F6,$86,$F7,$AD,$FF,$CF ; $2B2C
        DEFB    $B1,$F6,$60,$A5,$48,$48,$A5,$45,$A6,$46,$A4,$47,$28,$58,$60,$CD ; $2B3C
        DEFB    $8A,$FE,$7E,$1F,$30,$FC,$2C,$7E,$C9,$11,$01,$00,$C3,$68,$FE,$CD ; $2B4C
        DEFB    $B1,$FA,$2E,$C1,$7E,$17,$38,$FC,$CD,$85,$FE,$71,$C9,$11,$02,$00 ; $2B5C
        DEFB    $C3,$68,$FE,$11,$02,$00,$C3,$00,$00,$3A,$F2,$FE,$B7,$20,$03,$32 ; $2B6C
        DEFB    $F1,$FE,$0E,$00,$79,$32,$EA,$FE,$C9,$21,$80,$E0,$18,$03,$21,$8E ; $2B7C
        DEFB    $E0,$7B,$87,$87,$87,$87,$F5,$85,$6F,$F1,$C9,$11,$EE,$FE,$21,$04 ; $2B8C
        DEFB    $00,$3A,$B8,$F3,$3D,$B9,$38,$1D,$7E,$12,$13,$79,$12,$21,$33,$FA ; $2B9C
        DEFB    $CD,$8E,$FE,$E5,$11,$0A,$00,$19,$5E,$23,$56,$21,$05,$00,$19,$7E ; $2BAC
        DEFB    $32,$FC,$FE,$E1,$C9,$1A,$77,$2E,$00,$C9,$32,$8B,$E0,$C3,$47,$B2 ; $2BBC
        DEFB    $32,$8B,$E0,$C3,$57,$B2,$CD,$45,$FB,$32,$8B,$E0,$C9,$32,$83,$E0 ; $2BCC
        DEFB    $2A,$0D,$DC,$E9,$32,$83,$E0,$C9,$00,$00,$00,$E9,$FE,$00,$31 ; $2BDC
        DEFW    MAIN                     ; $2BEB
        DEFB    $AF,$21,$00,$FA,$77,$23,$77,$23,$77,$3E,$95,$32,$03,$00,$2A,$DE ; $2BED
        DEFB    $F3,$22,$49,$FB,$AF,$32,$04,$00,$3A,$BB,$F3,$FE,$06,$20,$0A,$21 ; $2BFD
        DEFB    $99,$FD,$22,$80,$F3,$D6,$03,$18,$13,$FE,$05,$28,$22,$D6,$03,$38 ; $2C0D
        DEFB    $1E,$20,$09,$21,$15,$FB,$36,$BE,$23,$23,$36,$1F,$F5,$CD,$9D,$FF ; $2C1D
        DEFB    $F1,$22,$B9,$FC,$CD,$98,$FF,$22,$37,$FB,$3E,$03,$32,$05,$FB,$3A ; $2C2D
        DEFB    $B9,$F3,$D6,$03,$38,$06,$CD,$9D,$FF,$22,$59,$FE,$3A,$BA,$F3,$D6 ; $2C3D
        DEFB    $03,$38,$14,$F5,$CD,$9D,$FF,$22,$6D,$FE,$F1,$FE,$02,$28,$08,$CD ; $2C4D
        DEFB    $98,$FF,$22,$73,$FE,$18,$0B,$21,$3E,$1A,$22,$72,$FE,$3E,$C9,$32 ; $2C5D
        DEFB    $74,$FE,$CD,$82,$FA,$3A,$98,$F3,$CD,$A8,$FF,$21,$B7,$FF,$7E,$B7 ; $2C6D
        DEFB    $CA,$E3,$FA,$E5,$CD,$4C,$FB,$E1,$23,$18,$F3,$0E,$FD,$71,$FD,$5B ; $2C7D
        DEFB    $FE,$A9,$FD,$4B,$FE,$C1,$FD,$B7,$FD,$B7,$FD,$21,$90,$FF,$18,$03 ; $2C8D
        DEFB    $21,$88,$FF,$87,$85,$6F,$7E,$2C,$66,$6F,$C9,$B7,$F2,$B4,$FF,$F5 ; $2C9D
        DEFB    $3A,$97,$F3,$CD,$4C,$FB,$F1,$C3,$4C,$FB,$0D,$0A,$0A,$0A,$20,$20 ; $2CAD
        DEFB    "   Softcard CP/M"    ; $2CBD  string
        DEFB    $0D    ; $2CCD  terminator
        DEFB    $0A,$20,$20,$20,$20,$20,$36,$30,$4B,$20,$56,$65,$72,$2E,$20,$32 ; $2CCE
        DEFB    $2E,$32,$33,$0D,$0A,$28,$63,$29,$20,$31,$39,$38,$30,$2C,$31,$39 ; $2CDE
        DEFB    "82 Microsoft"    ; $2CEE  string
        DEFB    $0D    ; $2CFA  terminator
        DEFB    $0A,$0D,$0A,$00,$FA                              ; $2CFB

    SAVEBIN "CPM60.bin", $0100, $2C00
