; NOTE: comments marked [AI] are machine-generated by claude-opus-4-8 and may be
; inaccurate; treat them as hints, not verified annotation.

; Generated by disasm_z80
; Source: PATCH
; Range:  $0100-$04FF  (1024 bytes)

    DEVICE NOSLOT64K

; -- External symbols --
WBOOT_VEC            EQU $0000               ; Warm-boot vector — JP WBOOT in BIOS. Touching it causes a CP/M warm boot.
CDISK                EQU $0004               ; Current drive (low nibble: 0=A, 1=B, ..., 15=P) and current user (high nibble, 0-15).
BDOS_VEC             EQU $0005               ; BDOS call vector — JP BDOS_ENTRY. Programs use CALL $0005 to invoke BDOS. Word at $0006 is also the top-of-TPA marker.
DEFAULT_FCB          EQU $005C               ; Default File Control Block — populated by CCP from command-line argument 1. Standard 36-byte FCB structure (drive + filename + extents + record number).
DEFAULT_RND          EQU $007D               ; Default FCB random record number (3 bytes — low/middle/high).
DEFAULT_DMA          EQU $0080               ; Default 128-byte DMA buffer. BDOS cold-init / DRV_ALLRESET (fn 13) set the DMA address here and WBOOT re-issues SETDMA($0080); sector/record I/O moves 128 bytes through it. At program load this same buffer doubles as the command tail: the first byte ($0080) holds the tail length (0-127) and the characters follow at $0081 (CMDLINE).
CMDLINE              EQU $0081               ; Command-line tail characters (uppercase, with leading space). Same buffer as DEFAULT_DMA.

; -- Mid-instruction references (shown inline as cover+offset) --
;   $03C2 -> WRITE_RECORD_VERIFY_1+1         z80 skip idiom: enters the operand of $21 at $03C1
;   $0427 -> BIOS_DISK_DISPATCH_1+1         z80 skip idiom: enters the operand of $21 at $0426
;   $042A -> BIOS_DISK_DISPATCH_2+1         z80 skip idiom: enters the operand of $21 at $0429
;   $042D -> BIOS_DISK_DISPATCH_3+1         z80 skip idiom: enters the operand of $21 at $042C
;   $0430 -> BIOS_DISK_DISPATCH_4+1         z80 skip idiom: enters the operand of $21 at $042F
;   $0433 -> BIOS_DISK_DISPATCH_5+1         z80 skip idiom: enters the operand of $21 at $0432

    ORG $0100

; [AI] Program entry at $0100. Sets the stack just below the work area and begins by saving the
;       command-tail length to decide command-line vs. interactive operation.
TPA_START:
        LD SP,BIOS_DISK_DISPATCH_14                ; $0100  31 FD 04
; [AI] Captures the command-tail length byte; a nonzero value means arguments were supplied so the
;       sign-on banner is skipped.
TPA_START_1:
        LD A,(DEFAULT_DMA)               ; $0103  3A 80 00
TPA_START_2:
        LD ($0563),A                     ; $0106  32 63 05
TPA_START_3:
        OR A                             ; $0109  B7
TPA_START_4:
        JR NZ,TPA_START_8                ; $010A  20 08
TPA_START_5:
        LD DE,BIOS_DISK_DISPATCH_13                ; $010C  11 9D 04
TPA_START_6:
        LD C,$09                         ; $010F  0E 09
TPA_START_7:
        CALL BDOS_VEC                    ; $0111  CD 05 00
; [AI] Top of the main per-command loop (interactive re-entry point): seeds the work area with the
;       warm-boot zero word and clears parser state before parsing the next command.
TPA_START_8:
        LD HL,WBOOT_VEC                  ; $0114  21 00 00
TPA_START_9:
        LD ($0506),HL                    ; $0117  22 06 05
TPA_START_10:
        XOR A                            ; $011A  AF
TPA_START_11:
        LD ($0068),A                     ; $011B  32 68 00
TPA_START_12:
        LD ($006A),A                     ; $011E  32 6A 00
TPA_START_13:
        CALL READ_COMMAND_LINE                    ; $0121  CD 90 03
        LD A,(IX+1)                      ; $0124  DD 7E 01
        CP $3A                           ; $0127  FE 3A
        JR NZ,TPA_START_14               ; $0129  20 15
        CALL GET_NEXT_CHAR                    ; $012B  CD 6A 03
        SUB $40                          ; $012E  D6 40
        LD (DEFAULT_FCB),A               ; $0130  32 5C 00
        INC IX                           ; $0133  DD 23
        LD A,(IX+0)                      ; $0135  DD 7E 00
        XOR $20                          ; $0138  EE 20
        JR NZ,TPA_START_14               ; $013A  20 04
        INC IX                           ; $013C  DD 23
        JR TPA_START_21                  ; $013E  18 3E
; [AI] Filename-parsing path: blank-fills the 11-byte FCB name/type field, then copies up to 8 name
;       characters from the input, dispatching on '.', space, and '=' delimiters.
TPA_START_14:
        LD HL,$0067                      ; $0140  21 67 00
        LD B,$0B                         ; $0143  06 0B
; [AI] Loop that pads the FCB filename+type field with spaces ($20) before the parsed name is laid
;       in.
TPA_START_15:
        LD (HL),$20                      ; $0145  36 20
        DEC HL                           ; $0147  2B
        DJNZ TPA_START_15                ; $0148  10 FB
        INC HL                           ; $014A  23
        LD B,$09                         ; $014B  06 09
; [AI] Scans the filename portion of the command, storing characters into the FCB and branching on
;       the extension dot, terminating space, or the '=' that introduces the patch value.
TPA_START_16:
        CALL GET_NEXT_CHAR                    ; $014D  CD 6A 03
        JR Z,TPA_START_17                ; $0150  28 10
        CP $2E                           ; $0152  FE 2E
        JR Z,TPA_START_18                ; $0154  28 0F
        CP $20                           ; $0156  FE 20
        JR Z,TPA_START_21                ; $0158  28 24
        CP $3D                           ; $015A  FE 3D
        JR Z,TPA_START_20                ; $015C  28 1B
        LD (HL),A                        ; $015E  77
        INC HL                           ; $015F  23
        DJNZ TPA_START_16                ; $0160  10 EB
; [AI] Common 'syntax/command error' exit: jumps to L_0319 to print the Command error message.
TPA_START_17:
        JP TPA_START_42                  ; $0162  C3 19 03
; [AI] Parses the 3-character file-type/extension into the FCB type field after a '.' is seen.
TPA_START_18:
        LD B,$04                         ; $0165  06 04
        LD HL,$0065                      ; $0167  21 65 00
; [AI] Loop copying extension characters into the FCB type field until a delimiter or length limit.
TPA_START_19:
        CALL GET_NEXT_CHAR                    ; $016A  CD 6A 03
        JR Z,TPA_START_17                ; $016D  28 F3
        CP $20                           ; $016F  FE 20
        JR Z,TPA_START_21                ; $0171  28 0B
        LD (HL),A                        ; $0173  77
        INC HL                           ; $0174  23
        DJNZ TPA_START_19                ; $0175  10 F3
        JR TPA_START_17                  ; $0177  18 E9
; [AI] Handles a leading '=' with no filename by repointing the input scanner back to the command
;       tail so the value list is parsed from the start.
TPA_START_20:
        LD IX,$0082                      ; $0179  DD 21 82 00
        XOR A                            ; $017D  AF
; [AI] Begins parsing the sector/offset number: clears the mode flag and accumulates a hex value
;       (D:HL) digit-by-digit until '=' or a delimiter.
TPA_START_21:
        LD (BIOS_DISK_DISPATCH_14),A               ; $017E  32 FD 04
        LD HL,WBOOT_VEC                  ; $0181  21 00 00
        LD D,L                           ; $0184  55
; [AI] Hex-accumulation loop for the address/sector argument; shifts the running value left one
;       nibble and ORs in each parsed digit.
TPA_START_22:
        LD A,(IX+0)                      ; $0185  DD 7E 00
        CP $3D                           ; $0188  FE 3D
        JR Z,TPA_START_24                ; $018A  28 13
        CALL PARSE_HEX_NIBBLE                    ; $018C  CD 53 03
        JP Z,TPA_START_42                ; $018F  CA 19 03
        LD C,A                           ; $0192  4F
        LD A,D                           ; $0193  7A
        LD B,$04                         ; $0194  06 04
; [AI] Inner 4-iteration shift loop that multiplies the 24-bit accumulator by 16 to make room for
;       the next hex digit.
TPA_START_23:
        ADD A,A                          ; $0196  87
        ADC HL,HL                        ; $0197  ED 6A
        DJNZ TPA_START_23                ; $0199  10 FB
        OR C                             ; $019B  B1
        LD D,A                           ; $019C  57
        JR TPA_START_22                  ; $019D  18 E6
; [AI] Stores the finished sector/byte address (D and HL) into the work area, then resets the
;       patch-byte buffer pointers/counts in preparation for reading the replacement bytes.
TPA_START_24:
        CALL GET_NEXT_CHAR                    ; $019F  CD 6A 03
        LD A,D                           ; $01A2  7A
        LD (BIOS_DISK_DISPATCH_15),A               ; $01A3  32 FE 04
        LD (BIOS_DISK_DISPATCH_16),HL              ; $01A6  22 FF 04
        LD HL,WBOOT_VEC                  ; $01A9  21 00 00
        LD A,L                           ; $01AC  7D
        LD ($0501),A                     ; $01AD  32 01 05
        LD ($0502),A                     ; $01B0  32 02 05
        LD ($0503),HL                    ; $01B3  22 03 05
        LD HL,$0534                      ; $01B6  21 34 05
        LD IY,$0507                      ; $01B9  FD 21 07 05
; [AI] Parses the list of new (replacement) patch bytes; on '(' it switches to also reading the
;       expected-old-byte list for verified patching.
TPA_START_25:
        LD A,(IX+0)                      ; $01BD  DD 7E 00
        CP $28                           ; $01C0  FE 28
        JR Z,TPA_START_27                ; $01C2  28 14
        CALL PARSE_HEX_BYTE                    ; $01C4  CD 40 03
        JR C,TPA_START_29                ; $01C7  38 2C
        CALL APPEND_PATCH_BYTE                    ; $01C9  CD 77 03
        CALL GET_NEXT_CHAR                    ; $01CC  CD 6A 03
        JR Z,TPA_START_29                ; $01CF  28 24
        CP $20                           ; $01D1  FE 20
        JR Z,TPA_START_25                ; $01D3  28 E8
; [AI] Error shortcut to the Command error exit for malformed value lists.
TPA_START_26:
        JP TPA_START_42                  ; $01D5  C3 19 03
; [AI] Begins parsing the parenthesised compare/old-byte list used when the user wants the patch
;       applied only if the existing bytes match.
TPA_START_27:
        CALL GET_NEXT_CHAR                    ; $01D8  CD 6A 03
        LD HL,$0507                      ; $01DB  21 07 05
        LD IY,$0506                      ; $01DE  FD 21 06 05
; [AI] Loop reading hex bytes of the old-value (compare) list until the closing ')'.
TPA_START_28:
        CALL PARSE_HEX_BYTE                    ; $01E2  CD 40 03
        JR C,TPA_START_26                ; $01E5  38 EE
        CALL APPEND_PATCH_BYTE                    ; $01E7  CD 77 03
        CALL GET_NEXT_CHAR                    ; $01EA  CD 6A 03
        CP $20                           ; $01ED  FE 20
        JR Z,TPA_START_28                ; $01EF  28 F1
        CP $29                           ; $01F1  FE 29
        JR NZ,TPA_START_26               ; $01F3  20 E0
; [AI] Resolves the target drive: uses the FCB-specified drive if present, otherwise the current
;       default drive, then locates that drive's BIOS disk parameter information.
TPA_START_29:
        LD A,(DEFAULT_FCB)               ; $01F5  3A 5C 00
        DEC A                            ; $01F8  3D
        JP P,TPA_START_30                ; $01F9  F2 FF 01
        LD A,(CDISK)                     ; $01FC  3A 04 00
; [AI] Calls into the disk-parameter lookup (SUB_0427) and, from the returned DPB, fetches the
;       sector size used to split the byte offset into record number plus in-record offset.
TPA_START_30:
        LD C,A                           ; $01FF  4F
        CALL BIOS_DISK_DISPATCH_1+1                ; $0200  CD 27 04
        LD A,H                           ; $0203  7C
        OR L                             ; $0204  B5
        JP Z,TPA_START_43                ; $0205  CA 1E 03
        LD BC,$000A                      ; $0208  01 0A 00
        ADD HL,BC                        ; $020B  09
        LD A,(HL)                        ; $020C  7E
        INC HL                           ; $020D  23
        LD H,(HL)                        ; $020E  66
        LD L,A                           ; $020F  6F
        LD A,(HL)                        ; $0210  7E
        LD ($0505),A                     ; $0211  32 05 05
        LD A,(BIOS_DISK_DISPATCH_15)               ; $0214  3A FE 04
        LD C,A                           ; $0217  4F
        AND $7F                          ; $0218  E6 7F
        LD B,A                           ; $021A  47
        LD ($0501),A                     ; $021B  32 01 05
        LD A,($0506)                     ; $021E  3A 06 05
        LD HL,$0507                      ; $0221  21 07 05
        CP (HL)                          ; $0224  BE
        JR NC,TPA_START_31               ; $0225  30 01
        LD A,(HL)                        ; $0227  7E
; [AI] Computes a flag (all-ones or zero via ADD/ADD/SBC) indicating whether the patch spans into a
;       second record, controlling the two-record read/write logic.
TPA_START_31:
        ADD A,B                          ; $0228  80
        ADD A,A                          ; $0229  87
        SBC A,A                          ; $022A  9F
        LD ($0562),A                     ; $022B  32 62 05
        LD A,C                           ; $022E  79
        LD HL,(BIOS_DISK_DISPATCH_16)              ; $022F  2A FF 04
        ADD A,A                          ; $0232  87
        ADC HL,HL                        ; $0233  ED 6A
        LD A,(BIOS_DISK_DISPATCH_14)               ; $0235  3A FD 04
        OR A                             ; $0238  B7
        JR Z,TPA_START_32                ; $0239  28 32
        LD (DEFAULT_RND),HL              ; $023B  22 7D 00
        XOR A                            ; $023E  AF
        LD ($007F),A                     ; $023F  32 7F 00
        LD C,$0F                         ; $0242  0E 0F
        LD DE,DEFAULT_FCB                ; $0244  11 5C 00
        CALL BDOS_VEC                    ; $0247  CD 05 00
        INC A                            ; $024A  3C
        LD DE,BIOS_DISK_DISPATCH_9                 ; $024B  11 5B 04
        JP Z,TPA_START_47                ; $024E  CA 30 03
        CALL SET_DMA_BUF1                    ; $0251  CD E3 03
        CALL WRITE_RECORD_VERIFY_1+1                ; $0254  CD C2 03
        LD A,($0562)                     ; $0257  3A 62 05
        OR A                             ; $025A  B7
        JR Z,TPA_START_34                ; $025B  28 40
        LD HL,(DEFAULT_RND)              ; $025D  2A 7D 00
        PUSH HL                          ; $0260  E5
        CALL ADVANCE_TO_REC2                    ; $0261  CD D7 03
        CALL WRITE_RECORD_VERIFY_1+1                ; $0264  CD C2 03
        POP HL                           ; $0267  E1
        LD (DEFAULT_RND),HL              ; $0268  22 7D 00
        JR TPA_START_34                  ; $026B  18 30
; [AI] Read-only display path (no '=' value given): divides the byte offset by the sector size to
;       derive the record number, reads the record, and dumps its bytes.
TPA_START_32:
        LD A,($0505)                     ; $026D  3A 05 05
        LD E,A                           ; $0270  5F
        LD D,$00                         ; $0271  16 00
        LD BC,$FFFF                      ; $0273  01 FF FF
; [AI] Repeated-subtraction division loop computing record number (quotient in BC) and in-record
;       offset (remainder in HL) from the linear byte address.
TPA_START_33:
        INC BC                           ; $0276  03
        OR A                             ; $0277  B7
        SBC HL,DE                        ; $0278  ED 52
        JR NC,TPA_START_33               ; $027A  30 FA
        ADD HL,DE                        ; $027C  19
        LD A,L                           ; $027D  7D
        LD ($0502),A                     ; $027E  32 02 05
        LD ($0503),BC                    ; $0281  ED 43 03 05
        LD BC,$0564                      ; $0285  01 64 05
        CALL BIOS_DISK_DISPATCH_4+1                ; $0288  CD 30 04
        CALL READ_RECORD_1                    ; $028B  CD EB 03
        CALL BIOS_READ_CHECK                    ; $028E  CD 1C 04
        LD A,($0562)                     ; $0291  3A 62 05
        OR A                             ; $0294  B7
        JR Z,TPA_START_34                ; $0295  28 06
        CALL READ_RECORD_2                    ; $0297  CD F8 03
        CALL BIOS_READ_CHECK                    ; $029A  CD 1C 04
; [AI] Applies the parsed patch bytes into the in-memory record buffer at the computed offset,
;       simultaneously verifying old bytes against the compare list when one was given.
TPA_START_34:
        LD HL,$0564                      ; $029D  21 64 05
        LD A,($0501)                     ; $02A0  3A 01 05
        LD C,A                           ; $02A3  4F
        LD B,$00                         ; $02A4  06 00
        ADD HL,BC                        ; $02A6  09
        EX DE,HL                         ; $02A7  EB
        LD BC,($0506)                    ; $02A8  ED 4B 06 05
        LD HL,$0508                      ; $02AC  21 08 05
        LD IX,$0535                      ; $02AF  DD 21 35 05
; [AI] Byte-merge loop: walks the record buffer, checking each existing byte against the expected-
;       old list and overwriting it with the new byte, aborting to L_032D on a verification
;       mismatch.
TPA_START_35:
        LD A,C                           ; $02B3  79
        OR B                             ; $02B4  B0
        JR Z,TPA_START_39                ; $02B5  28 22
        LD A,C                           ; $02B7  79
        OR A                             ; $02B8  B7
        JR Z,TPA_START_37                ; $02B9  28 10
        LD A,(DE)                        ; $02BB  1A
        CP (HL)                          ; $02BC  BE
        JR Z,TPA_START_36                ; $02BD  28 0A
        XOR (IX+0)                       ; $02BF  DD AE 00
        JP NZ,TPA_START_46               ; $02C2  C2 2D 03
        OR B                             ; $02C5  B0
        JP Z,TPA_START_46                ; $02C6  CA 2D 03
; [AI] Advances the compare-list pointer/count after a matched old byte.
TPA_START_36:
        DEC C                            ; $02C9  0D
        INC HL                           ; $02CA  23
; [AI] Stores the next replacement byte into the record buffer and advances the new-byte source
;       pointer/count.
TPA_START_37:
        LD A,B                           ; $02CB  78
        OR A                             ; $02CC  B7
        JR Z,TPA_START_38                ; $02CD  28 07
        LD A,(IX+0)                      ; $02CF  DD 7E 00
        LD (DE),A                        ; $02D2  12
        DEC B                            ; $02D3  05
        INC IX                           ; $02D4  DD 23
; [AI] Advances the destination buffer pointer for the next byte position in the merge loop.
TPA_START_38:
        INC DE                           ; $02D6  13
        JR TPA_START_35                  ; $02D7  18 DA
; [AI] After merging, the write path: random-writes the modified record(s) back to disk, handling
;       the second record when the patch crosses a sector boundary.
TPA_START_39:
        LD A,(BIOS_DISK_DISPATCH_14)               ; $02D9  3A FD 04
        OR A                             ; $02DC  B7
        JR Z,TPA_START_41                ; $02DD  28 20
        CALL SET_DMA_BUF1                    ; $02DF  CD E3 03
        CALL WRITE_RECORD_VERIFY                    ; $02E2  CD BF 03
        LD A,($0562)                     ; $02E5  3A 62 05
        OR A                             ; $02E8  B7
        JR Z,TPA_START_40                ; $02E9  28 06
        CALL ADVANCE_TO_REC2                    ; $02EB  CD D7 03
        CALL WRITE_RECORD_VERIFY                    ; $02EE  CD BF 03
; [AI] Closes the file via BDOS function 16 after a successful write and reports a write/disk error
;       if the close fails.
TPA_START_40:
        LD C,$10                         ; $02F1  0E 10
        LD DE,DEFAULT_FCB                ; $02F3  11 5C 00
        CALL BDOS_VEC                    ; $02F6  CD 05 00
        INC A                            ; $02F9  3C
        JP Z,TPA_START_44                ; $02FA  CA 23 03
        JR TPA_START_48                  ; $02FD  18 34
; [AI] Sequential/alternate write path that re-positions the DMA, writes the record, and on a
;       second-record patch writes the following record too.
TPA_START_41:
        CALL READ_RECORD_1                    ; $02FF  CD EB 03
        LD BC,$0564                      ; $0302  01 64 05
        CALL BIOS_DISK_DISPATCH_4+1                ; $0305  CD 30 04
        CALL BIOS_WRITE_CHECK                    ; $0308  CD 15 04
        LD A,($0562)                     ; $030B  3A 62 05
        OR A                             ; $030E  B7
        JR Z,TPA_START_48                ; $030F  28 22
        CALL READ_RECORD_2                    ; $0311  CD F8 03
        CALL BIOS_WRITE_CHECK                    ; $0314  CD 15 04
        JR TPA_START_48                  ; $0317  18 1A
; [AI] Error handler that loads DE with the 'Command error' message and falls into the print-and-
;       exit routine.
TPA_START_42:
        LD DE,BIOS_DISK_DISPATCH_7                 ; $0319  11 3E 04
        JR TPA_START_47                  ; $031C  18 12
; [AI] Error handler that selects the 'Invalid Drive' message.
TPA_START_43:
        LD DE,BIOS_DISK_DISPATCH_11                ; $031E  11 7C 04
        JR TPA_START_47                  ; $0321  18 0D
; [AI] Error handler that selects the 'Disk I/O error' message.
TPA_START_44:
        LD DE,BIOS_DISK_DISPATCH_8                 ; $0323  11 4C 04
        JR TPA_START_47                  ; $0326  18 08
; [AI] Error handler that selects the 'End of File error' message.
TPA_START_45:
        LD DE,BIOS_DISK_DISPATCH_10                ; $0328  11 6A 04
        JR TPA_START_47                  ; $032B  18 03
; [AI] Error handler that selects the 'Verification error' message used when an old-byte compare
;       fails.
TPA_START_46:
        LD DE,BIOS_DISK_DISPATCH_12                ; $032D  11 8A 04
; [AI] Prints the selected error/status message (via PRINT_MSG_CRLF) before falling through to the
;       loop/exit decision.
TPA_START_47:
        CALL PRINT_MSG_CRLF                    ; $0330  CD 7D 03
; [AI] Post-operation tail: restores the saved command-tail flag; loops back to L_0114 in
;       interactive mode or warm-boots back to CP/M when run from the command line.
TPA_START_48:
        LD A,($0563)                     ; $0333  3A 63 05
        LD (DEFAULT_DMA),A               ; $0336  32 80 00
        OR A                             ; $0339  B7
        JP Z,TPA_START_8                 ; $033A  CA 14 01
        JP WBOOT_VEC                     ; $033D  C3 00 00
; [AI] Parses a full hex byte (two hex digits) from the input via two PARSE_HEX_NIBBLE calls, returning the
;       combined value or setting carry at end-of-input.
PARSE_HEX_BYTE:
        CALL PARSE_HEX_NIBBLE                    ; $0340  CD 53 03
        SCF                              ; $0343  37
        RET Z                            ; $0344  C8
        ADD A,A                          ; $0345  87
        ADD A,A                          ; $0346  87
        ADD A,A                          ; $0347  87
        ADD A,A                          ; $0348  87
        PUSH AF                          ; $0349  F5
        CALL PARSE_HEX_NIBBLE                    ; $034A  CD 53 03
        JR Z,PARSE_HEX_NIBBLE_1                  ; $034D  28 18
        LD C,A                           ; $034F  4F
        POP AF                           ; $0350  F1
        OR C                             ; $0351  B1
        RET                              ; $0352  C9
; [AI] Reads one character and converts it from ASCII to a hex nibble (0-F), jumping to the Command
;       error handler on any non-hex character.
PARSE_HEX_NIBBLE:
        CALL GET_NEXT_CHAR                    ; $0353  CD 6A 03
        RET Z                            ; $0356  C8
        SUB $30                          ; $0357  D6 30
        JR C,PARSE_HEX_NIBBLE_1                  ; $0359  38 0C
        CP $0A                           ; $035B  FE 0A
        RET C                            ; $035D  D8
        SUB $07                          ; $035E  D6 07
        CP $0A                           ; $0360  FE 0A
        JR C,PARSE_HEX_NIBBLE_1                  ; $0362  38 03
        CP $10                           ; $0364  FE 10
        RET C                            ; $0366  D8
PARSE_HEX_NIBBLE_1:
        JP TPA_START_42                  ; $0367  C3 19 03
; [AI] Low-level input fetch: returns the next command/input character via the IX scan pointer,
;       folding lowercase to uppercase and returning Z on the terminating null.
GET_NEXT_CHAR:
        LD A,(IX+0)                      ; $036A  DD 7E 00
        OR A                             ; $036D  B7
        RET Z                            ; $036E  C8
        INC IX                           ; $036F  DD 23
        CP $60                           ; $0371  FE 60
        RET C                            ; $0373  D8
        SUB $20                          ; $0374  D6 20
        RET                              ; $0376  C9
; [AI] Appends a parsed byte to a growing buffer and bumps the associated length counter held at
;       (IY) â used to build the new-byte and old-byte patch lists.
APPEND_PATCH_BYTE:
        INC HL                           ; $0377  23
        LD (HL),A                        ; $0378  77
        INC (IY+0)                       ; $0379  FD 34 00
        RET                              ; $037C  C9
; [AI] Prints the '$'-terminated string at DE (BDOS function 9) followed by a CR/LF; the standard
;       message-output helper.
PRINT_MSG_CRLF:
        LD C,$09                         ; $037D  0E 09
        CALL BDOS_VEC                    ; $037F  CD 05 00
        LD E,$0D                         ; $0382  1E 0D
        LD C,$02                         ; $0384  0E 02
        CALL BDOS_VEC                    ; $0386  CD 05 00
; [AI] Outputs a single line-feed (BDOS console-out, function 2) â the CR/LF helper's second
;       half.
PRINT_LF:
        LD E,$0A                         ; $0389  1E 0A
PRINT_LF_1:
        LD C,$02                         ; $038B  0E 02
PRINT_LF_2:
        JP BDOS_VEC                      ; $038D  C3 05 00
; [AI] Interactive-mode handler: prints the '*' prompt and reads a command line via BDOS read-
;       console-buffer (function 10) into $007D, then points the parser at it.
READ_COMMAND_LINE:
        LD A,(DEFAULT_DMA)               ; $0390  3A 80 00
READ_COMMAND_LINE_1:
        OR A                             ; $0393  B7
READ_COMMAND_LINE_2:
        JR NZ,READ_COMMAND_LINE_15                ; $0394  20 24
READ_COMMAND_LINE_3:
        LD DE,BIOS_DISK_DISPATCH_6                 ; $0396  11 3A 04
READ_COMMAND_LINE_4:
        LD C,$09                         ; $0399  0E 09
READ_COMMAND_LINE_5:
        CALL BDOS_VEC                    ; $039B  CD 05 00
READ_COMMAND_LINE_6:
        LD A,$7D                         ; $039E  3E 7D
READ_COMMAND_LINE_7:
        LD (DEFAULT_DMA),A               ; $03A0  32 80 00
READ_COMMAND_LINE_8:
        LD C,$0A                         ; $03A3  0E 0A
READ_COMMAND_LINE_9:
        LD DE,DEFAULT_DMA                ; $03A5  11 80 00
READ_COMMAND_LINE_10:
        CALL BDOS_VEC                    ; $03A8  CD 05 00
READ_COMMAND_LINE_11:
        CALL PRINT_LF                    ; $03AB  CD 89 03
READ_COMMAND_LINE_12:
        LD A,(CMDLINE)                   ; $03AE  3A 81 00
READ_COMMAND_LINE_13:
        OR A                             ; $03B1  B7
READ_COMMAND_LINE_14:
        JR Z,READ_COMMAND_LINE_3                  ; $03B2  28 E2
        ADD A,$82                        ; $03B4  C6 82
        LD L,A                           ; $03B6  6F
        LD H,$00                         ; $03B7  26 00
        LD (HL),H                        ; $03B9  74
READ_COMMAND_LINE_15:
        LD IX,$0082                      ; $03BA  DD 21 82 00
        RET                              ; $03BE  C9
; [AI] Performs a BDOS random-write-with-verify (function 34) of the patched record to the default
;       FCB and maps the BDOS return code onto the appropriate error message.
WRITE_RECORD_VERIFY:
        LD C,$22                         ; $03BF  0E 22
WRITE_RECORD_VERIFY_1:
        LD HL,$210E                      ; $03C1  21 0E 21
        LD DE,DEFAULT_FCB                ; $03C4  11 5C 00
        CALL BDOS_VEC                    ; $03C7  CD 05 00
        OR A                             ; $03CA  B7
        RET Z                            ; $03CB  C8
        CP $04                           ; $03CC  FE 04
        JR Z,WRITE_RECORD_VERIFY_2                  ; $03CE  28 01
        DEC A                            ; $03D0  3D
WRITE_RECORD_VERIFY_2:
        JP Z,TPA_START_45                ; $03D1  CA 28 03
        JP TPA_START_44                  ; $03D4  C3 23 03
; [AI] Increments the FCB random-record number and points the DMA at the second buffer so the
;       following (spanned) record can be read or written.
ADVANCE_TO_REC2:
        LD HL,(DEFAULT_RND)              ; $03D7  2A 7D 00
        INC HL                           ; $03DA  23
        LD (DEFAULT_RND),HL              ; $03DB  22 7D 00
        LD DE,$05E4                      ; $03DE  11 E4 05
        JR SET_DMA_BUF1_1                    ; $03E1  18 03
; [AI] Sets the DMA address to the primary record buffer ($0564) via BDOS set-DMA (function 26)
;       ahead of a transfer.
SET_DMA_BUF1:
        LD DE,$0564                      ; $03E3  11 64 05
SET_DMA_BUF1_1:
        LD C,$1A                         ; $03E6  0E 1A
        JP BDOS_VEC                      ; $03E8  C3 05 00
; [AI] Sets up and issues a record read by loading the record number into the FCB and dispatching
;       through the jump-table read primitive.
READ_RECORD_1:
        LD BC,($0503)                    ; $03EB  ED 4B 03 05
        CALL BIOS_DISK_DISPATCH_5+1                ; $03EF  CD 33 04
        LD A,($0502)                     ; $03F2  3A 02 05
        LD C,A                           ; $03F5  4F
        JR BIOS_DISK_DISPATCH_3+1                  ; $03F6  18 35
; [AI] Reads the second (spanned) record into the alternate buffer, advancing the record/sector
;       number and carrying into the next track when the per-track sector count is exceeded.
READ_RECORD_2:
        LD BC,$05E4                      ; $03F8  01 E4 05
        CALL BIOS_DISK_DISPATCH_4+1                ; $03FB  CD 30 04
        LD A,($0502)                     ; $03FE  3A 02 05
        INC A                            ; $0401  3C
        LD HL,$0505                      ; $0402  21 05 05
        CP (HL)                          ; $0405  BE
        JR C,READ_RECORD_2_1                  ; $0406  38 09
        LD BC,($0503)                    ; $0408  ED 4B 03 05
        INC BC                           ; $040C  03
        CALL BIOS_DISK_DISPATCH_5+1                ; $040D  CD 33 04
        XOR A                            ; $0410  AF
READ_RECORD_2_1:
        LD C,A                           ; $0411  4F
        CALL BIOS_DISK_DISPATCH_3+1                ; $0412  CD 2D 04
; [AI] Issues a write primitive (jump-table slot 1) and checks its status, branching to the disk-
;       error handler on failure.
BIOS_WRITE_CHECK:
        LD C,$01                         ; $0415  0E 01
        CALL BIOS_DISK_DISPATCH_2+1                ; $0417  CD 2A 04
        JR BIOS_READ_CHECK_1                    ; $041A  18 03
; [AI] Issues a read primitive and checks its status, branching to the disk-error handler on
;       failure.
BIOS_READ_CHECK:
        CALL BIOS_DISK_DISPATCH                    ; $041C  CD 24 04
BIOS_READ_CHECK_1:
        OR A                             ; $041F  B7
        RET Z                            ; $0420  C8
        JP TPA_START_44                  ; $0421  C3 23 03
; [AI] Head of the misdisassembled BIOS-style jump table: loads an entry index into E, then (at
;       $0435) fetches the BIOS jump-table base from page zero, indexes it with E, and JP (HL)s into
;       the selected BIOS disk routine.
BIOS_DISK_DISPATCH:
        LD E,$27                         ; $0424  1E 27
BIOS_DISK_DISPATCH_1:
        LD HL,$1B1E                      ; $0426  21 1E 1B
BIOS_DISK_DISPATCH_2:
        LD HL,$2A1E                      ; $0429  21 1E 2A
BIOS_DISK_DISPATCH_3:
        LD HL,$211E                      ; $042C  21 1E 21
BIOS_DISK_DISPATCH_4:
        LD HL,$241E                      ; $042F  21 1E 24
BIOS_DISK_DISPATCH_5:
        LD HL,$1E1E                      ; $0432  21 1E 1E
        LD HL,($0001)                    ; $0435  2A 01 00
        LD L,E                           ; $0438  6B
        JP (HL)                          ; $0439  E9
BIOS_DISK_DISPATCH_6:
        DEFB    $0D,$0A,$2A,$24                                  ; $043A
BIOS_DISK_DISPATCH_7:
        DEFB    $43,$6F,$6D,$6D,$61,$6E,$64,$20,$65,$72,$72,$6F,$72,$24 ; $043E
BIOS_DISK_DISPATCH_8:
        DEFB    $44,$69,$73,$6B,$20,$49,$2F,$4F,$20,$65,$72,$72,$6F,$72,$24 ; $044C
BIOS_DISK_DISPATCH_9:
        DEFB    $46,$69,$6C,$65,$20,$6E,$6F,$74,$20,$66,$6F,$75,$6E,$64,$24 ; $045B
BIOS_DISK_DISPATCH_10:
        DEFB    $45,$6E,$64,$20,$6F,$66,$20,$46,$69,$6C,$65,$20,$65,$72,$72,$6F ; $046A
        DEFB    $72,$24                                          ; $047A
BIOS_DISK_DISPATCH_11:
        DEFB    $49,$6E,$76,$61,$6C,$69,$64,$20,$44,$72,$69,$76,$65,$24 ; $047C
BIOS_DISK_DISPATCH_12:
        DEFB    $56,$65,$72,$69,$66,$69,$63,$61,$74,$69,$6F,$6E,$20,$65,$72,$72 ; $048A
        DEFB    $6F,$72,$24                                      ; $049A
BIOS_DISK_DISPATCH_13:
        DEFB    $0D,$0A,$0D,$0A,$20,$20,$53,$6F,$66,$74,$63,$61,$72,$64,$20,$43 ; $049D
        DEFB    $50,$2F,$4D,$0D,$0A,$44,$69,$73,$6B,$20,$50,$61,$74,$63,$68,$20 ; $04AD
        DEFB    "Utility"    ; $04BD  string
        DEFB    $0D    ; $04C4  terminator
        DEFB    $0A,$28,$43,$29,$20,$31,$39,$38,$32,$20,$4D,$69,$63,$72,$6F,$73 ; $04C5
        DEFB    $6F,$66,$74,$0D,$0A,$24,$46,$69,$6C,$65,$20,$6E,$6F,$74,$20,$66 ; $04D5
        DEFB    $6F,$75,$6E,$64,$24,$45,$6E,$64,$20,$6F,$66,$20,$46,$69,$6C,$65 ; $04E5
        DEFB    $20,$65,$72,$72,$6F,$72,$24,$49                  ; $04F5
BIOS_DISK_DISPATCH_14:
        DEFB    $6E                                              ; $04FD
BIOS_DISK_DISPATCH_15:
        DEFB    $76                                              ; $04FE
BIOS_DISK_DISPATCH_16:
        DEFB    $61                                              ; $04FF

    SAVEBIN "PATCH.bin", $0100, $0400
